/* Bakan atama ekranı: portreli aday listesi, ideoloji etiketleri ve "alanına uygun" göstergesi. Eski TP/cd/appoint/candP yerine geçer. */
const TGE={Teknokrat:{kur:-.5,par:-.2},Popülist:{des:.5,acik:.3},Milliyetçi:{ord:.3,bat:-.2},Liberal:{bat:.3,par:-.2},'Sosyal Devletçi':{huz:.3,acik:.2},Militarist:{ord:.4,bol:-.2},Küreselci:{bat:.4,dog:-.2},Vizyoner:{buy:.2,par:-.1}};
const TGN=Object.keys(TGE);
const FIT={mb:['Teknokrat','Küreselci','Liberal'],maliye:['Teknokrat','Liberal','Küreselci'],sav:['Militarist','Milliyetçi'],ic:['Militarist','Milliyetçi'],dis:['Küreselci','Liberal','Vizyoner'],adalet:['Liberal','Sosyal Devletçi'],egit:['Vizyoner','Sosyal Devletçi','Teknokrat'],saglik:['Sosyal Devletçi','Teknokrat'],calisma:['Sosyal Devletçi','Popülist'],aile:['Sosyal Devletçi','Milliyetçi'],ulas:['Teknokrat','Vizyoner'],enerji:['Teknokrat','Vizyoner'],sanayi:['Teknokrat','Milliyetçi'],tarim:['Popülist','Sosyal Devletçi'],cevre:['Vizyoner','Sosyal Devletçi'],ticaret:['Liberal','Küreselci'],genc:['Vizyoner','Popülist'],kultur:['Vizyoner','Liberal']};
/* gerçek isimlerin küçük değişikliklerle uydurulmuş halleri ve genel isimler */
const BN=['Mehmet Şimşer','Ali Babacı','Hulusi Akarlı','Yaşar Güleç','Hakan Fidanlı','Ali Yerlikaç','Süleyman Soylar','Abdülhamit Gülsoy','Yılmaz Tunçer','Mahinur Özden','Yusuf Tekinalp','Fahrettin Kocalar','Alparslan Bayrakçı','Abdulkadir Uralcı','Mehmet Özhasan','Bekir Bozdal','Ömer Bolcan','Cevdet Yılmazer','Osman Aşkın Bakır','Nuri Ersöz','Şahap Kavcılar','Naci Ağbaz','Gaye Erkın','Murat Uysar','Murat Çetinkul','İbrahim Kalındır','Kemal Dervişer','Mansur Yavuz','Ali Mahir Başaran','Ayşe Ateşoğlu','Berat Albayrak','Selçuk Bayraktaroğlu','Zehra Taşkesenlioğlu','Hüseyin Çelikli','Binali Yıldırım','Numan Kurtulmuşoğlu','Taner Yıldızoğlu','Aylin Korkmaz','Berhudan Kutlu','Buse Doğan','Ferhat Sönmez','Feride Uçar','İlker Ateş','Kerem Balcı','Melis Çelik','Yağmur Karaca','Zeynep Koç','Aslı Öztürk','Burak Aslan','Cevdet Aksoy','Elif Güler','Elvin Özkan','Nurten Şahin','Orhan Güneş','Rıza Demirtaş','Selim Arslan','Selin Aydın','Tuğba Erdem','Emre Yalçın','Derya Kaplan','Volkan Tekin','Pınar Sezer','Barış Özdemir','Gizem Polat','Onur Kılıç'];
const TI={Militarist:['Orgeneral','Korgeneral','Tümgeneral','Hava Mareşali','Oramiral'],Teknokrat:['Prof. Dr.','Doç. Dr.'],Popülist:['Prof. Dr.','Doç. Dr.']},TOLD=['Büyükelçi','Daimî Temsilci','Müsteşar','Milletvekili'];
const SKN=['#e2b48f','#d9a47c','#c99068','#a9744f'],HRC=['#2a2220','#3b2f2a','#8c8c8c','#1c1c1c','#d8b45a','#a9a9a9'];
const bh=s=>{let h=7;for(const c of String(s))h=(h*31+c.charCodeAt(0))>>>0;return h;};
const bface=(seed,tg)=>{const h=bh(seed),sk=SKN[h%4],hr=HRC[(h>>3)%6],gl=(h>>6)%3===0,bd=(h>>8)%3===0,mil=tg.includes('Militarist'),tie=['#a02020','#2a54c4','#2e7d4f','#b8860b'][(h>>10)%4];return `<svg viewBox="0 0 64 64" width="52" height="52"><circle cx="32" cy="32" r="31" fill="#1b2430"/><path d="M8 62c2-14 12-20 24-20s22 6 24 20z" fill="${mil?'#3d4a36':'#1f2a3a'}"/><path d="M28 42l4 8 4-8z" fill="#f2f2f2"/><path d="M31 46h2l1 12h-4z" fill="${tie}"/><rect x="27" y="34" width="10" height="10" rx="3" fill="${sk}"/><ellipse cx="32" cy="26" rx="11" ry="13" fill="${sk}"/><path d="M20 24c0-10 6-14 12-14s12 4 12 14c-3-5-7-7-12-7s-9 2-12 7z" fill="${hr}"/>${mil?'<path d="M20 18c0-6 5-9 12-9s12 3 12 9z" fill="#2f3a2a"/><rect x="21" y="17" width="22" height="3" fill="#c9a24a"/>':''}<circle cx="27.5" cy="27" r="1.4" fill="#222"/><circle cx="36.5" cy="27" r="1.4" fill="#222"/>${gl?'<rect x="23" y="25" width="8" height="5" rx="2" fill="none" stroke="#222" stroke-width="1"/><rect x="33" y="25" width="8" height="5" rx="2" fill="none" stroke="#222" stroke-width="1"/>':''}${bd?'<path d="M24 32c3 8 13 8 16 0-3 3-13 3-16 0z" fill="'+hr+'"/>':'<path d="M27 34c3 2 7 2 10 0" stroke="#5a3a2a" stroke-width="1.6" fill="none"/>'}</svg>`;};
try{Object.keys(S.M||{}).forEach(k=>{S.M[k].name=cl(S.M[k].name);});}catch(e){}
const tgFx=tg=>{const o={};tg.forEach(t=>{const f=TGE[t]||{};for(const k in f)o[k]=Math.round(((o[k]||0)+f[k])*100)/100;});return o;};
const isFit=(k,tg)=>(FIT[k]||[]).some(t=>tg.includes(t));
const pickN=a=>a[Math.floor(Math.random()*a.length)];
const bnm=n=>{let r=String(n||'');[...Object.values(TI).flat(),'Prof.',...TOLD].forEach(t=>{if(r.startsWith(t+' '))r=r.slice(t.length+1);});return r;};
function cl(n){let r=String(n||'');if(r.startsWith('Prof. ')&&!r.startsWith('Prof. Dr.'))r='Prof. Dr. '+r.slice(6);TOLD.forEach(t=>{if(r.startsWith(t+' '))r=r.slice(t.length+1);});return r;};
const usedN=(ex)=>Object.keys(S.M||{}).filter(x=>x!==ex).map(x=>bnm(S.M[x].name));
const cd=k=>{const f=FIT[k]||TGN,u=usedN(k);let c;for(let n=0;n<30;n++){const tg=[];if(Math.random()<.6)tg.push(pickN(f));else tg.push(pickN(TGN));if(Math.random()<.55){const t=pickN(TGN);if(!tg.includes(t))tg.push(t);}
  const fit=isFit(k,tg),nm=pickN(BN),ti=tg.map(t=>TI[t]).find(x=>x&&Math.random()<.6),name=(ti?pickN(ti)+' ':'')+nm;
  c={name,sk:Math.round(fit?7+Math.random()*3:3+Math.random()*4),tg,fit};if(!u.includes(nm))break;}return c;};
const cds=k=>{const l=[];while(l.length<14){const c=cd(k);if(!l.some(x=>bnm(x.name)===bnm(c.name)))l.push(c);}l.sort((a,b)=>(b.fit-a.fit)||(b.sk-a.sk));return l;};
function aptCd(k){S.apm=S.apm||{};return S.apm[k]!==undefined&&S.month-S.apm[k]<12?12-(S.month-S.apm[k]):0;}
function appoint(i){const c=S.cand.l[i],k=S.cand.k,old=S.M[k].name;if(avail()<2)return;if(aptCd(k)){S.cand=null;logA('Kabine','Atama yapılamadı','Bu bakanlıkta yakın zamanda değişiklik yapıldı; '+aptCd(k)+' ay beklemelisin.');save();return render();}S.apm[k]=S.month;if(usedN(k).includes(bnm(c.name))){S.cand.l.splice(i,1);logA('Kabine','Atama yapılamadı',c.name+' zaten başka bir bakanlıkta görevli.');save();return render();}S.M[k]={name:c.name,sk:c.sk,note:c.tg.join(' · '),tg:c.tg,gv:55};applyFx(tgFx(c.tg));S.cur.spent+=2;S.par=clamp(S.par-.3,0,10);S.cand=null;logA('Kabine değişikliği',`${k==='mb'?'Merkez Bankası Başkanı':minName(k)+' Bakanı'} değişti`,`${old} görevden alındı. ${c.name} atandı (${c.tg.join(', ')}${c.fit?', alanına uygun':''}, yetkinlik ${c.sk}/10).`);save();render();}
var mtx=k=>{const m=S.M[k];if(!m)return '';m.name=cl(m.name);if(!m.tg){const h=bh(m.name);m.tg=[TGN[h%8]];if(h%3===0)m.tg.push(TGN[(h>>4)%8]);m.tg=[...new Set(m.tg)];}return (isFit(k,m.tg)?' · <b style="color:var(--good)">✦ alanına uygun</b>':'')+' · '+m.tg.join(' / ');};
{const c=document.createElement?document.createElement('style'):{};c.textContent='.bkov{position:fixed;inset:0;z-index:100;background:var(--bg);overflow-y:auto;padding:calc(10px + env(safe-area-inset-top,0px)) 16px 40px}.bkov .in{max-width:520px;margin:0 auto}.bkov .hd{display:flex;align-items:center;gap:10px}.bkov .hd button{width:40px;height:40px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--accent);font-size:22px;cursor:pointer}.bkov h3{margin:0;font-family:var(--display);font-size:24px;color:var(--accent)}.bkov .ef{color:var(--good);margin:6px 0 4px}.bkov .ca{display:flex;align-items:center;gap:12px;padding:10px 12px;margin-top:8px;border:1px solid var(--line);border-radius:12px;background:var(--pn)}.bkov .ca svg{flex:none;border-radius:50%;border:2px solid var(--accent)}.bkov .ca .tx{flex:1;min-width:0}.bkov .ca b{display:block;font-family:var(--display);font-size:17px;line-height:1.2;overflow-wrap:anywhere}.bkov .ca .tg{display:flex;flex-wrap:wrap;gap:2px 10px;font-size:13px}.bkov .ca .tg i{font-style:normal;color:#4a90d9}.bkov .ca .tg u{text-decoration:none;color:var(--good)}.bkov .ca small{display:block;color:var(--muted);font-size:12px}.bkov .ca .at{flex:none;text-align:right}.bkov .ca .at button{font-family:var(--display);font-weight:700;font-size:16px;letter-spacing:.08em;color:var(--accent);background:none;border:0;cursor:pointer;padding:2px 0}.bkov .ca .at button:disabled{opacity:.4}.bkov .ca .at span{display:block;color:var(--muted);font-size:12px}';try{document.head.appendChild(c);}catch(e){}}
var candP=()=>{const k=S.cand.k,mi=MIN.find(x=>x[0]===k),nm=k==='mb'?'Merkez Bankası Başkanı':minName(k)+' Bakanlığı',a=avail();
  return `<div class="bkov"><div class="in"><div class="hd"><button data-apx="1" aria-label="Geri">‹</button><h3>${nm}</h3></div>${mi?`<div class="ef">${fxText(mi[3])}</div>`:''}<div class="note">Alanına uygun olanlar daha yetkin gelir. Atama 2 puan harcar.</div>${S.cand.l.map((c,i)=>{const f=tgFx(c.tg);return `<div class="ca">${bface(c.name,c.tg)}<div class="tx"><b>${c.name}</b><div class="tg">${c.fit?'<u>✦ alanına uygun</u>':''}${c.tg.map(t=>`<i>${t}</i>`).join('')}</div><small>${fxText(f)}</small></div><div class="at"><button data-ap="${i}" ${a<2?'disabled':''}>ATA</button><span>yetkinlik ${c.sk}/10</span></div></div>`;}).join('')}</div></div>`;};
