/* ---------- Dış politika 2: yeni ülkeler, dünya haritası, temaslar, diplomasi, istihbarat, örgüt eylemleri, kurum kur, anlaşmalar, ordu ve savunma sanayii ---------- */
/* Yeni ülkeler: [id, ad, bölge, başlangıç ilişki (kurgusal), ticaret adı, not] */
CT.push(['jpn','Japonya','dog',62,'Japonya','Teknoloji ve yatırım ortağı; Sinop nükleer görüşmeleri geçmişte yapıldı.'],['kor','Güney Kore','dog',62,'Güney Kore','Altay tankı ve sanayi ortağı.'],['ind','Hindistan','dog',38,'Hindistan','Büyüyen pazar; Pakistan ve Keşmir hassasiyeti.'],['pak','Pakistan','bol',82,'Pakistan','Kardeş ülke; savunma sanayii müşterisi.'],['ukr','Ukrayna','bat',64,'Ukrayna','SİHA ve motor ortağı; savaş nedeniyle denge politikası.'],['geo','Gürcistan','bol',70,'Gürcistan','Bakü-Tiflis-Kars koridoru.'],['arm','Ermenistan','bol',24,'Ermenistan','Diplomatik ilişki yok; normalleşme süreci sürüyor.'],['kaz','Kazakistan','dog',74,'Kazakistan','Türk Devletleri Teşkilatı üyesi; Orta Koridor.'],['uzb','Özbekistan','dog',76,'Özbekistan','TDT üyesi; hızla büyüyen ticaret.'],['tkm','Türkmenistan','dog',70,'Türkmenistan','Doğalgaz potansiyeli; TDT gözlemcisi.'],['lby','Libya','bol',60,'Libya','Trablus hükümetiyle deniz yetki alanları mutabakatı.'],['som','Somali','bol',80,'Somali','Türkiye\'nin en büyük yurt dışı askerî üssü Mogadişu\'da.'],['can','Kanada','bat',46,'Kanada','NATO müttefiki; SİHA optik ambargosu yaşandı.'],['bra','Brezilya','dog',52,'Brezilya','G20 ortağı; BRICS üyesi.'],['esp','İspanya','bat',62,'İspanya','Hürjet ortaklığı ve NATO müttefiki.'],['nld','Hollanda','bat',46,'Hollanda','Büyük diaspora; yatırımcı ülke.'],['pol','Polonya','bat',60,'Polonya','SİHA müşterisi; NATO doğu kanadı.'],['swe','İsveç','bat',44,'İsveç','NATO üyeliği Türkiye onayıyla tamamlandı.'],['bgr','Bulgaristan','bat',60,'Bulgaristan','Komşu; doğalgaz ve göç işbirliği.'],['hun','Macaristan','bat',72,'Macaristan','AB içinde Türkiye\'ye en yakın hükümetlerden.'],['jor','Ürdün','bol',62,'Ürdün','Bölgesel istikrar ortağı.'],['kwt','Kuveyt','bol',66,'Kuveyt','Körfez yatırımcısı.'],['idn','Endonezya','dog',66,'Endonezya','KAAN ve fırkateyn müşterisi.'],['mys','Malezya','dog',68,'Malezya','Savunma ve helal ticaret ortağı.'],['nga','Nijerya','bol',56,'Nijerya','Afrika\'nın en kalabalık pazarı.'],['kktc','KKTC','bol',96,'KKTC','Yalnız Türkiye\'nin tanıdığı devlet; Kıbrıs meselesi.']);
Object.assign(CG,{jpn:80,kor:75,ind:85,pak:60,ukr:50,geo:15,arm:20,kaz:35,uzb:30,tkm:20,lby:15,som:5,can:60,bra:55,esp:55,nld:45,pol:55,swe:45,bgr:25,hun:30,jor:20,kwt:20,idn:45,mys:30,nga:25,kktc:5});Object.assign(CS,{pak:.4,kktc:.2,som:.5,uzb:.5,kaz:.5});
{const add=(o,L)=>{const g=ORG.find(x=>x[0]===o);if(g)L.forEach(c=>{if(!g[4].includes(c))g[4].push(c);});};add('nato',['can','esp','nld','pol','swe','bgr','hun']);add('ab',['esp','nld','pol','swe','bgr','hun']);add('g20',['jpn','kor','ind','can','bra','idn']);add('iit',['pak','jor','kwt','lby','som','idn','mys','nga','kaz','uzb','tkm']);add('sco',['ind','pak','kaz','uzb']);ORG.find(x=>x[0]==='bm')[4]=CT.map(c=>c[0]).filter(c=>c!=='kktc');}
/* Yeni örgütler */
ORG.push(['tdt','Türk Devletleri Teşkilatı','Siyasi ve ekonomik','5 üye + gözlemciler · 2009',['aze','kaz','uzb','tkm','kktc'],55,'Kurucu üye (2009)',[['ortakalfabe','Ortak alfabe ve eğitim','Ortak Türk alfabesi ve üniversite değişimi.',{dog:.03,des:.02}],['tdtfon','Türk Yatırım Fonu','Üyeler arası ortak yatırım fonu.',{rez:.08,dog:.03}],['koridor','Orta Koridor gümrük kolaylığı','Hazar geçişli ortak gümrük.',{cari:-.05,buy:.03}],['savunma','Savunma sanayii işbirliği','Ortak üretim ve eğitim.',{ord:.03,cari:-.02}]]],
 ['oecd','OECD','Ekonomik politika','38 üye · 1961',['usa','ger','uk','fra','ita','jpn','kor','can','esp','nld','pol','swe','hun'],55,'Kurucu üye (1961)',[['vergiseff','Vergi şeffaflığı','Otomatik bilgi değişimi ve kayıt dışıyla mücadele.',{acik:-.05,bat:.02}],['egitimpisa','Eğitim reformu iş birliği','PISA odaklı eğitim programı.',{buy:.02,des:.02}],['rekabet','Rekabet ve yönetişim incelemesi','Kamu ihale ve rekabet politikası.',{bat:.03,buy:.02}],['yesilb','Yeşil büyüme taahhüdü','Karbon fiyatlaması ve teşvik.',{bat:.03,buy:-.01}]]],
 ['ak','Avrupa Konseyi','İnsan hakları','46 üye · 1949',['ger','uk','fra','ita','gre','esp','nld','pol','swe','bgr','hun','ukr','geo','arm','aze'],55,'Kurucu üye (1949) · AİHM kararları bağlayıcı',[['aihm','AİHM kararlarının uygulanması','Bekleyen kararlar uygulanır.',{bat:.05,par:-.02}],['yerel','Yerel yönetimler şartı','Belediyelere daha fazla yetki.',{bat:.03,huz:.02}],['basin','Basın özgürlüğü eylem planı','Gazetecilere yönelik davalar azalır.',{bat:.05,des:-.01}],['istanbulsoz','Kadına şiddetle mücadele protokolü','Kadına şiddete karşı ortak izleme.',{bat:.04,des:.01}]]],
 ['d8','D-8 Ekonomik İşbirliği','Ekonomik','8 üye · 1997',['pak','egy','irn','idn','mys','nga'],50,'Kurucu üye (1997)',[['tercihli','Tercihli ticaret anlaşması','Üyeler arası gümrük indirimi.',{cari:-.03,bol:.02}],['helald8','Helal gıda pazarı','Ortak helal sertifika.',{cari:-.02}],['d8fon','D-8 kalkınma fonu','Ortak altyapı fonu.',{bol:.03,acik:.02}],['d8teknik','Teknoloji transferi','Mühendis değişimi ve ortak Ar-Ge.',{buy:.01}]]]);
ORG.forEach(o=>{const M={nato:[['karadeniz','Karadeniz güvenlik girişimi','Mayın temizliği ve deniz güvenliği.',{ord:.03,bat:.02}],['terorlist','PKK/YPG konusunda ortak tutum','Müttefiklerden terörle mücadelede net destek.',{des:.05,ord:.02,bat:-.01}]],ab:[['modern','Gümrük Birliği modernizasyonu','Tarım, hizmet ve kamu alımları kapsama girer.',{buy:.05,cari:-.04}],['erasmus','Erasmus ve Ufuk Avrupa','Öğrenci ve araştırmacı değişimi.',{des:.02,buy:.01}]],bm:[['iklimfon','İklim finansmanı','Gelişmekte olanlara iklim fonu.',{bat:.02,rez:.03}],['multeci','Mülteci yükü paylaşımı','Uluslararası fon ve yeniden yerleştirme.',{huz:.03,acik:-.03}]],g20:[['yapayzeka','Yapay zekâ yönetişimi','Ortak düzenleme çerçevesi.',{bat:.02}],['enerjig','Enerji geçişi finansmanı','Yenilenebilir yatırım fonu.',{cari:-.02}]],iit:[['filistin','Filistin için ortak diplomasi','Gazze\'ye insani yardım ve iki devletli çözüm.',{bol:.05,des:.03,bat:-.01}],['islamfon','İslam Kalkınma Bankası projeleri','Ortak altyapı kredisi.',{rez:.05}]],sco:[['terorsco','Bölgesel terörle mücadele yapısı','İstihbarat paylaşımı.',{ord:.02,dog:.03}],['enerjikul','Enerji kulübü','Uzun vadeli enerji alımı.',{enf:-.02,dog:.02}]]}[o[0]];if(M)M.forEach(d=>{if(!o[7].some(x=>x[0]===d[0]))o[7].push(d);});});
BKO.push('tdt','d8','oecd');
/* Dünya haritası */
const rlC=v=>v>=75?'#3FA35B':v>=60?'#8DC26A':v>=40?'#7D93A8':v>=25?'#D07A3A':'#B23A30';
function wmP(){const sel=S.wsel,c=sel&&CT.find(x=>x[0]===sel),z=S.wz!==0,vb=S.wz===2?'222 22 108 62':S.wz===3?'30 20 200 105':z?'148 8 112 66':'0 0 360 150',fs=S.wz===2?2:S.wz===3?3.2:z?2.1:4,hid=z?[]:['ger','fra','nld','pol','hun','bgr','gre','ita','aze','geo','arm','isr','jor','kwt','qat','uae','syr','kktc','uk','swe','ukr','irq','irn','tkm','uzb','pak','egy','lby','nga','som','mys','kor'];return `<h2>Dünya</h2><div class="panel" style="padding:8px"><div class="chips" style="margin:0 0 6px"><button class="btn sm ${z?'':'sec'}" data-wz="1">Avrupa ve Orta Doğu</button><button class="btn sm ${S.wz===0?'':'sec'}" data-wz="0">Dünya</button><button class="btn sm ${S.wz===2?'':'sec'}" data-wz="2">Asya</button><button class="btn sm ${S.wz===3?'':'sec'}" data-wz="3">Amerika-Afrika</button></div><svg viewBox="${vb}" style="width:100%;display:block;background:#0c1a22;border-radius:6px"><path d="${WMB}" fill="#2b2a24" stroke="#14130f" stroke-width=".25"/>${CT.map(x=>WMP[x[0]]?`<path data-wsel="${x[0]}" d="${WMP[x[0]]}" fill="${rlC(S.ul[x[0]])}" stroke="${x[0]===sel?'#fff':'#14130f'}" stroke-width="${x[0]===sel?.8:.25}" style="cursor:pointer"/>`:'').join('')}<path d="${WMP.tur}" fill="#F2C14E" stroke="#fff" stroke-width=".4"/><g font-family="Barlow,sans-serif" font-size="${fs}" text-anchor="middle" fill="#fff" stroke="#000" stroke-width="${fs/9}" paint-order="stroke" style="pointer-events:none;font-weight:600">${[['tur','Türkiye'],...CT.map(x=>[x[0],x[1]])].filter(x=>WML[x[0]]&&!hid.includes(x[0])).map(x=>`<text x="${WML[x[0]][0]}" y="${WML[x[0]][1]}">${x[1]}</text>`).join('')}</g></svg>
  <div style="display:flex;flex-wrap:wrap;gap:4px 10px;margin-top:6px">${[['Müttefik',80],['Dost',65],['Normal',50],['Gergin',30],['Düşman',10]].map(([n,v])=>`<span class="dl"><i style="display:inline-block;width:9px;height:9px;border-radius:2px;background:${rlC(v)};margin-right:4px"></i>${n}</span>`).join('')}<span class="dl"><i style="display:inline-block;width:9px;height:9px;border-radius:2px;background:#F2C14E;margin-right:4px"></i>Türkiye</span></div>
  ${c?`<div class="lever" style="margin-top:6px"><span class="n">${c[1]} <span class="st ${rl(S.ul[c[0]])[1]}">${rl(S.ul[c[0]])[0]}</span> · ${nf(S.ul[c[0]],0)}</span><span class="h">${c[5]} · ${RN[c[2]]} bloğu${S.dl[c[0]]?' · ikili anlaşma var':''}</span><div class="step">${sbtn(`data-usel="${c[0]}"`,S.usel===c[0]?'Kapat':'Temaslar')}${sbtn(`data-us="${c[0]}"`,'Sert açıklama')}${sbtn(`data-dpc="${c[0]}"`,'Diplomasi')}</div>${gbar(S.ul[c[0]],rl(S.ul[c[0]])[1])}${S.usel===c[0]?ulList(c):''}</div>`:'<div class="note">Haritada bir ülkeye dokunarak seç. Renk, ilişki düzeyini gösterir.</div>'}</div>`;}
/* Ek temaslar: [ad, açıklama, ilişki, etki, koşul] */
const yak=L=>c=>L.includes(c[0]),dis_=L=>c=>!L.includes(c[0]);
UHO.push(['Ortak askerî tatbikat','Kara, deniz ya da hava tatbikatı.',4,{ord:.04},dis_(['gre','isr','rus','irn','chn','arm','ind'])],['TİKA kalkınma yardımı','Okul, hastane ve su projeleri.',5,{acik:.02,reg:.05},yak(['som','lby','syr','irq','pak','nga','uzb','tkm','kaz','geo','kktc','jor'])],['Yunus Emre kültür merkezi','Türkçe kursu ve kültür etkinlikleri.',3,{acik:.005},()=>1],['Türkiye Bursları','Öğrencilere burs ve üniversite kontenjanı.',2,{},()=>1],['THY doğrudan uçuş hattı','Yeni hat ve turizm bağlantısı.',3,{cari:-.01},()=>1],['Ortak üretim yatırımı','Karşılıklı fabrika ve sanayi bölgesi.',5,{buy:.02,cari:-.02},dis_(['isr','arm'])],['Sınır kapısı ve gümrük modernizasyonu','Kapı kapasitesi ve tek pencere gümrük.',4,{cari:-.02},yak(['geo','irq','irn','syr','bgr','gre','aze'])],['Su ve enerji ortak projesi','Baraj, elektrik ticareti ve boru hattı.',4,{enf:-.01},yak(['irq','syr','geo','aze','bgr','tkm','kaz'])],['Büyükelçiyi istişareye çağır','Tepki için büyükelçi geri çağrılır.',-6,{des:.04},()=>1],['Ticari yaptırım uygula','İthalata kısıtlama; ilişki ve ticaret zarar görür.',-12,{des:.06,cari:.03},()=>1]);
/* Diplomasi: büyükelçilik düzeyi ve vize rejimi (ülke bazlı), küresel diplomasi girişimleri */
const DBE=[['Maslahatgüzar',{rel:-.3}],['Kariyer büyükelçi',{}],['Siyasi ağırlıklı büyükelçi',{rel:.4,acik:.003}]],DVZ=[['Vizesiz',{rel:.3,huz:-.004,cari:-.004}],['e-Vize',{}],['Vize zorunlu',{rel:-.3,huz:.003}]];
const DGO=[['Rusya-Ukrayna arabuluculuğu','İstanbul\'da müzakere ev sahipliği.',{bat:.1,dog:.1,des:.08},{ukr:3,rus:3,usa:1}],['Gazze için insani diplomasi','Yardım koridoru ve ateşkes çağrısı.',{bol:.15,des:.1,bat:-.05},{isr:-5,egy:3,qat:2,jor:2}],['Kafkasya barış süreci','Azerbaycan-Ermenistan normalleşmesine arabuluculuk.',{bol:.08,bat:.05},{arm:5,aze:1}],['Kıbrıs\'ta iki devletli çözüm kampanyası','KKTC\'nin tanınması için diplomatik çaba.',{des:.05,bat:-.05},{kktc:4,gre:-3}],['Türk dünyası zirvesi','TDT liderler zirvesine ev sahipliği.',{dog:.08,des:.05},{aze:3,kaz:3,uzb:3,tkm:3}],['Afrika açılımı','Somali, Libya ve Nijerya\'ya ticaret ve güvenlik paketi.',{bol:.08,acik:.02},{som:3,lby:3,nga:3}],['Körfez ekonomik diplomasisi','Yatırım ve swap görüşmeleri.',{rez:.5,bol:.05},{sau:2,uae:2,qat:2,kwt:2}],['Doğu Akdeniz enerji uzlaşı arayışı','Enerji forumu ve sınırlandırma görüşmeleri.',{bat:.06,bol:.04},{egy:3,gre:2,isr:1}],['Diaspora programı','Avrupa\'daki Türk toplumuyla bağlar.',{des:.04},{ger:1,nld:1,fra:-1}],['Uluslararası kamu diplomasisi','TRT World ve İletişim Başkanlığı kampanyası.',{bat:.04,dog:.04,bol:.04,acik:.02},{}]];
/* İstihbarat: ek operasyonlar (genis.js IO biçimi: [ad, açıklama, etki, riskli]) */
IO.push(['Kritik altyapı koruması','Enerji, su ve finans ağlarına siber kalkan.',{huz:.08,ord:.03},0],['Ekonomik istihbarat','Yabancı yatırım ve rekabet bilgisi toplanır.',{buy:.02,cari:-.02},0],['Dezenformasyonla mücadele','Sahte haber ağları tespit edilir; ifade özgürlüğü tartışması.',{huz:.08,bat:-.03},0],['Terör örgütüne sınır ötesi operasyon','Hedefli operasyon; başarı istihbarat gücüne bağlı.',{ord:.3,des:.3,huz:.1},1],['Yurt dışında vatandaş kurtarma','Kriz bölgesinden tahliye ve rehine kurtarma.',{des:.3,bol:.05},1],['Yabancı casus ağını çökert','Karşı casusluk operasyonu; ilgili ülkeyle gerginlik.',{ord:.1,huz:.05},1],['Muhalefeti izleme','İçeride gözetim: skandal riski yüksek.',{par:.1},1]);
/* Örgüt eylemleri: [ad, açıklama, destek bonusu, etki] */
const OAC=[['Zirveye ev sahipliği','İstanbul\'da zirve: diplomatik ağırlık artar.',8,{acik:.03,des:.05}],['Katkı payını artır','Örgüt bütçesine ve fonlarına ek katkı.',5,{acik:.03}],['Üst düzey temsil','Cumhurbaşkanı düzeyinde katılım.',3,{}],['Düşük temsil ve boykot','Tepki için toplantılara düşük düzeyde katılım.',-8,{des:.04}]];
/* Kurum kur: bütçe düzeyleri ve kurum eylemleri */
const KUB=['Düşük katkı','Orta katkı','Yüksek katkı'],KUA=[['Zirve düzenle','Üye liderleri İstanbul\'da toplanır.'],['Ortak fon kur','12 ay boyunca etki %30 artar.'],['Yeni üye davet et','İlişkisi en iyi aday ülke davet edilir.']];
/* Anlaşmalar: yeni anlaşmalar ve uygulama düzeyleri */
DEALS.push(['vize_ab','AB vize serbestisi yol haritası',3,{bat:1,des:.6,huz:.1},'72 kriter tamamlanır; Schengen vizesi kalkar.'],['kafkas','Kafkasya ulaşım koridoru',2,{bol:.6,dog:.5,cari:-.5},'Nahçıvan bağlantısı ve Orta Koridor.'],['libya','Libya deniz yetki alanları',2,{bol:.4,bat:-.3,ord:.2},'Doğu Akdeniz\'de münhasır ekonomik bölge.'],['somali','Somali savunma ve enerji anlaşması',2,{bol:.4,ord:.2,cari:-.2},'Deniz güvenliği ve petrol arama.'],['tahil','Karadeniz tahıl koridoru',2,{bat:.5,dog:.2,enf:-.3},'Ukrayna tahılının güvenli geçişi.'],['israil','İsrail ile ticaretin yeniden başlatılması',2,{bat:.2,bol:-.6,cari:-.4,des:-.6},'Gazze sonrası askıya alınan ticaret açılır.'],['suriye','Suriye yeniden inşa ortaklığı',2,{bol:.6,buy:.1,acik:.2},'Türk müteahhitlere ihale; geri dönüş hızlanır.'],['nukleer2','Sinop nükleer santral anlaşması',3,{cari:-.5,dog:.3,acik:.2},'Yeni nükleer santral için ortaklık.'],['f35','F-35 programına dönüş',3,{bat:.6,ord:.3,dog:-.3},'S-400 sorunu çözülmeli; CAATSA kalkar.'],['hindistan','Hindistan ile ticaret çerçevesi',2,{dog:.4,cari:-.3,bol:-.1},'Pakistan hassasiyeti nedeniyle temkinli.']);
Object.assign(DQ,{vize_ab:['ger','fra'],kafkas:['aze','arm'],libya:['lby'],somali:['som'],tahil:['ukr','rus'],israil:['isr'],suriye:['syr'],nukleer2:['jpn'],f35:['usa'],hindistan:['ind']});
const DLM=[['Tam uygulama','Bütün maddeler; tam etki.',1],['Kademeli','Aşamalı takvim; etki %65.',.65],['Sembolik','Niyet beyanı; etki %35, risk düşük.',.35]];
/* Ordu: askerlik sistemi, tatbikat, yurt dışı üsler, savunma projeleri */
const ASK=[['6 ay zorunlu + bedelli','Bugünkü sistem.',{},0],['12 ay zorunlu askerlik','Süre uzar; tecrübe artar, gençler tepkili.',{isz:-.02,des:-.03},3],['Profesyonel ordu ağırlıklı','Sözleşmeli personel artar; pahalı ama etkili.',{acik:.04,isz:-.01},5]];
const TAT=[['EFES tatbikatı','Ege\'de çok uluslu karma tatbikat.',3,{ord:.1,acik:.02},{aze:1,pak:1}],['Denizkurdu','Mavi Vatan\'da deniz tatbikatı.',3,{ord:.1,bol:.03,acik:.02},{gre:-3}],['Anadolu Kartalı','Uluslararası hava tatbikatı.',3,{ord:.08,acik:.02},{pak:2,qat:2,aze:2}],['NATO Steadfast tatbikatına katılım','Müttefiklerle ortak tatbikat.',2,{bat:.05,acik:.01},{usa:2,pol:2}],['Kış tatbikatı (Sarıkamış)','Zorlu iklimde kara tatbikatı.',2,{ord:.05,acik:.01},{}]];
const USB=[['qat','Katar üssü','Körfez\'de kalıcı askerî varlık.',{bol:.01,acik:.004}],['som','Somali (TURKSOM)','Afrika boynuzunda eğitim üssü.',{bol:.008,acik:.003}],['lby','Libya','Trablus hükümetine eğitim ve hava savunma.',{bol:.006,bat:-.004,acik:.004}],['aze','Azerbaycan','Ortak eğitim ve gözlem merkezi.',{dog:.006,acik:.002}],['kktc','KKTC','Kıbrıs Türk Barış Kuvvetleri.',{bol:.004,acik:.004}]];
const SPJ=[['kaan','KAAN milli muharip uçak',36,.12,{ord:.6,kap:10,ihr:3}],['altay','ALTAY ana muharebe tankı',18,.06,{ord:.3,kap:5,ihr:1}],['tf2000','TF-2000 hava savunma muhribi',30,.08,{ord:.4,kap:6,ihr:1}],['hurjet','HÜRJET jet eğitim uçağı',18,.05,{ord:.2,kap:5,ihr:2}],['anka3','ANKA-3 insansız savaş uçağı',12,.04,{ord:.3,kap:4,ihr:2}],['kizilelma','KIZILELMA insansız muharip uçak',15,.05,{ord:.35,kap:5,ihr:2}],['siper','SİPER uzun menzilli hava savunma',18,.07,{ord:.4,kap:5,ihr:1}],['milden','MİLDEN milli denizaltı',36,.08,{ord:.4,kap:6,ihr:1}],['celikkubbe','Çelik Kubbe entegre hava savunma',24,.1,{ord:.5,kap:6,ihr:0}],['gokbey','GÖKBEY genel maksat helikopteri',12,.03,{ord:.15,kap:3,ihr:1}]];
const SYP=[['SİHA ve İHA',18,.15],['Zırhlı araç',24,.12],['Korvet ve gemi',36,.25],['Hafif silah ve mühimmat',12,.06]];
function d2Ensure(){if(S.mil&&S.mil.as===undefined)S.mil.as=0;if(!S.mil)return;if(!S.mil.us)S.mil.us={som:1,qat:1,kktc:1};if(!S.spj)S.spj={};if(!S.spd)S.spd={};if(!S.kuD)S.kuD={t:0,m:[],b:1};if(S.og)ORG.forEach(o=>{const g=S.og[o[0]];if(g&&g.sb===undefined)g.sb=0;});}
function d2fx(){const F={};if(!S.mil||!S.dp)return F;mrg(F,ASK[S.mil.as||0][2]);USB.forEach(u=>{if((S.mil.us||{})[u[0]])mrg(F,u[3]);});for(const id in (S.spj||{})){const p=SPJ.find(x=>x[0]===id);if(p)F.acik=(F.acik||0)+p[3];}
  Object.values(S.dp.ok||{}).forEach(o=>{if(o.be!==undefined)mrg(F,DBE[o.be][1]);if(o.vz!==undefined)mrg(F,DVZ[o.vz][1]);});(S.ku||[]).forEach(u=>{F.acik=(F.acik||0)+.01*(u.b||0);});return F;}
function d2Up(){const h=[];d2Ensure();if(!S.dp)return h;
  Object.entries(S.dp.ok||{}).forEach(([c,o])=>{const r=(o.be!==undefined?DBE[o.be][1].rel||0:0)+(o.vz!==undefined?DVZ[o.vz][1].rel||0:0);if(r)relB(c,r);});
  USB.forEach(u=>{if((S.mil.us||{})[u[0]])relB(u[0],.3);});
  for(const id in S.spj){const p=SPJ.find(x=>x[0]===id),q=S.spj[id];if(S.sy&&S.sy.amb>0&&Math.random()<.5)continue;if(--q.left<=0){delete S.spj[id];S.spd[id]=S.month;if(S.sy){S.sy.kap=clamp(S.sy.kap+p[4].kap,0,100);S.sy.pih=(S.sy.pih||0)+p[4].ihr;}applyFx({ord:p[4].ord});h.unshift(`${p[1]} projesi tamamlandı: envantere girdi.`);}}
  ORG.forEach(o=>{const g=S.og[o[0]];if(g&&g.sb)g.sb*=.9;});(S.ku||[]).forEach(u=>{if(u.f>0)u.f--;});return h;}
function d2Click(t){const d=t.dataset;
  if(d.wz!==undefined){S.wz=+d.wz;render();return true;}
  if(d.wsel){S.wsel=S.wsel===d.wsel?null:d.wsel;render();return true;}
  if(d.dbe){const [c,k,v]=d.dbe.split(':');okc(c)[k]=+v;save();render();return true;}
  if(d.dgo!==undefined){const x=DGO[+d.dgo];if(!x)return true;const m=su('dgo'+d.dgo);suU('dgo'+d.dgo);applyFx(sfx2(x[2],m));for(const c in x[3])relB(c,x[3][c]*m*1.5),rel(c,x[3][c]*m);logA('Diplomasi',x[0],'Girişim başlatıldı.'+sat(m));hap(20,520);save();render();return true;}
  if(d.oac){const [o,i]=d.oac.split(':'),x=OAC[+i],g=S.og[o];if(!x||!g)return true;const m=su('oa'+o+i);suU('oa'+o+i);g.sb=clamp((g.sb||0)+x[2]*m,-20,20);applyFx(sfx2(x[3],m));logA(ORG.find(z=>z[0]===o)[1],x[0],'Uygulandı.'+sat(m));hap(20,520);save();render();return true;}
  if(d.kut!==undefined){S.kuD.t=+d.kut;render();return true;}
  if(d.kub!==undefined){S.kuD.b=+d.kub;render();return true;}
  if(d.kum){const m=S.kuD.m,i=m.indexOf(d.kum);if(i<0){if(m.length<8)m.push(d.kum);}else m.splice(i,1);render();return true;}
  if(d.kuc){const D=S.kuD;if(S.ku.length>=3||D.m.length<3)return true;const ok=D.m.filter(c=>Math.random()<S.ul[c]/100+.15+D.b*.08);
    if(ok.length<3){logA('Kurum kur',KT[D.t][0],`Davet edilen ${D.m.length} ülkeden yalnız ${ok.length} kabul etti; kuruluş için en az 3 üye gerekir.`);D.m.forEach(c=>rel(c,-1));}
    else{const n=KT[D.t][0].split(' ')[0]+' '+KUN[Math.floor(Math.random()*KUN.length)]+' Grubu';S.ku.push({t:D.t,n,m:ok,b:D.b,f:0});ok.forEach(c=>rel(c,3));applyFx({des:.2});logA('Kurum kur',n,`${ok.length} üyeyle kuruldu (${KUB[D.b].toLowerCase()}).`);S.kuD={t:0,m:[],b:1};}
    hap(20,520);save();render();return true;}
  if(d.kua){const [i,a]=d.kua.split(':').map(Number),u=S.ku[i];if(!u)return true;const m=su('ka'+i+a);suU('ka'+i+a);
    if(a===0){u.m.forEach(c=>{relB(c,2*m);rel(c,1*m);});applyFx({des:.05*m,acik:.02});}
    else if(a===1){u.f=12;applyFx({acik:.06});}
    else{const c=CT.filter(x=>!u.m.includes(x[0])&&S.ul[x[0]]>=45).sort((a,b)=>S.ul[b[0]]-S.ul[a[0]])[0];if(c){if(Math.random()<S.ul[c[0]]/100+.1){u.m.push(c[0]);rel(c[0],2);logA('Kurum kur',u.n,c[1]+' üye oldu.');}else logA('Kurum kur',u.n,c[1]+' daveti geri çevirdi.');}}
    hap(20,520);save();render();return true;}
  if(d.ask!==undefined){S.mil.as=+d.ask;logA('Ordu','Askerlik sistemi',ASK[+d.ask][0]+'.');save();render();return true;}
  if(d.tat!==undefined){const x=TAT[+d.tat];if(!x)return true;const m=su('tat'+d.tat);suU('tat'+d.tat);S.mil.tc=clamp(S.mil.tc+x[2]*m,0,100);applyFx(sfx2(x[3],m));for(const c in x[4])rel(c,x[4][c]*m);logA('Ordu',x[0],'Tatbikat yapıldı.'+sat(m));hap(20,520);save();render();return true;}
  if(d.usb){const u=S.mil.us;u[d.usb]=u[d.usb]?0:1;logA('Ordu',USB.find(x=>x[0]===d.usb)[1],u[d.usb]?'Üs kuruldu.':'Üs kapatıldı.');save();render();return true;}
  if(d.spj){const p=SPJ.find(x=>x[0]===d.spj);if(!p||S.spj[p[0]]||S.spd[p[0]]||Object.keys(S.spj).length>=3)return true;S.spj[p[0]]={left:p[2]};logA('Savunma sanayii',p[1],p[2]+' ay sürecek geliştirme programı başladı.');hap(20,520);save();render();return true;}
  if(d.syp){const [c,j]=d.syp.split(':'),y=S.sy,p=SYP[+j];if(!p||y.ks.length>=4||y.ks.some(k=>k.id===c)||S.ul[c]<55)return true;y.ks.push({id:c,left:p[1],w:p[2],p:p[0]});S.ul[c]=clamp(S.ul[c]+4,0,100);logA('Savunma ihracatı',CT.find(x=>x[0]===c)[1],p[0]+': '+p[1]+' aylık sözleşme.');hap(20,520);save();render();return true;}
  if(d.syc){S.syc=S.syc===d.syc?null:d.syc;render();return true;}
  return false;}
/* görünümler */
const opRow2=(n,h,b)=>`<div style="padding:7px 0;border-top:1px solid var(--line)"><b style="font-size:14px">${n}</b><div class="note" style="margin:2px 0 6px">${h}</div><div class="chips" style="margin:0">${b}</div></div>`;
function dipX(){const c=S.dpc,u=CT.find(x=>x[0]===c)||CT[0],o=okc(u[0]);if(o.be===undefined)o.be=1;if(o.vz===undefined)o.vz=1;
  return `<div class="panel"><b>${u[1]} · temsil ve vize</b>${opRow2('Büyükelçilik düzeyi','Siyasi ağırlıklı büyükelçi ilişkiyi her ay güçlendirir; maslahatgüzar düzeyine indirmek soğukluk mesajıdır.',DBE.map((x,i)=>`<button class="btn sm ${o.be===i?'':'sec'}" data-dbe="${u[0]}:be:${i}">${x[0]}</button>`).join(''))}${opRow2('Vize rejimi','Vizesiz geçiş turizmi ve ilişkiyi artırır, güvenlik denetimini zorlaştırır.',DVZ.map((x,i)=>`<button class="btn sm ${o.vz===i?'':'sec'}" data-dbe="${u[0]}:vz:${i}">${x[0]}</button>`).join(''))}</div>
  <div class="panel"><b>Küresel diplomasi girişimleri</b>${DGO.map((x,i)=>opRow(x[0],x[1]+(fxText(x[2])?' '+fxText(x[2])+'.':'')+(Object.keys(x[3]).length?' İlişki: '+Object.entries(x[3]).map(([k,v])=>(CT.find(z=>z[0]===k)||[0,k])[1]+' '+(v>0?'+':'')+v).join(', ')+'.':''),sbtn(`data-dgo="${i}"`,'Başlat'))).join('')}</div>`;}
function kuP(){const D=S.kuD,el=CT.filter(c=>S.ul[c[0]]>=45).sort((a,b)=>S.ul[b[0]]-S.ul[a[0]]);
  return `<h2>Kurum kur</h2><div class="panel"><b>Kurduğun örgütler (${S.ku.length}/3)</b>${S.ku.length?S.ku.map((u,i)=>`<div class="lever"><span class="n">${u.n}</span><span class="h">${KT[u.t][0]} · ${KUB[u.b||0]} · ${u.m.length} üye: ${u.m.map(c=>(CT.find(x=>x[0]===c)||[0,c])[1]).join(', ')}${u.f>0?' · ortak fon '+u.f+' ay':''}</span><div class="step">${KUA.map((a,j)=>sbtn(`data-kua="${i}:${j}"`,a[0].split(' ')[0]+' '+(a[0].split(' ')[1]||''))).join('')}${sbtn(`data-kf="${i}"`,'Feshet')}</div></div>`).join(''):'<div class="dl muted">Henüz yok.</div>'}<div class="note">${KUA.map(a=>a[0]+': '+a[1]).join(' ')}</div></div>
  ${S.ku.length<3?`<div class="panel"><b>Yeni örgüt</b><div class="dl" style="margin-top:6px">Tür</div><div class="chips">${KT.map((k,i)=>`<button class="btn sm ${D.t===i?'':'sec'}" data-kut="${i}">${k[0]}</button>`).join('')}</div><div class="note">${KT[D.t][1]} 6 üyede etki: ${fxText(KT[D.t][2])}.</div>
  <div class="dl" style="margin-top:6px">Türkiye'nin katkısı</div><div class="chips">${KUB.map((k,i)=>`<button class="btn sm ${D.b===i?'':'sec'}" data-kub="${i}">${k}</button>`).join('')}</div><div class="note">Yüksek katkı üyelerin katılma şansını ve örgütün etkisini artırır, bütçeye aylık yük bindirir.</div>
  <div class="dl" style="margin-top:6px">Davet edilecek ülkeler (${D.m.length}/8, ilişki 45 üstü)</div><div class="chips">${el.map(c=>`<button class="btn sm ${D.m.includes(c[0])?'':'sec'}" data-kum="${c[0]}">${c[1]} ${nf(S.ul[c[0]],0)}</button>`).join('')}</div>
  <div class="step" style="margin-top:8px">${sbtn('data-kuc="1"','Kuruluş zirvesini topla',D.m.length<3)}</div><div class="note">Her ülke ilişkisine ve katkı düzeyine göre katılmayı kabul eder; en az 3 üye gerekir. Reddedilen davetler ilişkiyi biraz bozar.</div></div>`:''}`;}
function ordX(){const m=S.mil,y=S.sy,act=Object.keys(S.spj),el=CT.filter(x=>S.ul[x[0]]>=55&&!y.ks.some(k=>k.id===x[0]));
  return `<div class="panel"><b>Askerlik sistemi</b>${ASK.map((a,i)=>opRow(a[0],a[1]+(fxText(a[2])?' '+fxText(a[2])+'.':'')+(a[3]?' Hazırlık hedefi +'+a[3]+'.':''),`<button class="btn sm ${(m.as||0)===i?'':'sec'}" data-ask="${i}">${(m.as||0)===i?'Seçili':'Seç'}</button>`)).join('')}</div>
  <div class="panel"><b>Tatbikatlar</b>${TAT.map((x,i)=>opRow(x[0],x[1]+' Tecrübe +'+x[2]+(fxText(x[3])?' · '+fxText(x[3]):'')+(Object.keys(x[4]).length?' · ilişki: '+Object.entries(x[4]).map(([k,v])=>(CT.find(z=>z[0]===k)||[0,k])[1]+' '+(v>0?'+':'')+v).join(', '):'')+'.',sbtn(`data-tat="${i}"`,'Düzenle'))).join('')}</div>
  <div class="panel"><b>Yurt dışı askerî varlık</b>${USB.map(u=>opRow(u[1],u[2]+' Aylık: '+fxText(u[3])+'; ilişki her ay artar.',sbtn(`data-usb="${u[0]}"`,(m.us||{})[u[0]]?'Kapat':'Kur'))).join('')}</div>
  <h2>Savunma sanayii projeleri</h2><div class="panel"><div class="dl">Süren: ${act.length}/3 · tamamlanan: ${Object.keys(S.spd).length}/${SPJ.length}</div>${SPJ.map(p=>{const q=S.spj[p[0]],dn=S.spd[p[0]]!==undefined;return opRow(p[1],`${p[2]} ay · aylık bütçe GSYH %${nf(p[3],2)} · bitince ordu +${p[4].ord}, sanayi kapasitesi +${p[4].kap}${p[4].ihr?', ihracat potansiyeli +'+p[4].ihr+' mlr $':''}.${q?' <b>'+q.left+' ay kaldı.</b>':''}`,dn?'<span class="st good">Envanterde</span>':q?'<span class="st warn">Sürüyor</span>':sbtn(`data-spj="${p[0]}"`,'Başlat',act.length>=3));}).join('')}<div class="note">Ambargo sürerken projeler yarı hızda ilerler.</div></div>
  <div class="panel"><b>Savunma ihracatı sözleşmeleri (${y.ks.length}/4)</b>${y.ks.map(k=>`<div class="dl">${(CT.find(c=>c[0]===k.id)||[0,k.id])[1]}: ${k.p||'Sözleşme'} · ${k.left} ay kaldı</div>`).join('')||'<div class="dl muted">Yok</div>'}
  ${el.map(c=>`<div class="lever"><span class="n">${c[1]}</span><span class="h">İlişki ${nf(S.ul[c[0]],0)}</span><div class="step">${sbtn(`data-syc="${c[0]}"`,S.syc===c[0]?'Kapat':'Ürünler')}</div>${S.syc===c[0]?`<div style="grid-column:1/-1">${SYP.map((p,j)=>opRow(p[0],`${p[1]} aylık sözleşme · savunma ihracatı +%${nf(p[2]*100,0)} · ilişki +4.`,sbtn(`data-syp="${c[0]}:${j}"`,'İmzala',y.ks.length>=4))).join('')}</div>`:''}</div>`).join('')}<div class="note">Sözleşme için ilişki 55 ve üstü olmalı.</div></div>`;}
AL.splice(0,AL.length,...DEALS,...PROJ,...PRIV);
