/* ---------- Dünya: ülke ilişkileri, gelen talepler, uluslararası örgütler, askeriye ---------- */
/* Ülkeler: [id, ad, bölge, başlangıç ilişki (kurgusal puan 0-100), ticaret adı, not] */
const CT=[['usa','ABD','bat',48,'ABD','NATO müttefiki; savunma ve teknoloji ortağı.'],['ger','Almanya','bat',55,'Almanya','En büyük ihracat pazarı.'],['uk','Birleşik Krallık','bat',58,'Birleşik Krallık','Serbest ticaret anlaşması ortağı.'],['gre','Yunanistan','bat',28,'Yunanistan','Ege ve Doğu Akdeniz\'de gerilimli komşu.'],['rus','Rusya','dog',50,'Rusya','Enerji tedarikçisi; ikinci büyük ithalat kaynağı.'],['chn','Çin','dog',52,'Çin','En büyük ithalat kaynağı.'],['aze','Azerbaycan','bol',88,'Azerbaycan','Yakın müttefik; enerji koridoru ortağı.'],['irn','İran','bol',45,'İran','Komşu; doğalgaz tedarikçisi.'],['irq','Irak','bol',52,'Irak','Komşu; önemli ihracat pazarı.'],['sau','Suudi Arabistan','bol',50,'Suudi Arabistan','Körfez sermayesi ve ticaret ortağı.'],['egy','Mısır','bol',40,'Mısır','Bölgesel rakip; ilişkiler normalleşme sürecinde.'],['qat','Katar','bol',75,'Katar','Yakın ortak; yatırım ve savunma işbirliği.']];
const REGB={bat:5,dog:5,bol:6},RN={bat:'Batı',dog:'Doğu',bol:'Bölge'};
const rl=r=>r>=75?['Müttefik','good']:r>=60?['Dost','good']:r>=40?['Normal','warn']:r>=25?['Gergin','bad']:['Düşman','bad'];
/* Örgütler: [id, ad, tür, bilgi, üye ülkeler (oylama), eşik %, Türkiye'nin durumu, kararlar [id, ad, açıklama, aylık etki]] */
const ORG=[
['nato','NATO','Askeri ittifak','32 üye · kuruluş 1949',['usa','ger','uk','gre'],55,'Üye (1952)',[['ortak','Ortak savunma üretimi','Ortak silah üretimi ve standardizasyon.',{ord:.05,cari:-.04,bat:.02}],['guney','Güney kanadı güçlendirme','Doğu Akdeniz ve Karadeniz\'de ortak duruş.',{ord:.04,bol:.03,acik:.06}]]],
['ab','Avrupa Birliği','Ekonomik birlik','27 üye · Gümrük Birliği 1995',['ger','gre','uk'],60,'Aday ülke (1999)',[['gb','Gümrük Birliği güncellemesi','Sanayi dışı ürünler ve hizmetleri kapsar.',{buy:.05,cari:-.05,bat:.03}],['vize','Vize serbestisi','Türk vatandaşına kolay Schengen vizesi.',{bat:.05,des:.06,huz:.02}]]],
['bm','Birleşmiş Milletler','Siyasi çatı','193 üye · kuruluş 1945',CT.map(c=>c[0]),45,'Kurucu üye (1945)',[['insani','İnsani yardım misyonu','Kriz bölgelerine ortak yardım.',{bol:.04,bat:.02,acik:.05}],['iklim','İklim mutabakatı','Emisyon ve uyum taahhütleri.',{bat:.04,enf:.02,acik:.04}]]],
['g20','G20','Ekonomik forum','19 ülke + AB ve AU · 1999',['usa','ger','uk','rus','chn','sau'],50,'Üye (1999)',[['borc','Borç yapılandırma girişimi','Yüksek borçlu ülkelere ortak çözüm.',{borc:-.12,acik:-.05}],['tic','Serbest ticaret bildirisi','Tarife ve kota indirimi.',{cari:-.04,buy:.04}]]],
['iit','İslam İşbirliği Teşkilatı','Siyasi ve ekonomik','57 üye · kuruluş 1969',['sau','egy','irn','irq','aze','qat'],50,'Kurucu üye (1969)',[['kalk','Ortak kalkınma fonu','Üyeler arası finansman havuzu.',{rez:.12,bol:.04}],['helal','Helal gıda standardı','Ortak sertifika ve gıda ticareti.',{cari:-.04,bol:.03}]]],
['sco','Şanghay İşbirliği Örgütü','Güvenlik ve ekonomi','10 üye',['rus','chn','irn'],50,'Diyalog ortağı (2012)',[['enerji','Enerji ortaklığı','Uzun vadeli enerji ve altyapı anlaşmaları.',{enf:-.04,dog:.05,bat:-.03}],['odeme','Ortak ödeme sistemi','Dolar dışı ticaret ve takas.',{rez:.1,dog:.04,bat:-.04}]]]];
const CMD=[['Stratejist','Hazırlık +5, tecrübe kazanımı %25 yüksek.',{hz:5,tg:1.25}],['Disiplinci','Hazırlık +8; ordu memnuniyeti −0,03/ay.',{hz:8,ord:-.03}],['Reformcu','Tecrübe +6; yerli üretimde ilerleme.',{tc:6,cari:-.02}]],G0=59.5,TM=['Düşük','Normal','Yoğun'];
const oSup=o=>{const l=o[4].map(k=>S.ul[k]);return clamp(.9*l.reduce((a,b)=>a+b,0)/l.length+5-(o[0]==='nato'&&natoAskida()?10:0),0,100);};
const natoAskida=()=>S.bud.sav<MB.sav*.95;
const gucu=()=>{const m=S.mil,f=(CMD[m.cmd]||[0,0,{}])[2];return clamp(.55*(m.hz+(f.hz||0))+.3*(m.tc+(f.tc||0))+.15*S.sec.san,0,100);};
function dunyaEnsure(){S.ul=S.ul||{};CT.forEach(c=>{if(S.ul[c[0]]===undefined)S.ul[c[0]]=c[3];});S.ub=S.ub||{};S.dl=S.dl||{};S.ta=S.ta||[];S.tn=S.tn||0;S.og=S.og||{};ORG.forEach(o=>{S.og[o[0]]=S.og[o[0]]||{dec:null,act:[]};});S.mil=S.mil||{hz:70,tc:45,tm:1,cmd:-1};}
/* sürekli etkiler (simulate içinde) */
function dsfx(){const F={},add=(o,m=1)=>{for(const k in o)F[k]=(F[k]||0)+o[k]*m;};if(!S.ul)return F;
  ['bat','dog','bol'].forEach(r=>{const l=CT.filter(c=>c[2]===r);F[r]=(F[r]||0)+.004*l.reduce((a,c)=>a+S.ul[c[0]]-c[3],0)/l.length;});
  ORG.forEach(o=>S.og[o[0]].act.forEach(a=>add(o[7].find(d=>d[0]===a.id)[3])));
  if(natoAskida())add({bat:-.04,ord:-.03});CT.forEach(c=>{if(S.dl[c[0]])add({cari:-.03,buy:.008});});
  const f=(CMD[S.mil.cmd]||[0,0,{}])[2];add({ord:(gucu()-G0)*.003+(f.ord||0),cari:f.cari||0,acik:[-.03,0,.1][S.mil.tm]});return F;}
const TT={sav:['Savunma işbirliği','ortak tatbikat ve savunma sanayii işbirliği öneriyor.',{ord:.3,acik:.05},6,-3],yat:['Yatırım anlaşması','karşılıklı yatırım koruma anlaşması öneriyor.',{buy:.05,cari:-.05},5,-2],ger:['Ticari gerilim','tarifeleri artırmakla tehdit ediyor ve masaya oturmak istiyor.',{des:-.15},4,-5],kredi:['Kredi talebi','kredi istiyor.',{bol:.15},10,-3]};
function dunyaUp(){const h=[];dunyaEnsure();
  CT.forEach(c=>{const id=c[0],o=rl(S.ul[id])[0],t=clamp(c[3]+(S[c[2]]-REGB[c[2]])*6+(S.ub[id]||0)+(S.dl[id]?8:0),5,95);S.ul[id]+=(t-S.ul[id])*.18;S.ub[id]=(S.ub[id]||0)*.85;const n=rl(S.ul[id])[0];if(n!==o&&(n==='Gergin'||n==='Düşman'||n==='Müttefik'))h.push(`${c[1]} ile ilişkiler ${n==='Müttefik'?'müttefiklik düzeyine çıktı':n==='Gergin'?'gerginleşti':'düşmanlık düzeyine indi'}.`);});
  S.ta=S.ta.filter(x=>{x.left--;if(x.left>0)return true;S.ul[x.c]=Math.max(0,S.ul[x.c]-2);return false;});
  if(S.ta.length<4&&Math.random()<.4){const c=CT[Math.floor(Math.random()*CT.length)],r=S.ul[c[0]];if(!S.ta.some(x=>x.c===c[0])){const ty=r>=55?['sav','kredi','yat'][Math.floor(Math.random()*3)]:r>=40?['yat','kredi'][Math.floor(Math.random()*2)]:'ger';S.ta.push({id:++S.tn,c:c[0],t:ty,left:3,x:ty==='kredi'?Math.round(rnd(.5,2)*10)/10:0});h.push(`${c[1]}, yeni bir talep iletti.`);}}
  ORG.forEach(o=>{const g=S.og[o[0]];g.act=g.act.filter(a=>{a.left--;if(a.left>0)return true;h.push(`${o[1]}: ${o[7].find(d=>d[0]===a.id)[1]} kararının süresi doldu.`);return false;});
    if(g.dec){g.dec.left--;if(g.dec.left<=0){const d=o[7].find(x=>x[0]===g.dec.id),s=oSup(o)+rnd(-6,6);if(s>=o[5]){g.act.push({id:d[0],left:12});h.push(`${o[1]}: "${d[1]}" kabul edildi (%${nf(s,0)} / %${o[5]}).`);}else{S.bat=clamp(S.bat-.05,0,10);h.push(`${o[1]}: "${d[1]}" önergesi reddedildi (%${nf(s,0)} / %${o[5]}).`);}g.dec=null;}}});
  const m=S.mil,f=(CMD[m.cmd]||[0,0,{}])[2],r=S.bud.sav/MB.sav;m.hz+=(clamp(70*Math.pow(r,.8)+[-8,0,6][m.tm]+8*rb('ssb'),10,100)-m.hz)*.2;m.tc=clamp(m.tc+[-.6,.25,1][m.tm]*(f.tg||1)-m.tc*.004,0,100);
  if(m.hz<40)h.push('Ordunun hazırlık düzeyi tehlikeli biçimde düştü.');if(natoAskida()&&S.month%6===0)h.push('NATO, savunma bütçesi %2 kuralı nedeniyle ayrıcalıklarını askıya aldı.');return h;}
/* eylemler */
const uc=(id,k)=>(S.cool[k+id]||0)-S.month;
function uact(a,id){const c=CT.find(x=>x[0]===id);if(!c)return;
  if(a==='h'){if(uc(id,'u')>0||avail()<1)return;S.cur.spent+=1;S.ub[id]=(S.ub[id]||0)+10;S.ul[id]=Math.min(100,S.ul[id]+4);S.cool['u'+id]=S.month+3;logA('Dış ilişkiler',c[1],'Heyet gönderildi.');}
  else if(a==='s'){if(uc(id,'s')>0)return;S.ub[id]=(S.ub[id]||0)-9;S.ul[id]=Math.max(0,S.ul[id]-4);S.cool['s'+id]=S.month+2;applyFx({des:.15,ord:.05});logA('Dış ilişkiler',c[1],'Sert açıklama yapıldı.');}
  else if(a==='d'){if(S.dl[id]||S.ul[id]<60||avail()<2)return;S.cur.spent+=2;S.dl[id]=1;logA('Dış ilişkiler',c[1],'İkili ticaret ve yatırım anlaşması imzalandı.');}
  hap(20,520);save();render();}
function tal(id,ok){const i=S.ta.findIndex(x=>x.id===id);if(i<0)return;const x=S.ta[i],t=TT[x.t],fx={...t[2]};S.ta.splice(i,1);
  if(ok){if(x.t==='kredi')fx.rez=-x.x;applyFx(fx);S.ub[x.c]=(S.ub[x.c]||0)+t[3];S.ul[x.c]=Math.min(100,S.ul[x.c]+t[3]);logA('Gelen talep',CT.find(c=>c[0]===x.c)[1],t[0]+' kabul edildi.');}
  else{S.ul[x.c]=Math.max(0,S.ul[x.c]+t[4]);logA('Gelen talep',CT.find(c=>c[0]===x.c)[1],t[0]+' reddedildi.');}hap(20,520);save();render();}
function teklif(oid,did){const o=ORG.find(x=>x[0]===oid),g=S.og[oid];if(!o||g.dec||g.act.some(a=>a.id===did)||avail()<1)return;S.cur.spent+=1;g.dec={id:did,left:3};logA(o[1],o[7].find(d=>d[0]===did)[1],'Önerge sunuldu; oylama 3 ay sonra.');hap(20,520);save();render();}
function milSet(k,v){const m=S.mil;if(k==='tm'){m.tm=v;}else{if(v===m.cmd||avail()<2||(S.cool.cmd||0)>S.month)return;S.cur.spent+=2;m.cmd=v;S.cool.cmd=S.month+12;logA('Genelkurmay',CMD[v][0],'Yeni Genelkurmay Başkanı atandı.');}hap(20,520);save();render();}
function dunyaClick(t){const d=t.dataset;
  if(d.uh){uact('h',d.uh);return true;}if(d.us){uact('s',d.us);return true;}if(d.ud){uact('d',d.ud);return true;}
  if(d.tay){tal(+d.tay,true);return true;}if(d.tan){tal(+d.tan,false);return true;}
  if(d.og){const p=d.og.split(':');teklif(p[0],p[1]);return true;}if(d.mtm!==undefined){milSet('tm',+d.mtm);return true;}if(d.mcd!==undefined){milSet('cmd',+d.mcd);return true;}return false;}
/* görünümler */
const tvol=n=>{const e=EP.find(x=>x[0]===n),i=IP.find(x=>x[0]===n);return (e?`ihracat ${nf(e[1],1)} mlr $`:'')+(e&&i?' · ':'')+(i?`ithalat ${nf(i[1],1)} mlr $`:'');};
function ulke(){const ta=S.ta.map(x=>{const c=CT.find(y=>y[0]===x.c),t=TT[x.t];return `<div class="lever"><span class="n">${c[1]}: ${t[0]}</span><span class="h">${c[1]} ${t[1].replace('kredi istiyor.',`${nf(x.x,1)} milyar dolar kredi istiyor.`)} Kabul: ${fxText({...t[2]})}${x.t==='kredi'?`, Rezerv −${nf(x.x,1)}`:''}, ilişki +${t[3]}. Kalan ${x.left} ay.</span><div class="step">${sbtn(`data-tay="${x.id}"`,'Kabul',0)}${sbtn(`data-tan="${x.id}"`,'Reddet',0)}</div></div>`;}).join('');
  return `<h2>Gelen talepler</h2><div class="panel">${ta||'<div class="dl">Şu an bekleyen talep yok.</div>'}<div class="note">Talepler 3 ay bekler; kabul etmek ilişkiyi güçlendirir, etkisi bedelli olabilir. Reddetmek ilişkiyi biraz soğutur. Bedelsizdir.</div></div>
  <h2>Ülke ilişkileri</h2>${['bat','dog','bol'].map(r=>`<div class="panel"><b>${RN[r]}</b> <span class="muted dl">itibar ${nf(S[r],1)}/10</span>${CT.filter(c=>c[2]===r).map(c=>{const id=c[0],v=S.ul[id],[lb,k]=rl(v),ch=uc(id,'u'),cs=uc(id,'s');return `<div class="lever"><span class="n">${c[1]} <span class="st ${k}">${lb}</span> <span class="dl muted">· ${nf(v,0)}</span></span><span class="h">${c[5]}${tvol(c[4])?' · '+tvol(c[4]):''}${S.dl[id]?' · ikili anlaşma var':''}</span><div class="step">${sbtn(`data-uh="${id}"`,ch>0?ch+' ay':'Heyet',ch>0||avail()<1)}${sbtn(`data-us="${id}"`,cs>0?cs+' ay':'Sert açıklama',cs>0)}${S.dl[id]||v<60?'':sbtn(`data-ud="${id}"`,'Anlaşma',avail()<2)}</div>${gbar(v,k)}</div>`;}).join('')}</div>`).join('')}<div class="note">İlişki puanları kurguseldir. Hedef puan; bölge itibarın ve eylemlerinle oluşur. Ortalama sapma Batı, Doğu ve Bölge itibarını, ticaretini ve örgüt oylamalarını etkiler. Anlaşma için ilişki 60 üstü olmalı. Sert açıklama ülke içinde desteği biraz artırır.</div>`;}
function orgut(){return `<h2>Uluslararası örgütler</h2>${ORG.map(o=>{const g=S.og[o[0]],s=oSup(o),k=s>=o[5]?'good':s>=o[5]-8?'warn':'bad',ak=o[0]==='nato'&&natoAskida();
  return `<div class="panel"><b>${o[1]}</b> <span class="muted dl">· ${o[2]} · ${o[3]}</span><div class="dl" style="margin-top:2px">Türkiye: <b>${o[6]}</b>${ak?' · <span class="st bad">Ayrıcalıklar askıda</span>':''}</div>${ak?'<div class="note">Savunma bütçesi GSYH\'nın %2\'sinin altında kalırsa ittifak ayrıcalıkları askıya alınır: Batı itibarı ve ordu memnuniyeti her ay düşer.</div>':''}<div class="dl" style="display:flex;justify-content:space-between;margin-top:6px"><span>Destek tahmini</span><span><span class="st ${k}">%${nf(s,0)}</span> / eşik %${o[5]}</span></div>${gbar(s,k)}
   ${g.dec?`<div class="dl">Müzakerede: <b>${o[7].find(d=>d[0]===g.dec.id)[1]}</b> · ${g.dec.left} ay sonra oylama</div>`:o[7].map(d=>{const on=g.act.find(a=>a.id===d[0]);return `<div class="lever"><span class="n">${d[1]}</span><span class="h">${d[2]} Etki: ${fxText(d[3])}${on?` · yürürlükte, ${on.left} ay kaldı`:''}</span><div class="step">${on?'<span class="st good">Yürürlükte</span>':sbtn(`data-og="${o[0]}:${d[0]}"`,'Teklif',avail()<1)}</div></div>`;}).join('')}</div>`;}).join('')}<div class="note">Bir örgütte aynı anda yalnız bir önerge tartışılır; oylama 3 ay sonra yapılır. Destek, üye ülkelerle ilişkinin ortalamasıdır (±6 şans payı). Kabul edilen karar 12 ay sürer. İlişkileri Ülkeler sekmesinden yükselt.</div>`;}
function askeri(){const m=S.mil,g=gucu(),pct=S.bud.sav,usd=pct/100*S.gdp,ak=natoAskida(),Bk=(n,v)=>`<div class="dl" style="display:flex;justify-content:space-between"><span>${n}</span><span>${nf(v,0)}</span></div>${gbar(v,v>=60?'good':v>=40?'warn':'bad')}`;
  return `<h2>Askeriye</h2><div class="panel">${Bk('Hazırlık',m.hz)}${Bk('Tecrübe',m.tc)}${Bk('Savaş gücü endeksi',g)}<div class="dl">Savunma bütçesi: GSYH'nın %${nf(pct,2)} ≈ ${nf(usd,1)} milyar $ · NATO %2 kuralı: <span class="st ${ak?'bad':'good'}">${ak?'karşılanmıyor':'karşılanıyor'}</span></div><div class="note">Hazırlık; savunma bütçesi, talim ve SSB bütçesiyle belirlenir. Güç endeksi 59,5'in üstündeyse ordu memnuniyeti artar, altındaysa azalır. Savunma bütçesini Bütçe sekmesinden, projeleri Anlaşma sekmesinden yönet.</div></div>
  <div class="panel"><b>Talim temposu</b><div class="chips" style="margin:8px 0">${TM.map((n,i)=>`<button class="btn sm ${m.tm===i?'':'sec'}" data-mtm="${i}">${n}</button>`).join('')}</div><div class="note">Düşük: tecrübe söner, bütçe rahatlar. Yoğun: tecrübe hızla artar, GSYH'ya +%0,10 yük bindirir.</div></div>
  <div class="panel"><b>Genelkurmay Başkanı</b> <span class="muted dl">· ${m.cmd<0?'atanmadı':CMD[m.cmd][0]}</span>${CMD.map((c,i)=>`<div class="lever"><span class="n">${c[0]}</span><span class="h">${c[1]}</span><div class="step">${m.cmd===i?'<span class="st good">Görevde</span>':sbtn(`data-mcd="${i}"`,'Ata',avail()<2||(S.cool.cmd||0)>S.month)}</div></div>`).join('')}<div class="note">Atama yapıldıktan 12 ay sonra değiştirilebilir.</div></div>`;}
