/* Yeni kriz olayları (10) ve sonradan tetiklenen "sonuç" olayları (14) */
EV.push(
{id:'k_sinirc',g:'kriz',tag:'ACİL · Sınır',t:'Sınır Hattında Çatışma',x:()=>`Güney sınırındaki karakola gece baskın yapıldı, iki asker şehit oldu. ${M.sav?M.sav.name:'Savunma Bakanı'} ve Genelkurmay misilleme için onay bekliyor. Sosyal medya intikam istiyor.`,c:[ ch(`Sınır ötesi sınırlı harekât`,3,`Hızlı ve sert yanıt.`,{des:2.5,ord:.6,bat:-.8,dog:.3,acik:.3,huz:-.3},`Harekât yapıldı. Kamuoyu destek verdi, uluslararası tepki geldi.`,{later:[{m:3,id:'l_sinirc'}]}), ch(`Hava harekâtı ve diplomatik baskı`,2,`Kayıp riski düşük.`,{des:1.2,ord:.3,bat:-.3,acik:.1},`Hava harekâtı yapıldı, taraflar mesaj aldı.`), ch(`Tırmandırma, sınırı tahkim et`,1,`Diplomatik yol, duvar ve kamera hattı.`,{des:-1.5,ord:-.5,huz:.3,bat:.4,acik:.2},`Tırmanma önlendi. Muhalefet "zayıflık" diye eleştirdi.`) ]},
{id:'k_gazkes',g:'kriz',tag:'ACİL · Enerji',t:'Doğalgaz Akışı Kesildi',x:()=>`Ana boru hattından gelen gaz bir arıza gerekçesiyle durduruldu. Depolar kış ortasında yüzde 30'un altında. Sanayi ve konut için kesinti planı hazırlanıyor.`,c:[ ch(`Sanayiye kesinti, konutları koru`,2,`Üretim durur, halk ısınır.`,{buy:-.5,isz:.3,des:1,huz:.3,enf:.2},`Sanayide üretim yavaşladı, evlerde ısınma sürdü.`,{later:[{m:2,id:'l_gazfatura'}]}), ch(`Spot LNG al, pahalıya olsun`,3,`Gemi ile hızlı tedarik.`,{cari:.5,acik:.5,rez:-2,des:.8},`LNG gemileri geldi. Fatura büyük oldu.`,{later:[{m:2,id:'l_gazfatura'}]}), ch(`Komşuyla acil anlaşma`,1,`Siyasi taviz karşılığı gaz.`,{bat:-.5,dog:.4,cari:.2,des:.3},`Anlaşma sağlandı, ama bir bedel ödendi.`) ]},
{id:'k_gocdalga',g:'kriz',tag:'ACİL · Göç',t:'Komşuda Çöküş, Kitlesel Göç Dalgası',x:()=>`Doğu komşuda rejim sarsıldı. Bir haftada yarım milyon kişi sınır kapılarına dayandı. Valiler barınma ve gıda istiyor, sosyal medyada tepki büyüyor.`,c:[ ch(`Sınırı aç, kamplar kur`,3,`İnsani yaklaşım.`,{huz:-.8,bat:.8,acik:.6,des:-1.5,bol:.2},`Binlerce kişi kamplara yerleştirildi. Maliyet büyük, tepki sert.`,{later:[{m:2,id:'l_gocuyum'}]}), ch(`Sınırı kapat, tampon bölge`,2,`Sınırda tutma.`,{huz:.3,bat:-1,des:1,ord:.2,acik:.3},`Sınır kapatıldı. İnsan hakları örgütleri tepki gösterdi.`), ch(`AB'den para karşılığı barındır`,2,`Pazarlık.`,{bat:.3,acik:-.2,des:-.5,huz:-.3},`AB finansman sözü verdi, kamuoyu bunu tartışıyor.`) ]},
{id:'k_yolsuzop',g:'kriz',tag:'ACİL · Operasyon',t:'Kamu Bankasında Büyük Operasyon',x:()=>`Savcılık bir kamu bankasında milyarlarca liralık usulsüz krediyi açıkladı. Gözaltı listesinde bakanlık ve parti kademeleri var. Piyasa açılışta sert düştü.`,c:[ ch(`Soruşturmaya tam destek`,2,`Kim çıkarsa çıksın.`,{des:-1,bat:1,par:-.8,acik:.2,rez:-.5},`Gözaltılar sürdü. Parti içi huzursuzluk arttı, dış güven toparlandı.`,{later:[{m:3,id:'l_yolsuzdava'}]}), ch(`Soruşturmayı sınırla`,2,`Sorunu küçült.`,{des:1,bat:-1,par:.3,huz:-.3},`Dosya daraltıldı. Muhalefet "örtbas" dedi.`,{later:[{m:3,id:'l_yolsuzdava'}]}), ch(`Bakanı ve yönetimi görevden al`,1,`Hızlı tasfiye.`,{des:.5,par:-.3,bat:.4},`Üst düzey isimler görevden alındı. Kriz yatıştı.`) ]},
{id:'k_siber2',g:'kriz',tag:'ACİL · Siber',t:'Bankalara ve E-Devlete Siber Saldırı',x:()=>`E-devlet, tapu ve iki büyük bankanın sistemleri saatlerdir kapalı. Saldırının arkasında yabancı bir devlet grubu olduğu düşünülüyor. Halk nakit çekmek için kuyrukta.`,c:[ ch(`Acil durum ve sistem izolasyonu`,2,`Önce hizmetleri kurtar.`,{buy:-.2,huz:.3,des:.5,acik:.3},`Sistemler günler içinde yeniden açıldı.`,{later:[{m:2,id:'l_siberfatura'}]}), ch(`Karşı saldırı ve suçlama`,3,`Failleri açıkla.`,{bat:-.5,ord:.3,des:1.5,dog:.2},`Suçlama sert tepkiye yol açtı, ama kamuoyu arkandaydı.`), ch(`Gizli kal, sessizce çöz`,1,`Panik yaratma.`,{des:-1,huz:-.3,bat:.2},`Basın sızıntılar yüzünden sizi eleştirdi.`) ]},
{id:'k_kuratak',g:'kriz',tag:'ACİL · Piyasa',cond:()=>S.rez<70,t:'Gece Yarısı Kur Atağı',x:()=>`Uluslararası piyasalarda aniden satış başladı. Kur birkaç saatte sert yükseldi, Merkez Bankası rezervleri eriyor. Başkan ${M.mb.name} telefonda bekliyor.`,c:[ ch(`Rezervden sat, kuru tut`,2,`Kur baskısı kırılır.`,{kur:-3,rez:-6,des:.5},`Rezerv eritilerek kur tutuldu. Uzun süre tutulamaz.`), ch(`Acil faiz artırımı`,2,`Sert sıkılaştırma.`,{kur:-4,rez:2,buy:-.5,isz:.4,des:-1.5,lv:{faiz:6}},`Faiz sert artırıldı. Kur geriledi, krediler daraldı.`), ch(`Sermaye kontrolü`,3,`Döviz çıkışına sınır.`,{kur:-2,rez:3,bat:-1.5,des:-.5,huz:-.2},`Kontrol getirildi. Yabancı yatırımcı bu hamleyi hatırlayacak.`) ]},
{id:'k_sokakpr',g:'kriz',tag:'ACİL · Sokak',t:'Ülke Çapında Protestolar',x:()=>`Bir park projesiyle başlayan gösteri on iki ilde meydanlara yayıldı. Sloganlar hükümeti hedef alıyor, polisle çatışmalar sürüyor. Dünya basını canlı yayında.`,c:[ ch(`Polisi geri çek, görüş`,2,`Diyaloğu aç.`,{huz:.5,des:-.5,bat:.5,par:-.3},`Gösteriler yatıştı. Parti içi "taviz" eleştirisi yükseldi.`), ch(`Sert müdahale`,2,`Düzeni sağla.`,{huz:-1.2,des:.8,bat:-1.2,ord:.2,par:.2},`Müdahale sürdü. Uluslararası eleştiri arttı.`,{later:[{m:2,id:'l_sokaksonu'}]}), ch(`Projeyi iptal et`,1,`Talebe boyun eğ.`,{huz:.8,des:-1,acik:-.1,par:-.2},`Proje durduruldu. Protestolar bitti, kimse tam memnun değil.`) ]},
{id:'k_maden2',g:'kriz',tag:'ACİL · Facia',t:'Maden Faciası',x:()=>`Bir kömür ocağında patlama oldu. Yüzün üzerinde işçi yer altında mahsur. Aileler kapıda bekliyor, kameralar canlı yayında. ${M.calisma?M.calisma.name:'Çalışma Bakanı'} bölgeye gidiyor.`,c:[ ch(`Bölgeye git, kurtarmayı yönet`,2,`Yakın ilgi göster.`,{des:.8,huz:.3,par:.2},`Kurtarma çalışmaları günlerce sürdü. Duruşun takdir gördü.`,{later:[{m:3,id:'l_madendava'}]}), ch(`Ruhsatları denetle, yasa çıkar`,3,`Yapısal çözüm.`,{des:.5,bat:.4,buy:-.1,acik:.1,huz:.3},`Denetim kampanyası başladı. Madenciler tedirgin.`,{later:[{m:3,id:'l_madendava'}]}), ch(`Hazır cevap ver, geç`,0,`Kriz iletişimi.`,{des:-2,huz:-.5,par:-.4},`"Kader planı" cevabı büyük tepki çekti.`) ]},
{id:'k_deniz',g:'kriz',tag:'ACİL · Doğu Akdeniz',t:'Doğu Akdeniz’de Savaş Gemileri Karşı Karşıya',x:()=>`Sismik arama gemisini koruyan fırkateynle komşunun savaş gemisi çarpıştı. NATO "itidal" diyor. Genelkurmay hazır durumda bekliyor, borsa düşüyor.`,c:[ ch(`Gemiyi bölgede tut, caydır`,2,`Kararlı duruş.`,{des:1.5,ord:.3,bat:-.8,dog:.2,huz:-.2,kur:1},`Gerilim yüksek kaldı. Halk arkandaydı.`), ch(`Gemiyi çek, müzakereye otur`,1,`Gerilimi düşür.`,{bat:.8,des:-1,ord:-.3,huz:.3,kur:-.5},`Taraflar masaya oturdu. Milliyetçi kesim hoşnutsuz.`), ch(`NATO arabuluculuğu iste`,1,`İttifak kartı.`,{bat:.6,des:-.2,dog:-.3,ord:.1},`Arabuluculuk gerilimi düşürdü.`) ]},
{id:'k_rehine',g:'kriz',tag:'ACİL · Rehine',t:'Yurt Dışında Rehine Krizi',x:()=>`Yabancı bir ülkede çalışan Türk mühendisler silahlı bir grup tarafından kaçırıldı. Aileler televizyonlarda hükümete yalvarıyor. İstihbarat, pazarlık kanalı açılabileceğini söylüyor.`,c:[ ch(`Gizli pazarlık, fidye yok`,2,`İstihbarat devrede.`,{des:.8,bat:.2,rez:-.3},`Mühendisler günler sonra kurtarıldı. Ayrıntılar kapalı.`), ch(`Askeri operasyon`,3,`Risk yüksek.`,{des:1.5,ord:.3,huz:-.3,bat:-.4},`Operasyon başarıyla bitti, kayıplar verildi.`,{later:[{m:2,id:'l_rehinemd'}]}), ch(`Diplomatik baskı, bekle`,1,`Süre uzar.`,{des:-1.5,huz:-.4,par:-.2},`Süre uzadıkça kamuoyu öfkelendi.`) ]},

/* SONUÇ OLAYLARI (kararların birkaç ay sonra geri dönüşü) */
{id:'l_sinirc',g:'later',tag:'Sonuç · Sınır',t:'Harekâtın Siyasi Faturası',x:()=>`Sınır ötesi harekâtın üzerinden üç ay geçti. Bölgede kalıcı üs talepleri ve uluslararası hukuk tartışması gündemde. Meclis harekâtın uzatılmasını oyluyor.`,c:[ ch(`Tezkereyi uzat`,2,`Kararlılık göster.`,{ord:.4,des:.5,bat:-.6,acik:.3},`Tezkere geçti. Askeri varlık sürüyor.`), ch(`Harekâtı sonlandır`,1,`Çekil.`,{bat:.7,des:-.8,ord:-.3,acik:-.1},`Birlikler geri çekildi. Milliyetçiler tepki gösterdi.`), ch(`Müttefiklerle ortak güvenlik bölgesi`,2,`Orta yol.`,{bat:.3,des:.2,dog:-.2,acik:.2},`Ortak bölge anlaşması imzalandı.`) ]},
{id:'l_gazfatura',g:'later',tag:'Sonuç · Enerji',t:'Kışın Enerji Faturası Geldi',x:()=>`Gaz krizinin hesabı çıktı: BOTAŞ'ın zararı büyük, sanayi odaları kayıpları tazmin etmeni istiyor. Muhalefet "kış öncesi hazırlık yapılmadı" diyor.`,c:[ ch(`BOTAŞ'ı bütçeden kurtar`,2,`Kamu zararı üstlen.`,{acik:.7,des:.5,enf:-.1,borc:.4},`Zarar bütçeye yazıldı.`), ch(`Faturaya yansıt`,1,`Zam yap.`,{enf:.6,des:-1.5,huz:-.4,acik:-.3},`Faturalar arttı, tepki çok.`), ch(`Depolama ve çeşitlendirme planı`,3,`Uzun vadeli çözüm.`,{cari:-.2,acik:.5,bat:.3,des:.2,dog:.1},`Yeni depolama yatırımları başladı.`) ]},
{id:'l_gocuyum',g:'later',tag:'Sonuç · Göç',t:'Kamplarda Uyum Krizi',x:()=>`Göçmen kampları dolup taştı, bazı şehirlerde yerel halkla gerginlik başladı. Belediye başkanları "yetki ve kaynak verin" diyor.`,c:[ ch(`Kentlere dağıt, kaynak aktar`,3,`Yük paylaşımı.`,{acik:.6,huz:-.3,des:-.5,bat:.4},`Dağıtım başladı, bazı belediyeler direndi.`), ch(`Kamplarda tut, sınırlı çalışma izni`,2,`Kontrollü model.`,{huz:.2,acik:.3,des:.3,isz:.1},`Kamp modeli sürdü.`), ch(`Geri dönüş programı`,2,`Güvenli bölge vaadi.`,{des:.8,bat:-.5,huz:.2,acik:.3},`Gönüllü geri dönüş programı başladı.`) ]},
{id:'l_yolsuzdava',g:'later',tag:'Sonuç · Yargı',t:'Yolsuzluk Davası Başladı',x:()=>`Banka soruşturması iddianameye döndü. Sanık sandalyesinde bir eski bakan var. Mahkemenin tutuklu yargılama kararı, tahliye ya da gizlilik hükmü gündemde.`,c:[ ch(`Yargı bağımsız karar versin`,1,`Karışma.`,{bat:.8,des:-.6,par:-.5},`Dava şeffaf yürüdü. Parti içi tepki var.`,{fn:()=>{try{yg().bag=Math.min(100,yg().bag+4)}catch(e){}return {fx:{bat:.8,des:-.6,par:-.5},msg:`Dava şeffaf yürüdü. Yargıya güven arttı, parti içinde tepki var.`}}}), ch(`Dosyada gizlilik kararı iste`,2,`Örtbas.`,{des:.5,bat:-1,par:.3},`Gizlilik kararı verildi. Basın ve muhalefet tepkili.`,{fn:()=>{try{yg().bag=Math.max(0,yg().bag-5)}catch(e){}return {fx:{des:.5,bat:-1,par:.3},msg:`Gizlilik kararı verildi. Yargı bağımsızlığı tartışıldı.`}}}), ch(`Arabulucu uzlaşma önder`,1,`Orta yol.`,{des:-.2,par:-.1,bat:.2},`Taraflar uzlaşmaya yanaştı.`) ]},
{id:'l_siberfatura',g:'later',tag:'Sonuç · Siber',t:'Saldırının Bedeli ve Savunma Planı',x:()=>`Siber saldırı yüzünden bankalar zarar yazdı, vatandaşın kişisel verileri sızdı. Meclis'te "kritik altyapı koruma" için bütçe ayrılması isteniyor.`,c:[ ch(`Ulusal siber savunma fonu`,3,`Büyük yatırım.`,{acik:.4,ord:.2,huz:.2,bat:.3},`Fon kuruldu, merkez kurulumu başladı.`), ch(`Bankalara düzenleme getir`,1,`Sorumluluğu özele yükle.`,{acik:-.1,bat:.2,des:-.2},`Düzenleme yürürlüğe girdi.`), ch(`Gündemden düşsün`,0,`Bekle.`,{des:-.5,huz:-.2},`Açıklar kapatılmadı, saldırı riski sürüyor.`) ]},
{id:'l_sokaksonu',g:'later',tag:'Sonuç · Sokak',t:'Gözaltılar ve Yargılamalar',x:()=>`Protestolardan sonra yüzlerce kişi yargılanıyor. Hukukçular orantısız müdahale iddialarını AİHM'e taşıyor. Avrupa gündemde.`,c:[ ch(`Yargılamaları hızlandır`,1,`Örnek ceza.`,{huz:-.4,bat:-.6,des:.3},`Davalar hızla sonuçlandı, tepkiler sürdü.`), ch(`Tahliye ve af`,2,`Uzlaşma jesti.`,{huz:.6,bat:.5,des:-.4,par:-.2},`Tutuklular tahliye edildi.`), ch(`Bağımsız soruşturma komisyonu`,1,`Şeffaflık.`,{bat:.5,huz:.3,des:-.2},`Komisyon kuruldu.`) ]},
{id:'l_madendava',g:'later',tag:'Sonuç · Emek',t:'Maden Davası ve Ruhsat Tartışması',x:()=>`Facianın davası başladı: şirket yöneticileri ve denetçiler yargılanıyor. Aileler "gerçek sorumlular" diyor. İşçi sendikaları ruhsat sistemini hedef alıyor.`,c:[ ch(`Ruhsat iptal ve ağır denetim`,2,`Sert tedbir.`,{buy:-.2,huz:.4,des:.5,bat:.3},`Birçok ruhsat askıya alındı.`), ch(`Tazminat fonu kur`,2,`Aile desteği.`,{acik:.3,des:.6,huz:.3},`Fon kuruldu.`), ch(`Süreci yargıya bırak`,0,`Bekle.`,{des:-.4,huz:-.2},`Dava uzun sürecek.`) ]},
{id:'l_rehinemd',g:'later',tag:'Sonuç · Dış Politika',t:'Operasyonun Diplomatik Sonuçları',x:()=>`Rehine operasyonu yapılan ülke egemenlik ihlali diyerek büyükelçiyi çağırdı. Kurtarılan mühendisler kahraman ilan edildi, ama ticaret ilişkileri risk altında.`,c:[ ch(`Resmi özür dileme`,1,`Normalleş.`,{des:-.4,bat:.3,dog:.2},`Gerilim azaldı.`), ch(`Karşılıklı ticaret yaptırımı`,2,`Sert yanıt.`,{cari:.3,des:.5,bat:-.3},`Yaptırımlar karşılıklı uygulandı.`), ch(`Üçüncü ülke arabulucu`,1,`Sessiz diplomasi.`,{des:0,bat:.2,dog:.2},`Arabulucu devreye girdi.`) ]},
{id:'l_tmsf',g:'later',tag:'Sonuç · Finans',t:'TMSF Devrinin Hesabı',x:()=>`Devralınan bankanın zararı beklenenden büyük çıktı. Kamu bankaları ek sermaye istiyor, Hazine'nin eli daralıyor.`,c:[ ch(`Ek sermaye aktar`,2,`Devlet üstlensin.`,{acik:.8,borc:.8,des:.2},`Ek sermaye aktarıldı.`), ch(`Bankayı özelleştir`,2,`Satışa çıkar.`,{acik:-.3,bat:.4,des:-.4,par:-.1},`Satış süreci başladı.`), ch(`Hesap verme soruşturması`,1,`Sorumlular bulunsun.`,{des:.2,bat:.3,par:-.2},`Soruşturma başlatıldı.`) ]},
{id:'l_kayyum',g:'later',tag:'Sonuç · Yerel',t:'Belediye Soruşturmasının Gölgesi',x:()=>`Belediye soruşturması büyüdü. İçişleri'ne "kayyum atansın" baskısı var. Muhalefet "seçilmişe darbe" diyor.`,c:[ ch(`Kayyum ata`,2,`Sert yol.`,{des:.5,bat:-1.2,huz:-.5,par:.2},`Kayyum atandı. Uluslararası tepki yoğun.`), ch(`Yargı sonucunu bekle`,1,`Süreç ilerlesin.`,{des:-.2,bat:.3,par:-.2},`Süreç yargıya bırakıldı.`), ch(`Merkezle uzlaşma görüşmesi`,1,`Pragmatik çözüm.`,{kol:.2,huz:.2,des:-.2},`Görüşmeler başladı.`) ]},
{id:'l_basin',g:'later',tag:'Sonuç · Basın',t:'Gazeteci Davalarına AB Tepkisi',x:()=>`Gazetecilere yönelik soruşturmalar AB Parlamentosu raporuna girdi. Avrupa Komisyonu "ilerleme raporunda" sert not düşecek.`,c:[ ch(`Davaları gözden geçir`,1,`Jest yap.`,{bat:.6,des:-.4,par:-.2},`Bazı dosyalar kapatıldı.`), ch(`Raporu "iç işi" diye reddet`,0,`Sert cevap.`,{bat:-.6,des:.5,dog:.1},`Rapor reddedildi.`), ch(`Basın özgürlüğü paketi hazırla`,2,`Reform sinyali.`,{bat:.8,des:-.2,par:-.3,acik:.1},`Paket duyuruldu.`) ]},
{id:'l_aftepki',g:'later',tag:'Sonuç · İnfaz',t:'İnfaz Düzenlemesi Tartışması',x:()=>`İnfaz düzenlemesinden yararlananların bir kısmı yeniden suç işledi. Mağdur aileleri ve muhalefet ayaktaki iktidardan hesap soruyor.`,c:[ ch(`Düzenlemeyi sıkılaştır`,1,`Geri adım.`,{huz:.3,des:.6,bat:-.2},`Düzenleme sıkılaştırıldı.`), ch(`Denetimli serbestlik için kaynak ayır`,2,`Sistemi güçlendir.`,{acik:.2,huz:.2,bat:.2},`Denetimli serbestlik güçlendi.`), ch(`Sadece savun`,0,`Değişiklik yok.`,{des:-.8,huz:-.3},`Tartışma büyüdü.`) ]},
{id:'l_kampus',g:'later',tag:'Sonuç · Gençlik',t:'Kampüs Eylemleri Yeniden Başladı',x:()=>`Üniversite eylemleri yeniden alevlendi. Öğrenci toplulukları rektör atamaları ve burs eşitsizliğini hedef alıyor.`,c:[ ch(`Rektörlerle ortak taslak`,1,`Diyalog.`,{huz:.4,des:.2,par:-.1},`Ortak taslak hazırlandı.`), ch(`Soruşturma ve disiplin`,1,`Sert.`,{huz:-.5,des:-.3,bat:-.4},`Disiplin soruşturmaları başladı.`), ch(`Burs ve yurt paketi`,2,`Karşılık ver.`,{acik:.4,des:.7,huz:.3},`Burs paketi açıklandı.`) ]},
{id:'l_gerilim2',g:'later',tag:'Sonuç · Göç',t:'Mahalle Gerginliği Yayılıyor',x:()=>`Mültecilere yönelik olaylar birkaç şehre yayıldı. Bazı iş yerleri hedef alındı, polis müdahale ediyor.`,c:[ ch(`Güvenlik ve adalet paketi`,2,`Failleri yakala.`,{huz:.5,des:.3,bat:.2,acik:.2},`Faillere ağır ceza geldi.`), ch(`Yerel bütçe desteği`,2,`Mahalleye kaynak.`,{acik:.3,huz:.4,des:.3},`Kaynak aktarıldı.`), ch(`Gündem dışı bırak`,0,`Geçiştir.`,{huz:-.6,des:-.5},`Gerilim sürüyor.`) ]}
);
/* Bu olaylara sonradan geri dönen sonuçlar ekle: [olay, seçenek sırası, sonuç olayı, ay] */
[['e_banka',0,'l_tmsf',3],['i_belediye',0,'l_kayyum',2],['i_belediye2',0,'l_kayyum',3],['i_medya',0,'l_basin',2],['i_infaz',0,'l_aftepki',3],['i_universite',1,'l_kampus',2],['i_ogrenci',1,'l_kampus',2],['i_gerilim',0,'l_gerilim2',2],['i_gerilim',1,'l_gerilim2',3]].forEach(([e,i,l,m])=>{try{const c=EVB[e]&&EVB[e].c[i];if(c&&!(c.later||[]).some(x=>x.id===l))c.later=(c.later||[]).concat([{m,id:l}]);}catch(x){}});
Object.assign(EVB,Object.fromEntries(EV.map(e=>[e.id,e])));
