/* ek17: Dış İlişkiler — ülke eylem menüsü (alt pencereler), anlaşma paketleri, ikili kredi, silah satışı, askerî destek, siyasi polemik, gelen anlaşma önerileri */
const PKT=[['sav','Savunma Paktı','Saldırıya uğrarsan savaşa katılırsın; ordu ve güvenlik güçlenir.',70,45,.35,{ord:.01}],['sinir','Serbest Sınır Anlaşması','Vizesiz geçiş: turizm ve ilişki artar, güvenlik denetimi zayıflar.',60,35,.3,{des:.01,huz:-.004}],['tic','Serbest Ticaret Anlaşması','Gümrük duvarları kalkar: ihracat artar, yerli üretici baskı görür.',55,35,.2,{cari:-.01,buy:.004}],['dos','Dostluk Anlaşması','Siyasi yakınlık; ilişki her ay biraz daha artar.',45,25,.25,{des:.004}],['yat','Yatırım Hakkı Anlaşması','Karşılıklı yatırım hakkı: döviz girişi ve fabrika yatırımı.',50,35,.2,{rez:.05,buy:.003}],['ask','Askerî Birlik Anlaşması','Ortak komuta ve üs kullanımı: ordu güçlenir, Batı itibarı düşebilir.',80,55,.55,{ord:.03,bat:-.01}]];
const DXA=[['tem','🤝','Heyet ve temaslar'],['yat','🏭','Yatırım ve ticaret'],['pk','📜','Anlaşma paketleri'],['kr','💳','Kredi anlaşması'],['ok','⚙️','Özel kurallar'],['ul','⚠️','Ültimatom']];
const DAS=[['Silah yardımı','Ücretsiz teçhizat; ilişki güçlenir, bütçeye yük biner.',7,{acik:.03,ord:-.02}],['Askerî danışman ve eğitim','Subay eğitimi ve danışman heyeti gönderilir.',5,{acik:.01,ord:.02}],['İstihbarat paylaşımı','Ortak tehdit bilgisi paylaşılır.',4,{ord:.02,huz:.02}],['Üs kullanımı karşılığı destek','Üs hakkı karşılığı askerî destek.',6,{ord:.03,bat:-.02}]];
const DPO=[['Tarihî ihtilafı gündeme getir','Halk hoşuna gider, karşı taraf küser.',-5,{des:.25}],['Sınır ve harita çıkışı','Haritalara tepki; milliyetçi kesim memnun.',-4,{des:.2,ord:.03}],['Zirveyi terk et','Ortak bildiriyi imzalamadan zirveden ayrıl.',-6,{des:.3,bat:-.03}],['Ticaret şovu','Kürsüde ticaret açığı grafikleri göster.',-4,{des:.15}],['Vize krizi','Karşılıklı vize sertleşmesi.',-3,{des:.12,cari:.01}]];
Object.defineProperty(LOAN,'ikili',{value:['İkili devlet kredisi',9,5,{},'',0],enumerable:false});
const pk=id=>{S.pk=S.pk||{};return S.pk[id]||(S.pk[id]={});};
const pkN=id=>Object.keys((S.pk||{})[id]||{}).filter(k=>PKT.some(p=>p[0]===k)).length;
function pkSign(id,k){const p=PKT.find(x=>x[0]===k),c=CT.find(x=>x[0]===id);if(!p||!c||pk(id)[k])return;if(!pkOk(id,k)||S.ul[id]<p[3]||avail()<1)return;S.cur.spent+=1;pk(id)[k]=S.month+1;if(k==='tic')S.dl[id]=1;S.ul[id]=clamp(S.ul[id]+3,0,100);logA('Dış ilişkiler',c[1],p[1]+' imzalandı.');hap(20,520);}
function pkBreak(id,k){const p=PKT.find(x=>x[0]===k);if(!pk(id)[k])return;delete pk(id)[k];S.ul[id]=clamp(S.ul[id]-6,0,100);logA('Dış ilişkiler',dxN(id),p[1]+' feshedildi.');}
function dxMonth(){try{S.pr=S.pr||[];Object.keys(S.pk||{}).forEach(id=>{Object.keys(S.pk[id]).forEach(k=>{const p=PKT.find(x=>x[0]===k);const kk=clamp((CG[id]??45)/60,.35,1.4);S.ul[id]=clamp(S.ul[id]+p[5],0,100);applyFx(Object.fromEntries(Object.entries(p[6]).map(([a,b])=>[a,b*kk])));if(S.ul[id]<p[4]){delete S.pk[id][k];logA('Dış ilişkiler',dxN(id),p[1]+' ilişkiler bozulduğu için sona erdi.');}});});
  S.pr.forEach(x=>x.left--);S.pr=S.pr.filter(x=>x.left>0);
  if(S.month%2===0&&S.pr.length<4){const c=CT.filter(c=>PKT.some(p=>pkOk(c[0],p[0])&&S.ul[c[0]]>=p[3]-5&&!pk(c[0])[p[0]])&&!S.pr.some(x=>x.c===c[0]));if(c.length){const k=c[Math.floor(Math.random()*c.length)],ps=PKT.filter(p=>pkOk(k[0],p[0])&&S.ul[k[0]]>=p[3]-5&&!pk(k[0])[p[0]]),p=ps[Math.floor(Math.random()*ps.length)];S.pr.push({c:k[0],k:p[0],left:5});}}}catch(e){}}
{const _y=yeniUp;yeniUp=function(){dxMonth();return _y.apply(this,arguments);};}
const dxAct=(kind,i,id)=>{const L=kind==='as'?DAS:DPO,x=L[i],c=CT.find(y=>y[0]===id);if(!x||!c||(kind==='as'&&avail()<1))return;const m=su('dx'+kind+i+id);suU('dx'+kind+i+id);if(kind==='as')S.cur.spent+=1;S.ul[id]=clamp(S.ul[id]+x[2]*m,0,100);applyFx(sfx2(x[3],m));logA('Dış ilişkiler',c[1],x[0]+'.'+sat(m));hap(20,520);};
function dxKredi(id){const c=CT.find(y=>y[0]===id),a=ui('krA',5),r=ui('krR',9),v=ui('krV',3);if(!c||S.loans.reduce((s,l)=>s+l.amt,0)+a>60)return;const p=dxKp(id,a,r);if(Math.random()<p){S.debt+=a;S.rez=Math.min(120,S.rez+a);S.borc=S.debt/S.gdp*100;S.loans.push({s:'ikili',amt:a,rate:r,end:S.month+v*12});S.ul[id]=clamp(S.ul[id]+2,0,100);logA('Dış ilişkiler',c[1],`${a} mlr $ kredi alındı (%${r} faiz, ${v} yıl vade).`);}else{S.ul[id]=clamp(S.ul[id]-1,0,100);logA('Dış ilişkiler',c[1],'Kredi talebi reddedildi.');}hap(20,520);}
const dxKp=(id,a,r)=>clamp(.25+S.ul[id]/130-a/60+(r-8)/25,.03,.97);
function dxSheet(){const [id,k]=(S.dxm||'').split(':'),c=CT.find(x=>x[0]===id);if(!c||!k)return '';const o=okc(id),t=DXA.find(x=>x[0]===k);let w='';
  if(k==='tem')w=uRows(c,false)+`<div class="step" style="margin-top:6px">${sbtn(`data-us="${id}"`,'Sert açıklama')}</div>`;
  else if(k==='yat')w=uRows(c,true)+DEALS.filter(e=>DQ[e[0]]&&DQ[e[0]].includes(id)).map(dRow).join('');
  else if(k==='pk')w=PKT.map(p=>{const on=pk(id)[p[0]],ok=S.ul[id]>=p[3];return opRow2(p[1]+(on?' ✓':''),`${p[2]} İmza eşiği ${p[3]}, bozulma eşiği ${p[4]}. Her ay ilişki +${p[5]}.`,on?sbtn(`data-dxp="${id}:${p[0]}:0"`,'Feshet'):sbtn(`data-dxp="${id}:${p[0]}:1"`,ok?'İmzala':'İlişki yetersiz',!ok||avail()<1));}).join('');
  else if(k==='kr'){const a=ui('krA',5),r=ui('krR',9),v=ui('krV',3),p=dxKp(id,a,r);w=`<div class="dl">Tutar: ${a} mlr $</div>${sld('krA',1,30,1,a)}<div class="dl">Faiz: %${r}/yıl</div>${sld('krR',3,16,.5,r)}<div class="dl">Vade: ${v} yıl</div>${sld('krV',1,10,1,v)}<div class="note">Kabul olasılığı: <b>%${nf(p*100,0)}</b> · yüksek faiz ve yüksek ilişki şansı artırır. Mevcut dış borç: ${nf(S.loans.reduce((s,l)=>s+l.amt,0),1)}/60 mlr $.</div><div class="step">${sbtn(`data-dxk="${id}"`,'Teklif et')}</div>`;}
  else if(k==='sl'){const y=S.sy;w=S.ul[id]<55?'<div class="note">Silah satışı için ilişki en az 55 olmalı.</div>':SYP.map((p,j)=>opRow2(p[0],`${p[1]} aylık sözleşme · savunma ihracatı +%${nf(p[2]*100,0)} · ilişki +4.`,sbtn(`data-syp="${id}:${j}"`,'İmzala',y.ks.length>=4||y.ks.some(q=>q.id===id)))).join('')+`<div class="note">Aynı anda en çok 4 ihracat sözleşmesi (${y.ks.length}/4).</div>`;}
  else if(k==='as')w=DAS.map((x,i)=>opRow(x[0],`${x[1]} İlişki +${x[2]} · ${fxText(x[3])}.`,sbtn(`data-dxg="as:${i}:${id}"`,'Uygula',avail()<1))).join('');
  else if(k==='po')w=DPO.map((x,i)=>opRow(x[0],`${x[1]} İlişki ${x[2]} · ${fxText(x[3])}.`,sbtn(`data-dxg="po:${i}:${id}"`,'Uygula'))).join('')+'<div class="note">Polemik halk desteğini artırır ama ilişkiyi bozar; tekrarladıkça etkisi azalır.</div>';
  else if(k==='ok')w=opRow2('Transit rotası','Kapalı rota ilişkiyi bozar; öncelikli rota ticareti artırır.',TR.map((m,i)=>dpBtn('data-dok',id+':tr:'+i,m[0],o.tr===i)).join(''))+opRow2('Göçmen anlaşması','İlişki +, huzur −, bütçe +.',GA.map((m,i)=>dpBtn('data-dok',id+':ga:'+i,m[0],o.ga===i)).join(''))+opRow2('Büyükelçilik','Ağırlıklı büyükelçi ilişkiyi güçlendirir.',DBE.map((x,i)=>`<button class="btn sm ${(o.be===undefined?1:o.be)===i?'':'sec'}" data-dbe="${id}:be:${i}">${x[0]}</button>`).join(''))+opRow2('Vize rejimi','Vizesiz geçiş turizmi ve ilişkiyi artırır.',DVZ.map((x,i)=>`<button class="btn sm ${(o.vz===undefined?1:o.vz)===i?'':'sec'}" data-dbe="${id}:vz:${i}">${x[0]}</button>`).join(''))+opRow2('Gümrük tarifesi','Ülkeye özel tarife farkı (eksi = indirim).','')+xrow('dtf');
  else w=xrow('dul');
  return `<div class="dxs" data-dxx="1"><div class="dxb"><div style="display:flex;justify-content:space-between;align-items:center"><b style="font-size:17px">${c[1]} · ${t[2]}</b>${sbtn('data-dxx="1"','Kapat')}</div><div class="dl" style="margin:2px 0 6px">İlişki ${nf(S.ul[id],0)}/100 · ${rl(S.ul[id])[0]}</div>${w}</div></div>`;}
function dxCard(c,full){const id=c[0],v=S.ul[id],[lb,k]=rl(v),op=full||S.usel===id,dm=S.dp.m[id]||0,fav=(S.fav||{})[id];
  const rows=op?`<div style="grid-column:1/-1;margin-top:4px"><div class="dl">${c[5]}${tvol(c[4])?' · '+tvol(c[4]):''}</div>${DXA.map(([a,ic,n])=>`<button class="dxa" data-dxa="${id}:${a}"><span>${ic}</span><b>${n}${a==='pk'&&pkN(id)?' · '+pkN(id)+' imzalı':''}</b><i>›</i></button>`).join('')}</div>`:'';
  return `<div class="lever"><span class="n"><button class="btn sm sec" style="min-width:0;padding:0 7px" data-dxf="${id}">${fav?'★':'☆'}</button> ${c[1]} <span class="st ${k}">${lb}</span> <span class="dl muted">· ${nf(v,0)}${dm?' · diplomat':''}${pkN(id)?' · '+pkN(id)+' anlaşma':''}</span></span>${op?'':`<span class="h">${c[5]}</span>`}<div class="step">${full?'':sbtn(`data-dxo="${id}"`,op?'Kapat':'Aç')}</div>${gbar(v,k)}${rows}</div>`;}
{const _p=dxP;dxP=function(){let h=_p();const n=(S.ta||[]).length+(S.pr||[]).length;
  if(S.dxt==='talep')h=h.replace('</div>','</div>'+(S.pr||[]).map((x,i)=>{const p=PKT.find(q=>q[0]===x.k);return `<div class="panel"><div class="dl"><b>${dxN(x.c)}</b>, ${p[1]} öneriyor. <span class="muted">${x.left} ay kaldı</span></div><div class="note">${p[2]}</div><div class="step">${sbtn(`data-dxr="${i}:1"`,'Kabul et',S.ul[x.c]<p[3]-10)}${sbtn(`data-dxr="${i}:0"`,'Reddet')}</div></div>`;}).join(''));
  if(n)h=h.replace(/(data-dxt="talep">Talepler)( \(\d+\))?/,`$1 (${n})`);return h+dxSheet();};}
V.dis=dxP;
if(document.addEventListener)document.addEventListener('click',ev=>{const t=ev.target.closest&&ev.target.closest('[data-dxa],[data-dxx],[data-dxp],[data-dxk],[data-dxg],[data-dxr]');if(!t)return;const d=t.dataset;
  if(d.dxx&&t.classList.contains('dxs')&&ev.target!==t)return;ev.stopPropagation();ev.preventDefault();
  if(d.dxa)S.dxm=d.dxa;else if(d.dxx)S.dxm=null;
  else if(d.dxp){const [id,k,on]=d.dxp.split(':');on==='1'?pkSign(id,k):pkBreak(id,k);}
  else if(d.dxk)dxKredi(d.dxk);
  else if(d.dxg){const [kd,i,id]=d.dxg.split(':');dxAct(kd,+i,id);}
  else if(d.dxr){const [i,ok]=d.dxr.split(':'),x=S.pr[+i];if(x){S.pr.splice(+i,1);if(ok==='1'){const p=PKT.find(q=>q[0]===x.k);pk(x.c)[x.k]=S.month+1;if(x.k==='tic')S.dl[x.c]=1;S.ul[x.c]=clamp(S.ul[x.c]+3,0,100);logA('Gelen öneri',dxN(x.c),p[1]+' kabul edildi.');}else S.ul[x.c]=clamp(S.ul[x.c]-1,0,100);}}
  save();render();},true);
