/* ek18: Dış İlişkiler — genişletilmiş anlaşma paketleri, ikili kredi (borç al/ver), özel kurallar ve ültimatom türleri */
PKT.push(['enj','Enerji Ortaklığı','Doğalgaz, elektrik ve boru hattı işbirliği: enerji maliyeti düşer.',55,35,.2,{enf:-.01,cari:-.006}],['ist','İstihbarat Paylaşımı','Ortak tehdit değerlendirmesi: güvenlik ve ordu güçlenir.',70,50,.3,{huz:.005,ord:.008}]);
const ULK=[['Ticaret tavizi','Gümrük ve kota indirimi iste.',{cari:-.012,acik:-.004}],['Deniz ve yetki alanı','Tartışmalı alanda taviz iste.',{des:.08,ord:.02,bat:-.01}],['Vatandaşları serbest bıraktır','Tutuklu vatandaşların iadesi.',{des:.1,huz:.02}],['Yaptırımı kaldır','Türkiye\'ye uygulanan kısıtlamaları kaldırmasını iste.',{rez:.1,enf:-.02}],['Resmî özür','Diplomatik özür iste.',{des:.12,bat:-.01}]];
const lentN=id=>(S.lent||[]).filter(l=>l.c===id);
function dxKredi(id){const c=CT.find(y=>y[0]===id),a=ui('krA',5),r=ui('krR',9),v=ui('krV',3);if(!c||avail()<1||S.loans.reduce((s,l)=>s+l.amt,0)+a>60)return;S.cur.spent+=1;const sm=su('kr'+id);suU('kr'+id);if(Math.random()<dxKp(id,a,r)){S.debt+=a;S.rez=Math.min(120,S.rez+a);S.borc=S.debt/S.gdp*100;S.loans.push({s:'ikili',c:id,amt:a,rate:r,end:S.month+v*12});S.ul[id]=clamp(S.ul[id]+2*sm,0,100);logA('Dış ilişkiler',c[1],`${a} mlr $ kredi alındı (%${r} faiz, ${v} yıl vade).`);}else{S.ul[id]=clamp(S.ul[id]-1,0,100);logA('Dış ilişkiler',c[1],'Kredi talebi reddedildi.');}hap(20,520);}
function dxVer(id){const c=CT.find(y=>y[0]===id),a=ui('lnA',5),r=ui('lnR',6),v=ui('lnV',3);S.lent=S.lent||[];if(!c||avail()<1||S.rez-a<8||S.lent.reduce((s,l)=>s+l.amt,0)+a>40)return;S.cur.spent+=1;const sm=su('kr'+id);suU('kr'+id);const p=clamp(.95-(r-3)/12+S.ul[id]/400,.1,.97);if(Math.random()<p){S.rez-=a;S.lent.push({c:id,amt:a,rate:r,end:S.month+v*12});S.ul[id]=clamp(S.ul[id]+3*sm,0,100);applyFx({bol:.01*sm});logA('Dış ilişkiler',c[1],`${a} mlr $ kredi verildi (%${r} faiz, ${v} yıl vade).`);}else logA('Dış ilişkiler',c[1],'Kredi teklifimizi kabul etmedi (faiz yüksek bulundu).');hap(20,520);}
function dxEarly(id,i){const L=S.loans.filter(l=>l.c===id),l=L[i];if(!l||S.rez-l.amt<8)return;S.rez-=l.amt;S.debt=Math.max(0,S.debt-l.amt);S.borc=S.debt/S.gdp*100;S.loans.splice(S.loans.indexOf(l),1);logA('Dış ilişkiler',dxN(id),`${nf(l.amt,1)} mlr $ kredi erken kapatıldı.`);hap(20,520);}
{const _y=yeniUp;yeniUp=function(){try{S.lent=S.lent||[];S.lent=S.lent.filter(l=>{S.rez=Math.min(120,S.rez+l.amt*l.rate/1200);if(Math.random()<.004*(1.4-S.ul[l.c]/100)){logA('Dış ilişkiler',dxN(l.c),`${nf(l.amt,1)} mlr $ kredi geri ödenmedi (temerrüt).`);S.ul[l.c]=clamp(S.ul[l.c]-10,0,100);return false;}if(l.end<=S.month){S.rez=Math.min(120,S.rez+l.amt);return false;}return true;});
  }catch(e){}return _y.apply(this,arguments);};}
function dxUlt(id,k){const c=CT.find(y=>y[0]===id),s=ui('ulS',3),x=ULK[k];S.ulc=S.ulc||{};if(!c||!x||!ulOk(id,k)||S.month-(S.ulc[id]===undefined?-99:S.ulc[id])<6)return;S.ulc[id]=S.month;const m=su('dxu'+id);suU('dxu'+id);const p=clamp(.1+(gucu()-(CG[id]??45))/100+S.ul[id]/500,.05,.8)*(1.2-s*.06);
  if(Math.random()<p){S.ul[id]=clamp(S.ul[id]-s*1.6,0,100);const f={};for(const q in x[2])f[q]=x[2][q]*s*m;applyFx(f);logA('Ültimatom',c[1],x[0]+': başarılı. '+(fxText(f)||''));}else{S.ul[id]=clamp(S.ul[id]-s*4,0,100);applyFx({des:-.12*s,ord:-.04*s});logA('Ültimatom',c[1],x[0]+': başarısız; ilişki ve itibar zarar gördü.');}hap(20,520);}
function dxSheet(){const [id,k]=(S.dxm||'').split(':'),c=CT.find(x=>x[0]===id);if(!c||!k)return '';const o=okc(id),t=DXA.find(x=>x[0]===k);let w='';
  if(k==='tem')w=uRows(c,false)+`<div class="step" style="margin-top:6px">${sbtn(`data-us="${id}"`,'Sert açıklama')}</div>`;
  else if(k==='yat'){const m=DEALS.filter(e=>DQ[e[0]]&&DQ[e[0]].includes(id));w=m.length?m.map(dRow).join(''):'<div class="note">Bu ülkeyle imzalanabilecek özel anlaşma yok. Genel anlaşmalar Anlaşmalar sekmesinde.</div>';}
  else if(k==='pk'){const n=pkN(id),mo=Object.keys(pk(id)).reduce((s,q)=>s+((PKT.find(x=>x[0]===q)||[])[5]||0),0);w=`<div class="note" style="margin:0 0 4px">İmzalı ${n}/${PKT.filter(p=>pkOk(id,p[0])).length} · aylık toplam ilişki +${nf(mo,2)}. Her imza 1 puan harcar.</div>`+PKT.filter(p=>pkOk(id,p[0])).map(p=>{const on=pk(id)[p[0]],ok=S.ul[id]>=p[3];return opRow2(p[1]+(on?' ✓ '+(S.month+1-on)+' aydır':''),`${p[2]} Aylık: ilişki +${p[5]}${fxText(p[6])?' · '+fxText(p[6]):''}. İmza eşiği ${p[3]}, bozulma eşiği ${p[4]}.`,on?sbtn(`data-dxp="${id}:${p[0]}:0"`,'Feshet'):sbtn(`data-dxp="${id}:${p[0]}:1"`,ok?'İmzala':'İlişki '+p[3]+' gerek',!ok||avail()<1));}).join('');}
  else if(k==='kr'){const a=ui('krA',5),r=ui('krR',9),v=ui('krV',3),p=dxKp(id,a,r),mine=S.loans.filter(l=>l.c===id),ln=lentN(id),la=ui('lnA',5),lr=ui('lnR',6),lv=ui('lnV',3);
    w=`<div class="dl"><b>Aramızdaki krediler</b></div>${mine.length?mine.map((l,i)=>`<div class="lever"><span class="n">Aldığımız: ${nf(l.amt,1)} mlr $</span><span class="h">%${l.rate} faiz · ${Math.max(0,l.end-S.month)} ay kaldı · aylık faiz ${nf(l.amt*l.rate/1200,2)} mlr $</span><div class="step">${sbtn(`data-dxe="${id}:${i}"`,'Erken kapat',S.rez-l.amt<8)}</div></div>`).join(''):''}${ln.map(l=>`<div class="dl">Verdiğimiz: ${nf(l.amt,1)} mlr $ · %${l.rate} · ${Math.max(0,l.end-S.month)} ay kaldı · aylık gelir ${nf(l.amt*l.rate/1200,2)} mlr $</div>`).join('')}${mine.length||ln.length?'':'<div class="dl muted">Henüz kredi yok.</div>'}
    <div class="dl" style="margin-top:10px"><b>Borç iste</b></div><div class="dl">Tutar: ${a} mlr $</div>${sld('krA',1,30,1,a)}<div class="dl">Faiz: %${r}/yıl</div>${sld('krR',3,16,.5,r)}<div class="dl">Vade: ${v} yıl</div>${sld('krV',1,10,1,v)}<div class="note">Kabul olasılığı <b>%${nf(p*100,0)}</b> · yıllık faiz yükü ${nf(a*r/100,2)} mlr $ · toplam dış borç ${nf(S.loans.reduce((s,q)=>s+q.amt,0),1)}/60 mlr $.</div><div class="step">${sbtn(`data-dxk="${id}"`,'Teklif et')}</div>
    <div class="dl" style="margin-top:10px"><b>Kredi ver</b></div><div class="dl">Tutar: ${la} mlr $</div>${sld('lnA',1,20,1,la)}<div class="dl">Faiz: %${lr}/yıl</div>${sld('lnR',2,12,.5,lr)}<div class="dl">Vade: ${lv} yıl</div>${sld('lnV',1,8,1,lv)}<div class="note">Rezervden çıkar; aylık faiz geliri ${nf(la*lr/1200,2)} mlr $. Karşı taraf düşük faizi daha kolay kabul eder; temerrüt riski ilişki yükseldikçe azalır. Verilen toplam ${nf((S.lent||[]).reduce((s,q)=>s+q.amt,0),1)}/40 mlr $.</div><div class="step">${sbtn(`data-dxv="${id}"`,'Kredi ver',S.rez-la<8)}</div>`;}
  else if(k==='ok')w=(TRN.includes(id)?opRow2('Transit rotası','Kapalı rota ilişkiyi bozar; öncelikli rota ticareti artırır.',TR.map((m,i)=>dpBtn('data-dok',id+':tr:'+i,m[0],o.tr===i)).join('')):'')+(GCM.includes(id)?opRow2('Göçmen anlaşması','İlişki +, huzur −, bütçe +.',GA.map((m,i)=>dpBtn('data-dok',id+':ga:'+i,m[0],o.ga===i)).join('')):'')+opRow2('Diplomat','Ekonomik mod ilişkiyi, askerî mod ordu ilişkisini de artırır; her diplomat bütçeye küçük yük bindirir.',DM.map((m,i)=>dpBtn('data-dpm',id+':'+i,m[0],(S.dp.m[id]||0)===i)).join(''))+opRow2('Büyükelçilik','Ağırlıklı büyükelçi ilişkiyi güçlendirir.',DBE.map((x,i)=>`<button class="btn sm ${(o.be===undefined?1:o.be)===i?'':'sec'}" data-dbe="${id}:be:${i}">${x[0]}</button>`).join(''))+opRow2('Vize rejimi','Vizesiz geçiş turizmi ve ilişkiyi artırır.',DVZ.map((x,i)=>`<button class="btn sm ${(o.vz===undefined?1:o.vz)===i?'':'sec'}" data-dbe="${id}:vz:${i}">${x[0]}</button>`).join(''))+opRow2('Gümrük tarifesi','Ülkeye özel tarife farkı (eksi = indirim).','')+xrow('dtf');
  else{const s=ui('ulS',3),ks=ulKs(id),lk=S.month-((S.ulc||{})[id]===undefined?-99:S.ulc[id]),p=clamp(.1+(gucu()-(CG[id]??45))/100+S.ul[id]/500,.05,.8)*(1.2-s*.06);
    w=`<div class="dl"><b>Talep</b></div><div class="chips">${ULK.map((x,i)=>ulOk(id,i)?`<button class="btn sm ${ks===i?'':'sec'}" data-dxs2="${i}">${x[0]}</button>`:'').join('')}</div><div class="note">${ULK[ks][1]} Başarıda: ${fxText(Object.fromEntries(Object.entries(ULK[ks][2]).map(([q,v])=>[q,v*s])))||'-'}.</div><div class="dl">Sertlik: ${s}/10</div>${sld('ulS',1,10,1,s)}<div class="note">Başarı şansı ≈ <b>%${nf(p*100,0)}</b> (savaş gücü ve ilişkiye bağlı). Başarıda ilişki −${nf(s*1.6,1)}; başarısızlıkta ilişki −${nf(s*4,1)}, halk desteği −${nf(s*.12,1)}, ordu −${nf(s*.04,2)}. Aynı ülkeye 6 ayda bir verilebilir${lk<6?' (kalan '+(6-lk)+' ay)':''}.</div><div class="step">${sbtn(`data-dxu="${id}:${ks}"`,'Ültimatom ver',lk<6)}</div>`;}
  return `<div class="dxs" data-dxx="1"><div class="dxb"><div style="display:flex;justify-content:space-between;align-items:center"><b style="font-size:17px">${c[1]} · ${t[2]}</b>${sbtn('data-dxx="1"','Kapat')}</div><div class="dl" style="margin:2px 0 6px">İlişki ${nf(S.ul[id],0)}/100 · ${rl(S.ul[id])[0]}</div>${w}</div></div>`;}
if(document.addEventListener)document.addEventListener('click',ev=>{const t=ev.target.closest&&ev.target.closest('[data-dxe],[data-dxv],[data-dxu],[data-dxs2]');if(!t)return;ev.stopPropagation();ev.preventDefault();const d=t.dataset;
  if(d.dxe){const [id,i]=d.dxe.split(':');dxEarly(id,+i);}else if(d.dxv)dxVer(d.dxv);else if(d.dxu){const [id,k]=d.dxu.split(':');dxUlt(id,+k);}else if(d.dxs2)S.ui.ulK=+d.dxs2;
  save();render();},true);

/* eski kayıtlardan kaldırılan paketleri temizle */
{const _c=dxMonth;dxMonth=function(){try{Object.keys(S.pk||{}).forEach(id=>Object.keys(S.pk[id]).forEach(k=>{if(!PKT.some(p=>p[0]===k))delete S.pk[id][k];}));S.pr=(S.pr||[]).filter(x=>PKT.some(p=>p[0]===x.k));}catch(e){}return _c.apply(this,arguments);};}
{const _r=render;render=function(){try{Object.keys(S.pk||{}).forEach(id=>Object.keys(S.pk[id]).forEach(k=>{if(!PKT.some(p=>p[0]===k))delete S.pk[id][k];}));if(S.pr)S.pr=S.pr.filter(x=>PKT.some(p=>p[0]===x.k));}catch(e){}return _r.apply(this,arguments);};}
