/* ek23: ek temalar (Meclis Gecesi, Gazete Baskısı, Kızıl Salon), rahat yoğunluk, karar kartı renk kodu, kriz manşeti */
const TEMA2=[['meclis','Meclis Gecesi','Cormorant+Garamond:wght@600;700&family=Source+Sans+3:wght@400;600'],['gazete','Gazete Baskısı','Playfair+Display:wght@700;900&family=Source+Serif+4:wght@400;600'],['kizil','Kızıl Salon','Fraunces:wght@600;800&family=Work+Sans:wght@400;600']];
function temaFont(){try{const t=document.documentElement.getAttribute('data-theme'),x=TEMA2.find(a=>a[0]===t);if(!x||document.getElementById('tf-'+t))return;const l=document.createElement('link');l.id='tf-'+t;l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family='+x[2]+'&display=swap';document.head.appendChild(l);}catch(e){}}
{const _a=arayuzApply;arayuzApply=function(){_a.apply(this,arguments);try{const d=document.documentElement;if(ls('km-dn')==='rahat')d.setAttribute('data-dens','rahat');else d.removeAttribute('data-dens');}catch(e){}temaFont();};}
{const _e=eventCard;eventCard=function(e,i){let h=_e.apply(this,arguments);try{const d=EVB[e.id];h=h.replace('<article class="card ','<article class="card cat-'+d.g+' ');if(d.g==='kriz'&&e.ch===null)h=h.replace('<div class="tag">','<div class="live"><i></i>SON DAKİKA · CANLI</div><div class="tag">');}catch(x){}return h;};}
const ayarT=()=>{const cur=ls('km-th')||'auto',rh=ls('km-dn')==='rahat';return `<div class="panel"><div class="dl">Ek temalar</div><div class="chips" style="margin:6px 0 4px">${TEMA2.map(([v,n])=>`<button class="btn sm ${cur===v?'':'sec'}" data-th="${v}">${n}</button>`).join('')}</div></div><div class="panel"><div class="dl">Görünüm yoğunluğu</div><div class="chips" style="margin:6px 0 4px"><button class="btn sm ${rh?'sec':''}" data-set="km-dn:kompakt">Kompakt</button><button class="btn sm ${rh?'':'sec'}" data-set="km-dn:rahat">Rahat</button></div><div class="note">Rahat: büyük dokunma alanı ve geniş boşluk. Kompakt: ekranda daha çok bilgi.</div></div>`;};
{const _k=karar;karar=function(){let h=_k.apply(this,arguments);try{(S.cur.events||[]).forEach((e,i)=>{const d=EVB[e.id];if(d)h=h.replace('data-evo="'+i+'"','data-evo="'+i+'" data-cat="'+d.g+'"');});}catch(x){}return h;};V.karar=karar;}
{const _r=render;render=function(){const x=_r.apply(this,arguments);temaFont();return x;};}
arayuzApply();
