/* ---------- ek3.js: parametrik eylem çerçevesi (yüzde / miktar kaydırıcılı kararlar) + ekonomi genişlemesi ---------- */
let XM=1;
const xkey=n=>{let h=7;for(const c of n)h=(h*31+c.charCodeAt(0))%99991;return 'xs_'+h;};
document.addEventListener('click',e=>{XM=1;const t=e.target.closest&&e.target.closest('button');if(!t)return;const r=t.closest('[data-xk]');if(r&&S&&S.ui&&S.ui[r.dataset.xk])XM=S.ui[r.dataset.xk]/100;setTimeout(()=>{XM=1;},0);},true);
const XD={};
/* xd(id,{g:grup,t:başlık,d:açıklama,lo,hi,st,v,lab:v=>etiket,r:v=>sonuç yazısı,fx:v=>etki,ap:(v,m)=>özel etki,ok:v=>engel metni}) */
const xd=(id,o)=>{XD[id]=o;return id;};
const gtL=()=>S.gdp*S.kur;
function xrow(id){const o=XD[id];if(!o)return '';const v=clamp(ui('xa_'+id,o.v),o.lo,o.hi),last=(S.xr||{})[id],bad=o.ok&&o.ok(v);
  return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${o.t}</b> · ${o.lab(v)}<div class="note" style="margin:2px 0 0">${o.r(v)}</div></div>${sld('xa_'+id,o.lo,o.hi,o.st,v)}<div class="note" style="margin:2px 0 4px">${o.d}</div><div class="chips" style="margin:0">${sbtn(`data-xa="${id}"`,o.btn||'Uygula',bad)}</div>${bad?`<div class="note">${bad}</div>`:''}${last?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(last.m)}): ${last.t}</div>`:''}</div>`;}
const xpan=(t,ids,note)=>`<div class="panel"><b>${t}</b>${ids.map(xrow).join('')}${note?`<div class="note">${note}</div>`:''}</div>`;
function xdo(id){const o=XD[id];if(!o)return;const v=clamp(ui('xa_'+id,o.v),o.lo,o.hi);if(o.ok&&o.ok(v))return;const m=su('xa'+id);suU('xa'+id);if(o.ap)o.ap(v,m);if(o.fx)applyFx(sfx2(o.fx(v),m));S.xr=S.xr||{};const tx=o.r(v)+sat(m);S.xr[id]={m:S.month,t:tx};logA(o.g||'Karar',o.t,o.lab(v));hap(20,520);save();render();}
function ek3Click(t){const d=t.dataset;
  if(d.xa){xdo(d.xa);return true;}
  if(d.ozs){const [id]=d.ozs.split(':');ozPay(id);return true;}
  if(d.ozm){const [id,i]=d.ozm.split(':');S.ui['ozm_'+id]=+i;render();return true;}
  if(d.tarz){tarSet();return true;}
  return false;}
{const _a=arayuzClick;arayuzClick=function(t){return ek3Click(t)||_a(t);};}
/* ---------- Piyasa araçları: miktar / oran ayarlı ---------- */
const pz=()=>S.pz||(S.pz={kn:50,fb:0,b:100}),R1=x=>nf(x,x!==0&&Math.abs(x)<.095?2:1);
xd('sw',{g:'Piyasa',t:'Merkez bankası swap hattı',d:'Körfez ve Çin merkez bankalarıyla yerel para swapı. Brüt hat büyüdükçe güven artar; hattın %40\'ı net rezerve yansır.',lo:1,hi:40,st:1,v:10,lab:v=>v+' mlr $ hat',r:v=>`Net rezerv +${R1(v*.4)} mlr $ · kredi notu güveni +${R1(v*.05)}.`,fx:v=>({rez:v*.4}),ap:(v,m)=>{pz().kn=clamp(pz().kn+v*.05*m,0,100);}});
xd('dvt',{g:'Piyasa',t:'Döviz mevduatına ek vergi',d:'Liraizasyon için döviz hesaplarından alınan ek vergi. Tasarruf sahipleri tepkilidir.',lo:0,hi:15,st:1,v:3,lab:v=>'%'+v+' ek vergi',r:v=>`Rezerv +${R1(v*.15)} mlr $ · kur baskısı ${R1(v*.08)} puan azalır · halk desteği −${R1(v*.03)}.`,fx:v=>({rez:v*.15,kur:-v*.08,des:-v*.03})});
xd('ha',{g:'Piyasa',t:'Halka arz teşviki',d:'Halka arzlarda kurumlar vergisi indirimi ve hızlı onay.',lo:0,hi:100,st:10,v:30,lab:v=>'%'+v+' vergi indirimi',r:v=>`Borsa +%${R1(v*.04)} · bütçe maliyeti ${tl(v*.0006)}.`,fx:v=>({acik:v*.0006}),ap:(v,m)=>{pz().b*=1+v*.04*m/100;}});
xd('tem',{g:'Piyasa',t:'Temettü stopajı indirimi',d:'Hisse senedi temettüsünde stopaj oranı düşürülür.',lo:0,hi:10,st:1,v:3,lab:v=>v+' puan indirim',r:v=>`Borsa +%${R1(v*.4)} · yabancı girişi +${R1(v*.08)} mlr $/ay · maliyet ${tl(v*.006)}.`,fx:v=>({acik:v*.006}),ap:(v,m)=>{pz().b*=1+v*.4*m/100;pz().fb=(pz().fb||0)+v*.08*m;}});
xd('vf',{g:'Piyasa',t:'Varlık Fonu ile borsaya destek',d:'Kamu fonu hisse alır; piyasa yükselir, şeffaflık eleştirilir.',lo:5,hi:200,st:5,v:30,lab:v=>v+' milyar ₺ alım',r:v=>{const p=v/gtL()*100;return `Borsa +%${R1(p*25)} · bütçe maliyeti ${tl(p)} · MB güvenilirliği −${R1(p*2)}.`;},fx:v=>({acik:v/gtL()*100}),ap:(v,m)=>{pz().b*=1+v/gtL()*100*25*m/100;S.gv=clamp(S.gv-v/gtL()*100*2*m,0,100);}});
xd('kkm',{g:'Piyasa',t:'Kur korumalı mevduattan çıkış',d:'KKM hesapları kademeli TL\'ye dönüştürülür; bütçe rahatlar, kur kısa süre oynar.',lo:5,hi:100,st:5,v:25,lab:v=>'stokun %'+v+'\'i',r:v=>`Bütçe yükü ${tl(v*.0015)} azalır · kur +%${R1(v*.012)} · güven +${R1(v*.01)}.`,fx:v=>({acik:-v*.0015,kur:v*.012}),ap:(v,m)=>{pz().kn=clamp(pz().kn+v*.01*m,0,100);}});
xd('tst',{g:'Piyasa',t:'Yabancıya tahvil stopaj istisnası',d:'DİBS faiz gelirinde stopaj düşer; sıcak para girer.',lo:0,hi:15,st:1,v:5,lab:v=>v+' puan indirim',r:v=>`Yabancı girişi +${R1(v*.1)} mlr $/ay · maliyet ${tl(v*.003)}.`,fx:v=>({acik:v*.003}),ap:(v,m)=>{pz().fb=(pz().fb||0)+v*.1*m;}});
xd('rs',{g:'Piyasa',t:'Yatırımcı toplantıları (roadshow)',d:'Hazine ve MB ekibi New York, Londra ve Körfez\'de yatırımcıyla görüşür.',lo:1,hi:10,st:1,v:3,lab:v=>v+' şehir turu',r:v=>`Güven +${R1(v*.3)} · yabancı girişi +${R1(v*.15)} mlr $/ay · maliyet ${tl(v*.004)}.`,fx:v=>({acik:v*.004}),ap:(v,m)=>{pz().kn=clamp(pz().kn+v*.3*m,0,100);pz().fb=(pz().fb||0)+v*.15*m;}});
xd('as',{g:'Piyasa',t:'Açığa satış yasağı',d:'Çöküş anlarında spekülasyonu keser; yabancı yatırımcı temkinli olur.',lo:5,hi:90,st:5,v:20,lab:v=>v+' gün yasak',r:v=>`Borsa +%${R1(v*.04)} · yabancı girişi −${R1(v*.01)} mlr $/ay · Batı itibarı −${R1(v*.001)}.`,fx:v=>({bat:-v*.001}),ap:(v,m)=>{pz().b*=1+v*.04*m/100;pz().fb=(pz().fb||0)-v*.01*m;}});
xd('bsk',{g:'Piyasa',t:'Bankacılık sermaye artırımı',d:'Bankalar sermaye tamponunu artırır; kredi büyümesi yavaşlar, sistem sağlamlaşır.',lo:1,hi:5,st:.5,v:2,lab:v=>'+'+v+' puan sermaye tamponu',r:v=>`Güven +${R1(v*.8)} · kredi büyümesi −%${R1(v*.15)} GSYH.`,fx:v=>({buy:-v*.15}),ap:(v,m)=>{pz().kn=clamp(pz().kn+v*.8*m,0,100);}});
const _pzX=pzX;pzX=function(){return xpan('Piyasa araçları · miktar ve oran ayarlı',['sw','dvt','ha','tem','vf','kkm','tst','rs','as','bsk'],'Kaydırıcıyla miktarı seçersin; sonuç satırı o değerin tahmini etkisini gösterir. Aynı aracı tekrar kullanmak etkisini azaltır.')+_pzX();};
/* ---------- Özelleştirme: yüzdesel hisse satışı ve yöntem ---------- */
const OZY=[['Stratejik ortak (blok)','Tek yatırımcıya devir: en yüksek bedel (x1,0), en sert tepki.',1,1,0],['Halka arz','Borsada hisse satışı: x0,75 bedel, tepkiyi azaltır, borsayı canlandırır.',.75,.5,3],['Yönetim hakkı devri','Mülkiyet devlette kalır; x0,5 bedel, hafif tepki.',.5,.3,0],['Çalışanlara hisse','İşçilere ve emeklilere: x0,4 bedel, sendika tepkisi azalır.',.4,.1,1],['Varlık Fonu\'na aktarım','Kamu içi devir: x0,6 bedel, yabancı güveni artmaz.',.6,.15,0],['Kira sertifikası (sukuk)','Varlığa dayalı borçlanma; x0,55 bedel, mülkiyet kalır.',.55,.2,0]];
const ozSold=id=>S.oz2&&S.oz2[id]!==undefined?100:((S.oz3||{})[id]||0);
function ozPay(id){const v=OZV.find(x=>x[0]===id);if(!v)return;S.oz3=S.oz3||{};const mo=ui('ozm_'+id,0),M=OZY[mo],left=100-ozSold(id),p=Math.min(left,ui('ozp_'+id,20));if(p<=0)return;const sm=su('oz'+id);suU('oz'+id);const g=v[2]*M[2]*p/100*Math.min(1.5,sm);
  S.oz3[id]=ozSold(id)+p;if(S.oz3[id]>=100){S.oz2=S.oz2||{};S.oz2[id]=Math.min(2,mo);}
  applyFx({rez:g*.6,acik:-g/S.gdp*100*.8,des:-(.2*M[3]+.05*v[3]*M[3])*p/100});S.acikP=(S.acikP||0)-g/S.gdp*100*.25;S.gr.kamu=clamp(S.gr.kamu-v[3]*M[3]*p/100,5,95);if(S.pz)S.pz.b*=1+M[4]*p/100/100*3;if(S.lb&&S.lb.sen)S.lb.sen.t=clamp(S.lb.sen.t-v[3]*M[3]*p/100*1.5,-100,100);
  S.xr=S.xr||{};S.xr['oz_'+id]={m:S.month,t:`%${p} hisse (${M[0]}) satıldı: ${R1(g)} mlr $ gelir; rezerve ve bütçeye aktı.`};logA('Özelleştirme',v[1],`%${p} · ${M[0]} · ${R1(g)} mlr $`);hap(20,520);save();render();}
const ozPanel=()=>{S.oz3=S.oz3||{};return `<h2>Özelleştirme · hisse satışı</h2><div class="panel">${OZV.map(v=>{const id=v[0],sold=ozSold(id),left=100-sold,mo=ui('ozm_'+id,0),M=OZY[mo],p=Math.min(left,ui('ozp_'+id,20)),g=v[2]*M[2]*p/100,last=(S.xr||{})['oz_'+id];
  return `<div style="padding:8px 0;border-top:1px solid var(--line)"><b>${v[1]}</b> <span class="muted">· devlet payı %${left} · değer ${nf(v[2],1)} mlr $</span><div class="note" style="margin:2px 0">${v[4]}</div>${left<=0?'<span class="st good">Tamamı satıldı</span>':`<div class="chips" style="margin:4px 0">${OZY.map((m,i)=>`<button class="btn sm ${mo===i?'':'sec'}" data-ozm="${id}:${i}">${m[0]}</button>`).join('')}</div><div class="dl">Satış: %${p} hisse · tahmini gelir ${R1(g)} mlr $ · tepki ${R1(v[3]*M[3]*p/100)} puan<div class="note" style="margin:2px 0 0">${M[1]}</div></div>${sld('ozp_'+id,5,left,5,p)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-ozs="${id}"`,'Hisse sat')}</div>`}${last?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(last.m)}): ${last.t}</div>`:''}</div>`;}).join('')}<div class="note">Hisseler birkaç seferde satılabilir. Gelir rezerve ve bütçeye gider; kamu çalışanları ve sendikalar tepki gösterir.</div></div>`;};
{const _s=sektor2;sektor2=function(){const h=_s(),i=h.indexOf('<h2>Özelleştirme</h2>');return (i<0?h:h.slice(0,i))+ozPanel();};}
/* ---------- Ek gümrük tarifesi: yüzdesel + sonuç ---------- */
function tarSet(){const v=ui('tarv',S.tar);if(avail()<1||v===S.tar)return;S.cur.spent+=1;const old=S.tar;S.tar=clamp(v,0,40);const d=S.tar-old;S.xr=S.xr||{};S.xr.tar={m:S.month,t:tarRes(S.tar,old)};logA('Dış ticaret','Ek gümrük tarifesi',`%${old} → %${S.tar}`);save();render();}
const tarRes=(v,old)=>{const d=v-(old===undefined?S.tar:old);return `İthalat yaklaşık ${d>=0?'−':'+'}%${R1(Math.abs(d)*.45)} · enflasyon ${d>=0?'+':'−'}${R1(Math.abs(d)*.1)} puan · gümrük geliri ${d>=0?'+':'−'}${tl(Math.abs(d)*.012)} · yerli sanayi ${d>=0?'+':'−'}${R1(Math.abs(d)*.2)} puan · Batı itibarı ${d>=0?'−':'+'}${R1(Math.abs(d)*.04)}${v>8?' · yüksek oran: karşı tarife riski':''}.`;};
const tarP=()=>{const v=ui('tarv',S.tar),l=(S.xr||{}).tar;return `<div class="panel"><b>Ek gümrük tarifesi · yüzdesel ayar</b><div class="dl">Hedef: %${v} (şu an %${S.tar})<div class="note" style="margin:2px 0 0">${v===S.tar?'Değişiklik yok.':tarRes(v)}</div></div>${sld('tarv',0,40,1,v)}<div class="chips" style="margin:4px 0 0">${sbtn('data-tarz="1"','Tarifeyi uygula',avail()<1||v===S.tar)}</div>${l?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`:''}</div>`;};
/* ---------- Ticaret politikaları: oran / hacim ayarlı ---------- */
xd('ek',{g:'Dış ticaret',t:'Eximbank ihracat kredisi hacmi',d:'Döviz kazandırana ucuz kredi; hacim büyüdükçe bütçe maliyeti artar.',lo:1,hi:30,st:1,v:6,lab:v=>v+' mlr $ kredi',r:v=>`İhracat +%${R1(v*.4)} (12 ay) · maliyet ${tl(v*.008)}.`,fx:v=>({acik:v*.008}),ap:(v,m)=>{S.txb=(S.txb||[]).concat([{x:v*.4*m/100,m:0,left:12,n:'Eximbank kredisi %'+v}]);}});
xd('dmp',{g:'Dış ticaret',t:'Dampinge karşı ek vergi',d:'Ucuz çelik, tekstil ve elektronik ithalatına ek vergi.',lo:5,hi:60,st:5,v:15,lab:v=>'%'+v+' ek vergi',r:v=>`İthalat −%${R1(v*.08)} (12 ay) · enflasyon +${R1(v*.01)} · Çin ilişkisi −${R1(v*.12)}.`,fx:v=>({enf:v*.01,rel:{chn:-v*.12}}),ap:(v,m)=>{S.txb=(S.txb||[]).concat([{x:0,m:-v*.08*m/100,left:12,n:'Damping vergisi %'+v}]);}});
xd('kot',{g:'Dış ticaret',t:'Altın ve lüks ithalat kotası',d:'Cari açığı büyüten altın ve lüks tüketim ithalatına miktar sınırı.',lo:5,hi:60,st:5,v:20,lab:v=>'ithalatta %'+v+' kısıt',r:v=>`İthalat −%${R1(v*.1)} (12 ay) · halk desteği −${R1(v*.01)} · Batı itibarı −${R1(v*.003)}.`,fx:v=>({des:-v*.01,bat:-v*.003}),ap:(v,m)=>{S.txb=(S.txb||[]).concat([{x:0,m:-v*.1*m/100,left:12,n:'İthalat kotası %'+v}]);}});
xd('ara',{g:'Dış ticaret',t:'Ara malı gümrüğünü indir',d:'Sanayi girdisinde gümrük indirimi; üretim maliyeti düşer.',lo:1,hi:15,st:1,v:4,lab:v=>v+' puan indirim',r:v=>`İthalat +%${R1(v*.3)} · enflasyon −${R1(v*.01)} · ihracat +%${R1(v*.2)} · maliyet ${tl(v*.01)}.`,fx:v=>({enf:-v*.01,acik:v*.01}),ap:(v,m)=>{S.txb=(S.txb||[]).concat([{x:v*.2*m/100,m:v*.3*m/100,left:12,n:'Ara malı gümrük indirimi'}]);}});
xd('fuar',{g:'Dış ticaret',t:'Fuar ve ticaret heyeti programı',d:'Yeni pazarlarda fuar katılımı ve ticaret heyetleri.',lo:1,hi:20,st:1,v:5,lab:v=>v+' ülkede program',r:v=>`İhracat +%${R1(v*.3)} (12 ay) · maliyet ${tl(v*.004)}.`,fx:v=>({acik:v*.004}),ap:(v,m)=>{S.txb=(S.txb||[]).concat([{x:v*.3*m/100,m:0,left:12,n:v+' ülkede fuar programı'}]);}});
xd('hdg',{g:'Dış ticaret',t:'İhracatçıya kur sigortası',d:'Kur dalgalanmasına karşı devlet destekli sigorta.',lo:1,hi:50,st:1,v:10,lab:v=>v+' mlr $ teminat',r:v=>`İhracat +%${R1(v*.12)} (12 ay) · maliyet ${tl(v*.006)}.`,fx:v=>({acik:v*.006}),ap:(v,m)=>{S.txb=(S.txb||[]).concat([{x:v*.12*m/100,m:0,left:12,n:'Kur sigortası'}]);}});
{const _t=ticX;ticX=function(){return tarP()+xpan('Ticaret politikaları · oran ve hacim ayarlı',['ek','dmp','kot','ara','fuar','hdg'],'Etkiler 12 ay sürer; aynı önlem tekrarlandıkça etkisi azalır.')+_t();};}
/* ---------- BDDK ---------- */
xd('kk',{g:'BDDK',t:'Kredi kartı taksit ve limit düzenlemesi',d:'Taksit sayısı ve limit sıkılaştırılır ya da gevşetilir (eksi = gevşet).',lo:-5,hi:5,st:.5,v:1,lab:v=>(v>=0?'+':'')+v+' puan sıkılaştırma',r:v=>`Tüketim talebi ${v>=0?'−':'+'}${R1(Math.abs(v)*.08)} · enflasyon ${v>=0?'−':'+'}${R1(Math.abs(v)*.05)} · halk desteği ${v>=0?'−':'+'}${R1(Math.abs(v)*.1)}.`,fx:v=>({buy:-v*.08,enf:-v*.05,des:-v*.1})});
xd('ltv',{g:'BDDK',t:'Konut kredisi peşinat oranı (LTV)',d:'Konut kredisinde peşinat zorunluluğu değişir.',lo:-10,hi:20,st:5,v:5,lab:v=>(v>=0?'+':'')+v+' puan peşinat',r:v=>`Konut talebi ${v>=0?'−':'+'}%${Math.abs(v)*.8} · kira enflasyonu ${v>=0?'−':'+'}${R1(Math.abs(v)*.01)} · inşaat sektörü ${v>=0?'zayıflar':'canlanır'}.`,fx:v=>({buy:-v*.012,enf:-v*.01,isz:v*.01})});
xd('kft',{g:'BDDK',t:'Bireysel kredi faiz tavanı',d:'Bireysel ihtiyaç kredilerinde azami faiz sınırı.',lo:-10,hi:10,st:1,v:0,lab:v=>(v>=0?'+':'')+v+' puan',r:v=>`Tüketim ${v<0?'+':'−'}${R1(Math.abs(v)*.05)} · enflasyon ${v<0?'+':'−'}${R1(Math.abs(v)*.03)} · halk desteği ${v<0?'+':'−'}${R1(Math.abs(v)*.04)}.`,fx:v=>({buy:-v*.05,enf:-v*.03,des:-v*.04})});
xd('sy',{g:'BDDK',t:'Bankalara sermaye yeterlilik şartı',d:'Sermaye yeterlilik rasyosu üst sınırı; sistem sağlamlaşır, kredi daralır.',lo:0,hi:6,st:.5,v:1,lab:v=>'+'+v+' puan şart',r:v=>`Güven +${R1(v*.6)} · kredi −%${R1(v*.1)} GSYH · bankalar kâr uyarısı verir.`,fx:v=>({buy:-v*.1}),ap:(v,m)=>{pz().kn=clamp(pz().kn+v*.6*m,0,100);}});
xd('ys',{g:'BDDK',t:'Yabancı para kredi kısıtı',d:'Yurt içi şirketlerin döviz borçlanması sınırlanır.',lo:0,hi:40,st:5,v:10,lab:v=>'%'+v+' kısıt',r:v=>`Kur riski azalır (kur −%${R1(v*.04)}) · yatırım −${R1(v*.02)} puan büyüme.`,fx:v=>({kur:-v*.04,buy:-v*.02})});
const bddkP=()=>xpan('BDDK · bankacılık düzenlemeleri',['kk','ltv','kft','sy','ys'],'Sonuçlar satır altında yazılır; sıkı düzenleme enflasyonu düşürür ama büyümeyi yavaşlatır.');
/* ---------- Hazine: iç borçlanma çeşitleri ve geri alım ---------- */
const ib=(id,t,d,rt,fxk,ap)=>xd(id,{g:'Hazine',t,d,lo:50,hi:1500,st:50,v:300,lab:v=>nf(v,0)+' milyar ₺ ihale',r:v=>{const X=v/gtL()*100;return `GSYH'nin %${nf(X,2)}'i · yıllık faiz yükü ≈ ${tl(X*(S.lv.faiz+rt)/100)} · ${fxk(X)}`;},fx:v=>({}),ap:(v,m)=>{const X=v/gtL()*100*m;S.idb=(S.idb||0)+X;ap(X);}});
ib('i1','TL sabit faizli tahvil (2 yıl)','Standart bono; piyasa faiziyle ihale edilir.',2,X=>`enflasyon +${R1(.05*X)} · kredi talebi −${R1(.06*X)}.`,X=>applyFx({enf:.05*X,buy:-.06*X,rez:.02*X}));
ib('i2','TÜFE\'ye endeksli tahvil (5 yıl)','Enflasyona endeksli; ucuz görünür ama enflasyon yükselirse maliyet artar.',0,X=>`faiz yükü enflasyona bağlı · kredi talebi −${R1(.05*X)}.`,X=>{applyFx({buy:-.05*X,rez:.02*X});S.idb+=X*.15;});
ib('i3','Kira sertifikası (sukuk, 3 yıl)','Varlığa dayalı İslami finansman; Körfez yatırımcısı ilgi gösterir.',1,X=>`rezerv +${R1(.04*X)} · Körfez ilişkisi +${R1(X*.1)}.`,X=>{applyFx({rez:.04*X,rel:{sau:X*.1,qat:X*.1,uae:X*.1}});});
ib('i4','Döviz cinsi iç borçlanma','Yurt içinde dolar tahvili; kur riski hazinede kalır.',-2,X=>`rezerv +${R1(.12*X)} · kur baskısı −${R1(.1*X)} · kur riski artar.`,X=>{applyFx({rez:.12*X,kur:-.1*X});});
ib('i5','Altın tahvili','Altına endeksli devlet tahvili; tasarrufu kamuya çeker.',0,X=>`rezerv +${R1(.08*X)} · cari açık −${R1(.03*X)}.`,X=>{applyFx({rez:.08*X,cari:-.03*X});});
xd('gb',{g:'Hazine',t:'İç borç geri alım ihalesi',d:'Piyasadan eski tahvil satın alınır; bütçe fazlasıyla finanse edilir.',lo:50,hi:800,st:50,v:200,lab:v=>nf(v,0)+' milyar ₺ geri alım',ok:v=>(S.idb||0)<v/gtL()*100?'İç borç stoku bu geri alım için yetersiz.':'',r:v=>{const X=v/gtL()*100;return `iç borç −%${nf(X,2)} GSYH · faiz yükü −${tl(X*S.lv.faiz/100*.5)} · bütçeye ${tl(X)} nakit çıkışı.`;},fx:v=>({}),ap:(v,m)=>{const X=v/gtL()*100*m;S.idb=Math.max(0,(S.idb||0)-X);applyFx({acik:X*.6,buy:.03*X,enf:-.02*X});}});
const hzIc=()=>xpan('Hazine · iç borçlanma çeşitleri',['i1','i2','i3','i4','i5','gb'],'Her ihalenin faiz yükü bütçeye eklenir. Geri alım ihalesi borç stokunu küçültür.');
/* ---------- Hazine: dış borç — yeni kaynaklar ve krediyi kapat ---------- */
Object.assign(LOAN,{sukuk:['Uluslararası sukuk',7.5,5,{dog:.1,bol:.15},'Körfez kökenli yatırımcılara kira sertifikası.',25],ab:['AB / AYB kalkınma kredisi',3.5,12,{bat:.35,des:-.2},'Uzun vadeli, düşük faiz; AB şartları ve reform koşulu.',15],jbic:['Japon JBIC / samuray tahvili',2.8,10,{bat:.1,dog:.1},'Çok düşük faiz; proje bazlı kullanım koşulu.',12],rus:['Rus ihracat kredisi',4.5,8,{dog:.3,bat:-.3},'Enerji ve nükleer projelere bağlı; Batı rahatsız olur.',15],iskb:['İslam Kalkınma Bankası',4,10,{bol:.3,dog:.1},'Orta faiz, uzun vade; İİT üyelerinde itibar.',12],sind:['Sendikasyon kredisi (1 yıl)',8.5,1,{bat:.02},'Bankalardan kısa vadeli; yenilenmezse yük bindirir.',20],yesil:['Yeşil tahvil',6.5,10,{bat:.2,des:.1},'İklim projelerine bağlı; AB ile ilişkileri güçlendirir.',15]});
const lnKey=l=>l.s+'_'+l.end;
xd('kapa',{g:'Hazine',t:'Krediyi kapat (erken geri ödeme)',d:'Kalan en pahalı krediden başlayarak erken ödeme yapılır; rezerv düşer, faiz yükü azalır.',lo:1,hi:30,st:1,v:5,lab:v=>v+' mlr $ erken ödeme',ok:v=>S.rez-v<12?'Rezerv bu ödeme için yetersiz (en az 12 mlr $ kalmalı).':(S.loans.length?'':'Aktif kredi yok.'),r:v=>{const top=S.loans.slice().sort((a,b)=>b.rate-a.rate)[0];return top?`Önce ${LOAN[top.s][0]} (%${top.rate}) kapatılır · yıllık faiz −${R1(Math.min(v,top.amt)*top.rate/100)} mlr $ · rezerv −${v} mlr $ · borç/GSYH −%${R1(v/S.gdp*100)}.`:'Aktif kredi yok.';},fx:v=>({}),ap:(v,m)=>{let rem=v;S.loans.sort((a,b)=>b.rate-a.rate).forEach(l=>{const d=Math.min(l.amt,rem);l.amt-=d;rem-=d;});S.loans=S.loans.filter(l=>l.amt>.01);S.debt=Math.max(0,S.debt-v);S.borc=S.debt/S.gdp*100;applyFx({rez:-v,des:.05*v*.1});}});
xd('yap',{g:'Hazine',t:'Dış borç vade uzatımı',d:'Kredi verenlerle görüşme: kısa vadeli borç uzun vadeye çevrilir.',lo:1,hi:20,st:1,v:5,lab:v=>v+' mlr $ yapılandırma',ok:()=>S.loans.length?'':'Aktif kredi yok.',r:v=>`Önümüzdeki 12 ay geri ödeme baskısı azalır · güven +${R1(v*.1)} · ek maliyet ${R1(v*.02)} mlr $.`,fx:v=>({}),ap:(v,m)=>{S.loans.forEach(l=>{l.end+=Math.round(12*m);});pz().kn=clamp(pz().kn+v*.1*m,0,100);applyFx({acik:v*.02/S.gdp*100});}});
const hzDis=()=>xpan('Hazine · dış borç yönetimi',['kapa','yap'],'Yeni kaynaklar yukarıdaki dış borç alımı bölümünde: sukuk, AB/AYB, JBIC, Rus ihracat kredisi, İslam Kalkınma Bankası, sendikasyon ve yeşil tahvil.');
{const _k=kurum;kurum=function(){let h=_k();const ws=['rez','borrow','repay','ice','kre','af','ikr'];ws.forEach(w=>{const l=(S.xr||{})['k_'+w];if(l)h=h.replace(new RegExp('(data-act="'+w+'"[^>]*>[^<]*</button></div>)'),`$1<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`);});const i=h.indexOf('<div class="panel"><b>BDDK');return i<0?h+hzDis()+hzIc()+bddkP():h.slice(0,i)+hzDis()+hzIc()+bddkP()+h.slice(i);};}
{const _act=act;act=function(w){const n=S.log.length;_act(w);if(S.log.length>n&&S.imsg){S.xr=S.xr||{};S.xr['k_'+w]={m:S.month,t:S.imsg};save();render();}};}
