/* ---------- ek4.js: toplum (politika düzeyi, hizmet bütçesi, işgücü), belediye, lobi/maaş, yasalar, kararname, hizip ---------- */
/* Politika düzeyi: S.plp[id] = destek yüzdesi (100 = standart); eski 2 = %160 */
const plm=id=>{const v=(S.plp||{})[id];return (v!==undefined?v:S.pol[id]===2?160:100)/100;},plg=id=>1+(plm(id)-1)*.67;
/* ---------- Yeni politikalar ---------- */
PL.push(
['yurtburs','Eğitim','Üniversite burs ve yurt desteği','Öğrenci başına aylık burs ve yurt kontenjanı.',{des:.07,huz:.04,acik:.14},{genc:9,kentli:2}],
['okulonc','Eğitim','Okul öncesi eğitim seferberliği','4-5 yaş çocuklara ücretsiz anaokulu.',{des:.05,acik:.12,buy:.02},{muhaf:3,genc:2,ucret:4}],
['dijital','Eğitim','Dijital dönüşüm ve kodlama okulları','Okullarda yazılım ve yapay zekâ eğitimi.',{buy:.04,acik:.08,bat:.03},{genc:6,sanayi:3}],
['saglikt','Sosyal','Ücretsiz aile hekimliği genişletme','Randevusuz poliklinik ve ilaç katkı payı muafiyeti.',{des:.09,huz:.05,acik:.18},{emekli:6,ucret:3,dogu:3}],
['sosyalk','Sosyal','Sosyal konut hamlesi','Dar gelirliye uzun vadeli düşük faizli konut.',{des:.08,acik:.2,buy:.08,enf:.02},{ucret:7,genc:5,esnaf:2}],
['engelli','Sosyal','Engelli ve bakım hizmetleri paketi','Bakım maaşı, erişilebilirlik ve rehabilitasyon.',{des:.04,huz:.04,acik:.08},{muhaf:2,kentli:2,emekli:2}],
['kadin','Sosyal','Kadın istihdamı ve kreş desteği','Kreş zorunluluğu, esnek çalışma ve istihdam teşviki.',{isz:-.05,des:.04,acik:.09},{kentli:5,genc:3,muhaf:-2}],
['yasli','Sosyal','Yaşlı bakım ve gündüz evleri','Belediyelerle ortak yaşlı bakım ağı.',{des:.05,huz:.03,acik:.08},{emekli:6,muhaf:3}],
['siber','Güvenlik','Siber güvenlik ve veri koruma','Kritik altyapı için ulusal siber ordu.',{huz:.03,bat:.02,acik:.05,ord:.02},{milli:3,kentli:2}],
['afetf','Güvenlik','Afet hazırlık seferberliği','Deprem toplanma alanları, yapı denetimi ve gönüllü ağı.',{huz:.05,acik:.14,des:.03},{kentli:3,muhaf:3,dogu:3}],
['denetim','Güvenlik','Yolsuzlukla mücadele ve şeffaflık','Kamu ihale denetimi ve bağımsız sayıştay.',{bat:.05,des:.03,acik:-.04,par:-.03},{kentli:6,sanayi:2,kamu:-3}],
['sulama','Tarım','Havza bazlı sulama ve kuraklık programı','Damla sulama ve gölet; su verimliliği.',{enf:-.03,acik:.1,des:.04},{ciftci:8,dogu:3}],
['kooper','Tarım','Tarım kooperatifleri ve hal reformu','Üretici-market arası aracı zinciri kısalır.',{enf:-.05,acik:.05,des:.03},{ciftci:6,esnaf:-2}],
['soguk','Tarım','Hububat alım ve depolama programı','TMO alım fiyatı ve depo kapasitesi.',{enf:-.03,acik:.1,des:.05},{ciftci:7}],
['ihrnak','Sanayi','İhracatçıya vergi iadesi hızlandırma','KDV ve gümrük iadelerinde hızlı ödeme.',{cari:-.05,acik:.08,buy:.04},{sanayi:7,esnaf:2}],
['otomot','Sanayi','Yerli elektrikli araç ve batarya teşviki','Yerli otomobil alım garantisi ve batarya tesisi.',{cari:-.06,acik:.12,buy:.05},{sanayi:5,milli:4,genc:2}],
['teknopark','Sanayi','Teknopark ve girişim sermayesi','Girişimci vergi bağışıklığı ve ortak fon.',{buy:.04,acik:.06,bat:.03},{genc:5,sanayi:3,kentli:3}],
['guneş','Enerji','Çatı güneş enerjisi desteği','Konut ve fabrika çatılarında üretim teşviki.',{cari:-.05,acik:.07,des:.02},{sanayi:3,kentli:3,muhaf:1}],
['yerlik','Enerji','Yerli kömür ve doğalgaz sübvansiyonu','Hane ısınma ve elektrik faturası desteği.',{enf:-.04,acik:.12,des:.06},{ucret:5,emekli:5}],
['medyaf','Kültür','Bağımsız yayın ve basın fonu','Yerel gazete ve dijital yayınlara destek.',{bat:.03,par:-.03,acik:.03},{kentli:5,genc:3,milli:-2}],
['spor','Kültür','Spor tesisleri ve amatör lig seferberliği','Her ilçeye spor kompleksi ve amatör destek.',{huz:.04,des:.03,acik:.08},{genc:5,muhaf:2}]
);
/* ---------- Politikalar görünümü: yüzdesel destek düzeyi ---------- */
const plCost=(p,v)=>(p[4].acik||0)*v/100,plOn=id=>!!S.pol[id];
function plApply(id){const p=PL.find(x=>x[0]===id);if(!p)return;const v=ui('plv_'+id,plOn(id)?Math.round(plm(id)*100):100),on=plOn(id);S.plp=S.plp||{};
  if(v<=0){if(on){delete S.pol[id];delete S.plp[id];logA('Politika',p[2],'Kapatıldı.');}}
  else{if(!on&&(Object.keys(S.pol).length>=8||avail()<1))return;if(!on){S.cur.spent+=1;S.pol[id]=1;}S.plp[id]=v;logA('Politika',p[2],`%${v} destek düzeyiyle yürürlükte.`);}
  S.xr=S.xr||{};S.xr['pl_'+id]={m:S.month,t:v<=0?'Politika kapatıldı.':`%${v} düzeyinde uygulanıyor: aylık bütçe etkisi ${tl(plCost(p,v))}, grup tepkileri ${gfx(Object.fromEntries(Object.entries(p[5]).map(([k,x])=>[k,Math.round(x*(1+(v/100-1)*.67)*10)/10])))}.`};
  hap(20,520);save();render();}
function politika(){const n=Object.keys(S.pol).length,cats=[...new Set(PL.map(p=>p[1]))],ta=PL.reduce((a,p)=>a+(S.pol[p[0]]?(p[4].acik||0)*plm(p[0]):0),0);
  return `<h2>Politikalar</h2><div class="panel"><div class="dl" style="display:flex;justify-content:space-between"><span>Yürürlükte</span><span><b>${n}</b> / 8 · bütçe etkisi GSYH ${ta>=0?'+':'−'}%${nf(Math.abs(ta),2)}</span></div><div class="note">En fazla 8 politika aynı anda yürürlükte olabilir. Her politikanın destek düzeyini %0 (kapalı) ile %250 arasında ayarlarsın: etkiler, bütçe yükü ve grup tepkileri düzeyle orantılı büyür. Yürürlükteki politikanın düzeyini istediğin zaman değiştirebilirsin.</div></div>${cats.map(c=>`<div class="panel"><b>${c}</b>${PL.filter(p=>p[1]===c).map(p=>{const id=p[0],on=plOn(id),v=ui('plv_'+id,on?Math.round(plm(id)*100):100),l=(S.xr||{})['pl_'+id];
    return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${p[2]}</b> ${on?'<span class="st good">yürürlükte %'+Math.round(plm(id)*100)+'</span>':''}<div class="note" style="margin:2px 0 0">${p[3]} Seçilen düzey %${v}: etki ${fxText(Object.fromEntries(Object.entries(p[4]).map(([k,x])=>[k,x*v/100])))} · tepki ${gfx(Object.fromEntries(Object.entries(p[5]).map(([k,x])=>[k,Math.round(x*(1+(v/100-1)*.67)*10)/10])))}.</div></div>${sld('plv_'+id,0,250,10,v)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-plx="${id}"`,on?(v<=0?'Kapat':'Düzeyi değiştir'):'Yürürlüğe sok',!on&&(n>=8||avail()<1||v<=0))}</div>${l?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`:''}</div>`;}).join('')}</div>`).join('')}`;}
/* ---------- Hizmet bütçesi: yüzde ile artır / azalt ---------- */
const svRef=v=>{const b={};v[2].forEach(k=>b[k]=S.bud[k]);return b;};
function svPrev(v,p){const b=svRef(v),c0=cov(v);v[2].forEach(k=>S.bud[k]=clamp(b[k]*(1+p/100),MB[k]*.4,MB[k]*2));const c1=cov(v);v[2].forEach(k=>S.bud[k]=b[k]);return [c0,c1];}
function svDo(id){const v=SV.find(x=>x[0]===id);if(!v)return;const p=ui('svp_'+id,10),m=su('sv'+id);suU('sv'+id);const [c0]=svPrev(v,0);v[2].forEach(k=>S.bud[k]=clamp(S.bud[k]*(1+p*m/100),MB[k]*.4,MB[k]*2));const c1=cov(v);
  S.xr=S.xr||{};S.xr['sv_'+id]={m:S.month,t:`Bütçe %${p>=0?'+':''}${nf(p*m,0)}: karşılama %${nf(c0,0)} → %${nf(c1,0)}.`+sat(m)};applyFx({des:(c1-c0)*.02});logA('Hizmet',v[1],`bütçe %${p>=0?'+':''}${nf(p*m,0)}`);hap(20,520);save();render();}
const svP=()=>`<div class="panel"><b>Hizmet bütçesi · yüzdesel destek</b>${SV.map(v=>{const id=v[0],p=ui('svp_'+id,10),[c0,c1]=svPrev(v,p),l=(S.xr||{})['sv_'+id];return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${v[1]}</b> · bütçe ${p>=0?'+':''}${p}%<div class="note" style="margin:2px 0 0">Karşılama %${nf(c0,0)} → %${nf(c1,0)} · yıllık maliyet ≈ ${tl(v[2].reduce((a,k)=>a+Math.abs(MB[k])*p/100,0)/Math.max(1,v[2].length)*.12)}.</div></div>${sld('svp_'+id,-30,60,5,p)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-svx="${id}"`,'Bütçeyi değiştir',!p)}</div>${l?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`:''}</div>`;}).join('')}<div class="note">Bütçe kalemi doğrudan yüzde artırılır ya da kısılır; hizmet karşılaması buna göre değişir.</div></div>`;
{const _h=hizmet;hizmet=function(){return _h()+svP()+polOz();};}
const polOz=()=>'';
/* ---------- İşgücü piyasası ---------- */
xd('ksa',{g:'İşgücü',t:'Kısa çalışma ödeneği',d:'Kriz dönemlerinde işten çıkarma yerine devlet maaşın bir bölümünü öder.',lo:10,hi:80,st:5,v:30,lab:v=>'maaşın %'+v+'\'i devletten',r:v=>`İşsizlik −${R1(v*.006)} puan · maliyet ${tl(v*.004)} · işveren tepkisi hafif.`,fx:v=>({isz:-v*.006,acik:v*.004})});
xd('isg',{g:'İşgücü',t:'İşsizlik sigortası kapsamı',d:'Ödenek süresi ve miktarı artar; iş bulma isteği hafif düşebilir.',lo:0,hi:12,st:1,v:3,lab:v=>'+'+v+' ay ödenek süresi',r:v=>`Halk desteği +${R1(v*.12)} · maliyet ${tl(v*.015)} · huzur +${R1(v*.02)}.`,fx:v=>({des:v*.12,acik:v*.015,huz:v*.02})});
xd('kdm',{g:'İşgücü',t:'Kıdem tazminatı fonu',d:'Tazminatı fona çevirir; işveren yükü azalır, işçi güvencesi tartışılır.',lo:0,hi:100,st:10,v:40,lab:v=>'işveren yükü %'+v+' fona',r:v=>`Yatırım +%${R1(v*.02)} büyüme · işçi desteği −${R1(v*.04)} · sanayici desteği +${R1(v*.04)}.`,fx:v=>({buy:v*.02,des:-v*.01}),ap:(v,m)=>{S.gr.ucret=clamp(S.gr.ucret-v*.04*m,0,100);S.gr.sanayi=clamp(S.gr.sanayi+v*.04*m,0,100);}});
xd('kdi',{g:'İşgücü',t:'Kayıt dışı istihdam denetimi',d:'Denetim sıklaşır; vergi ve prim tabanı genişler, küçük işletme zorlanır.',lo:5,hi:100,st:5,v:25,lab:v=>'denetim yoğunluğu %'+v,r:v=>`Kayıt dışılık −${R1(v*.04)} puan · gelir +${tl(v*.004)} · esnaf tepkisi −${R1(v*.04)}.`,fx:v=>({acik:-v*.004,isz:v*.003}),ap:(v,m)=>{S.gr.esnaf=clamp(S.gr.esnaf-v*.04*m,0,100);}});
xd('esn',{g:'İşgücü',t:'Esnek ve uzaktan çalışma düzenlemesi',d:'Yarı zamanlı ve uzaktan çalışmayı kolaylaştırır; kadın ve genç istihdamı artar.',lo:5,hi:100,st:5,v:30,lab:v=>'esneklik düzeyi %'+v,r:v=>`İşsizlik −${R1(v*.004)} · işçi tepkisi −${R1(v*.03)} · genç desteği +${R1(v*.03)}.`,fx:v=>({isz:-v*.004}),ap:(v,m)=>{S.gr.genc=clamp(S.gr.genc+v*.03*m,0,100);S.gr.ucret=clamp(S.gr.ucret-v*.03*m,0,100);}});
xd('yab',{g:'İşgücü',t:'Yabancı işgücü çalışma izni kotası',d:'Sektör bazlı çalışma izni; kota artarsa işgücü ucuzlar, ücret baskısı artar.',lo:0,hi:100,st:10,v:30,lab:v=>'kota %'+v,r:v=>`İşsizlik ${v>30?'+':'−'}${R1(Math.abs(v-30)*.004)} · sanayici desteği ${v>30?'+':'−'}${R1(Math.abs(v-30)*.03)} · milliyetçi tepkisi ${v>30?'+':'−'}${R1(Math.abs(v-30)*.04)}.`,fx:v=>({isz:(v-30)*.004,buy:(v-30)*.002}),ap:(v,m)=>{S.gr.sanayi=clamp(S.gr.sanayi+(v-30)*.03*m,0,100);S.gr.milli=clamp(S.gr.milli-(v-30)*.04*m,0,100);}});
xd('gnc',{g:'İşgücü',t:'Genç istihdam teşviki',d:'İlk işe girenlerde işveren primi devletten.',lo:5,hi:100,st:5,v:30,lab:v=>'prim desteği %'+v,r:v=>`İşsizlik −${R1(v*.006)} · maliyet ${tl(v*.005)} · genç desteği +${R1(v*.05)}.`,fx:v=>({isz:-v*.006,acik:v*.005}),ap:(v,m)=>{S.gr.genc=clamp(S.gr.genc+v*.05*m,0,100);}});
xd('mes',{g:'İşgücü',t:'Mesleki yeterlilik ve beceri belgesi',d:'Sektörlerle ortak sertifika; işgücü niteliği yükselir.',lo:1,hi:20,st:1,v:5,lab:v=>v+' sektörde belge zorunlu',r:v=>`İşsizlik −${R1(v*.015)} · büyüme +${R1(v*.01)} · maliyet ${tl(v*.006)}.`,fx:v=>({isz:-v*.015,buy:v*.01,acik:v*.006})});
{const _s=sinif;sinif=function(){return _s()+xpan('İşgücü piyasası · düzenlemeler',['ksa','isg','kdm','kdi','esn','yab','gnc','mes'],'İşsizlik ve hanehalkı gelirine etkiler birkaç ayda yansır; işçi ve işveren tepkileri grup hoşnutluğunda görünür.');};}
/* ---------- Belediyeler ---------- */
BLA.push(['Raylı sistem ve metro projesi','Merkezi bütçeden metro ve tramvay finansmanı.',{acik:.05,des:.04,buy:.03},4],['Su ve kanalizasyon yatırımı','İSKİ/ASKİ benzeri kuruluşlara kredi ve hibe.',{acik:.03,huz:.03},3],['Sosyal konut protokolü','TOKİ ile ortak konut projesi.',{acik:.06,des:.04},3],['Afet dönüşüm fonu','Riskli yapı dönüşümüne kaynak.',{acik:.05,huz:.03},3.5],['Kültür ve festival desteği','Yerel kültür etkinlikleri ve turizm tanıtımı.',{acik:.02,des:.02},2],['Doğrudan gelir vergisi payı','Yerel yönetimlere ek pay aktarılır.',{acik:.04},3],['Ortak seçim stratejisi','İttifak kurup aday uyumu için görüşme yapılır.',{par:.03},1.5],['Başkanla özel görüşme','Büyükşehir başkanıyla kapalı toplantı.',{},1]);
xd('bpy',{g:'Belediye',t:'Belediyelere gelir vergisi payı',d:'Merkezi vergilerden yerel yönetimlere aktarılan pay.',lo:-2,hi:6,st:.5,v:0,lab:v=>(v>=0?'+':'')+v+' puan pay',r:v=>`Maliyet ${tl(v*.04)} · hizmet karşılaması ${v>=0?'+':'−'}${R1(Math.abs(v)*.4)} · halk desteği ${v>=0?'+':'−'}${R1(Math.abs(v)*.05)} · muhalefet belediyeleri ${v>=0?'rahatlar':'tepki gösterir'}.`,fx:v=>({acik:v*.04,des:v*.05,huz:v*.02})});
xd('bbr',{g:'Belediye',t:'Belediye borçlanma izni',d:'Büyükşehirlerin dış borçlanma limiti.',lo:0,hi:20,st:1,v:5,lab:v=>v+' mlr $ limit',r:v=>`Yatırım +%${R1(v*.15)} büyüme · borç riski +${R1(v*.2)} puan · yerel güven +${R1(v*.1)}.`,fx:v=>({buy:v*.015,borc:v*.003})});
xd('bdn',{g:'Belediye',t:'Yerel yönetim denetimi',d:'Sayıştay ve içişleri denetim yoğunluğu.',lo:5,hi:100,st:5,v:30,lab:v=>'denetim yoğunluğu %'+v,r:v=>`Kayıp azalır (bütçe +${tl(v*.001)}) · belediye tepkisi −${R1(v*.03)} · halk desteği ${v>50?'−':'+'}${R1(Math.abs(v-50)*.01)}.`,fx:v=>({acik:-v*.001,des:(50-v)*.01})});
xd('bhr',{g:'Belediye',t:'Yerel hizmet reformu',d:'Belediye personeli ve hizmet standardı reformu.',lo:1,hi:10,st:1,v:3,lab:v=>v+' hizmet alanında reform',r:v=>`Hizmet kalitesi +${R1(v*.5)} · huzur +${R1(v*.02)} · maliyet ${tl(v*.01)}.`,fx:v=>({huz:v*.02,des:v*.03,acik:v*.01})});
{const _b=belP;belP=function(){return xpan('Belediyeler · genel politikalar',['bpy','bbr','bdn','bhr'])+_b();};}
