/* ---------- ek5.js: lobi/maaş masası, yasalar (yürürlükte / değil), kararnameler, hizip, kurum programları, politika kolları ---------- */
/* ---------- Lobi: çok kademeli birimler, daha çok görüşme biçimi ---------- */
const lbExp=(a,k)=>{if(a.length>3)return a;const [x,y,z]=a;if(k==='s')return [1,2,3,4,5,6];return [...new Set([x*.5,x,(x+y)/2,y,(y+z)/2,z,z*1.5,z*2].map(v=>Math.round(v*2)/2))];};
Object.keys(LT).forEach(id=>LT[id].forEach(x=>{x[2]=lbExp(x[2],x[3]);}));
LMO.sen.push(['Sektörel masa toplantıları','Metal, tekstil ve kamu sektörleriyle ayrı ayrı oturumlar.',9,{des:.02}],['Eylem öncesi gizli görüşme','Grev kararı alınmadan kapalı kapılar ardında görüşme.',13,{par:-.02}],['Sendika yönetim kurulu ziyareti','Genel merkezlerde tek tek ziyaret ve söz.',7,{}],['Ortak basın açıklaması','Sendikalarla ortak çerçeve metni açıklanır.',10,{des:.03}],['Yıllık değerlendirme toplantısı','Yıl sonu raporu; ücret ve çalışma koşulları gözden geçirilir.',12,{des:.02,huz:.02}]);
LMO.isv.push(['Sektör meclisleri toplantısı','Sanayi, ticaret ve hizmet meclisleriyle oturum.',8,{}],['Yatırım ortamı raporu görüşmesi','TÜSİAD ve MÜSİAD ile ortak yatırım ortamı çalıştayı.',12,{buy:.02}],['Ortak ihracat zirvesi','TİM ile ihracat hedefi toplantısı.',11,{cari:-.02}],['Bilgilendirme kahvaltısı','Bakanların iş insanlarıyla gayriresmî görüşmesi.',6,{}],['Vergi uzlaşma komisyonu','Vergi yükü ve ceza düzenlemeleri için komisyon.',10,{acik:.02}]);
LMO.oda.push(['Baro başkanlarıyla toplantı','Yargı reformu için hukukçularla istişare.',10,{bat:.02}],['Mühendis ve mimar odaları çalıştayı','Yapı denetimi ve deprem hazırlığı çalıştayı.',9,{huz:.02}],['Tabip odası toplantısı','Sağlık politikaları ve hekim sorunları.',9,{des:.02}],['Esnaf odaları ziyareti','Oda yönetimleriyle yerel sorunlar.',7,{}]);
LMO.stk.push(['STK platformu toplantısı','Çevre, kadın, hukuk ve kültür STK\'larıyla ortak toplantı.',9,{bat:.02}],['Proje ortaklığı çağrısı','Kamu-STK ortak proje fonu açıklanır.',12,{acik:.02}],['Hak temelli kuruluşlarla görüşme','İnsan hakları örgütleriyle kapalı görüşme.',8,{bat:.03,par:-.02}],['Yerel inisiyatif ziyareti','Mahalle ve köy düzeyinde ziyaret.',6,{}]);
LMO.vak.push(['Cemaat liderleriyle iftar','Geleneksel ortak iftar ve yemek.',9,{}],['Vakıf projelerine destek','Eğitim ve yardım vakıflarına kaynak.',12,{acik:.02}],['Diyanet ile ortak toplantı','Din hizmetleri ve toplum projeleri.',8,{}],['Hayır kampanyası ortaklığı','Ramazan ve kış yardımı ortak kampanyası.',10,{huz:.02}]);
/* ---------- Yıllık ücret ve emeklilik masası (üçlü / devlet) ---------- */
const S_mx=()=>(S.mx=S.mx||{kamu:100,pens:100,minw0:S.minw||28075});
const mxR=k=>S_mx()[k]/Math.max(1,S.cpi||100)*100;
function minwDo(){const G=ui('mwg',10),W=Math.max(6,Math.round(S.enf*.45)),E=Math.max(2,Math.round(S.enf*.18)),m=su('mw');suU('mw');const eo=G<=E*1.8,wo=G>=W*.7;let t,fx;
  if(eo&&wo){t='Üç taraf (sendika, işveren, devlet) uzlaştı.';fx={des:1,huz:.4};}else if(eo){t='İşveren ve devlet oy çokluğuyla karar verdi; işçi temsilcileri tepkili.';fx={des:-1.2,huz:-.6};}else if(wo){t='İşçi ve devlet oy çokluğuyla karar verdi; işveren itiraz etti.';fx={des:1.2,huz:.3,buy:-.2,isz:.2};}else{t='Taraflar uzlaşamadı; devlet kendi önerisini uyguladı, iki taraf da tepkili.';fx={des:-.8,huz:-.4};}
  const g=G*m;S.minw=Math.round(S.minw*(1+g/100));applyFx({...fx,enf:.04*g,acik:.015*g});S.gr.ucret=clamp(S.gr.ucret+g*.4,0,100);if(S.lb&&S.lb.sen)S.lb.sen.t=clamp(S.lb.sen.t+(eo&&!wo?-6:wo?5:2),-100,100);
  S.xr=S.xr||{};S.xr.mw={m:S.month,t:`${t} Yeni net asgari ücret ≈ ${nf(S.minw,0)} ₺ (+%${nf(g,1)}).`+sat(m)};logA('Ücret masası','Asgari ücret',`+%${nf(g,1)}`);hap(20,520);save();render();}
function maasDo(k){const id=k==='kamu'?'mkm':'mem',v=ui(id,k==='kamu'?10:10),m=su(id);suU(id);const g=v*m,d=k==='kamu'?{acik:.03*g,enf:.015*g,des:.03*g}:{acik:.035*g,enf:.012*g,des:.04*g,huz:.01*g};applyFx(d);S_mx()[k==='kamu'?'kamu':'pens']*=1+g/100;
  if(k==='kamu'){S.gr.kamu=clamp(S.gr.kamu+g*.7,0,100);S.gb.kamu=clamp((S.gb.kamu||0)+g*.3,-30,30);}else{S.gr.emekli=clamp(S.gr.emekli+g*.7,0,100);S.gb.emekli=clamp((S.gb.emekli||0)+g*.3,-30,30);}
  if(S.lb&&S.lb.sen)S.lb.sen.t=clamp(S.lb.sen.t+g*.3,-100,100);S.xr=S.xr||{};S.xr[id]={m:S.month,t:`${k==='kamu'?'Kamu maaşları':'Emekli aylıkları'} +%${nf(g,1)}: yıllık bütçe maliyeti ≈ ${tl(.035*g*1.4)}, enflasyona ek baskı +${nf(.015*g,2)} puan.`+sat(m)};logA('Ücret masası',k==='kamu'?'Kamu maaşı':'Emekli aylığı',`+%${nf(g,1)}`);hap(20,520);save();render();}
function mxTab(){const e=S.enf,W=Math.max(6,Math.round(e*.45)),E=Math.max(2,Math.round(e*.18)),G=ui('mwg',10),l=S.xr||{},lg=k=>l[k]?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l[k].m)}): ${l[k].t}</div>`:'';
  const t1=G<=E*1.8&&G>=W*.7?'uzlaşma beklenir':G<=E*1.8?'işçi tarafı tepki gösterir':G>=W*.7?'işveren tepki gösterir':'iki taraf da tepki gösterir';
  return `<h2>Yıllık Ücret ve Emeklilik Masası</h2><div class="panel"><div class="note" style="margin:0 0 6px">Asgari ücret sendika, devlet, işçi ve işveren temsilcilerinin ortak anlaşmasıyla belirlenir. Kamu maaşları ve emekli aylıkları devletin kontrolündedir; sendikalarla toplu görüşme yapılır. Etkiler maliyet ve enflasyon üzerinden hesaplanır.</div>
  <div class="dl"><b>Asgari ücret (üçlü masa)</b> · net ${nf(S.minw,0)} ₺<div class="note" style="margin:2px 0 0">İşçi talebi ≈ %${W} · işveren önerisi ≈ %${E} · teklifin: %${G} → yeni ücret ≈ ${nf(S.minw*(1+G/100),0)} ₺ · ${t1} · maliyet ≈ ${tl(.015*G)}.</div></div>${sld('mwg',0,100,1,G)}<div class="chips" style="margin:4px 0 0">${sbtn('data-mwx="1"','Üçlü toplantıyı yap')}</div>${lg('mw')}
  <div style="border-top:1px solid var(--line);margin-top:8px;padding-top:8px"></div>${[['kamu','Kamu maaşı (devlet + kamu sendikaları)','mkm',mxR('kamu')],['pens','Emekli aylığı (devlet)','mem',mxR('pens')]].map(([k,n,id,r])=>{const v=ui(id,10);return `<div class="dl"><b>${n}</b> · reel değer %${nf(r,0)}<div class="note" style="margin:2px 0 0">Artış %${v} · yıllık maliyet ≈ ${tl(.035*v*1.4)} · enflasyona +${nf(.015*v,2)} puan · ${k==='kamu'?'kamu çalışanı desteği':'emekli desteği'} +${nf(v*.7,1)}.</div></div>${sld(id,0,60,1,v)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-mxk="${k}"`,'Anlaşmayı uygula')}</div>${lg(id)}`;}).join('')}</div>`;}
{lobi=function(){return mxTab();};}
/* ---------- Yasalar: daha fazla yasa, yürürlükte olanlar / olmayanlar, yürürlükten kaldırma ---------- */
LAWS.push(
['hukukd','Hukuk Devleti Paketi',3,301,.45,'Bağımsız yargı güvenceleri ve tutukluluk sınırları.',{bat:.7,des:.3,par:-.3}],
['basin','Basın Özgürlüğü Yasası',3,301,.2,'Gazeteci koruma ve bağımsız yayın düzenlemesi.',{bat:.6,des:.4,par:-.3}],
['gelirdv','Dijital Hizmet Vergisi Kanunu',2,301,.4,'Küresel platformlara vergi; Batı ile gerilim doğabilir.',{acik:-.35,bat:-.2}],
['emekli2','Emekliye Refah Payı Yasası',3,301,.65,'Düşük emekli aylıklarına refah payı ve taban aylık.',{des:1.2,acik:.5,huz:.3}],
['konut','Konut Edindirme Yasası',3,301,.55,'Konut kredisi desteği ve kamu arsa tahsisi.',{des:1,buy:.3,acik:.35}],
['egitim','Eğitim Reformu Yasası',3,301,.4,'Müfredat, öğretmen atama ve okul öncesi zorunluluk.',{des:.6,bat:.3,acik:.15}],
['mesleki','Meslek Liseleri Yasası',2,301,.55,'Sanayi ile ortak meslek eğitimi ve çıraklık.',{isz:-.2,buy:.15,acik:.1}],
['kamuist','Kamu Personel Rejimi Yasası',3,301,.35,'Kamuda liyakat sınavı ve kadro düzeni.',{bat:.3,des:-.3,par:-.2}],
['tapu','İmar Barışı Yasası',2,301,.5,'Yapı kayıt belgesi; kaçak yapılara af.',{des:.8,huz:.2,acik:-.2,bat:-.2}],
['enerji','Enerji Piyasası Yasası',2,301,.4,'Elektrik ve doğalgazda serbest piyasa, sübvansiyon sınırı.',{acik:-.3,enf:.2,cari:-.1}],
['nukl','Nükleer Enerji Yasası',2,301,.35,'Yeni santral ve yakıt ithalatı çerçevesi.',{cari:-.2,dog:.1,bat:-.05}],
['sosyalg','Sosyal Güvenlik Reformu Yasası',3,301,.25,'Prim tabanı ve erken emeklilik düzeni.',{acik:-.5,des:-.9,huz:-.2}],
['kadin2','Kadın Hakları ve Şiddet Önleme Yasası',2,301,.55,'Koruyucu tedbirler, nafaka ve sığınma evi.',{des:.5,bat:.3,huz:.2}],
['sigara','Alkol ve Tütün Düzenlemesi',1,301,.5,'Satış saatleri ve vergi; sağlık harcaması azalır.',{acik:-.1,des:-.1}],
['spor','Spor Kulüpleri Yasası',1,301,.55,'Kulüp borç yapılandırması ve şeffaflık.',{des:.3,acik:.05}],
['gida','Gıda ve Tarım Yasası',2,301,.5,'Sözleşmeli tarım, hal yasası ve fiyat izleme.',{enf:-.1,des:.3,acik:.1}],
['veri','Kişisel Verilerin Korunması Yasası',2,301,.45,'AB uyumlu veri koruma ve ceza.',{bat:.4,buy:-.05}],
['yapay','Yapay Zekâ Düzenleme Yasası',2,301,.4,'Kritik alanlarda yapay zekâ denetimi ve test.',{bat:.3,buy:.05,huz:.05}],
['sinir','Sınır ve Göç Yasası',3,301,.4,'Geri gönderme hızlandırılır; yasadışı giriş cezası artar.',{huz:.4,bat:-.3,des:.3}],
['iltica','İltica ve Geçici Koruma Yasası',3,301,.3,'Geçici koruma statüsü ve vatandaşlık yolu.',{bat:.4,huz:-.2,des:-.4}],
['savunma','Savunma Sanayii Yasası',2,301,.65,'Ar-Ge teşviki ve ihracat kolaylığı.',{ord:.2,cari:-.1,acik:.1}],
['harc','Kamu Harcama Disiplini Yasası',2,301,.5,'Bütçe açığı için harcama tavanı.',{acik:-.45,des:-.3,bat:.2}],
['sendika','Sendikal Haklar Yasası',3,301,.3,'Sendikalaşma eşiği ve grev hakkı genişler.',{des:.5,buy:-.1,bat:.15,par:-.1}],
['grev','Grev Ertelemesi Yasası',3,301,.4,'Grev erteleme yetkisi; huzur artar, işçi tepkisi artar.',{huz:.15,des:-.4,bat:-.15}],
['ihale2','Kamu İhale Şeffaflık Yasası',2,301,.45,'Pazarlık usulü sınırlanır, ihale açık yapılır.',{bat:.3,acik:-.2,par:-.15}],
['miras','Miras ve Servet Vergisi Yasası',3,301,.2,'Büyük servete ve mirasa vergi.',{acik:-.5,des:-.2,bat:-.05}],
['ozel2','Vakıf Üniversiteleri Yasası',2,301,.45,'Vakıf üniversitelerinde denetim ve burs şartı.',{des:.2,bat:.1}],
['deprem','Deprem Sigortası ve Dönüşüm Yasası',3,301,.6,'Zorunlu sigorta ve kentsel dönüşüm fonu.',{huz:.3,acik:.15,des:.4}],
['cevre','Çevre ve Orman Yasası',2,301,.4,'Orman koruma ve maden izinlerine sınır.',{bat:.2,des:.2,buy:-.05}],
['kultur','Kültür ve Sanat Destek Yasası',1,301,.55,'Sinema, tiyatro ve kültür fonu.',{des:.2,bat:.1,acik:.05}]
);
const lawInfo=l=>{const [id,n,c,need,ap,d,fx]=l;return {id,n,c,need,d,fx};};
function lawRepeal(id){const l=LAWS.find(x=>x[0]===id);if(!l||!S.laws[id]||avail()<2)return;const f={};for(const k in l[6])f[k]=-l[6][k]*.6;const r=['rp_'+id+'_'+S.month,l[1]+' Yürürlükten Kaldırılması',2,301,.35,'Mevcut yasa yürürlükten kaldırılır; etkileri geri alınır.',f,{repeal:id}];S.cl=S.cl.slice(-19).concat([r]);propose(r[0],false);}
const lawP=()=>{const all=LAWS.map(l=>l),on=all.filter(l=>S.laws[l[0]]),off=all.filter(l=>!S.laws[l[0]]),a=avail(),flt=S.lawf||0,lab=['Tümü','Ekonomi','Sosyal','Güvenlik / dış'],pass=l=>!flt||(flt===1?(l[6].acik!==undefined||l[6].buy!==undefined||l[6].cari!==undefined||l[6].enf!==undefined):flt===2?(l[6].des!==undefined||l[6].huz!==undefined):(l[6].bat!==undefined||l[6].ord!==undefined||l[6].dog!==undefined));
  return `<h2>Yasalar</h2><div class="chips" style="margin:0 0 6px">${lab.map((x,i)=>`<button class="btn sm ${flt===i?'':'sec'}" data-lawf="${i}">${x}</button>`).join('')}</div><div class="panel"><b>Yürürlükte olanlar (${on.filter(pass).length})</b>${on.filter(pass).length?on.filter(pass).map(([id,n,c,need,,d,fx])=>`<div class="lever"><span class="n">${n}</span><span class="h">${d} <b>(${fxText(fx)}.)</b> Yürürlükten kaldırma ${need} oy ister.</span><div class="step"><span class="st good">Yürürlükte</span>${sbtn(`data-lawr="${id}"`,'Kaldırma teklifi',a<2)}</div></div>`).join(''):'<div class="note">Bu başlıkta yürürlükte yasa yok.</div>'}</div>
  <div class="panel"><b>Yürürlükte olmayanlar (${off.filter(pass).length})</b>${off.filter(pass).map(([id,n,c,need,,d,fx])=>`<div class="lever"><span class="n">${n}</span><span class="h">${d} <b>(Geçerse: ${fxText(fx)}.)</b> ${need} kabul oyu gerekir.</span><div class="step">${sbtn(`data-law="${id}"`,`Meclise sun`,a<c)}</div></div>`).join('')}<div class="note">Teklif Genel Kurul'da oylanır: kabul, ret ve çekimser oylar ile katılmayan milletvekilleri olur; sonuç partilerin tutumuna göre değişir. Yürürlükteki yasayı kaldırmak da oylamaya tabidir; etkileri %60 geri alınır.</div></div>`;};
{const _m=meclis;meclis=function(){const h=_m().replace(/<h2>Vaatler[\s\S]*?(?=<h2>Yasa Taslağı<\/h2>)/,''),i=h.indexOf('<h2>Yasalar</h2>');return (i<0?h:h.slice(0,i))+lawP();};}
/* ---------- Cumhurbaşkanlığı kararnameleri (yalnızca Cumhurbaşkanı) ---------- */
const kd=(id,t,d,lo,hi,st,v,lab,r,fx,ap,ok)=>xd(id,{g:'Kararname',t,d,lo,hi,st,v,lab,r,fx,ap,ok,btn:'Kararname çıkar'});
kd('k1','Olağanüstü hal ilanı','MGK önerisiyle sınırlı bölgelerde OHAL. Huzur artar, itibar ve halk desteği düşer.',1,6,1,2,v=>v+' ay OHAL',v=>`Huzur +${R1(v*.25)} · Batı itibarı −${R1(v*.12)} · halk desteği −${R1(v*.2)}.`,v=>({huz:v*.25,bat:-v*.12,des:-v*.2}));
kd('k2','Merkez Bankası başkanı ataması','Kararnameyle başkan değişikliği; güvenilirlik sınırlı sürede dalgalanır.',-3,3,1,0,v=>v>0?'şahin (sert) başkan':v<0?'güvercin (gevşek) başkan':'teknokrat başkan',v=>`Güven ${v>0?'+':'−'}${R1(Math.abs(v)*2+(v===0?1:0))} · kur ${v>0?'−':'+'}${R1(Math.abs(v)*.6)}%.`,v=>({kur:-v*.6}),(v,m)=>{S.gv=clamp(S.gv+(v===0?1.5:Math.abs(v)*2*(v>0?1:-1))*m,0,100);});
kd('k3','Üst kademe kamu atamaları','Valiler, müsteşarlar ve kurum başkanları. Sadakat ya da liyakat ağırlığı seçilir.',-100,100,10,0,v=>v>0?'liyakat ağırlıklı %'+v:v<0?'sadakat ağırlıklı %'+(-v):'dengeli',v=>`Reformcu hizip ${v>0?'+':'−'}${R1(Math.abs(v)*.1)} · Sadakatçi ${v<0?'+':'−'}${R1(Math.abs(v)*.1)} · bürokrasi performansı ${v>0?'+':'−'}${R1(Math.abs(v)*.03)}.`,v=>({}),(v,m)=>{S.fb.R+=v*.1*m;S.fb.S-=v*.1*m;if(S.bu)S.bu.yz=clamp(S.bu.yz-v*.05*m,0,100);});
kd('k4','Cumhurbaşkanlığı affı','Hastalık ve yaş gerekçesiyle cezaların hafifletilmesi.',1,200,1,20,v=>v+' kişilik af listesi',v=>`Halk desteği ${v>50?'−':'+'}${R1(Math.abs(v-50)*.01)} · adalet algısı ${v>100?'−':'+'}${R1(.002*v)}.`,v=>({des:(50-v)*.01,bat:v>100?-.1:.02}));
kd('k5','Enerji fiyat kararnamesi','BOTAŞ ve EPDK tarifelerine sübvansiyon (+) ya da zam (−).',-30,30,5,0,v=>v>=0?'sübvansiyon %'+v:'zam %'+(-v),v=>`Enflasyon ${v>=0?'−':'+'}${R1(Math.abs(v)*.02)} · maliyet ${tl(v*.01)} · halk desteği ${v>=0?'+':'−'}${R1(Math.abs(v)*.03)}.`,v=>({enf:-v*.02,acik:v*.01,des:v*.03}));
kd('k6','Kamulaştırma ve acele kamulaştırma','Stratejik proje arazileri için kamulaştırma kararı.',1,20,1,3,v=>v+' proje',v=>`Büyüme +${R1(v*.04)} · maliyet ${tl(v*.012)} · çiftçi tepkisi −${R1(v*.3)}.`,v=>({buy:v*.04,acik:v*.012}),(v,m)=>{S.gr.ciftci=clamp(S.gr.ciftci-v*.3*m,0,100);});
kd('k7','Kamu kurumlarında tasarruf genelgesi','Araç, makam ve seyahat harcamalarında kısıntı.',5,50,5,15,v=>'%'+v+' kısıntı',v=>`Bütçe +${tl(v*.003)} · kamu çalışanı tepkisi −${R1(v*.06)}.`,v=>({acik:-v*.003}),(v,m)=>{S.gr.kamu=clamp(S.gr.kamu-v*.06*m,0,100);});
kd('k8','Rektör ve üniversite atamaları','Cumhurbaşkanı atar; akademik özerklik tartışması.',0,100,10,30,v=>v+'% yeni atama',v=>`Parti içi memnuniyet +${R1(v*.04)} · genç ve kentli tepkisi −${R1(v*.05)} · Batı itibarı −${R1(v*.003)}.`,v=>({bat:-v*.003}),(v,m)=>{S.fb.S+=v*.04*m;S.gr.genc=clamp(S.gr.genc-v*.05*m,0,100);S.gr.kentli=clamp(S.gr.kentli-v*.05*m,0,100);});
kd('k9','Seferberlik ve güvenlik kararnamesi','Sınır birliklerini ve atış alanlarını güçlendirir.',1,10,1,2,v=>'seviye '+v,v=>`Ordu hazırlığı +${R1(v*.04)} · maliyet ${tl(v*.015)} · huzur +${R1(v*.03)}.`,v=>({ord:v*.04,acik:v*.015,huz:v*.03}));
kd('k10','Döviz ve ihracat rejimi kararnamesi','İhracat bedelinin yurda getirilme ve dönüştürme oranı.',0,60,5,20,v=>'%'+v+' dönüşüm zorunluluğu',v=>`Rezerv +${R1(v*.12)} mlr $ · ihracatçı tepkisi −${R1(v*.05)} · kur −%${R1(v*.04)}.`,v=>({rez:v*.12,kur:-v*.04}),(v,m)=>{S.gr.sanayi=clamp(S.gr.sanayi-v*.05*m,0,100);});
kd('k11','Yatırım ve teşvik kararnamesi','Bölge ve sektör bazlı teşvik belgeleri.',1,30,1,5,v=>v+' bölge/sektör',v=>`Yatırım +${R1(v*.05)} büyüme · maliyet ${tl(v*.01)} · sanayici desteği +${R1(v*.3)}.`,v=>({buy:v*.05,acik:v*.01}),(v,m)=>{S.gr.sanayi=clamp(S.gr.sanayi+v*.3*m,0,100);});
kd('k12','Kamu yatırım programı revizyonu','Büyük projelerin ertelenmesi ya da hızlandırılması.',-20,20,5,0,v=>v>=0?'%'+v+' hızlandırma':'%'+(-v)+' erteleme',v=>`Büyüme ${v>=0?'+':'−'}${R1(Math.abs(v)*.015)} · maliyet ${tl(v*.003)} · enflasyon ${v>=0?'+':'−'}${R1(Math.abs(v)*.004)}.`,v=>({buy:v*.015,acik:v*.003,enf:v*.004}));
kd('k13','Dış politika yönlendirme kararnamesi','Büyükelçilik atamaları ve diplomatik öncelik yönü.',-3,3,1,0,v=>v>0?'Batı yönlü':v<0?'Doğu yönlü':'dengeli',v=>`${v>0?'Batı':v<0?'Doğu':'Her iki yön'} ilişkisi ${v===0?'+0,1':(v>0?'+':'−')+R1(Math.abs(v)*.12)}.`,v=>({bat:v*.12,dog:-v*.12}));
kd('k14','Sivil savunma ve afet yönetimi kararnamesi','AFAD, il yönetimleri ve gönüllü ağı için yetki ve bütçe.',1,10,1,3,v=>'seviye '+v,v=>`Afet hazırlığı +${R1(v*.8)} · huzur +${R1(v*.03)} · maliyet ${tl(v*.008)}.`,v=>({huz:v*.03,acik:v*.008}),(v,m)=>{S.bud.ic=clamp(S.bud.ic*(1+v*.003*m),MB.ic*.4,MB.ic*2);});
const kdP=()=>xpan('Cumhurbaşkanlığı kararnameleri',['k1','k3','k4','k5','k6','k7','k11','k12','k14'],'Bu kararnameler Meclis oylaması gerektirmez; yalnızca Cumhurbaşkanı çıkarır. Etkiler anında uygulanır, tekrar kullanıldıkça etkisi azalır.');
{const _c=cbP;cbP=function(){return _c()+kdP();};}
/* ---------- Hizip: yönetim temsili yerine çeşitli araçlar ---------- */
const hzAp=(k,df,dm,dp,dc)=>(v,m)=>{S.fb[k]+=df*v*m;if(dm)S.fac[k]+=dm*v*m;if(dp)S.par=clamp(S.par+dp*v*m,0,10);if(dc)Object.keys(dc).forEach(o=>S.fb[o]+=dc[o]*v*m);hzN();};
HZF.forEach(([k,n])=>{
 xd('hz_'+k+'_a',{g:'Parti',t:n+' · milletvekili aday kontenjanı',d:'Gelecek seçimde aday listesindeki payı.',lo:0,hi:30,st:1,v:8,lab:v=>'listede %'+v+' kontenjan',r:v=>`Hizip memnuniyeti +${R1(v*.6)} · ağırlığı +${R1(v*.12)} · diğer hizipler −${R1(v*.15)} · parti birliği −${R1(v*.003)}.`,fx:v=>({}),ap:hzAp(k,.6,.12,-.003,Object.fromEntries(HZF.filter(x=>x[0]!==k).map(x=>[x[0],-.15])))});
 xd('hz_'+k+'_b',{g:'Parti',t:n+' · ortak çalıştay ve program',d:'Hizbin uzmanlarıyla ortak politika çalıştayı.',lo:1,hi:10,st:1,v:3,lab:v=>v+' oturum',r:v=>`Memnuniyet +${R1(v*.9)} · maliyet ${tl(v*.003)}.`,fx:v=>({acik:v*.003}),ap:hzAp(k,.9,0,0)});
 xd('hz_'+k+'_c',{g:'Parti',t:n+' · il teşkilatı kadro payı',d:'İl başkanlığı ve teşkilat görevlerinde kadro payı.',lo:0,hi:40,st:2,v:10,lab:v=>'%'+v+' kadro',r:v=>`Memnuniyet +${R1(v*.4)} · ağırlık +${R1(v*.15)} · yolsuzluk algısı +${R1(v*.003)}.`,fx:v=>({bat:-v*.003}),ap:hzAp(k,.4,.15,0)});
 xd('hz_'+k+'_d',{g:'Parti',t:n+' · disiplin süreci',d:'Uyarıdan ihraca kademeli disiplin; hizbin ağırlığını düşürür ama küskünlük yaratır.',lo:1,hi:5,st:1,v:1,lab:v=>['uyarı','kınama','kesin ihraç talebi','görevden alma','tasfiye'][v-1],r:v=>`Ağırlık −${R1(v*1.5)} · memnuniyet −${R1(v*3)} · bölünme riski ${v>=4?'yüksek':'orta'} · parti disiplini +${R1(v*.02)}.`,fx:v=>({}),ap:(v,m)=>{S.fac[k]=Math.max(3,S.fac[k]-v*1.5*m);S.fb[k]-=v*3*m;S.par=clamp(S.par+v*.02*m,0,10);hzN();}});
});
{const _p=partiP;partiP=function(){let h=_p();h=h.replace(/<div class="step">(?:<button class="btn sm sec" data-hz="[^"]*" title="[^"]*">[^<]*<\/button>)+<\/div>/g,'');return h+HZF.map(([k,n])=>xpan('Hizip araçları · '+n,['hz_'+k+'_a','hz_'+k+'_b','hz_'+k+'_c','hz_'+k+'_d'])).join('');};}
/* ---------- Kurum programları: ölçek ve süre ayarlı ---------- */
function pgGo(id){const g=PG.find(x=>x[0]===id);if(!g||S.prg.length>=3||S.prg.some(p=>p.id===id)||avail()<1)return;const sc=ui('pgs_'+id,100),du=ui('pgd_'+id,g[2]);S.cur.spent+=1;S.prg.push({id,left:du,s:sc/100});logA('Program',g[1],`ölçek %${sc}, ${du} ay.`);hap(20,520);save();render();}
const pgP2=()=>`<h2>Programlar</h2><div class="panel">${PG.map(g=>{const p=S.prg.find(x=>x.id===g[0]),id=g[0],sc=ui('pgs_'+id,100),du=ui('pgd_'+id,g[2]);return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${g[1]}</b>${p?` <span class="st good">${p.left} ay kaldı · ölçek %${Math.round(p.s*100)}</span>`:''}${p?'':`<div class="note" style="margin:2px 0 0">Ölçek %${sc} · ${du} ay · aylık etki: ${fxText(Object.fromEntries(Object.entries(g[3]).map(([k,v])=>[k,v*sc/100])))} · toplam bütçe etkisi ≈ ${tl((g[3].acik||0)*sc/100*du)} · bitince bonus.</div>`}</div>${p?'':`${sld('pgs_'+id,25,250,25,sc)}${sld('pgd_'+id,3,24,3,du)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-pgx="${id}"`,'Programı başlat',S.prg.length>=3)}</div>`}</div>`;}).join('')}<div class="note">En fazla 3 program aynı anda sürer. İlk kaydırıcı ölçeği (pilot %25 – ulusal %250), ikincisi süreyi (3-24 ay) belirler; maliyet ve aylık etki ölçekle orantılıdır.</div></div>`;
pgP=pgP2;
/* ---------- Politika kolları: ince ayar ---------- */
xd('pk3',{g:'Politika kolu',t:'TL mevduat teşviki',d:'TL mevduat getirisine vergi istisnası ve dolarizasyonu azaltma.',lo:0,hi:100,st:5,v:25,lab:v=>'stopaj istisnası %'+v,r:v=>`Kur −%${R1(v*.02)} · rezerv +${R1(v*.04)} · maliyet ${tl(v*.003)}.`,fx:v=>({kur:-v*.02,rez:v*.04,acik:v*.003})});
xd('pk4',{g:'Politika kolu',t:'Kur sepeti ağırlığı (dolar–euro)',d:'Euro ağırlığı artarsa Avrupa ticareti rahatlar, dolar borçları kurdan etkilenir.',lo:-20,hi:20,st:5,v:0,lab:v=>v>=0?'euro +'+v:'dolar +'+(-v),r:v=>`Batı ilişkisi ${v>=0?'+':'−'}${R1(Math.abs(v)*.01)} · ihracat ${v>=0?'+':'−'}%${R1(Math.abs(v)*.03)} · kur oynaklığı ↑.`,fx:v=>({bat:v*.01,cari:-v*.005})});
xd('pk5',{g:'Politika kolu',t:'MB bilanço küçültme',d:'Piyasadaki likidite çekilir.',lo:0,hi:30,st:2,v:6,lab:v=>'%'+v+' küçülme',r:v=>`Enflasyon −${R1(v*.02)} · büyüme −${R1(v*.02)} · kur −%${R1(v*.03)}.`,fx:v=>({enf:-v*.02,buy:-v*.02,kur:-v*.03})});
xd('pk7',{g:'Politika kolu',t:'Kamu bankalarına sermaye desteği',d:'Ziraat ve Halkbank sermayesi; kredi arzı genişler.',lo:1,hi:15,st:1,v:3,lab:v=>v+' mlr $',r:v=>`Kredi +%${R1(v*.1)} GSYH · maliyet ${tl(v/S.gdp*100)}.`,fx:v=>({buy:v*.1,acik:v/S.gdp*100})});
{const _k=kurum;kurum=function(){let h=_k();const i=h.indexOf('<div class="panel"><b>Merkez Bankası · rezerv'),x=xpan('Politika kolları · ince ayar',['pk3','pk4','pk5','pk7']);return i<0?h+x:h.slice(0,i)+x+h.slice(i);};}
/* ---------- Yönlendirme ---------- */
function ek5Click(t){const d=t.dataset;
  if(d.plx){plApply(d.plx);return true;}
  if(d.svx){svDo(d.svx);return true;}
  if(d.mwx){minwDo();return true;}
  if(d.mxk){maasDo(d.mxk);return true;}
  if(d.lawr){lawRepeal(d.lawr);return true;}
  if(d.lawf!==undefined){S.lawf=+d.lawf;render();return true;}
  if(d.pgx){pgGo(d.pgx);return true;}
  return false;}
{const _a=arayuzClick;arayuzClick=function(t){return ek5Click(t)||_a(t);};}
