/* ---------- ek6.js: dış politika — ülke temasları, anlaşmalar, diplomasi, istihbarat, örgütler ---------- */
/* ---------- Ülke temasları: çok daha fazla seçenek ---------- */
const alL=()=>true;
UHO.push(
['Dışişleri Bakanı ziyareti','Üst düzey resmî ziyaret ve ortak bildiri.',4,{acik:.004},alL],
['Devlet başkanı düzeyinde ziyaret','Cumhurbaşkanı ziyareti; ağırlıklı mesaj.',8,{acik:.01,des:.02},alL],
['Ortak ticaret heyeti','İş insanlarıyla ortak heyet ve B2B görüşmeleri.',4,{cari:-.02,acik:.006},alL],
['Burs ve değişim programı','Türkiye Bursları ve öğrenci değişimi.',3,{acik:.006,reg:.03},alL],
['Kültür yılı etkinlikleri','Karşılıklı kültür ve sanat yılı.',3,{acik:.004},alL],
['Enerji işbirliği görüşmesi','Doğalgaz, elektrik ve yenilenebilir enerji masası.',5,{cari:-.03,acik:.004},dis_(['isr','arm'])],
['Havayolu seferleri ve sınır kapısı','Doğrudan uçuş ve yeni sınır kapıları.',5,{buy:.01,cari:-.01},alL],
['Savunma sanayii ortaklığı görüşmesi','Ortak üretim ve teknoloji aktarımı görüşmesi.',5,{ord:.03,acik:.004},dis_(['gre','arm','isr','irn'])],
['Diaspora ve toplum etkinliği','Diaspora derneklerine ve toplum köprülerine destek.',3,{des:.02,acik:.003},alL],
['Ortak medya ve dijital projesi','Ortak yayın, kültür ve dijital içerik.',3,{bol:.01},alL],
['Hukuk ve yargı işbirliği anlaşması','İade, hukuki yardım ve adli işbirliği.',3,{huz:.01},alL],
['İklim ve su diplomasisi','Ortak su yönetimi ve iklim projesi.',3,{bat:.01},alL],
['Tarım ve gıda işbirliği','Tarım ürünleri ticaretinde kolaylık.',4,{enf:-.01,cari:-.01},alL],
['Protesto notası','Ülkeyi resmî olarak uyarırsın; yurt içinde destek alır.',-6,{ord:.04,des:.03},alL],
['Büyükelçiyi istişare için geri çağır','Soğukluk mesajı; ilişki düşer, itibar gelişir.',-10,{ord:.06,bat:-.02},alL],
['Ticarette kısıtlama','Belirli ürünlere ek gümrük ve kota getirirsin.',-12,{enf:.03,cari:-.01},alL]);
/* ---------- Anlaşmalar: yeni anlaşmalar + yüzdesel uygulama düzeyi ---------- */
DEALS.push(['gb_ab','AB Gümrük Birliği güncellemesi',3,{bat:.8,cari:-.3,acik:-.1},'Kapsam hizmet ve tarımı da içerir.'],['enerji_az','Azerbaycan doğalgaz kapasite anlaşması',2,{cari:-.4,bol:.3,acik:.05},'TANAP kapasitesi ve fiyat formülü.'],['korfez_yat','Körfez yatırım fonu anlaşması',2,{rez:2,buy:.2,bol:.4,bat:-.1},'Sovereign fonlardan doğrudan yatırım.'],['kusak','Kuşak ve Yol işbirliği',3,{dog:.7,cari:-.3,bat:-.4,buy:.1},'Orta Koridor ve liman yatırımı.'],['jpn_yat','Japon yatırım ve teknoloji paketi',2,{buy:.2,cari:-.2,bat:.1},'Otomotiv ve robotik.'],['kor_sav','Güney Kore savunma sanayii ortaklığı',2,{ord:.3,cari:-.1,dog:.2},'K2 tankı ve KF-21 uçak programları.'],['can_ft','Kanada serbest ticaret anlaşması',2,{cari:-.15,bat:.2},'Tarım ve maden ticareti.'],['bra_tar','Brezilya tarım ve maden ortaklığı',2,{enf:-.1,cari:-.1,dog:.1},'Soya, demir cevheri ve ortak üretim.'],['nga_enj','Nijerya enerji ve inşaat anlaşması',2,{cari:-.15,bol:.2},'Doğal gaz ve altyapı müteahhitliği.'],['pol_sav','Polonya savunma ve gıda anlaşması',2,{bat:.2,ord:.1,cari:-.1},'NATO yan işbirliği.'],['ukr_san','Ukrayna sanayi ve tahıl anlaşması',2,{enf:-.1,dog:.1,bat:.1,ord:.1},'Motor teknolojisi, havacılık.'],['egy_dz','Mısır deniz yetki alanları anlaşması',2,{bol:.4,bat:-.1,ord:.1},'Doğu Akdeniz yetki alanları.'],['irq_kal','Irak kalkınma yolu projesi',2,{cari:-.2,bol:.3,buy:.05},'Kalkınma Yolu demiryolu ve otoyol.'],['suudi_sav','Suudi Arabistan savunma ve yatırım',3,{rez:1.5,ord:.2,bol:.3},'SİHA satışı ve ortak yatırım.'],['pak_san','Pakistan sanayi ve savunma anlaşması',2,{ord:.2,dog:.2,cari:-.05},'Ortak üretim ve eğitim.'],['mys_hel','Malezya helal ürün ve finans anlaşması',2,{cari:-.1,dog:.1},'İslami finans ve helal sertifika.'],['idn_sav','Endonezya savunma ve inşaat anlaşması',2,{ord:.2,cari:-.1,dog:.2},'Ortak üretim ve savunma ihracatı.'],['hun_tdt','Macaristan Türk Devletleri gözlemci ortaklığı',1,{dog:.2,bat:.1,des:.05},'Orta Avrupa köprüsü.']);
Object.assign(DQ,{gb_ab:['ger'],enerji_az:['aze'],korfez_yat:['qat','sau'],kusak:['chn'],jpn_yat:['jpn'],kor_sav:['kor'],can_ft:['can'],bra_tar:['bra'],nga_enj:['nga'],pol_sav:['pol'],ukr_san:['ukr'],egy_dz:['egy'],irq_kal:['irq'],suudi_sav:['sau'],pak_san:['pak'],mys_hel:['mys'],idn_sav:['idn'],hun_tdt:['hun']});
DLM.splice(0,DLM.length,['Niyet beyanı',`etki %20`,.2],['Sembolik',`etki %35`,.35],['Çerçeve anlaşma','etki %50',.5],['Kademeli','etki %65',.65],['Geniş kapsamlı','etki %80',.8],['Tam uygulama','etki %100',1],['Genişletilmiş paket','etki %120; maliyet ve tepki de artar',1.2]);
AL.splice(0,AL.length,...DEALS,...PROJ,...PRIV);
function dealSign(id){const i=ui('dlv_'+id,5),e=DEALS.find(x=>x[0]===id);if(!e||isDone(e))return;const n=S.log.length;dealAct(id+':'+i);if(S.log.length>n&&isDone(e)){S.xr=S.xr||{};const md=DLM[i][2];S.xr['dl_'+id]={m:S.month,t:`${DLM[i][0]} (%${Math.round(md*100)}) imzalandı: ${fxText(sfx2(e[3],md))||'doğrudan etki yok'}.`};if(md>1)applyFx({des:-.05,bat:-.02*(DQ[id]?1:0)});save();render();}}
function dis2(){const L=DEALS,a=avail();return `<h2>Anlaşmalar ve ittifaklar</h2><div class="panel">${L.map(e=>{const dn=isDone(e),q=DQ[e[0]],i=ui('dlv_'+e[0],5),md=DLM[i][2],l=(S.xr||{})['dl_'+e[0]];
  return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${e[1]}</b> ${dn?'<span class="st good">Yürürlükte'+(S.dlm&&S.dlm[e[0]]!==undefined?' · '+DLM[S.dlm[e[0]]][0]:'')+'</span>':''}<div class="note" style="margin:2px 0 0">${e[4]}${q?' Şart: '+q.map(c=>(CT.find(x=>x[0]===c)||[0,c])[1]+' ilişkisi '+nf(S.ul[c],0)+'/50').join(', ')+'.':''}${dn?'':` Düzey: ${DLM[i][0]} (%${Math.round(md*100)}) → ${fxText(sfx2(e[3],md))||'etkisiz'}.`}</div></div>${dn?'':sld('dlv_'+e[0],0,6,1,i)+`<div class="chips" style="margin:4px 0 0">${sbtn(`data-dsg="${e[0]}"`,'Anlaşmayı imzala',e[2]>a)}</div>`}${l?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`:''}</div>`;}).join('')}<div class="note">Her anlaşma bir kez yapılır; kaydırıcı uygulama düzeyini belirler (niyet beyanından genişletilmiş pakete). Karşı ülke ilişkisi en az 50 olmalıdır.</div></div>`;}
/* ---------- Diplomasi: gümrük, ültimatom, istihbarat — yüzdesel / kademeli ---------- */
const dc=()=>CT.find(x=>x[0]===S.dpc)||CT[0];
xd('dtf',{g:'Diplomasi',t:'Ülkeye özel gümrük tarifesi',d:'Seçili ülke ürünlerine uygulanan tarife farkı (eksi = indirim).',lo:-30,hi:40,st:2,v:0,lab:v=>dc()[1]+' · '+(v>=0?'+':'')+v+' puan tarife',r:v=>`İlişki ${v<=0?'+':'−'}${R1(Math.abs(v)*.1)} · cari açık ${v<=0?'+':'−'}${R1(Math.abs(v)*.003)} puan · ihracat gelir ${v>=0?'+':'−'}${tl(Math.abs(v)*.002)} · ${v>10?'karşı tarife riski':'risk düşük'}.`,fx:v=>({cari:v*.003,acik:-v*.002}),ap:(v,m)=>{const c=dc()[0],o=okc(c);rel(c,-v*.1*m);o.tf=v<-6?0:v>6?2:1;}});
xd('dul',{g:'Diplomasi',t:'Ültimatom',d:'Sertlik arttıkça kazanç ve zarar büyür; başarı şansı savaş gücüne ve ilişkiye bağlı.',lo:1,hi:10,st:1,v:3,lab:v=>dc()[1]+' · sertlik '+v+'/10',r:v=>{const c=dc()[0],p=clamp(.1+(gucu()-(CG[c]??45))/100,.05,.7)*(1.2-v*.06)*100;return `Başarı şansı ≈ %${nf(p,0)} · başarıda ordu +${R1(v*.06)}, ilişki −${R1(v*1.6)} · başarısızlıkta ilişki −${R1(v*4)}, halk desteği −${R1(v*.12)}.`;},fx:v=>({}),ap:(v,m)=>{const c=dc()[0],p=clamp(.1+(gucu()-(CG[c]??45))/100,.05,.7)*(1.2-v*.06)*(.6+.4*m);if(Math.random()<p){rel(c,-v*1.6);applyFx({ord:.06*v*m,bat:-.02*v});S.xr.dul_o='başarılı';}else{rel(c,-v*4);applyFx({ord:-.04*v,des:-.12*v,[dc()[2]]:-.06*v});S.xr.dul_o='başarısız';}}});
{const _d=xdo;xdo=function(id){const n=S.log.length;S.xr=S.xr||{};S.xr.dul_o='';_d(id);if(id==='dul'&&S.xr.dul_o&&S.log.length>n){S.xr.dul.t='Ültimatom '+S.xr.dul_o+'. '+S.xr.dul.t;save();render();}};}
IO.push(['Diplomatik istihbarat','Yabancı heyetlerin niyet analizi: itibar ve diplomasi.',{bat:.04,dog:.04},0],['Terörle mücadele istihbaratı','Sınır ötesi ağları takip.',{huz:.12,ord:.05},0],['Kara para ve kripto takibi','Mali istihbarat birimi.',{acik:-.05,bat:.02},0],['Savunma sanayii koruması','Casusluğa karşı sanayi güvenliği.',{ord:.06,cari:-.01},0],['Yabancı medya etkisi analizi','Etki kampanyalarını izle.',{des:.03,huz:.05},0],['Gizli arabuluculuk','Kapalı kanal diplomasisi; başarı güce bağlı.',{bat:.1,bol:.1},1]);
const ioY=i=>ui('ioy'+i,60);
const ioP=()=>{const I=S.dp&&S.dp.ig;if(!I||!I.on)return '';return `<div class="panel"><b>İstihbarat operasyonları · yoğunluk ayarlı</b><div class="note">Yoğunluk arttıkça etki büyür; gizli operasyonlarda ifşa riski de artar. Merkez gücü ${nf(I.g,0)}/100.</div>${IO.map((x,i)=>{const y=ioY(i),risk=x[3]?clamp(1-I.g/110*(1.15-y/200),.1,.9):0,l=(S.xr||{})['io'+i];return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${x[0]}</b> · yoğunluk %${y}<div class="note" style="margin:2px 0 0">${x[1]} Etki ${fxText(sfx2(x[2],y/100))}${x[3]?` · başarı şansı ≈ %${nf((1-risk)*100,0)}`:''}.</div></div>${sld('ioy'+i,10,150,10,y)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-ioy="${i}"`,'Yürüt')}</div>${l?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`:''}</div>`;}).join('')}</div>`;};
function ioDo(i){const x=IO[i],I=S.dp.ig,y=ioY(i)/100,m=su('io');if(!x||!I.on)return;suU('io');S.xr=S.xr||{};let t;
  if(x[3]){const p=clamp(I.g/110*(1.15-y/2),.1,.85);if(Math.random()<p){applyFx(sfx2(x[2],m*y));t='Operasyon başarılı: '+fxText(sfx2(x[2],m*y))+'.';}else{rel(['usa','rus','ger'][Math.floor(Math.random()*3)],-8*y);applyFx({bat:-.2*y,ord:-.1*y});t='Operasyon ifşa oldu: ilişkiler ve itibar zarar gördü.';}}
  else{applyFx(sfx2(x[2],m*y));t='Uygulandı: '+fxText(sfx2(x[2],m*y))+'.'+sat(m);}
  S.xr['io'+i]={m:S.month,t};logA('İstihbarat',x[0],`yoğunluk %${y*100}`);hap(20,520);save();render();}
{const _p=dipP;dipP=function(){let h=_p();h=h.replace(/<div class="lever"><span class="n">Gümrük tarifesi<\/span>[\s\S]*?<\/div><\/div>/,'').replace(/<div class="lever"><span class="n">Ültimatom<\/span>[\s\S]*?<\/div><\/div>/,'');const i=h.indexOf('<div class="panel"><b>İstihbarat merkezi</b>');let mid='<div class="panel"><b>'+dc()[1]+' · tarife ve ültimatom</b>'+['dtf','dul'].map(xrow).join('')+'</div>';
  if(i<0)return h+mid;let j=h.indexOf('</div></div>',h.indexOf('data-igo'));const hh=h.slice(0,i)+mid+h.slice(i);return hh.replace(/<div class="lever"><span class="n">Siber dinleme[\s\S]*?(?=<div class="note">Merkez her ay)/,'').replace(/(<div class="lever">(?:(?!<div class="lever">)[\s\S])*?data-iop="\d+"[\s\S]*?<\/div><\/div>)+/g,'')+ioP();};}
/* ---------- Örgütler: önerge yaklaşımı ve etkinlik seçenekleri ---------- */
TS.splice(0,TS.length,['Acil oylama · 1 ay',1,-10,'1 ay sonra oylama, destek −10'],['Hızlandırılmış · 2 ay',2,-5,'2 ay sonra oylama, destek −5'],['Standart · 3 ay',3,0,'3 ay sonra oylama'],['Ön görüşmeli · 4 ay',4,5,'4 ay, ön görüşmeyle destek +5'],['Üye ziyaretli · 5 ay',5,9,'5 ay, ikili ziyaretlerle destek +9'],['Lobi turlu · 6 ay',6,13,'6 ay, lobi turuyla destek +13'],['Zirve diplomasisi · 8 ay',8,18,'8 ay, zirve görüşmeleriyle destek +18'],['Koalisyon kurma · 10 ay',10,23,'10 ay, ortak kampanya ve koalisyonla destek +23']);
OAC.push(['Ek katkı payı: %10','Üyelik aidatına %10 ek katkı.',3,{acik:.015}],['Ek katkı payı: %25','Üyelik aidatına %25 ek katkı; fon ve projelerde söz hakkı.',6,{acik:.035}],['Ek katkı payı: %50','Aidat ve gönüllü fona büyük katkı.',10,{acik:.08,des:.02}],['Dışişleri Bakanı düzeyinde temsil','Bakan düzeyinde katılım.',2,{}],['Bakan yardımcısı düzeyinde temsil','Düşük ama sürekli katılım.',1,{}],['Gündem önerisi sun','Toplantı gündemine Türkiye önerisi eklenir.',4,{}],['Komisyon başkanlığına aday ol','Teknik komisyon başkanlığı için kampanya.',5,{acik:.01}],['Gözlemci misyonu gönder','Bölgesel barış ve seçim gözlemi.',4,{acik:.01,bat:.02}],['Ortak bildiri hazırlığı','Üyelerle ortak bildiri için kapalı çalışma.',5,{}],['Yan toplantı ve resepsiyon','Zirve marjında ikili görüşmeler.',3,{acik:.005}],['Bölgesel fon başlat','Üyelere kalkınma projesi fonu.',7,{acik:.04,bol:.03}],['Üyeliği askıya alma tehdidi','Sert tutum; destek düşer, yurt içi destek artar.',-10,{des:.06,bat:-.05}]);
function orgY(){S.osel=S.osel||null;return `<h2>Örgütlerde etkinlik</h2><div class="panel">${ORG.map(o=>{const g=S.og[o[0]];return `<div class="lever"><span class="n">${o[1]}</span><span class="h">Destek %${nf(oSup(o),0)}${g.sb?' (etkinlik '+(g.sb>0?'+':'')+nf(g.sb,0)+')':''} · ${o[6]}</span><div class="step">${sbtn(`data-osel="${o[0]}"`,S.osel===o[0]?'Kapat':'Etkinlikler')}</div>${S.osel===o[0]?`<div style="grid-column:1/-1">${OAC.map((x,i)=>opRow(x[0],x[1]+' Destek '+(x[2]>0?'+':'')+x[2]+(fxText(x[3])?' · '+fxText(x[3]):'')+'.',sbtn(`data-oac="${o[0]}:${i}"`,'Gerçekleştir'))).join('')}</div>`:''}</div>`;}).join('')}<div class="note">Etkinlik bonusu her ay %10 söner. Kaydırıcıyla etkinliğin ölçeğini (katkı, süre, düzey) ayarlarsın.</div></div>`;}
/* ---------- Yönlendirme ---------- */
function ek6Click(t){const d=t.dataset;
  if(d.dsg){dealSign(d.dsg);return true;}
  if(d.ioy!==undefined){ioDo(+d.ioy);return true;}
  if(d.osel){S.osel=S.osel===d.osel?null:d.osel;render();return true;}
  return false;}
{const _a=arayuzClick;arayuzClick=function(t){return ek6Click(t)||_a(t);};}
