/* ---------- ek7.js: askeri — komuta kademesi, savunma ithalatı, yerli üretim, ihracat sözleşmeleri, envanter ---------- */
/* ---------- Komuta kademesi: yeni birlikler ve komutanlar ---------- */
KK.push(['ozel','Özel Kuvvetler Komutanlığı'],['jand','Jandarma Genel Komutanlığı'],['sibr','Siber Komutanlığı']);
KO.kara.push(['Orgeneral Tuna Aydın','Genelkurmay planlama geçmişi: hazırlık +3, tecrübe +3.',{hz:3,tc:3}]);
KO.hava.push(['Orgeneral Derya Kaplan','Uzay ve füze savunma: hazırlık +4, tecrübe +3.',{hz:4,tc:3}]);
KO.deniz.push(['Oramiral Barış Yurt','Amfibi harekât: hazırlık +3, tecrübe +4.',{hz:3,tc:4}]);
KO.ozel=[['Tümgeneral Emre Çınar','Sınır ötesi harekât tecrübesi: tecrübe +5.',{tc:5}],['Tümgeneral Seda Yalçın','Eğitim ve esneklik: hazırlık +3, tecrübe +3.',{hz:3,tc:3}],['Tümgeneral Orhan Tekin','Terörle mücadele: tecrübe +4, huzur katkısı.',{tc:4,huz:.01}]];
KO.jand=[['Orgeneral Ali Rıza Bal','İç güvenlik tecrübesi: huzur katkısı, hazırlık +2.',{hz:2,huz:.02}],['Orgeneral Nilgün Toprak','Modern jandarma: hazırlık +3, tecrübe +2.',{hz:3,tc:2}],['Orgeneral Kemal Sezer','Sınır güvenliği: hazırlık +3, huzur +.',{hz:3,huz:.015}]];
KO.sibr=[['Tümgeneral Cenk Arslan','Siber savunma uzmanı: hazırlık +3, Batı itibarı.',{hz:3,bat:.01}],['Tümgeneral Ece Yıldız','Siber operasyon: tecrübe +4.',{tc:4}],['Tümgeneral Murat Özkan','Kritik altyapı koruması: hazırlık +4, huzur.',{hz:4,huz:.01}]];
{const _g=genisEnsure;genisEnsure=function(){_g();if(S.kk)KK.forEach(([b])=>{if(S.kk[b]===undefined)S.kk[b]=-1;});};}
xd('kd1',{g:'Komuta',t:'Genelkurmay yapılanması ve subay eğitimi',d:'Karargâh ve birlik yapısı sadeleştirilir; subay yetiştirme ve kurmay eğitimi artar.',lo:1,hi:10,st:1,v:3,lab:v=>'seviye '+v,r:v=>`Hazırlık +${R1(v*.6)} · tecrübe +${R1(v*.5)} · maliyet ${tl(v*.014)} · ordu memnuniyeti +${R1(v*.01)}.`,fx:v=>({acik:v*.014,ord:v*.01}),ap:(v,m)=>{S.mil.hz=clamp(S.mil.hz+v*.6*m,0,100);S.mil.tc=clamp(S.mil.tc+v*.5*m,0,100);}});
xd('kd3',{g:'Komuta',t:'Terfi ve emeklilik düzeni (YAŞ)',d:'Üst kademede genç komutanlara yer açılır.',lo:-3,hi:3,st:1,v:0,lab:v=>v>0?'gençleştirme '+v:v<0?'kıdemi koru '+(-v):'mevcut düzen',r:v=>`Tecrübe ${v>=0?'+':'−'}${R1(Math.abs(v)*.5)} · ordu memnuniyeti ${v>=0?'−':'+'}${R1(Math.abs(v)*.03)} · hazırlık ${v>=0?'+':'−'}${R1(Math.abs(v)*.4)}.`,fx:v=>({ord:-v*.03}),ap:(v,m)=>{S.mil.hz=clamp(S.mil.hz+v*.4*m,0,100);S.mil.tc=clamp(S.mil.tc+v*.5*m,0,100);}});
xd('kd4',{g:'Komuta',t:'Birlik konuşlanma düzeni',d:'Birlikler doğu, batı ve deniz bölgeleri arasında yeniden dağıtılır.',lo:-3,hi:3,st:1,v:0,lab:v=>v>0?'doğu/güney ağırlıklı '+v:v<0?'batı/deniz ağırlıklı '+(-v):'dengeli',r:v=>`${v>0?'Sınır güvenliği':'Ege ve Doğu Akdeniz caydırıcılığı'} güçlenir · Yunanistan ilişkisi ${v>0?'+':'−'}${R1(Math.abs(v)*.5)} · huzur ${v>0?'+':'−'}${R1(Math.abs(v)*.02)}.`,fx:v=>({huz:v*.02}),ap:(v,m)=>{rel('gre',v*.5*m);}});
xd('kd5',{g:'Komuta',t:'Askerî yargı ve disiplin reformu',d:'Disiplin süreçleri sivil denetime yaklaşır.',lo:0,hi:5,st:1,v:1,lab:v=>'seviye '+v,r:v=>`Batı itibarı +${R1(v*.04)} · ordu memnuniyeti −${R1(v*.04)} · NATO uyumu +${R1(v*.5)}.`,fx:v=>({bat:v*.04,ord:-v*.04})});
{const _k=komP;komP=function(){return _k()+xpan('Komuta · yapılanma kararları',['kd1','kd3','kd4','kd5']);};}
/* ---------- Savunma ithalatı: ürünü hangi ülke üretiyorsa ondan ---------- */
/* [id, ad, kategori, güç puanı/adet, birim, tedarikçiler: [ülke, birim fiyat (milyon $), teslim (ay), minimum ilişki, not]] */
const DEFI=[
['f16','F-16 Block 70 (Viper) savaş uçağı','Hava',.06,'uçak',[['usa',80,24,45,'Lockheed Martin']],40],
['f35','F-35A Lightning II','Hava',.12,'uçak',[['usa',90,36,55,'Lockheed Martin; S-400 varsa satış engellenir']],40],
['typh','Eurofighter Typhoon','Hava',.1,'uçak',[['uk',115,30,40,'BAE Systems'],['ger',118,30,40,'Airbus'],['ita',112,30,40,'Leonardo'],['esp',114,30,40,'Airbus']],40],
['rafale','Dassault Rafale','Hava',.11,'uçak',[['fra',95,30,40,'Dassault']],40],
['gripen','Saab Gripen E','Hava',.07,'uçak',[['swe',60,24,40,'Saab']],30],
['kf21','KF-21 Boramae','Hava',.08,'uçak',[['kor',68,36,35,'KAI']],40],
['jf17','JF-17 Thunder / J-10CE','Hava',.05,'uçak',[['pak',30,18,40,'JF-17 (PAC)'],['chn',50,20,35,'J-10CE (Chengdu)']],50],
['su35','Su-35 savaş uçağı','Hava',.09,'uçak',[['rus',85,24,35,'Sukhoi; ABD yaptırım riski']],24],
['s400','Uzun menzilli hava savunma bataryası','Hava savunma',.45,'batarya',[['rus',500,18,35,'S-400 (Almaz-Antey); CAATSA riski'],['usa',1000,36,50,'Patriot (Raytheon)'],['fra',650,30,40,'SAMP/T (Eurosam)'],['ita',650,30,40,'SAMP/T (Eurosam)'],['chn',300,24,35,'HQ-9 (CPMIEC)']],6],
['tank','Ana muharebe tankı','Kara',.012,'tank',[['ger',15,24,40,'Leopard 2A7 (KNDS)'],['kor',9,18,35,'K2 Black Panther (Hyundai Rotem)'],['pol',8,18,40,'K2PL (ortak üretim)'],['usa',10,24,50,'M1A2 Abrams (GDLS)'],['rus',5,18,35,'T-90MS (Uralvagonzavod)']],300],
['heli','Taarruz ve nakliye helikopteri','Hava',.02,'helikopter',[['usa',25,24,45,'UH-60 Black Hawk / AH-64'],['ita',25,24,40,'AW149 (Leonardo)'],['rus',10,18,35,'Mi-17 / Ka-52'],['chn',18,18,35,'Z-10']],60],
['fre','Fırkateyn (FREMM / Gowind)','Deniz',.35,'gemi',[['ita',700,48,40,'FREMM (Fincantieri)'],['fra',420,42,40,'Gowind (Naval Group)'],['uk',480,48,40,'Type 31 (Babcock)'],['kor',380,42,35,'FFX Batch (HHI)']],6],
['sub','Hücumbot / denizaltı','Deniz',.4,'denizaltı',[['ger',550,60,45,'Type 214 (TKMS)'],['kor',480,60,40,'KSS-III (HHI)'],['swe',500,60,40,'A26 (Saab)']],4],
['him','Çoklu roketatar sistemi','Kara',.02,'sistem',[['usa',8,18,50,'HIMARS (Lockheed)'],['kor',9,18,40,'K239 Chunmoo (Hanwha)'],['isr',7,12,45,'PULS (Elbit)']],60],
['top','Obüs ve topçu sistemi','Kara',.012,'sistem',[['ger',10,24,40,'PzH 2000 (KNDS)'],['kor',4.5,18,35,'K9 Thunder (Hanwha)'],['pol',5,18,40,'Krab (HSW)']],100],
['muh','155mm mühimmat (bin adet)','Mühimmat',.003,'bin adet',[['ger',3.5,6,40,'Rheinmetall'],['pol',2.4,6,40,'PGZ'],['kor',2.8,6,35,'Poongsan'],['usa',3.8,9,45,'General Dynamics'],['ukr',2,6,40,'Ukroboronprom']],500],
['fuz','Havadan havaya ve havadan karaya füze','Mühimmat',.004,'füze',[['uk',2,12,40,'Meteor (MBDA)'],['fra',1.8,12,40,'MICA (MBDA)'],['usa',1.5,12,45,'AMRAAM (Raytheon)']],300],
['insa','Silahlı insansız hava aracı','Hava',.025,'İHA',[['usa',30,24,50,'MQ-9 Reaper'],['chn',12,12,35,'Wing Loong II'],['isr',20,18,45,'Heron TP']],40],
['rad','Radar ve erken uyarı sistemi','Elektronik',.06,'sistem',[['usa',400,36,55,'E-7 Wedgetail'],['swe',120,24,40,'Erieye (Saab)'],['isr',90,18,45,'EL/M-2084 (IAI)'],['kor',70,18,35,'Hanwha radar']],10],
['tfk','Piyade tüfeği (bin adet)','Kara',.002,'bin adet',[['ita',.9,6,40,'Beretta'],['ger',1.3,9,40,'Heckler & Koch'],['usa',1.1,9,45,'Colt']],500]];
const dfInv=()=>(S.inv=S.inv||{}),dfPend=()=>(S.invp=S.invp||[]);
const dfCC=id=>{const x=DEFI.find(z=>z[0]===id);return x?x[5]:[];};
const dfSel=id=>{const L=dfCC(id),i=ui('dfs_'+id,0);return L[Math.min(i,L.length-1)];};
function dfPrev(x){const id=x[0],n=ui('dfn_'+id,Math.min(2,x[6])),p=dfSel(id),c=p[0],rl0=S.ul[c]||0,emb=rl0<p[3],pr=p[1]*(1+(rl0<55?.15:0)),tot=n*pr/1000;return {n,p,c,emb,tot,pr,pw:n*x[3]*2};}
function dfBuy(id){const x=DEFI.find(z=>z[0]===id);if(!x)return;const o=dfPrev(x);if(o.emb||S.rez-o.tot<12)return;const m=su('df'+id);suU('df'+id);S.rez-=o.tot;dfPend().push({id,n:o.n,due:S.month+o.p[2],c:o.c,src:o.p[4]});
  const fx={acik:o.tot/S.gdp*100*.05,cari:o.tot*.05};if(o.c==='rus'&&(id==='s400'||id==='su35')){rel('usa',-10);rel('ger',-3);fx.bat=-.5;logA('Savunma ithalatı','Yaptırım riski','ABD ilişkisi düştü: CAATSA yaptırımı gündemde.');}rel(o.c,Math.min(6,2+o.tot*2)*m);applyFx(fx);
  S.xr=S.xr||{};S.xr['df_'+id]={m:S.month,t:`${o.n} ${x[4]} sipariş edildi (${CT.find(z=>z[0]===o.c)[1]}): ${nf(o.tot,2)} mlr $ rezervden ödendi, teslimat ${o.p[2]} ay sonra (${dateLabel(S.month+o.p[2])}). Envantere +${R1(o.pw)} güç puanı katar.`+sat(m)};logA('Savunma ithalatı',x[1],`${o.n} ${x[4]} · ${CT.find(z=>z[0]===o.c)[1]}`);hap(20,520);save();render();}
const dfP=()=>{const r=[];const cats=[...new Set(DEFI.map(x=>x[2]))];
  return `<div class="panel"><b>Savunma ithalatı</b><div class="note" style="margin:2px 0 6px">Her sistemi yalnızca gerçekten üreten ülkelerden alırsın. Ödeme rezervden yapılır; teslimat süre alır. İlişkisi eşiğin altındaki ülke satmaz, 55'in altında fiyat %15 artar. Rezerv: ${nf(S.rez,1)} mlr $.</div>${DEFI.map(x=>{const o=dfPrev(x),L=x[5],id=x[0],sel=Math.min(ui('dfs_'+id,0),L.length-1),l=(S.xr||{})['df_'+id];
    return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${x[1]}</b><div class="note" style="margin:2px 0 0">${x[2]} · tedarikçi: ${CT.find(z=>z[0]===o.c)[1]} (${o.p[4]}) · birim ${nf(o.pr,1)} milyon $ · teslim ${o.p[2]} ay · ${o.n} ${x[4]} = ${nf(o.tot,2)} mlr $ · güç +${R1(o.pw)}${o.emb?` · <b style="color:var(--bad)">ilişki ${nf(S.ul[o.c],0)}/${o.p[3]}: satmıyor</b>`:''}</div></div>${L.length>1?`<div class="chips" style="margin:4px 0">${L.map((p,i)=>`<button class="btn sm ${sel===i?'':'sec'}" data-dfs="${id}:${i}">${CT.find(z=>z[0]===p[0])[1]}</button>`).join('')}</div>`:''}<div class="dl" style="font-size:12px">Miktar: ${o.n} ${x[4]}</div>${sld('dfn_'+id,1,x[6],x[6]>100?10:1,o.n)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-dfb="${id}"`,'Sipariş ver',o.emb||S.rez-o.tot<12)}</div>${l?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`:''}</div>`;}).join('')}</div>`;};
/* ---------- Yerli üretim hatları ve ihracat ---------- */
/* [id, ad, asgari sanayi kapasitesi, birim maliyet (milyon $), birim ihracat fiyatı, güç puanı/adet, kurulum maliyeti (mlr $), azami yıllık adet, gerekli proje] */
const OWN=[['siha','Bayraktar / Akıncı SİHA',15,3,6,.025,.3,60,''],['zam','Zırhlı araç (Kirpi, Arma, Tulpar)',20,1,1.8,.01,.4,400,''],['top','Obüs ve roketatar (Fırtına, T-122)',25,4,7,.015,.5,80,''],['fuz','Roketsan füzeleri (Tayfun, Çakır)',30,1.5,2.8,.02,.8,300,''],['gem','Korvet ve açık deniz karakol gemisi',35,180,260,.5,2,3,''],['hsv','Hava savunma sistemleri (Hisar, Siper)',45,60,100,.08,2.5,10,''],['tnk','Altay ana muharebe tankı',50,8,12,.05,3,60,'altay'],['kaan','KAAN muharip uçak',60,120,170,.15,6,18,'kaan'],['muh','Mühimmat ve hafif silah (lot)',10,.4,.7,.004,.1,2000,'']];
const OWNX=['usa','gre','arm','isr','irn'];
const owPl=()=>(S.opl=S.opl||{}),owSt=()=>(S.ost=S.ost||{}),owCt=()=>(S.oct=S.oct||[]);
const owOk=x=>(S.sy.kap||0)>=x[2]&&(!x[8]||S.spd[x[8]]!==undefined);
function owLine(id){const x=OWN.find(z=>z[0]===id);if(!x||!owOk(x))return;const r=ui('owr_'+id,Math.min(10,x[7])),old=owPl()[id]||0,setup=old?0:x[6];if(S.rez-setup<12)return;S.rez-=setup;owPl()[id]=r;S.xr=S.xr||{};S.xr['ow_'+id]={m:S.month,t:r?`Üretim hattı yıllık ${r} adede ayarlandı. Aylık maliyet ≈ ${nf(r*x[3]/12/1000,3)} mlr $${setup?`; kurulum ${nf(setup,1)} mlr $ ödendi`:''}. Ürün stoka girer: ordu güçlenir ya da ihracat sözleşmesine ayrılır.`:'Üretim hattı kapatıldı.'};logA('Savunma sanayii',x[1],`yıllık ${r} adet`);hap(20,520);save();render();}
function owExp(id){const x=OWN.find(z=>z[0]===id);if(!x)return;const c=ui('oxc_'+id,'sau'),n=ui('oxn_'+id,5),fp=ui('oxp_'+id,100)/100;if(OWNX.includes(c)||(S.ul[c]||0)<50||owCt().length>=5)return;if(Math.random()>clamp(1.1-(fp-.6)*.9+((S.ul[c]||50)-50)/200,.2,1)){logA('Savunma ihracatı',x[1],'Karşı taraf fiyatı yüksek buldu; sözleşme imzalanmadı.');hap(20,520);save();render();return;}const mo=Math.max(3,Math.ceil(n/Math.max(.5,(owPl()[id]||1)/12)));
  owCt().push({id,c,n,left:mo,d:n/mo,pr:x[4]*fp});S.xr=S.xr||{};S.xr['ox_'+id]={m:S.month,t:`${CT.find(z=>z[0]===c)[1]}'a ${n} adet ${x[1]} satış sözleşmesi imzalandı: ${mo} ayda teslim, toplam ≈ ${nf(n*x[4]*fp/1000,3)} mlr $ gelir. Stoktan düşülür; ordu envanteri azalır.`};rel(c,2+Math.max(0,1-fp)*8-Math.max(0,fp-1)*4);logA('Savunma ihracatı',x[1],`${CT.find(z=>z[0]===c)[1]} · ${n} adet`);hap(20,520);save();render();}
const owStock=id=>owSt()[id]||0;
const owP=()=>`<div class="panel"><b>Yerli üretim ve ihracat</b><div class="note" style="margin:2px 0 6px">Savunma sanayii kapasitesi ${nf(S.sy.kap,0)}/100. Her ürün için asgari kapasite gerekir; hat kurulumu ve aylık üretim maliyeti rezervden/bütçeden karşılanır. Üretilen ürün stoka girer: tutarsan ordun güçlenir, satarsan para kazanırsın (satılan ürün stoktan düşer).</div>${OWN.map(x=>{const id=x[0],ok=owOk(x),r=ui('owr_'+id,Math.min(10,x[7])),c=ui('oxc_'+id,'sau'),n=ui('oxn_'+id,5),fp=ui('oxp_'+id,100),l=(S.xr||{})['ow_'+id],l2=(S.xr||{})['ox_'+id],cl=CT.find(z=>z[0]===c)||CT[0],bad=OWNX.includes(c)||(S.ul[c]||0)<50;
  return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div class="dl"><b>${x[1]}</b> ${ok?'':`<span class="st bad">kapasite ${x[2]} gerekir${x[8]?' ve proje tamamlanmalı':''}</span>`}<div class="note" style="margin:2px 0 0">Birim maliyet ${x[3]} milyon $ · ihracat fiyatı ${x[4]} milyon $ · stok ${nf(owStock(id),1)} · hat: ${owPl()[id]||0} adet/yıl · kurulum ${x[6]} mlr $.</div></div>${ok?`<div class="dl" style="margin-top:4px">Üretim hattı: yıllık ${r} adet · aylık maliyet ≈ ${nf(r*x[3]/12/1000,3)} mlr $<div class="note" style="margin:2px 0 0">Satmazsan her yıl ${r} adet ordu envanterine girer (güç +${R1(r*x[5])}).</div></div>${sld('owr_'+id,0,x[7],x[7]>100?10:1,r)}<div class="chips" style="margin:4px 0">${sbtn(`data-owl="${id}"`,owPl()[id]?'Hattı güncelle':'Hattı kur')}</div>${l?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l.m)}): ${l.t}</div>`:''}
  <div class="dl" style="margin-top:6px">İhracat: ${cl[1]} · ${n} adet · fiyat %${fp}<div class="note" style="margin:2px 0 0">Gelir ≈ ${nf(n*x[4]*fp/100/1000,3)} mlr $ · ilişki ${nf(S.ul[c]||0,0)}${bad?' · <b style="color:var(--bad)">bu ülkeye satış yapılamaz (ilişki 50 altı ya da yasaklı)</b>':''} · sözleşme ${owCt().length}/5.</div></div><div class="chips" style="margin:4px 0">${CT.filter(z=>!OWNX.includes(z[0])&&(S.ul[z[0]]||0)>=50).slice(0,14).map(z=>`<button class="btn sm ${c===z[0]?'':'sec'}" data-oxc="${id}:${z[0]}">${z[1]}</button>`).join('')}</div><div class="dl" style="font-size:12px">Adet: ${n}</div>${sld('oxn_'+id,1,Math.max(2,Math.min(x[7],x[7]>100?200:20)),x[7]>100?10:1,n)}<div class="dl" style="font-size:12px">Fiyat: %${fp} (düşük fiyat satışı kolaylaştırır)</div>${sld('oxp_'+id,60,150,5,fp)}<div class="chips" style="margin:4px 0 0">${sbtn(`data-oxs="${id}"`,'İhracat sözleşmesi imzala',bad||owCt().length>=5)}</div>${l2?`<div class="note" style="color:var(--gold,#F2C14E)">Son sonuç (${dateLabel(l2.m)}): ${l2.t}</div>`:''}`:''}</div>`;}).join('')}</div>`;
/* ---------- Envanter ---------- */
const invPow=()=>{let p=0;DEFI.forEach(x=>{p+=(dfInv()[x[0]]||0)*x[3]*2;});OWN.forEach(x=>{p+=owStock(x[0])*x[5];});return Math.min(12,p);};
const invP=()=>{const rows=[];DEFI.forEach(x=>{const n=dfInv()[x[0]]||0;if(n)rows.push([x[1]+' (ithal)',n,x[4],n*x[3]*2]);});OWN.forEach(x=>{const n=owStock(x[0]);if(n>=.5)rows.push([x[1]+' (yerli)',n,'adet',n*x[5]]);});
  return `<div class="panel"><b>Envanter</b> <span class="muted dl">· toplam güç katkısı +${R1(invPow())} (üst sınır 12)</span>${rows.length?rows.map(r=>`<div class="dl" style="display:flex;justify-content:space-between;gap:8px;border-top:1px solid var(--line);padding:4px 0"><span>${r[0]}</span><span>${nf(r[1],r[1]%1?1:0)} ${r[2]} · +${R1(r[3])}</span></div>`).join(''):'<div class="note">Envanter boş: ithalat siparişi ver ya da yerli üretim hattı kur.</div>'}${dfPend().length?`<div class="dl" style="margin-top:8px"><b>Bekleyen teslimatlar</b></div>${dfPend().map(p=>`<div class="dl" style="display:flex;justify-content:space-between;gap:8px"><span>${(DEFI.find(x=>x[0]===p.id)||[0,p.id])[1]}</span><span>${p.n} · ${dateLabel(p.due)}</span></div>`).join('')}`:''}${owCt().length?`<div class="dl" style="margin-top:8px"><b>İhracat sözleşmeleri</b></div>${owCt().map(c=>`<div class="dl" style="display:flex;justify-content:space-between;gap:8px"><span>${(OWN.find(x=>x[0]===c.id)||[0,c.id])[1]} → ${(CT.find(z=>z[0]===c.c)||[0,c.c])[1]}</span><span>${nf(c.d*c.left,0)} adet · ${c.left} ay</span></div>`).join('')}`:''}</div>`;};
/* ---------- Aylık işleyiş ---------- */
function dfUp(){const h=[];dfPend();S.invp=S.invp.filter(p=>{if(S.month<p.due)return true;dfInv()[p.id]=(dfInv()[p.id]||0)+p.n;h.push(`${(DEFI.find(x=>x[0]===p.id)||[0,p.id])[1]}: ${p.n} adet teslim alındı (${p.src}).`);return false;});
  OWN.forEach(x=>{const r=owPl()[x[0]]||0;if(!r)return;const u=r/12,c=u*x[3]/1000;owSt()[x[0]]=owStock(x[0])+u;applyFx({acik:c/S.gdp*100});S.rez=Math.max(-5,S.rez-c*.4);});
  let val=0;DEFI.forEach(x=>{const n=dfInv()[x[0]]||0;if(n){val+=n*Math.min(...x[5].map(p=>p[1]))/1000;dfInv()[x[0]]=n*(1-.03/12);}});OWN.forEach(x=>{const n=owStock(x[0]);if(n){val+=n*x[3]/1000;owSt()[x[0]]=n*(1-.03/12);}});const up=val*.04/12;if(up>0){applyFx({acik:up/S.gdp*100});S.rez=Math.max(-5,S.rez-up*.3);}
  owCt().forEach(c=>{const x=OWN.find(z=>z[0]===c.id),u=Math.min(c.d,owStock(c.id));owSt()[c.id]=owStock(c.id)-u;const rev=u*c.pr/1000;S.rez=clamp(S.rez+rev,-5,120);applyFx({cari:-rev*.2,acik:-rev/S.gdp*100*.5});if(u<c.d*.8){rel(c.c,-1.5);}c.left--;});
  const done=owCt().filter(c=>c.left<=0);done.forEach(c=>{h.push(`${(OWN.find(x=>x[0]===c.id)||[0,c.id])[1]}: ${(CT.find(z=>z[0]===c.c)||[0,c.c])[1]} sözleşmesi tamamlandı.`);rel(c.c,2);if(S.sy)S.sy.pih=(S.sy.pih||0)+.3;});S.oct=owCt().filter(c=>c.left>0);return h;}
{const _u=d2Up;d2Up=function(){const h=_u()||[];return h.concat(dfUp());};}
{const _o=ordX;ordX=function(){const h=_o().split('<div class="panel"><b>Savunma ihracatı sözleşmeleri')[0];const y=S.sy;return h+dfP()+owP()+invP()+(y.ks.length?`<div class="panel"><b>Süren eski ihracat sözleşmeleri</b>${y.ks.map(k=>`<div class="dl">${(CT.find(c=>c[0]===k.id)||[0,k.id])[1]}: ${k.p||'Sözleşme'} · ${k.left} ay kaldı</div>`).join('')}</div>`:'');};}
function ek7Click(t){const d=t.dataset;
  if(d.dfs){const [id,i]=d.dfs.split(':');S.ui['dfs_'+id]=+i;render();return true;}
  if(d.dfb){dfBuy(d.dfb);return true;}
  if(d.owl){owLine(d.owl);return true;}
  if(d.oxc){const [id,c]=d.oxc.split(':');S.ui['oxc_'+id]=c;render();return true;}
  if(d.oxs){owExp(d.oxs);return true;}
  return false;}
{const _a=arayuzClick;arayuzClick=function(t){return ek7Click(t)||_a(t);};}
