/* ek9: IMF ekranı, yıl sonu raporu, kararlar arası kısa notlar */
/* ---------- Bilgi ekranları (S.scr) ---------- */
const YRS=[['enf','Enflasyon','%',1,1],['buy','Büyüme','%',1,0],['isz','İşsizlik','%',1,1],['acik','Bütçe açığı / GSYH','%',1,1],['borc','Dış borç / GSYH','%',1,1],['rez','Net rezerv','mlr $',0,0],['kur','Dolar / TL','₺',2,1],['des','Halk desteği','%',1,0]];
function yrRep(){const H=S.hist||{},n=(H.enf||[]).length,a=Math.max(0,n-13),r=YRS.map(([k,l,u,d,low])=>{const h=H[k]||[S[k]],x=h[Math.min(a,h.length-1)],y=S[k],df=y-x,good=low?df<=0:df>=0;return {k,l,u,d,x,y,df,good,low}});
  const gd=['enf','buy','isz','acik','borc','rez','des'].filter(k=>{const s=STATS.find(z=>z.k===k);return s&&s.st(S[k])==='good';}).length,g=gd>=6?'A':gd>=4?'B':gd>=3?'C':gd>=2?'D':'F';
  const nd=(S.nd||0)-(S.yrN||0),nk=(S.nk||0)-(S.yrK||0);return {y:dateLabel(S.month).split(' ')[1],g,r,nd,nk,imf:!!S.imfK,m:S.month};}
function yrScr(R){const w=R.r.filter(x=>x.good).sort((a,b)=>Math.abs(b.df/(b.x||1))-Math.abs(a.df/(a.x||1)))[0],b=R.r.filter(x=>!x.good).sort((a,b)=>Math.abs(b.df/(b.x||1))-Math.abs(a.df/(a.x||1)))[0];
  const row=x=>`<div class="lever"><span class="n">${x.l}</span><span class="h"><b style="color:${x.good?'#6fcf8a':'#e8826f'}">${x.df>=0?'▲':'▼'} ${nf(Math.abs(x.df),x.d)}${x.u==='%'?' puan':' '+x.u}</b> · ${nf(x.x,x.d)} → ${nf(x.y,x.d)} ${x.u}</span></div>`;
  return `<div class="wrap"><div class="end"><div class="muted" style="font-family:var(--mono);font-size:12px">Aralık özeti · ${R.y}</div><h1>${R.first?'İlk 3 ay notu':'Yıl notu'}: ${R.g}</h1><p>${R.first?'Oyunun ilk 3 ayında':'Bu yıl'} ${R.nd} karar verdin${R.nk?`, ${R.nk} krizi yönettin`:''}.${w?` En iyi gelişme: ${w.l}.`:''}${b?` En zayıf nokta: ${b.l}.`:''}</p><div class="panel">${R.r.map(row).join('')}</div>${R.imfNew?imfBlk():''}<button class="btn" data-scrx="1" style="width:100%;margin-top:10px">Devam</button></div></div>`;}
const imfBlk=()=>`<div class="panel"><b>IMF'ye gittin</b><div class="note">Rezervler tükenmek üzereyken IMF'den acil kredi alındı: rezerv +${S.imfA||15} mlr $, dış borç +${S.imfA||15} mlr $, halk desteği −3 puan, parti içi huzur −0,3. Bu can simidi yalnızca bir kez kullanılır; rezerv yeniden −5 mlr $ altına inerse Ekonomik Çöküş yaşanır. Swap, yabancı para kredi kısıtı ve döviz mevduatına ek vergi rezervi hemen güçlendirir.</div></div>`;
function imfScr(){return `<div class="wrap"><div class="end"><div class="muted" style="font-family:var(--mono);font-size:12px">Rezerv krizi · ${dateLabel(S.month)}</div><h1>IMF'ye Gittin</h1><p>Merkez Bankası rezervleri tükenmek üzereyken hükümet IMF'den acil kredi talep etti.</p>${imfBlk()}<button class="btn" data-scrx="1" style="width:100%;margin-top:10px">Devam</button></div></div>`;}
{const _e=endTurn;endTurn=function(){const i0=S.imfK,m0=S.month;_e();try{if(S.month===m0)return;const im=S.imfK&&!i0;
  if(dateLabel(S.month).startsWith('Aralık')){const R=yrRep();R.first=!(S.yrs&&S.yrs.length);R.imfNew=!!im;S.yrs=S.yrs||[];S.yrs.push(R);S.yrN=S.nd||0;S.yrK=S.nk||0;S.scr={k:'yr',R};}
  else if(im)S.scr={k:'imf'};save();}catch(e){}};}
{const _r=render;render=function(){_r();try{if(S.scr&&document.querySelector('main')){const a=document.getElementById('app');a.innerHTML=S.scr.k==='imf'?imfScr():yrScr(S.scr.R);window.scrollTo(0,0);}}catch(e){}};}
{const _c=arayuzClick;arayuzClick=function(t){if(t.dataset.scrx){S.scr=null;save();render();window.scrollTo(0,0);return true;}return _c(t);};}
/* Karne sekmesine geçmiş yıl raporları */
{const _d=V.donem;if(_d)V.donem=function(){let h=_d();const y=S.yrs||[];if(!y.length)return h;return h+`<div class="panel"><b>Yıl sonu raporları</b>${y.slice().reverse().map(R=>`<div class="lever"><span class="n">${R.y}${R.first?' · İlk 3 ay':''} · Not ${R.g}</span><span class="h">${R.nd} karar · ${R.r.filter(x=>x.good).length}/${R.r.length} gösterge iyileşti${R.imf?' · IMF kredisi kullanıldı':''}</span></div>`).join('')}</div>`;};}
/* ---------- Kararlar arası kısa notlar (etkiler fx ve ap tanımlarıyla doğrulandı) ---------- */
const XN={sw:'Rezervi anında artırır; bütçeye maliyeti yoktur.',dvt:'Rezervi artırır, kuru rahatlatır; tasarruf sahiplerinin tepkisiyle halk desteği düşer.',ha:'Borsayı ve yabancı girişini artırır; vergi geliri azalır.',vf:'Borsayı hemen yükseltir; bütçeye maliyeti vardır.',kkm:'Bütçeye nefes aldırır ama kur baskısını artırır.',rs:'Güveni ve yabancı girişini artırır; küçük bir bütçe maliyeti vardır.',as:'Borsayı yükseltir; Batı ilişkileri küçük ölçüde zarar görür.',bsk:'Güveni artırır ama kredi büyümesini ve büyümeyi düşürür; genel kredi hacmi artışıyla ters yönlüdür.',bkre:'Büyümeyi ve istihdamı artırır; enflasyon ve cari açık da artar, rezerv azalır.',kk:'Enflasyonu düşürür; büyüme ve halk desteği zarar görür.',kft:'Tavanı yükseltmek enflasyonu, büyümeyi ve halk desteğini düşürür; indirmek tersini yapar.',ltv:'Peşinatı artırmak enflasyonu düşürür; büyümeyi yavaşlatır, işsizliği artırır.',ys:'Kuru rahatlatır ve rezervi artırır; büyüme yavaşlar.',sy:'Bankaları sağlamlaştırır; büyümeyi yavaşlatır.',ek:'İhracatı 12 ay artırır; bütçe maliyeti vardır.',dmp:'İthalatı kısar ve yerli sanayiyi korur; enflasyon artar, Çin ilişkisi bozulur.',kot:'İthalatı sınırlar; halk desteği ve Batı ilişkileri zarar görür.',ara:'Enflasyonu düşürür; gümrük geliri azalır, bütçe açığı artar.',i1:'Enflasyonu hafif artırır, kredi talebini ve büyümeyi kısar.',i2:'Büyümeyi hafif kısar; enflasyon yükselirse faiz yükü de artar.',i4:'Rezervi artırır ve kuru rahatlatır; kur riski Hazine\'de kalır.',ksa:'İşsizliği azaltır; bütçe açığını artırır.',kdi:'Bütçe açığını azaltır; işsizlik artar, esnaf grubu tepki gösterir.',gnc:'İşsizliği azaltır, genç grubu memnun eder; bütçe açığı artar.',bpy:'Bütçe açığı artar; halk desteği ve huzur yükselir.',bbr:'Büyümeyi hafif artırır; borç da artar.',k4:'50 kişiden küçük listeler halk desteğini artırır; büyük listeler azaltır, 100\'ü aşınca Batı ilişkisi zarar görür.',k5:'Sübvansiyon enflasyonu düşürür ve desteği artırır, bütçeyi zorlar; zam tersini yapar.',k7:'Bütçe açığını azaltır; kamu çalışanı grubu tepki gösterir.',k12:'Hızlandırma büyümeyi artırır; bütçe açığı ve enflasyon da artar.',pk3:'Kuru rahatlatır ve rezervi artırır; küçük bir bütçe maliyeti vardır.',pk5:'Enflasyonu ve kuru rahatlatır; büyümeyi yavaşlatır.',pk7:'Büyümeyi artırır; bütçe maliyeti yüksektir.',kd1:'Hazırlık ve tecrübeyi artırır; bütçe maliyeti vardır, ordu memnuniyeti yükselir.',kd3:'Gençleştirme hazırlık ve tecrübeyi artırır, ordu memnuniyetini düşürür; kıdemi korumak tersini yapar.'};
for(const k in XN)if(typeof XD!=='undefined'&&XD[k]&&XD[k].d.indexOf('Not:')<0)XD[k].d+=' Not: '+XN[k];
/* ---------- Danışman ve haber akışı (Masa) ---------- */
function advP(){const it=[],ev=S.cur.events.filter(e=>e.ch===null).length,te=typeof toEl==='function'?toEl():99;
  if(ev)it.push([100,ev+' karar bekliyor','Karar vermeden ay bitmez.','karar']);
  if(S.rez<25)it.push([S.rez<8?96:S.rez<15?80:55,'Net rezerv '+nf(S.rez,0)+' mlr $',S.imfK?'IMF kredisi kullanıldı, −5 mlr $ altı çöküş getirir. Swap ve döviz araçlarına bak.':'0 altına inerse IMF acil kredisi devreye girer. Piyasa araçlarına bak.','piyasa']);
  if(S.enf>25)it.push([S.enf>45?90:S.enf>35?70:50,'Enflasyon %'+nf(S.enf,1),'Faiz, kredi ve politika kollarıyla fiyat baskısını azalt.','kurum']);
  if(S.acik>4.5)it.push([S.acik>8?85:S.acik>6?65:45,'Bütçe açığı %'+nf(S.acik,1),'Vergi ve harcama kalemlerini gözden geçir.','butce']);
  if(S.des<40)it.push([S.des<30?88:S.des<35?66:48,'Halk desteği %'+nf(S.des,0),'Hizmet, politika ve toplum gruplarına bak.','toplum']);
  if(S.isz>11)it.push([S.isz>15?72:52,'İşsizlik %'+nf(S.isz,1),'İşgücü düzenlemeleri ve sektör destekleri yardımcı olur.','nufus']);
  if(S.par<4.5)it.push([S.par<3?75:54,'Parti içi birlik '+nf(S.par,1)+'/10','Hizip araçlarıyla grupları dengele.','kabine']);
  if(S.ord<4.5)it.push([S.ord<3?74:53,'Ordu memnuniyeti '+nf(S.ord,1)+'/10','Komuta ve savunma kararlarına bak.','askeri']);
  if(S.kol<4.5)it.push([S.kol<3?73:51,'İttifak uyumu '+nf(S.kol,1)+'/10','Meclis ve ortaklarla ilişkiyi onar.','meclis']);
  if(te<=6)it.push([60,'Seçime '+te+' ay var','Destek ve karne durumuna bak.','donem']);
  it.sort((a,b)=>b[0]-a[0]);const top=it.slice(0,3);
  return `<div class="panel"><b>Danışman · bu ay öncelik</b>${top.length?top.map(x=>`<div class="lever"><span class="n">${x[1]}</span><span class="h">${x[2]}</span><div class="step"><button class="btn sm" data-go="${x[3]}">Git</button></div></div>`).join(''):'<div class="note">Acil bir sorun görünmüyor. Bu ay uzun vadeli yatırım ve reform için iyi bir fırsat.</div>'}</div>`;}
function newsP(){const L=(S.log||[]).slice(-8).reverse();if(!L.length)return '';return `<div class="panel"><b>Haber akışı</b>${L.map(x=>`<div class="lever"><span class="n">${dateLabel(x.m)} · ${x.t}</span><span class="h"><b>${x.c}</b>${x.msg?' — '+String(x.msg).slice(0,110)+(String(x.msg).length>110?'…':''):''}</span></div>`).join('')}</div>`;}
function cutPn(h,t){const i=h.indexOf('<b>'+t+'</b>');if(i<0)return h;const a=h.lastIndexOf('<div class="panel"',i);if(a<0)return h;let d=0,j=a;const re=/<div\b|<\/div>/g;re.lastIndex=a;let m;while((m=re.exec(h))){d+=m[0]==='</div>'?-1:1;if(d===0){j=re.lastIndex;break}}return h.slice(0,a)+h.slice(j);}
{const _m=V.masa;V.masa=function(){return advP()+cutPn(_m(),'Bu ay dikkat')+newsP();};}
render();
