/* ek9: IMF ekranı, yıl sonu raporu, kararlar arası kısa notlar */
/* ---------- Bilgi ekranları (S.scr) ---------- */
const YRS=[['enf','Enflasyon','%',1,1],['buy','Büyüme','%',1,0],['isz','İşsizlik','%',1,1],['acik','Bütçe açığı / GSYH','%',1,1],['borc','Dış borç / GSYH','%',1,1],['rez','Net rezerv','mlr $',0,0],['kur','Dolar / TL','₺',2,1],['des','Halk desteği','%',1,0]];
function yrRep(){const H=S.hist||{},n=(H.enf||[]).length,a=Math.max(0,n-13),r=YRS.map(([k,l,u,d,low])=>{const h=H[k]||[S[k]],x=h[Math.min(a,h.length-1)],y=S[k],df=y-x,good=low?df<=0:df>=0;return {k,l,u,d,x,y,df,good,low}});
  const gd=['enf','buy','isz','acik','borc','rez','des'].filter(k=>{const s=STATS.find(z=>z.k===k);return s&&s.st(S[k])==='good';}).length,g=gd>=6?'A':gd>=4?'B':gd>=3?'C':gd>=2?'D':'F';
  const nd=(S.nd||0)-(S.yrN||0),nk=(S.nk||0)-(S.yrK||0);return {y:dateLabel(S.month).split(' ')[1],g,r,nd,nk,imf:!!S.imfK,m:S.month};}
function yrScr(R){const w=R.r.filter(x=>x.good).sort((a,b)=>Math.abs(b.df/(b.x||1))-Math.abs(a.df/(a.x||1)))[0],b=R.r.filter(x=>!x.good).sort((a,b)=>Math.abs(b.df/(b.x||1))-Math.abs(a.df/(a.x||1)))[0];
  const row=x=>`<div class="lever"><span class="n">${x.l}</span><span class="h"><b style="color:${x.good?'#6fcf8a':'#e8826f'}">${x.df>=0?'▲':'▼'} ${nf(Math.abs(x.df),x.d)}${x.u==='%'?' puan':' '+x.u}</b> · ${nf(x.x,x.d)} → ${nf(x.y,x.d)} ${x.u}</span></div>`;
  return `<div class="wrap"><div class="end"><div class="muted" style="font-family:var(--mono);font-size:12px">Yıl sonu raporu · ${R.y}</div><h1>Yıl Notu: ${R.g}</h1><p>Bu yıl ${R.nd} karar verdin${R.nk?`, ${R.nk} krizi yönettin`:''}.${w?` En iyi gelişme: ${w.l}.`:''}${b?` En zayıf nokta: ${b.l}.`:''}${R.imf?' IMF acil kredisi kullanıldı; ikinci bir rezerv krizi çöküş getirir.':''}</p><div class="panel">${R.r.map(row).join('')}</div><button class="btn" data-scrx="1" style="width:100%;margin-top:10px">Devam</button></div></div>`;}
function imfScr(){return `<div class="wrap"><div class="end"><div class="muted" style="font-family:var(--mono);font-size:12px">Rezerv krizi · ${dateLabel(S.month)}</div><h1>IMF'ye Gittin</h1><p>Merkez Bankası rezervleri tükenmek üzereyken hükümet IMF'den acil kredi talep etti. 15 milyar $ kaynak hemen geldi, ama bunun bir bedeli oldu.</p><div class="panel"><div class="lever"><span class="n">Rezerv</span><span class="h">+15 mlr $ acil kredi</span></div><div class="lever"><span class="n">Dış borç</span><span class="h">+15 mlr $ ek borç</span></div><div class="lever"><span class="n">Halk desteği</span><span class="h">−3 puan: "IMF'ye teslim olundu" tepkisi</span></div><div class="lever"><span class="n">Parti içi huzur</span><span class="h">−0,3: muhalifler hükümeti sorumlu tutuyor</span></div></div><div class="note">Bu can simidi yalnızca bir kez kullanılır. Rezerv yeniden −5 mlr $ altına inerse Ekonomik Çöküş yaşanır: swap, döviz zorunlu karşılığı ve yabancı para kredi kısıtıyla rezervi hemen güçlendir.</div><button class="btn" data-scrx="1" style="width:100%;margin-top:10px">Devam</button></div></div>`;}
{const _e=endTurn;endTurn=function(){const i0=S.imfK,m0=S.month;_e();try{if(S.month===m0)return;S.scr=S.scr||null;if(S.imfK&&!i0)S.scr={k:'imf'};
  if(dateLabel(S.month).startsWith('Aralık')){const R=yrRep();S.yrs=S.yrs||[];S.yrs.push(R);S.yrN=S.nd||0;S.yrK=S.nk||0;if(!S.scr)S.scr={k:'yr',R};}save();}catch(e){}};}
{const _r=render;render=function(){_r();try{if(S.scr&&document.querySelector('main')){const a=document.getElementById('app');a.innerHTML=S.scr.k==='imf'?imfScr():yrScr(S.scr.R);window.scrollTo(0,0);}}catch(e){}};}
{const _c=arayuzClick;arayuzClick=function(t){if(t.dataset.scrx){const q=S.scr;S.scr=null;if(q&&q.k==='imf'&&S.yrs&&S.yrs.length&&S.yrs[S.yrs.length-1].m===S.month&&dateLabel(S.month).startsWith('Aralık'))S.scr={k:'yr',R:S.yrs[S.yrs.length-1]};save();render();window.scrollTo(0,0);return true;}return _c(t);};}
/* Karne sekmesine geçmiş yıl raporları */
{const _d=V.donem;if(_d)V.donem=function(){let h=_d();const y=S.yrs||[];if(!y.length)return h;return h+`<div class="panel"><b>Yıl sonu raporları</b>${y.slice().reverse().map(R=>`<div class="lever"><span class="n">${R.y} · Yıl notu ${R.g}</span><span class="h">${R.nd} karar · ${R.r.filter(x=>x.good).length}/${R.r.length} gösterge iyileşti${R.imf?' · IMF kredisi kullanıldı':''}</span></div>`).join('')}</div>`;};}
/* ---------- Kararlar arası kısa notlar ---------- */
const XN={sw:'Rezervi güçlendirir; swap kullandıkça dış bağımlılık artar.',dvt:'Dolarizasyonu yavaşlatır; TL mevduat teşviki (politika kolu) ile birlikte daha etkili olur.',vf:'Borsayı kısa vadede toparlar; tek başına kalıcı çözüm değildir, açığa satış yasağıyla birlikte kullanılabilir.',kkm:'Çıkış hızlanırsa kur oynar; önce rezervi ve faiz yönünü güçlendir.',as:'Kısa vadede rahatlatır, uzun vadede yabancı yatırımcı güvenini zayıflatır.',rs:'Yabancı tahvil istisnasıyla birlikte sermaye girişini artırır.',tst:'Roadshow ile aynı anda kullanılırsa girişler daha kalıcı olur.',bsk:'Kredi büyümesini yavaşlatır; büyümeyi isteyen genel kredi hacmi kararıyla çelişir.',bkre:'Büyümeyi artırır, enflasyon ve cari açığı da artırır; bankacılık sermaye artırımıyla dengelenir.',kk:'Limit sıkılaşınca enflasyon düşer ama tüketim ve halk desteği zarar görür.',kft:'Faiz tavanı destek kazandırır, ancak bankalar krediyi kısabilir.',ltv:'Peşinat artınca konut balonu soğur, inşaat sektörü yavaşlar.',ys:'Kuru rahatlatır ve rezervi korur; şirketlerin yatırımı yavaşlar.',sy:'Sağlamlaştırır ama kredi arzını daraltır; büyümeyi isteyen dönemde dikkat.',ek:'Büyümeyi destekler; bütçe maliyeti vardır, kur sigortası ile birlikte ihracatçıya iki yönlü destek verir.',hdg:'İhracat kredisi ile birlikte kullanılırsa ihracatçı kur riskinden korunur.',dmp:'Yerli sanayiyi korur, ama karşı ülke tepkisi ilişkileri bozabilir.',kot:'Cari açığı azaltır; ithalata bağımlı sanayide maliyet ve enflasyon artabilir.',ara:'Üretim maliyetini düşürür; gümrük geliri azalır.',fuar:'Etkisi yavaş gelir; diplomatik ilişkiler iyiyse daha verimli olur.',i1:'Faiz yükü gelecek aylara taşınır; enflasyon düşerken maliyeti de düşer.',i2:'Enflasyon yükselirse borç maliyeti de yükselir.',i4:'Kur yükselirse borç büyür; kur riskini sen taşırsın.',gb:'Faiz yükünü hafifletir ama o ay nakit çıkışı yaratır.',kapa:'Faiz yükünü azaltır; rezerv ve nakit gerektirir.',yap:'Kısa vadeli ödeme baskısını azaltır; toplam faiz maliyeti artar.',ksa:'İşsizliği tutar; bütçeye yük bindirir.',kdi:'Vergi gelirini artırır; kısa vadede işsizlik görünür hale gelir.',gnc:'Genç işsizliği azaltır; bütçe maliyeti vardır.',bpy:'Belediyeleri rahatlatır; bütçe açığını büyütür.',bbr:'Yerel yatırımı artırır; belediye borç riski büyür.',k4:'Destek kazandırabilir; hukuk ve kamu düzeni göstergelerine bedeli olabilir.',k7:'Bütçe açığını azaltır; kamu hizmetleri ve memur memnuniyeti zarar görebilir.',k5:'Enflasyonu kısa vadede baskılar; enerji bütçe maliyetini artırır.',k12:'Yatırım artarsa büyüme artar, açık da artar.',pk3:'Döviz zorunlu karşılığı ve faiz kararlarıyla birlikte düşünülmeli.',pk5:'Enflasyonu düşürür; büyümeyi yavaşlatır.',pk7:'Kredi arzını büyütür; bankacılık sermaye artırımıyla ters yönlüdür.',kd1:'Komuta kademesiyle ordu memnuniyeti arasında denge kur.',kd3:'Genç komutanlar yenilik getirir; kıdemliler memnuniyetsiz olabilir.'};
for(const k in XN)if(typeof XD!=='undefined'&&XD[k]&&XD[k].d.indexOf('Not:')<0)XD[k].d+=' Not: '+XN[k];
render();
