/* ---------- Ekonomi 2: ek politika kolları, piyasa araçları, özelleştirme, sektör programları, ticaret ve ihracat politikası, politika ve program kataloğu ---------- */
/* Ek para ve makroihtiyati kollar: [anahtar, ad, açıklama] ; aralık LVR'de */
const LEV2=[['zk','Zorunlu karşılık oranı','Bankaların Merkez Bankası\'nda tutması gereken mevduat payı. Yükseldikçe kredi daralır, enflasyon ve büyüme düşer, rezerv artar.'],['kb','Kredi büyüme sınırı (yıllık)','BDDK\'nın ticari ve bireysel kredilere koyduğu büyüme tavanı. Yüksek tavan büyümeyi ve ithalatı, düşük tavan dezenflasyonu destekler.'],['mud','Kur müdahalesi','Merkez Bankası\'nın döviz piyasasına müdahale yoğunluğu. Sıkı müdahale kuru sabitler ama rezervi eritir.'],['mk','Makroihtiyati sıkılık','Kredi kartı taksit, taşıt ve konut kredisi limitleri. Sıkılık tüketimi, enflasyonu ve cari açığı frenler.']];
LVR.zk=[0,30,1];LVR.kb=[5,80,5];LVR.mud=[0,3,1];LVR.mk=[0,3,1];
const LVD={zk:10,kb:30,mud:1,mk:1},MUD=['Serbest dalgalı','Ölçülü','Sıkı yönetilen','Sabite yakın'],MKS=['Gevşek','Normal','Sıkı','Çok sıkı'];
const LVF={zk:v=>'%'+nf(v,0),kb:v=>'%'+nf(v,0),mud:v=>MUD[v],mk:v=>MKS[v]};
function levFx(){const F={},L=S.lv||{},a=(k,v)=>{F[k]=(F[k]||0)+v;};if(L.zk===undefined)return F;
  const z=L.zk-10,kb=(L.kb-30)/10,m=L.mk-1,u=L.mud-1;
  a('enf',-.025*z+.05*kb-.06*m);a('buy',-.035*z+.22*kb-.2*m);a('rez',.02*z-.4*u+(u<0?.15:0));a('cari',.02*kb-.03*m);a('des',.015*kb-.03*m-(u<0?.05:0));a('isz',-.01*kb+.01*m);return F;}
const levD=()=>{const L=S.lv||{};return L.mud===undefined?0:-.45*(L.mud-1)+(S.rez<10&&L.mud>1?.6*(L.mud-1):0);};
/* Piyasa araçları: [ad, açıklama, anlık etki, {kn: not, fb: yabancı akımı mlr $/ay (söner), b: borsa %}] */
const PZO=[['Swap anlaşması (Körfez ve Çin)','Merkez bankalarıyla yerel para swapı: brüt rezerv ve güven artar.',{rez:1.5},{kn:.5}],['Kredi kuruluşlarına sunum','Hazine ekibi derecelendirme kuruluşlarına program anlatır.',{},{kn:1}],['Merkez Bankası bağımsızlığı taahhüdü','Faiz kararlarına müdahale etmeme sözü; parti içinde rahatsızlık.',{par:-.08},{kn:2,gv:6}],['Bankacılık stres testi ve sermaye artırımı','Bankalar sermaye tamponu artırır, kredi büyümesi yavaşlar.',{buy:-.03},{kn:1.5}],['Yabancıya tahvil vergi istisnası','DİBS faiz gelirinde stopaj kaldırılır; sıcak para girer.',{acik:.04},{fb:.8}],['Halka arz teşviki','Halka arzlarda vergi indirimi ve hızlı onay.',{acik:.02,buy:.02},{b:3}],['Temettü stopajını düşür','Hisse senedi getirisi artar.',{acik:.03},{b:4,fb:.4}],['Varlık Fonu ile borsaya destek','Kamu fonu hisse alır; piyasa yükselir, şeffaflık eleştirilir.',{acik:.06},{b:5,kn:-.3}],['Açığa satış yasağı','Çöküş anlarında spekülasyonu keser; yabancı yatırımcı temkinli.',{bat:-.03},{b:2,kn:-.5,fb:-.4}],['Kur korumalı mevduattan çıkış','KKM hesapları TL\'ye dönüştürülür; bütçe rahatlar, kur kısa süre oynar.',{acik:-.08,kur:1},{kn:1}],['Döviz mevduatına ek vergi','Liraizasyon için döviz hesaplarına vergi; tasarruf sahipleri tepkili.',{rez:.5,kur:-.8,des:-.05},{}],['Yatırım danışma konseyi','Uluslararası fon yöneticileriyle yıllık konsey.',{bat:.03},{kn:.5,fb:.5}]];
/* Özelleştirme: [anahtar, varlık, değer (mlr $), kamu çalışanı tepkisi, açıklama] ; yöntem: blok satış / halka arz / işletme hakkı devri */
const OZV=[['tt','Türk Telekom hazine payı',3,4,'Hazinenin %25 hissesi; telekom sendikaları tepkili.'],['thy','THY hissesi (Varlık Fonu)',2.5,3,'Ulusal havayolunda kamu payı azalır; milliyetçi tepki.'],['halk','Halkbank hissesi',2,4,'Kamu bankası; yaptırım davası nedeniyle değerlemesi düşük.'],['seker','Şeker fabrikaları',.8,6,'TÜRKŞEKER fabrikaları; pancar üreticisi ve işçiler tepkili.'],['eti','Eti Maden işletmeleri',3,5,'Bor rezervleri; stratejik varlık tartışması.'],['liman','İzmir ve Derince limanları',1.5,3,'TCDD limanları; ihracat lojistiği rahatlar.'],['euas','EÜAŞ termik santralleri',4,6,'Elektrik üretim santralleri; elektrik fiyatı riski.'],['oto','Otoyol ve köprü işletmesi',3,2,'Geçiş ücretleri artabilir.'],['arsa','Hazine arazileri ve kamu binaları',2,1,'Şehir içi kamu taşınmazları; kentsel rant tartışması.'],['ziraat','Ziraat Sigorta ve Emeklilik',1,2,'Kamu sigorta şirketi halka açılır.']];
const OZM=[['Blok satış','Tamamı tek alıcıya; en yüksek gelir, en sert tepki.',1,1,0],['Halka arz','Hisse borsada satılır; gelirin %70\'i, tepki yarıya iner, borsa canlanır.',.7,.5,3],['İşletme hakkı devri','25-49 yıllık kiralama; gelirin %45\'i, mülkiyet devlette kalır.',.45,.35,0]];
function ozAct(id,mo){const v=OZV.find(x=>x[0]===id),m=OZM[mo];S.oz2=S.oz2||{};if(!v||!m||S.oz2[id]!==undefined)return;S.oz2[id]=mo;const g=v[2]*m[2];
  applyFx({rez:g*.6,acik:-g/S.gdp*100*.8,des:-.2*m[3]-.05*v[3]*m[3]});S.acikP=(S.acikP||0)-g/S.gdp*100*.25;S.gr.kamu=clamp(S.gr.kamu-v[3]*m[3],5,95);if(S.pz)S.pz.b*=1+m[4]/100;if(S.lb)S.lb.sen.t=clamp(S.lb.sen.t-v[3]*m[3]*1.5,-100,100);
  logA('Özelleştirme',v[1],`${m[0]}: ${nf(g,1)} mlr $ gelir.`);hap(20,520);save();render();}
/* Sektör programları: [ad, açıklama, sektör endeksi artışı, anlık etki] */
const SCO={tur:[['Yurt dışı tanıtım kampanyası','Go Türkiye ve fuarlarla tanıtım.',3,{acik:.03,cari:-.03}],['Sağlık ve termal turizm teşviki','Hastane ve termal tesis yatırımlarına destek.',4,{acik:.05,cari:-.04}],['Kongre ve kruvaziyer limanları','Liman ve kongre merkezi yatırımı.',4,{acik:.08,buy:.02}],['Turizmde KDV indirimi','Konaklamada KDV düşer; fiyat rekabeti artar.',5,{acik:.1,cari:-.05}]],
 tar:[['Tarımsal sulama yatırımı','Damla sulama ve gölet projeleri.',4,{acik:.08,enf:-.03}],['Sözleşmeli üretim modeli','Sanayici ile çiftçi önceden fiyat sözleşmesi yapar.',3,{enf:-.02}],['Tarım sigortası (TARSİM) desteği','Prim desteği artar; kuraklık riski azalır.',3,{acik:.04}],['Hayvancılık ve yem desteği','Et ve süt üretimi artar.',4,{acik:.06,enf:-.03}]],
 san:[['Organize sanayi bölgesi','Yeni OSB ve altyapı.',4,{acik:.08,buy:.04,isz:-.03}],['Yeşil dönüşüm kredisi','AB karbon vergisine uyum için kredi.',3,{acik:.05,bat:.03}],['Yüksek teknoloji teşviki (HIT-30)','Çip, batarya ve elektrikli araç yatırımları.',5,{acik:.12,buy:.05,cari:-.05}],['Enerji maliyetine destek','Sanayi elektriğine indirim.',3,{acik:.08,enf:-.02}]],
 ene:[['YEKA yenilenebilir enerji ihalesi','Güneş ve rüzgâr kapasitesi artar.',4,{acik:.04,cari:-.05}],['Karadeniz gazı ikinci faz','Sakarya sahasında üretim artışı.',5,{acik:.08,cari:-.06}],['Nükleer santral programı','Akkuyu sonrası ikinci santral anlaşması.',5,{acik:.1,dog:.04}],['Elektrik iletim ve depolama','Şebeke ve batarya depolama yatırımı.',3,{acik:.06}]]};
function scAct(k,i){const x=SCO[k]&&SCO[k][i];if(!x)return;const m=su('sc'+k+i);suU('sc'+k+i);S.sec[k]=clamp(S.sec[k]+x[2]*m,0,100);applyFx(sfx2(x[3],m));logA('Sektör',x[0],'Endeks +'+nf(x[2]*m,1)+'.');hap(20,520);save();render();}
function sektor2(){S.oz2=S.oz2||{};const N={tur:'Turizm',tar:'Tarım',san:'Sanayi',ene:'Enerji'};
  return `<h2>Sektörler</h2><div class="panel">${Object.keys(N).map(k=>`<div class="lever"><span class="n">${N[k]} · ${nf(S.sec[k],0)}/100</span><span class="h">${{tur:'Turizm cari açığı azaltır.',tar:'Tarım gıda enflasyonunu düşürür.',san:'Sanayi büyüme ve ihracatı taşır.',ene:'Enerji dışa bağımlılığı ve cari açığı azaltır.'}[k]}</span><div class="step">${sbtn(`data-scs="${k}"`,S.scs===k?'Kapat':'Programlar')}</div>${gbar(S.sec[k],S.sec[k]>=55?'good':S.sec[k]>=40?'warn':'bad')}${S.scs===k?`<div style="grid-column:1/-1">${SCO[k].map((x,i)=>opRow(x[0],x[1]+' Endeks +'+x[2]+(fxText(x[3])?' · '+fxText(x[3]):'')+'.',sbtn(`data-sco="${k}:${i}"`,'Uygula'))).join('')}</div>`:''}</div>`).join('')}<div class="note">Sektör ortalaması 50'nin üstündeyse büyüme artar.</div></div>
  <h2>Özelleştirme</h2><div class="panel">${OZV.map(v=>{const d=S.oz2[v[0]];return `<div class="lever"><span class="n">${v[1]}</span><span class="h">${v[4]} Tahmini değer ${nf(v[2],1)} mlr $.${d!==undefined?' <b>'+OZM[d][0]+' ile özelleştirildi.</b>':''}</span><div class="step">${d!==undefined?'<span class="st good">Tamamlandı</span>':OZM.map((m,i)=>sbtn(`data-ozv="${v[0]}:${i}"`,m[0])).join('')}</div></div>`;}).join('')}<div class="note">${OZM.map(m=>m[0]+': '+m[1]).join(' ')} Gelir rezerve ve bütçeye gider; kamu çalışanları ve sendikalar tepki gösterir.</div></div>`;}
/* Ticaret ve ihracat politikası: [ad, açıklama, ihracat %, ithalat %, süre (ay), anlık etki] */
const TRO=[['Eximbank ihracat kredisi','Döviz kazandırana ucuz kredi.',6,0,12,{acik:.05}],['E-ihracat ve dijital pazar desteği','Pazaryeri ve kargo desteği.',3,0,18,{acik:.02}],['Ticaret müşavirliği ve fuar katılımı','Yeni pazarlarda fuar ve ticaret heyeti.',3,0,12,{acik:.02}],['Lojistik ve liman yatırımı','Liman, demiryolu ve Orta Koridor bağlantısı.',4,-1,24,{acik:.1,buy:.03}],['Serbest bölge ve dahilde işleme','Vergisiz ithal girdi ile ihracat.',5,1,24,{acik:.03}],['Turquality markalaşma desteği','Türk markalarına yurt dışı tanıtım ve mağaza desteği.',4,0,24,{acik:.04}],['Kur riskine karşı hedge desteği','İhracatçıya kur sigortası.',3,0,12,{acik:.04}],['Dampinge karşı vergi','Ucuz çelik ve tekstil ithalatına ek vergi.',0,-3,12,{enf:.05,rel:{chn:-4}}],['İthalat gözetimi ve ön izin','Tüketim malı ithalatına gözetim ve ön izin.',0,-4,12,{enf:.08,bat:-.05}],['Altın ithalatı kotası','Cari açığı büyüten altın ithalatına kota.',0,-5,12,{des:-.05}],['Lüks tüketim ithalatına ek vergi','Lüks araç, telefon ve kozmetik ithalatına vergi.',0,-2,12,{acik:-.03,des:-.03}],['Ara malı ithalatını kolaylaştır','Sanayi girdisinde gümrük indirimi.',2,3,12,{enf:-.03}]];
function trAct(i){const x=TRO[i];if(!x)return;const m=su('tro'+i);suU('tro'+i);S.txb=(S.txb||[]).concat([{x:x[2]*m/100,m:x[3]*m/100,left:x[4],n:x[0]}]);applyFx(sfx2(x[5],m));logA('Dış ticaret',x[0],x[4]+' ay sürecek.'+sat(m));hap(20,520);save();render();}
const trB=()=>(S.txb||[]).reduce((a,b)=>[a[0]+b.x,a[1]+b.m],[0,0]);
function exAct(i){S.exs=S.exs||{};const m=su('exs'+i);suU('exs'+i);S.exs[i]=clamp((S.exs[i]||0)+.08*m,0,.4);applyFx({acik:.04*m});logA('İhracat',EXG[i][0],'Sektör destek programı başlatıldı.');hap(20,520);save();render();}
const exB=()=>{const w=EXG.map(g=>g[1]),z=w.reduce((a,b)=>a+b,0);return EXG.reduce((a,g,i)=>a+((S.exs||{})[i]||0)*w[i]/z,0);};
function ticX(){const b=trB(),on=(S.txb||[]);return `<h2>Ticaret ve İhracat Politikası</h2><div class="panel"><div class="dl">Süren önlemler: ihracat ${b[0]>=0?'+':''}%${nf(b[0]*100,1)} · ithalat ${b[1]>=0?'+':''}%${nf(b[1]*100,1)} · sektör programları ihracata +%${nf(exB()*100,1)}</div>${on.length?on.map(o=>`<div class="dl muted">${o.n}: ${o.left} ay</div>`).join(''):''}
  ${TRO.map((x,i)=>opRow(x[0],`${x[1]} ${x[2]?'İhracat +%'+x[2]+' ':''}${x[3]?'İthalat '+(x[3]>0?'+':'−')+'%'+Math.abs(x[3])+' ':''}· ${x[4]} ay${fxText(x[5])?' · '+fxText(x[5]):''}.`,sbtn(`data-tro="${i}"`,'Uygula'))).join('')}</div>
  <div class="panel"><b>Sektörel ihracat programları</b>${EXG.map((g,i)=>opRow(g[0],`2025 ihracatı ${nf(g[1],1)} mlr $. Sektöre özel pazar, kredi ve tasarım desteği; destek düzeyi %${nf(((S.exs||{})[i]||0)*100,0)} (en fazla %40, yavaş söner).`,sbtn(`data-exs="${i}"`,'Destekle'))).join('')}</div>`;}
/* Politika kataloğuna ek politikalar */
PL.push(['kamuyat','Ekonomi','Kamu yatırım seferberliği','Yol, okul ve hastane yatırımlarına hız.',{buy:.15,acik:.25,enf:.04},{sanayi:3,ucret:2}],['yesil','Ekonomi','Yeşil dönüşüm fonu','Sanayide karbon azaltımı ve enerji verimliliği.',{buy:.05,acik:.1,bat:.03},{kentli:3,sanayi:1}],
 ['cocuk','Sosyal','Çocuk parası','Her çocuk için aylık ödeme.',{des:.08,acik:.15},{muhaf:4,ucret:2}],['engelli','Sosyal','Engelli ve bakım aylığı artışı','Engelli ve bakıma muhtaç aylıkları artar.',{des:.05,acik:.08,huz:.03},{muhaf:2,emekli:1}],['toki','Sosyal','Sosyal konut (TOKİ) seferberliği','Dar gelirliye uzun vadeli konut.',{huz:.05,des:.08,acik:.2,buy:.05},{ucret:4,genc:4}],
 ['toplumpol','Güvenlik','Toplum destekli polislik','Mahalle karakolları ve önleyici polislik.',{huz:.08,acik:.05},{kentli:2,dogu:1}],['siber','Güvenlik','Siber güvenlik merkezi','Kritik altyapı ve kamu ağlarına koruma.',{huz:.03,ord:.02,acik:.04},{}],
 ['okulonc','Eğitim','Zorunlu okul öncesi eğitim','5 yaş zorunlu, ücretsiz anaokulu.',{buy:.02,des:.04,acik:.08},{ucret:2,kentli:2}],['stem','Eğitim','Fen ve yazılım liseleri','Kodlama, robotik ve yapay zekâ okulları.',{buy:.03,acik:.05},{genc:3}],
 ['ailehek','Sağlık','Aile hekimliği güçlendirme','Hekim başına nüfus azalır, koruyucu sağlık.',{des:.05,acik:.08,huz:.02},{emekli:3}],['ilac','Sağlık','İlaç fiyat kuru güncellemesi','İlaç kuru artırılır; ilaç yokluğu biter, fiyat artar.',{enf:.03,des:.02,cari:.02},{emekli:-1}],
 ['koop','Tarım','Üretici kooperatifleri','Aracıyı azaltan kooperatif ağı.',{enf:-.03,acik:.06},{ciftci:5}],['tohum','Tarım','Yerli tohum programı','Yerli tohum ıslahı ve dağıtımı.',{enf:-.01,cari:-.02,acik:.03},{ciftci:3}],
 ['yeka','Enerji','Yenilenebilir enerji alım garantisi','Güneş ve rüzgâra uzun vadeli alım garantisi.',{cari:-.06,acik:.04,bat:.02},{kentli:2}],['nukleer','Enerji','Nükleer enerji programı','Sinop ve Trakya santralleri.',{cari:-.05,acik:.1,dog:.03},{kentli:-2,milli:2}],
 ['yunus','Kültür','Kültürel diplomasi (Yunus Emre, TRT World)','Türkçe, kültür merkezleri ve uluslararası yayın.',{bat:.03,bol:.03,acik:.03},{}],['uyum','Göç','Göçmen uyum programı','Dil, eğitim ve kayıtlı istihdam.',{huz:.04,bat:.03,acik:.05},{milli:-3,kentli:2}],['geri','Göç','Geri kabul ve sınır dışı merkezleri','Düzensiz göçmenler için geri gönderme merkezleri.',{huz:.03,bat:-.03,acik:.05},{milli:4,kentli:-2}]);
/* Ek programlar: [anahtar, ad, süre (ay), aylık etki] */
PG.push(['dep','Deprem dönüşüm seferberliği',12,{huz:.05,acik:.12,buy:.04}],['arge','Ar-Ge ve teknoloji hamlesi',10,{buy:.04,cari:-.05,acik:.08}],['tur','Turizm tanıtım kampanyası',6,{cari:-.08,acik:.04}],['sul','Tarımsal sulama programı',10,{enf:-.04,acik:.08}],['ver','Enerji verimliliği seferberliği',8,{cari:-.06,acik:.05}],['dij','Dijital dönüşüm programı',8,{buy:.03,acik:.05}],['kad','Kadın istihdamı programı',8,{isz:-.06,des:.05,acik:.05}],['sag','Sağlıkta bekleme süresi programı',6,{des:.08,acik:.08}],['pzr','Büyük ihracatçı pazar programı',8,{cari:-.1,acik:.05}]);
function e2Ensure(){if(!S.lv)return;for(const k in LVD){if(S.lv[k]===undefined)S.lv[k]=LVD[k];if(S.lv0[k]===undefined)S.lv0[k]=S.lv[k];}if(!S.oz2)S.oz2={};if(!S.txb)S.txb=[];if(!S.exs)S.exs={};}
function e2Up(){S.txb=(S.txb||[]).filter(o=>--o.left>0);for(const i in (S.exs||{}))S.exs[i]*=.97;if(S.pz){S.pz.fb=(S.pz.fb||0)*.7;}return [];}
function e2Click(t){const d=t.dataset;
  if(d.pzo!==undefined){const x=PZO[+d.pzo],p=S.pz;if(!x||!p)return true;const m=su('pzo'+d.pzo);suU('pzo'+d.pzo);applyFx(sfx2(x[2],m));const h=x[3];if(h.kn)p.kn=clamp(p.kn+h.kn*m,0,100);if(h.fb)p.fb=(p.fb||0)+h.fb*m;if(h.b)p.b*=1+h.b*m/100;if(h.gv)S.gv=clamp(S.gv+h.gv*m,0,100);logA('Piyasa',x[0],'Uygulandı.'+sat(m));hap(20,520);save();render();return true;}
  if(d.ozv){const p=d.ozv.split(':');ozAct(p[0],+p[1]);return true;}
  if(d.scs){S.scs=S.scs===d.scs?null:d.scs;render();return true;}
  if(d.sco){const p=d.sco.split(':');scAct(p[0],+p[1]);return true;}
  if(d.tro!==undefined){trAct(+d.tro);return true;}
  if(d.exs!==undefined){exAct(+d.exs);return true;}
  return false;}
let pzX=()=>`<div class="panel"><b>Piyasa araçları</b>${PZO.map((x,i)=>{const h=x[3],t=[h.kn?'not '+(h.kn>0?'+':'')+h.kn:'',h.fb?'yabancı girişi '+(h.fb>0?'+':'')+h.fb+' mlr $/ay':'',h.b?'borsa +%'+h.b:'',h.gv?'MB güvenilirliği +'+h.gv:'',fxText(x[2])].filter(Boolean).join(' · ');return opRow(x[0],x[1]+(t?' '+t+'.':''),sbtn(`data-pzo="${i}"`,'Uygula'));}).join('')}<div class="note">Aynı aracı tekrar kullanmak etkisini azaltır.${sat(1)}</div></div>`;
