/* ---------- Olay verisi ---------- */
const ch=(l,ss,d,fx,m,x)=>Object.assign({l,ss,d,fx:fx||{},m:m||''},x||{});
const EV=[
/* EKONOMİ */
{id:'e_rez',g:'eko',tag:'Ekonomi',t:'Rezervler Eriyor',x:()=>`Merkez Bankası'nın net rezervi ${nf(S.rez,1)} milyar dolara geriledi. ${M.maliye.name} acil toplantı istiyor: "Ya sıkılaşma ya dışarıdan finansman. Bekleyemeyiz."`,c:[ ch('Sıkılaşma paketi',3,'Vergi artışı ve harcama kesintisi. Enflasyon düşer, halk tepki gösterir.',{enf:-1.2,acik:-0.8,rez:2,des:-3,huz:-1,isz:0.4,par:-0.5,lv:{vergi:1}},'Paket Meclis\'ten geçti. Piyasalar olumlu karşıladı, sokaklar sessiz kalmadı.'), ch('Körfez ve Çin ile swap görüşmesi',2,'Rezerv rahatlar, dış politikada bağımlılık riski doğar.',{rez:9,kur:-2,borc:1.5,dog:1,bat:-0.5,bol:0.5},'Swap hatları açıldı ama şartlar henüz kamuoyuna anlatılmadı.',{later:[{m:2,id:'l_swap'}]}), ch('IMF ile temasa geç',4,'Piyasa güveni artar. Parti içi ve sokakta büyük tepki olur.',{rez:12,kur:-4,enf:-1,borc:2,bat:1.5,dog:-0.5,des:-4,par:-1,fG:-8,fR:5},'IMF heyeti Ankara\'da. Gelenekçi kanat "egemenlik" diyerek ayağa kalktı.',{later:[{m:3,id:'l_imf'}]}), ch('Faizi sabit tut, kuru kontrollü serbest bırak',1,'Riskli bir kumar. Kur ya oturur ya sıçrar.',{},'',{fn:()=>Math.random()<0.4?{fx:{kur:2,rez:1,des:0.5},msg:'Piyasa sakin karşıladı, kur kontrollü kaldı.'}:{fx:{kur:9,enf:2,rez:-3,des:-2,huz:-0.5},msg:'Kur sıçradı. Ertesi gün borsa sert düştü.',later:[{m:1,id:'l_kur'}]}}) ]},
{id:'e_enerji',g:'eko',tag:'Ekonomi · Enerji',t:'Enerji Fiyatları Fırladı',x:()=>`Petrol varil başına 104 dolara çıktı, doğalgaz spot fiyatları kış öncesi yükseliyor. BOTAŞ zarar yazıyor, ${M.maliye.name} "bu fatura bütçeye sığmaz" diyor.`,c:[ ch('Faturaları sübvanse et',2,'BOTAŞ\'a bütçeden kaynak aktarılır. Fatura sabit kalır.',{acik:0.6,enf:-0.4,des:1,huz:0.2},'Faturalar sabit kaldı. Bütçe açığı biraz büyüdü.'), ch('Zammı tüketiciye yansıt',1,'Bütçe rahatlar, hane bütçeleri sıkışır.',{enf:1.8,des:-2.5,huz:-0.5,acik:-0.2},'Elektrik ve doğalgaza zam geldi. Sosyal medyada tepki büyüdü.'), ch('Uzun vadeli doğalgaz anlaşması',3,'Azerbaycan, Rusya ve Katar arasında dengeli tedarik.',{cari:-1.5,dog:0.5,bat:-0.3,bol:0.3,acik:0.2},'On yıllık tedarik sözleşmeleri imzalandı. Enerji arzı güvenceye alındı.'), ch('Yenilenebilir ve nükleer teşvik paketi',3,'Uzun vadeli çözüm, kısa vadede maliyetli.',{acik:0.4,cari:-2,buy:0.2,des:0.5},'Teşvik paketi yatırımcı ilgisi çekti. Etkisi yıllar içinde görünecek.') ]},
{id:'e_banka',g:'eko',tag:'Ekonomi · Finans',t:'Orta Boy Banka Batıyor',x:()=>`Mevduatın yaklaşık %6\'sını tutan özel bir banka sermaye yetersizliği bildirdi. Mevduat sahipleri şubelere gidiyor. Merkez Bankası Başkanı ${M.mb.name} müdahale bekliyor.`,c:[ ch('TMSF\'ye devret, mevduatı garanti et',3,'Panik durur, maliyet devlete yazılır.',{acik:0.7,borc:0.8,des:1,rez:-1},'Mevduatlar garanti altına alındı. Kuyruklar dağıldı.'), ch('Kamu bankalarına devrettir',2,'Hızlı çözüm, kamu bilançosuna yük.',{acik:0.3,enf:0.3,bat:-0.3,par:0.3},'Banka kamu bankalarınca devralındı. Muhalefet "kayırma" dedi.'), ch('Batmasına izin ver',1,'Piyasa disiplini, ama yayılma riski.',{isz:0.6,des:-3,kur:5,rez:-2,bat:0.3},'Banka kapandı. Yayılma korkusuyla kur yükseldi.'), ch('Yabancı ortak bul',2,'Batılı bir fon sermaye koyar, yönetim payı ister.',{bat:0.8,dog:-0.2,rez:3,des:-0.5,fG:-3},'Yabancı ortak bulundu. Gelenekçiler "yabancıya satış" diye eleştirdi.') ]},
{id:'e_reyting',g:'eko',tag:'Ekonomi · Piyasa',t:'Kredi Derecelendirme Uyarısı',x:()=>`Büyük bir derecelendirme kuruluşu görünümü negatife çekmekle tehdit ediyor. Yabancı yatırımcının tahvil pozisyonları izleniyor.`,c:[ ch('Orta vadeli disiplin programı açıkla',2,'Bütçe hedeflerini kamuoyuyla paylaş.',{acik:-0.6,bat:0.8,des:-1,huz:-0.2},'Program duyuruldu. Kurum uyarısını erteledi.'), ch('Yatırımcı turu (roadshow)',1,'Bakanlar dünya finans merkezlerinde sunum yapar.',{bat:0.5,rez:2,kur:-1},'Turdan olumlu mesajlar geldi. Somut sonuç sınırlı.'), ch('Ulusal irade söylemine yaslan',0,'Kuruma sert yanıt ver, iç kamuoyunu toparla.',{des:1,bat:-1,rez:-3,kur:3},'Söylem sokakta karşılık buldu. Piyasa aynı şekilde tepki vermedi.') ]},
{id:'e_ihracat',g:'eko',tag:'Ekonomi · Sanayi',t:'İhracatçılar Sıkıştı',x:()=>`Reel değerlenen kur ve pahalı kredi yüzünden ihracat siparişleri düşüyor. Sanayi odaları acil paket istiyor, bazı organize sanayi bölgelerinde vardiyalar kısıldı.`,c:[ ch('Düşük faizli Eximbank kredisi',2,'İhracatçıya ucuz kaynak.',{buy:0.4,acik:0.3,isz:-0.3,des:1,enf:0.2},'Kredi paketi devreye girdi. Siparişler toparlanıyor.'), ch('Vergi indirimi',3,'Kurumlar vergisinde geçici indirim.',{acik:0.7,buy:0.3,des:1,par:0.3},'İndirim geçti. Sanayiciler memnun, Maliye endişeli.'), ch('Yeni pazarlar için ticaret heyetleri',2,'Afrika, Körfez, Orta Asya.',{cari:-2,dog:0.7,buy:0.2,bol:0.3},'Heyetler yola çıktı. İlk anlaşmalar aylar içinde gelecek.'), ch('Piyasaya bırak',0,'Müdahale etme.',{buy:-0.4,isz:0.4,des:-1.5},'Sanayi odaları hükümeti "ilgisizlikle" suçladı.') ]},
{id:'e_tarim',g:'eko',tag:'Ekonomi · Tarım',t:'Kuraklık Hasadı Vurdu',x:()=>`İç Anadolu'da rekolte %20 düştü. Buğday fiyatları yükseliyor, çiftçi kooperatifleri devlet desteği bekliyor.`,c:[ ch('Çiftçiye doğrudan destek',2,'Nakit yardım ve mazot desteği.',{acik:0.4,des:1.5,huz:0.3,enf:0.1},'Destek ödemeleri başladı. Kırsalda memnuniyet arttı.'), ch('Buğday ithalatı, gümrük indirimi',1,'Fiyat baskısını kırar, döviz harcatır.',{cari:1.2,enf:-0.6,des:-0.5},'İthalat gemileri limana yanaştı. Ekmek fiyatı sabit kaldı.'), ch('Uzun vadeli sulama yatırımı',3,'Kalıcı çözüm, kısa vadede maliyet.',{acik:0.3,buy:0.2,des:0.5,huz:0.3},'Sulama projeleri ihaleye çıktı.'), ch('Yardım kampanyası başlat',1,'Sivil toplumla birlikte gıda yardımı.',{des:0.5,huz:0.2},'Kampanya kısa vadede rahatlattı.') ]},
{id:'e_borsa',g:'eko',tag:'Ekonomi · Piyasa',t:'Piyasalarda Panik',cond:()=>S.kur>52||S.rez<15,x:()=>`Risk primi (CDS) sıçradı, yabancı çıkışı hızlandı. Kur ${nf(S.kur,2)}, rezerv ${nf(S.rez,1)} milyar dolar. Ekranlar kırmızı.`,c:[ ch('Sürpriz faiz artırımı',2,'Politika faizi 5 puan artar.',{rez:3,kur:-3,buy:-0.3,des:-1,lv:{faiz:5}},'Merkez Bankası sürpriz kararla faizi artırdı. Kur geriledi.'), ch('Sermaye kontrolleri',4,'Kur baskısı azalır, itibar zedelenir.',{kur:-5,rez:5,bat:-2,par:-0.5,des:-1},'Yeni düzenlemeler yürürlüğe girdi. Yabancı fonlar tepki gösterdi.'), ch('Rezervden döviz sat',1,'Kuru tutmaya çalış.',{rez:-6,kur:-4},'Bankalar dövizi satış ekranından çekti. Rezerv 6 milyar dolar eridi.'), ch('Sakinlik mesajı ver',1,'Sadece sözle güven vermeye çalış.',{},'',{fn:()=>Math.random()<0.4?{fx:{kur:-2},msg:'Mesaj işe yaradı. Kur bir miktar geriledi.'}:{fx:{kur:7,rez:-3,des:-2},msg:'Mesaj piyasada karşılık bulmadı. Kur sıçradı.'}}) ]},
{id:'e_turizm',g:'eko',tag:'Ekonomi · Turizm',t:'Rekor Turizm Sezonu Fırsatı',x:()=>`Yaz rezervasyonları rekor seviyede. Turizm sektörü ek destek ve kolaylık istiyor. Döviz girişi için önemli bir fırsat.`,c:[ ch('Tanıtım ve promosyon fonu',2,'Erken rezervasyon kampanyası.',{cari:-3,buy:0.3,isz:-0.3,acik:0.2},'Kampanya başladı. Rezervasyonlar arttı.'), ch('Vize kolaylığı',1,'Bazı ülkelere vizesiz giriş.',{cari:-2,bat:0.3,dog:0.5,huz:-0.2},'Vizeler kalktı. Turist sayısı yükselişte.'), ch('Kıyı yatırım teşvik affı',2,'İmar konusunda esneklik.',{cari:-2,des:-0.5,huz:-0.2,par:0.3},'İmar esnekliği yatırımcıyı sevindirdi, çevreciler eleştirdi.') ]},
{id:'e_kayitdisi',g:'eko',tag:'Ekonomi · Maliye',t:'Kayıt Dışı Ekonomi',x:()=>`Vergi gelirleri hedefin gerisinde. ${M.maliye.name} kayıt dışılıkla mücadele planı sunuyor.`,c:[ ch('Sert denetim kampanyası',3,'Ciddi kaynak yaratır, esnafı kızdırır.',{acik:-0.8,des:-1,huz:-0.3},'Denetimler başladı. Esnaf odaları itiraz etti.'), ch('Vergi barışı',1,'Geçmiş borçlara af, yeni kayıt karşılığı.',{acik:-0.3,rez:0,des:0.5,bat:-0.2},'Af çıktı. Bir miktar gelir toplandı.'), ch('Dijital takip sistemi',2,'Fatura ve POS entegrasyonu.',{acik:-0.5,buy:-0.1,des:-0.3},'Sistem devrede. Sonuçlar birkaç ay sonra görünür.') ]},
{id:'e_yatirim',g:'eko',tag:'Ekonomi · Yatırım',t:'Dev Fabrika Yatırım Teklifi',x:()=>`Uluslararası bir üretici, yarı iletken ve otomotiv fabrikası için ülkeye 6 milyar dolarlık yatırım teklif etti. Talepleri: arazi, teşvik, enerji garantisi.`,c:[ ch('Batılı üreticiyi seç',3,'Teknoloji transferi, Batı ile bağ güçlenir.',{bat:1,buy:0.3,rez:3,dog:-0.3},'Yatırım imzalandı. Bölgede on binlerce istihdam bekleniyor.'), ch('Doğulu üreticiyi seç',3,'Daha cömert teşvik, jeopolitik ağırlık.',{dog:1,buy:0.3,rez:3,bat:-0.5},'Yatırım imzalandı. Batı başkentleri temkinli yorum yaptı.'), ch('Yerli ortaklıkla koşullu kabul',2,'Yerli sanayiye pay şartı.',{buy:0.2,rez:1,par:0.3},'Yerli ortaklık şartı kabul edildi ama yatırım küçüldü.'), ch('Reddet',0,'Şartlar ağır.',{des:-0.5,isz:0.1},'Fabrika başka ülkeye gitti.') ]},
/* İÇ SİYASET / GÜVENLİK */
{id:'i_sendika',g:'ic',tag:'İç siyaset · Emek',t:'Sendikalar Ültimatom Verdi',x:()=>`Sendikalar asgari ücret için 15 günlük süre verdi. Aksi halde büyük yürüyüş ve iş bırakma. ${M.ic.name} "gerekirse yasaklarız" diyor.`,c:[ ch('Masaya otur, kısmi ara zam ver',2,'Bütçeye yük, huzur getirir.',{acik:0.5,enf:0.5,des:2,huz:1,par:0.3},'Ara zam kararlaştırıldı. Sendikalar eylemi erteledi.'), ch('Taviz verme, eylemleri sınırla',1,'Kısa vadede kontrol, uzun vadede öfke.',{huz:-1.5,des:-1.5,par:0.3},'Yürüyüşler kısıtlandı. Öfke birikiyor.',{later:[{m:2,id:'l_greve'}]}), ch('Doğrudan halka seslen',1,'Karizma testi. Başarı desteğe bağlı.',{},'',{fn:()=>Math.random()<0.3+S.des/100?{fx:{des:2.5,huz:0.5},msg:'Konuşma karşılık buldu. Sendikalar tonu düşürdü.'}:{fx:{des:-1,huz:-0.5},msg:'Konuşma soğuk karşılandı. "Fedakârlık" sözü tepki çekti.'}}) ]},
{id:'i_skandal',g:'ic',tag:'İç siyaset · Yolsuzluk',t:'Bakan Hakkında Yolsuzluk İddiası',x:()=>`Bir gazete, ${M.maliye.name}'in yakınlarının kamu ihalelerinden pay aldığını yazdı. Muhalefet meclis araştırması istiyor, koalisyon ortağı sessiz.`,c:[ ch('Bakanı savun',2,'Bakanın yanında dur. Kısa vadede birlik, uzun vadede risk.',{des:-2,par:0.3,huz:-0.3},'Bakan yerinde kaldı. İddialar sönmedi.',{later:[{m:3,id:'l_skandal'}]}), ch('İstifa ettir',1,'Hızlı sonuç, hizip içi hesaplaşma.',{des:0.5,par:-0.5,huz:0.3},'Bakan istifa etti. Muhalefet "geç kalındı" dedi.'), ch('Bağımsız soruşturma aç',3,'Şeffaflık, ama beklenmedik sonuç riski.',{des:1.5,par:-0.7,bat:0.5,huz:0.3},'Soruşturma başladı. Hükümet "hesap vermekten çekinmiyor" imajı verdi.'), ch('Medya ambargosu',2,'Haberi bastır.',{des:-1,bat:-0.8,huz:-0.3},'Ambargo geldi. Sosyal medyada konu daha da büyüdü.') ]},
{id:'i_koalisyon',g:'ic',tag:'İç siyaset · Koalisyon',t:'Ortağın Yeni Talepleri',cond:()=>S.coal.length>0,x:()=>`${(PART[S.coal[0]]||PART[best()]).n} lideri ${(PART[S.coal[0]]||PART[best()]).lead} iki bakanlık ve belediye kadrolarında pay istiyor. "Kabul edilmezse güvenoyunu yeniden düşünürüz" diyor.`,c:[ ch('Talepleri kabul et',2,'Koalisyon sağlam kalır, parti içinden tepki gelir.',{kol:2,par:-0.8,des:-0.5},'İki bakanlık el değiştirdi. Koalisyon rahatladı, parti içi hoşnutsuz.'), ch('Pazarlığa gir',1,'Kısmi taviz ver.',{},'',{fn:()=>Math.random()<0.55?{fx:{kol:1,par:-0.2},msg:'Orta yol bulundu. Ortak lider yumuşadı.'}:{fx:{kol:-0.5,des:-0.5},msg:'Pazarlık tıkandı. Ortak lider "sabrımız tükeniyor" dedi.'}}), ch('Reddet',1,'Otoriteni göster.',{kol:-2,par:0.5,des:0.5},'Ret yanıtı geldi. Ortak lider hükümete mesafe koydu.'), ch('Muhalefetle gizli temas',3,'Riskli yedek plan.',{kol:-1,par:-0.5},'',{fn:()=>Math.random()<0.5?{fx:{kol:-1,des:1,par:-0.3},msg:'Görüşmeler kapalı kapılar ardında ilerledi. Ortak lider bunu öğrendi ve öfkelendi.'}:{fx:{kol:-2,des:-2,par:-0.5},msg:'Görüşme basına sızdı. Skandal büyüdü.'}}) ]},
{id:'i_hizip',g:'ic',tag:'İç siyaset · Parti',t:'Parti İçi Hizip Krizi',cond:()=>S.par<7,x:()=>`Gelenekçiler kurultay tarihi istiyor, Reformcular kadro değişimi talep ediyor. Sadakatçiler ise "lidere dokunulmaz" diyor.`,c:[ ch('Kurultay tarihi ver',2,'Demokratik görünüm, risk.',{par:0.7,des:0.3,fG:3},'Kurultay tarihi açıklandı. Gelenekçiler sakinleşti.'), ch('Kadro değişimi yap',2,'Reformculara yer aç.',{par:0.3,fR:5,fG:-4,des:0.3},'Yeni isimler görev aldı. Gelenekçiler kırgın.'), ch('Disiplin soruşturması',1,'Sert mesaj ver.',{par:-0.5,fS:3,fR:-2,des:-0.3},'Disiplin süreçleri başladı. Parti kamuoyunda "bölünme" haberleri çıktı.'), ch('Görmezden gel',0,'Zamanın çözmesini bekle.',{par:-0.8},'Hizip mücadelesi gazetelere taşındı.') ]},
{id:'i_medya',g:'ic',tag:'İç siyaset · Basın',t:'Gazeteci Soruşturmaları',x:()=>`Haberleri hükümeti zor durumda bırakan üç gazeteci hakkında soruşturma açıldı. Uluslararası basın örgütleri ve AB temsilcileri tepki gösteriyor.`,c:[ ch('Soruşturmaları destekle',1,'Sert tutum.',{des:0.3,bat:-1.2,huz:-0.5,par:0.3},'Soruşturmalar sürüyor. Yurt dışı tepkiler artıyor.',{later:[{m:2,id:'l_ab_tepki'}]}), ch('Basın özgürlüğü paketi',3,'Uzlaşmacı jest.',{bat:1,des:0.5,par:-0.5,huz:0.3},'Paket duyuruldu. Gelenekçiler "zafiyet" dedi.'), ch('Yorum yapma',0,'Yargıya bırak.',{bat:-0.3,des:-0.3},'Konu bir süre daha gündemde kaldı.') ]},
{id:'i_belediye',g:'ic',tag:'İç siyaset · Yerel yönetim',t:'Muhalefet Belediyesine Soruşturma',x:()=>`Büyükşehir belediye başkanı hakkında ihale iddiaları var. Savcılık gözaltı istiyor, bazı isimler kayyum önerisinde bulunuyor.`,c:[ ch('Yargı süreci işlesin',1,'Doğrudan müdahale etme.',{des:-0.3,bat:0.3,huz:-0.3},'Süreç yargıda ilerliyor. Muhalefet "siyasi" dedi.'), ch('Kayyum atanmasını destekle',2,'Sert müdahale.',{des:-1.5,bat:-1,huz:-1,par:0.3},'Kayyum atandı. Şehirde protestolar başladı.'), ch('Uzlaşı arayışı',2,'Başkan ile görüşme.',{des:0.5,huz:0.5,par:-0.4,kol:-0.3},'Görüşme yapıldı. Muhalefet temkinli olumlu.') ]},
{id:'i_deprem',g:'ic',tag:'İç güvenlik · Afet',t:'Marmara\'da 6,4\'lük Deprem',x:()=>`Sabaha karşı Marmara\'da 6,4 büyüklüğünde deprem oldu. Yüzlerce bina hasarlı, ölü ve yaralılar var. Afet ekipleri sahada.`,c:[ ch('Tam kapasiteyle müdahale, bölgeye git',2,'Hızlı koordinasyon, kişisel liderlik.',{des:2,huz:0.5,acik:0.4,par:0.3},'Ekipler hızla bölgeye ulaştı. Liderlik imajı güçlendi.'), ch('Olağanüstü hal ilan et',2,'Merkezi kontrol.',{huz:0.3,des:0.5,bat:-0.3},'OHAL ilan edildi. Kurtarma çalışmaları merkezden yönetiliyor.'), ch('Uluslararası yardım çağrısı',1,'Batı ve Doğu\'dan yardım.',{bat:0.5,dog:0.5,bol:0.5,des:0.3},'Yardım uçakları geldi. İtibar arttı.'), ch('Yeniden imar affı',2,'Hızlı yeniden yapım.',{des:-1,huz:-0.3,acik:0.2},'İmar affı tartışması alevlendi.') ]},
{id:'i_teror',g:'ic',tag:'İç güvenlik',t:'İstanbul\'da Bombalı Saldırı',x:()=>`Kalabalık bir meydanda bombalı saldırı: 11 ölü, 40\'tan fazla yaralı. ${M.ic.name} sert önlemler istiyor, kamuoyu kararlılık bekliyor.`,c:[ ch('OHAL ve geniş operasyonlar',3,'Sert güvenlik yaklaşımı.',{huz:-0.5,des:1,bat:-1,par:0.3},'Operasyon dalgası başladı. Yüzlerce gözaltı yapıldı, eleştiriler geldi.'), ch('Hedefli istihbarat operasyonu',2,'Sınırlı ve kesin.',{huz:0.5,des:1,ord:0.3},'Sorumlular saatler içinde yakalandı. Kamuoyu memnun.'), ch('Sakin, hukuk çerçevesinde',1,'Soğukkanlı mesaj.',{huz:0.3,bat:0.5,des:-0.5},'Hükümet sakinlik çağrısı yaptı. Muhalefet "zayıflık" dedi.'), ch('Sınır ötesi karşılık',3,'Misilleme.',{ord:0.5,des:1.5,bol:-1,bat:-0.5,huz:0.2},'Havadan operasyon yapıldı. Bölgede gerginlik arttı.') ]},
{id:'i_anayasa',g:'ic',tag:'İç siyaset · Anayasa',t:'Anayasa Değişikliği Önerisi',x:()=>`Parti içinde, yönetim sistemini yeniden düzenleyen bir anayasa taslağı dolaşıyor. Koalisyon ortağı ve muhalefet farklı şeyler istiyor.`,c:[ ch('Masaya koy, Meclis\'e sun',4,'Büyük siyasi sermaye gerekir.',{des:-1,kol:-1,par:0.5,huz:-0.5},'Taslak Meclis\'e sunuldu. Tartışma alevlendi.'), ch('Ertele',0,'Şimdilik gündeme alma.',{par:-0.3,des:0.3},'Öneri sessizce rafa kalktı.'), ch('Muhalefetle uzlaşı komisyonu',2,'Çok partili çalışma.',{des:0.5,kol:-0.3,par:-0.3,bat:0.5},'Komisyon kuruldu. İlk toplantı olumlu geçti.') ]},
{id:'i_universite',g:'ic',tag:'İç siyaset · Gençlik',t:'Öğrenci Eylemleri',x:()=>`Barınma krizi ve kira artışları nedeniyle üniversitelerde eylemler başladı. Talep: yurt, burs ve kira sınırı.`,c:[ ch('Yurt ve burs paketi',2,'Bütçeye ek yük.',{acik:0.3,des:1,huz:0.6,par:0.2},'Yurt kapasitesi artırılıyor, burslar yükseltildi.'), ch('Polis müdahalesi',1,'Sert cevap.',{huz:-1,des:-1,bat:-0.4},'Müdahale sonrası eylemler büyüdü.'), ch('Öğrenci temsilcileriyle görüşme',1,'Diyalog.',{huz:0.4,des:0.3},'Görüşmeler başladı. Gerilim düştü.') ]},
{id:'i_yargi',g:'ic',tag:'İç siyaset · Yargı',t:'Yargı Reformu Paketi',x:()=>`AB ve iç kamuoyu yargı bağımsızlığı konusunda reform istiyor. Bakanlık taslağı hazırladı, parti içi görüşler farklı.`,c:[ ch('Kapsamlı reform',3,'Batı ile ilişkiler düzelir.',{bat:1.2,des:0.5,par:-0.7,huz:0.3},'Reform açıklandı. Avrupa\'dan olumlu ilk tepkiler geldi.'), ch('Sınırlı düzenleme',1,'Ufak adımlar.',{bat:0.3,par:-0.1},'Düzenleme geçti. Etki sınırlı.'), ch('Mevcut düzeni koru',0,'Değişiklik yok.',{bat:-0.3,par:0.2},'Reform gündemi rafa kalktı.') ]},
/* DIŞ İŞLERİ / ASKERİ */
{id:'d_multeci',g:'dis',tag:'Dış işleri · Göç',t:'Sınırda Yeni Mülteci Dalgası',x:()=>`Komşu ülkedeki iç savaş yüzünden sınıra yeni bir mülteci dalgası yaklaşıyor. Aynı bölgede silahlı grupların hareketliliği var. Genelkurmay ek birlik istiyor, ${M.dis.name} diplomasiyi öneriyor.`,c:[ ch('Ek birlik yığ, güvenli bölge seçeneği',2,'Askeri güç, uluslararası eleştiri.',{ord:0.5,bol:-0.5,bat:-0.5,huz:0.3,des:0.5},'Ek birlikler sınıra kaydırıldı. Güvenli bölge planı masada.'), ch('BM ve AB ile ortak yönetim',2,'Diplomatik kazanç, iç kamuoyu tepkisi.',{bat:1,bol:0.5,des:-1,huz:-0.3},'Finansman ve ortak yönetim müzakereleri açıldı.'), ch('Sınırı kapat, insani koridor bırak',1,'Hızlı çözüm, insan hakları eleştirisi.',{huz:0.3,bat:-1,bol:-0.5,des:0.3},'Sınır kapatıldı. Sınır kapılarında yığılma başladı.',{later:[{m:2,id:'l_sinir'}]}) ]},
{id:'d_nato',g:'dis',tag:'Dış işleri · İttifak',t:'NATO Harcama Baskısı',x:()=>`İttifak zirvesinde savunma harcamalarının GSYH\'nin %3,5\'ine çıkarılması talebi masada. Batılı başkentler net bir taahhüt bekliyor.`,c:[ ch('Kademeli artışı kabul et',3,'İttifaka güvence, bütçeye yük.',{bat:1.5,ord:0.5,acik:0.4,dog:-0.5,lv:{sav:0.5}},'Kademeli artış taahhüdü verildi. Müttefikler memnun.'), ch('Kısmi taahhüt ver',1,'Orta yol.',{bat:0.3},'Sınırlı bir taahhüt verildi.'), ch('Doğu ile ilişkileri öne çıkar',2,'Alternatif ittifak sinyali.',{dog:1,bat:-1.5,ord:-0.3},'Doğu başkentlerine yönelik açılım basında geniş yankı buldu.') ]},
{id:'d_ab',g:'dis',tag:'Dış işleri · Avrupa',t:'AB Gümrük Birliği Güncellemesi',x:()=>`Brüksel, gümrük birliğinin güncellenmesi için bazı siyasi şartlar öne sürüyor. Sanayiciler ve turizm sektörü olumlu, parti içinde ise itiraz var.`,c:[ ch('Şartları kabul et, müzakereyi ilerlet',3,'Ekonomik kazanç, iç siyasette maliyet.',{bat:1.5,buy:0.4,cari:-1.5,par:-0.7,des:-0.5},'Müzakere süreci hızlandı. Sanayi odaları memnun.'), ch('Şartları pazarlık konusu yap',2,'Tavizleri sınırla.',{bat:0.5,buy:0.2,par:-0.2},'Karşılıklı tavizlerle süreç canlı kaldı.'), ch('Müzakereyi dondur',0,'Alternatif pazarlar ara.',{bat:-1,dog:0.5,par:0.3,des:0.3},'Masadan kalkıldı. AB yorum yapmadı.') ]},
{id:'d_rusya',g:'dis',tag:'Dış işleri · Yaptırım',t:'İkincil Yaptırım Baskısı',x:()=>`Batılı başkentler, üçüncü ülkeler üzerinden yapılan ticareti hedef alan yaptırımlar hazırlıyor. Bazı bankalar ve şirketler risk altında.`,c:[ ch('Yaptırımlara uy',2,'Batı memnun, ticaret düşer.',{bat:1.2,dog:-1,cari:1,buy:-0.2},'Riskli işlemler durduruldu. Müttefikler olumlu yanıt verdi.'), ch('Dengeli tutum, resmi uyumsuzluk',2,'Sessiz esneklik.',{bat:-0.4,dog:0.4,cari:-1},'Resmi çizgi korunurken bazı ticaret sürdü.'), ch('Açıkça karşı çık',1,'Bağımsız dış politika vurgusu.',{dog:0.8,bat:-1.5,des:0.8,rez:-2,kur:2},'Yaptırımlara açık itiraz edildi. Piyasa tepki verdi.') ]},
{id:'d_deniz',g:'dis',tag:'Dış işleri · Deniz yetki alanı',t:'Doğu Akdeniz\'de Sondaj Gerilimi',x:()=>`Komşu bir ülke tartışmalı sularda arama izni verdi. Deniz Kuvvetleri alarmda, ${M.dis.name} "kriz büyümeden masaya oturalım" diyor.`,c:[ ch('Donanma eşliğinde sondaj gemisi',3,'Kararlılık gösterisi.',{ord:0.7,des:1.5,bat:-1.2,bol:-1,huz:-0.2},'Gemiler bölgeye yöneldi. Müttefikler "sükûnet" çağrısı yaptı.'), ch('Ortak enerji formülü ile diplomasi',2,'Uzlaşı arayışı.',{bol:1,bat:0.7,des:-0.5,ord:-0.3},'Görüşmeler başladı. Kamuoyunda "taviz" tartışması çıktı.'), ch('Uluslararası tahkim',2,'Hukuk yolu.',{bat:0.7,bol:0.4,des:-0.3},'Konu uluslararası mahkemeye taşındı.'), ch('Geri adım at',0,'Gerginliği düşür.',{ord:-0.7,des:-1.5,bol:0.5,par:-0.3},'Geri adım kamuoyunda zayıflık olarak yorumlandı.') ]},
{id:'d_arabulucu',g:'dis',tag:'Dış işleri · Diplomasi',t:'Arabuluculuk Fırsatı',x:()=>`İki komşu ülke arasında gerilim yükseliyor. Her iki taraf da ${M.dis.name} üzerinden gizli mesajlar gönderiyor. Bir zirve düzenleme fırsatı var.`,c:[ ch('Zirve ev sahipliği yap',3,'İtibar kazandırır, başarısızlık riski.',{},'',{fn:()=>Math.random()<0.55?{fx:{bol:1.5,bat:0.8,dog:0.8,des:1},msg:'Zirve ortak bildiriyle sonuçlandı. Diplomasi başarısı kutlandı.'}:{fx:{bol:-0.5,des:-1},msg:'Zirve sonuçsuz kaldı. Taraflar birbirini suçladı.'}}), ch('Perde arkası temas',1,'Gizli çaba.',{bol:0.5,des:0.2},'Temaslar başladı, sessizce ilerliyor.'), ch('Taraf tutma, uzak dur',0,'Kendi çıkarını koru.',{bol:-0.3},'Türkiye tarafsız kaldı.') ]},
{id:'d_abd',g:'dis',tag:'Dış işleri · Tedarik',t:'Savaş Uçağı Tedariki Engellendi',x:()=>`Müttefik bir ülkenin parlamentosu savaş uçağı satışını bloke etti. ${M.sav.name}: "Yerli üretimi hızlandırmamız şart."`,c:[ ch('Yerli savaş uçağı programına ek kaynak',3,'Uzun vadede bağımsızlık.',{ord:0.7,acik:0.4,buy:0.2,des:0.5},'Ek kaynak aktarıldı. Yerli program hızlanacak.'), ch('Avrupa/Asya alternatifi ara',2,'Geçici çözüm.',{ord:0.2,bat:-0.2,dog:0.3},'Alternatif tedarikçilerle görüşmeler başladı.'), ch('Müttefikle müzakere',2,'Taviz karşılığı serbest bırak.',{bat:0.5,ord:0.2,des:-0.5},'Müzakere sonucu bazı şartlarla sevkiyat izni çıktı.') ]},
{id:'d_cin',g:'dis',tag:'Dış işleri · Yatırım',t:'Çin\'den 18 Milyar Dolarlık Paket',x:()=>`Çin, altyapı ve enerji projeleri için 18 milyar dolarlık finansman önerdi. Şartlar ağır, borç tuzağı riski var.`,c:[ ch('Kabul et',3,'Hızlı finansman.',{rez:5,buy:0.5,borc:2,dog:1,bat:-1},'Anlaşma imzalandı. Batılı başkentler kaygı bildirdi.'), ch('Şartlı ve küçültülmüş paket',2,'Pazarlıkla daha güvenli.',{rez:2,buy:0.2,borc:0.7,dog:0.5},'Paket küçültülerek kabul edildi.'), ch('Reddet',0,'Kaynak başka yerden aranır.',{dog:-0.5,bat:0.3},'Teklif reddedildi.') ]},
/* ASKERİ */
{id:'a_ihale',g:'dis',tag:'Askeri · Savunma sanayii',t:'İHA ve Füze İhracat Sözleşmesi',x:()=>`Yerli savunma sanayii büyük bir ihracat anlaşması için hükümetten onay bekliyor. Alıcı ülke bölgede tartışmalı bir aktör.`,c:[ ch('Onayla',2,'Döviz gelir, itibar riski.',{cari:-2.5,ord:0.5,buy:0.2,bat:-0.7,bol:-0.3},'Sözleşme imzalandı. Savunma sanayii memnun.'), ch('Şartlı onay',2,'Kullanım denetimi ile.',{cari:-1.5,bat:-0.1,ord:0.3},'Şartlı onay çıktı. Alıcı ülke kabul etti.'), ch('Reddet',0,'Etik gerekçeler.',{bat:0.5,ord:-0.3,cari:0.3},'Sözleşme iptal edildi. Sanayi hayal kırıklığına uğradı.') ]},
{id:'a_operasyon',g:'dis',tag:'Askeri · Sınır güvenliği',t:'Sınır Ötesi Operasyon Talebi',x:()=>`Genelkurmay, sınır boyunca silahlı gruplara karşı sınır ötesi bir operasyon için onay istiyor. ${M.sav.name} destekliyor, ${M.dis.name} uyarıyor.`,c:[ ch('Tam ölçekli operasyon',4,'Güçlü mesaj, yüksek risk.',{ord:1,des:1.5,bat:-1.5,bol:-1.5,huz:-0.3,acik:0.3},'Operasyon başladı. Uluslararası eleştiriler yükseldi.'), ch('Sınırlı hava harekâtı',2,'Hedefli vuruş.',{ord:0.5,des:0.7,bat:-0.5,bol:-0.5},'Hava harekâtı sınırlı hedeflere yapıldı.'), ch('Diplomatik yol',1,'Temaslar sürsün.',{ord:-0.3,bol:0.3,bat:0.3},'Diplomatik kanallar denendi.'), ch('Ret',0,'Şimdilik gerek yok.',{ord:-0.7,des:-0.5},'Talep reddedildi. Genelkurmayda memnuniyetsizlik var.') ]},
{id:'a_siber',g:'dis',tag:'Askeri · İstihbarat',t:'Devlet Kurumlarına Siber Saldırı',x:()=>`Enerji, maliye ve sağlık sistemlerine yönelik koordineli bir siber saldırı yaşandı. Kaynağı belirsiz.`,c:[ ch('Siber savunma kurumu kur',3,'Kalıcı çözüm.',{ord:0.4,acik:0.2,huz:0.3,bat:0.3},'Yeni siber savunma kurumu kuruldu.'), ch('Saldırgana kamuoyu önünde ithamda bulun',2,'Diplomatik tepki riski.',{des:0.8,bat:-0.5,bol:-0.5},'Suçlama yapıldı. Karşı taraf reddetti.'), ch('Sessizce onar',1,'Kamuoyuna yansımasın.',{des:-0.5,huz:-0.2},'Sistemler onarıldı. Saldırı yine de basına sızdı.') ]},
{id:'a_yas',g:'dis',tag:'Askeri · Kadro',t:'YAŞ Terfi ve Emeklilik Kararları',x:()=>`Yüksek Askeri Şura toplanıyor. ${M.sav.name}, kendi adaylarını önceliklendirmek istiyor, bazı generaller endişeli.`,c:[ ch('Genelkurmay önerisine uy',1,'Kadro istikrarı.',{ord:0.7,par:-0.2},'Kararlar orduda memnuniyetle karşılandı.'), ch('Sivil iradenin önceliği',3,'Sivil kontrolü güçlendir.',{ord:-0.7,bat:0.5,des:0.3,par:0.2},'Bazı atamalar hükümetin tercihine göre yapıldı.'), ch('Orta yol',2,'İki tarafı uzlaştır.',{ord:0.2},'Uzlaşmayla karar alındı.') ]},
{id:'a_darbe',g:'dis',tag:'Askeri · Kriz',t:'Kışlada Huzursuzluk İddiaları',cond:()=>S.ord<5,x:()=>`Gizli bir kaynak, bazı subayların hükümetin politikalarından rahatsız olduğunu ve "çözüm arayışında" olduğunu ileriyor. Tehdit gerçek mi, söylenti mi belirsiz.`,c:[ ch('Ordu ile açık görüşme',2,'Sorunları duy.',{ord:1.5,par:-0.3,des:-0.3},'Görüşmeler yapıldı. Gerginlik düştü.'), ch('Şüphelileri emekli et',3,'Sert temizlik.',{ord:-1,huz:-0.5,des:0.3,bat:-0.3},'Bir grup subay emekli edildi. Ordu içinde ürperti var.'), ch('Savunma harcamalarını artır',3,'Moral ve maaş.',{ord:1.2,acik:0.4,lv:{sav:0.25}},'Maaş ve donanım artışı açıklandı. Ordu memnun.'), ch('Aldırma',0,'Söylenti.',{ord:-0.5,huz:-0.5},'Söylentiler sürdü.') ]},
/* GECİKMELİ ETKİLER */
{id:'l_greve',g:'later',tag:'Sonuç · Emek',t:'Genel Grev Başladı',x:()=>`İki ay önce verdiğin sert karar karşılığını buldu. Sendikalar birlik olup genel greve gitti. Limanlar, fabrikalar ve belediyeler durdu.`,c:[ ch('Zorunlu tahkim ve yasak',2,'Sert cevap.',{huz:-1,des:-1,par:0.3,buy:-0.3},'Grev yasaklandı. Sokakta gerilim yüksek.'), ch('Müzakere, ara zam',2,'Taviz ver.',{acik:0.6,huz:1.5,des:1,enf:0.3},'Grev sona erdi. Sendikalar kazanım elde etti.'), ch('Arabulucu ata',1,'Tarafsız üçüncü isim.',{huz:0.5,des:0.3},'Arabulucu görüşmelere başladı.') ]},
{id:'l_kur',g:'later',tag:'Sonuç · Ekonomi',t:'Kur Şoku Yayılıyor',x:()=>`Dolar\'ın sıçraması fiyatlara yansıyor. Şirketler döviz borcunu ödemekte zorlanıyor.`,c:[ ch('Acil faiz artırımı',2,'7,5 puan.',{kur:-4,rez:3,buy:-0.4,des:-1,lv:{faiz:7.5}},'Faiz sert artırıldı. Kur bir miktar toparlandı.'), ch('Rezervden döviz sat',1,'Kuru tut.',{kur:-3,rez:-5},'Rezervden döviz satıldı.'), ch('Sadece söylem',0,'Bekle.',{kur:3,des:-1.5,enf:1},'Beklenen düzelme gelmedi. Fiyat artışları hızlandı.') ]},
{id:'l_swap',g:'later',tag:'Sonuç · Finansman',t:'Körfez Finansmanının Şartları',x:()=>`Swap anlaşmasının ayrıntıları sızdı. Yatırım ve altyapı projelerinde imtiyazlar isteniyor. Muhalefet "ülkeyi satıyorsunuz" diyor.`,c:[ ch('Şartları kabul et',2,'Finansmanı koru.',{rez:3,dog:0.5,des:-1.5,par:-0.5},'Şartlar kabul edildi. Kamuoyunda tartışma çıktı.'), ch('Yeniden pazarlık',2,'Daha ılımlı şartlar.',{rez:1,des:-0.3,dog:0.2},'Pazarlık yapıldı. Şartlar yumuşadı.'), ch('Şeffaf açıklama yap',1,'Tüm ayrıntıları paylaş.',{des:0.5,par:-0.2},'Ayrıntılar açıklandı. Tartışma yatıştı.') ]},
{id:'l_imf',g:'later',tag:'Sonuç · IMF',t:'IMF İlk Gözden Geçirme',x:()=>`IMF ekibi ilk değerlendirme için geldi. Harcama kesintisi ve bazı kamu ihaleleri için şeffaflık şartları getirdi.`,c:[ ch('Şartları kabul et',2,'Güven ve kaynak.',{acik:-0.8,rez:3,bat:0.5,des:-1.5,huz:-0.4},'Şartlar kabul edildi. Kaynak dilimi serbest bırakıldı.'), ch('Pazarlıkla esnet',3,'Bazı şartları yumuşat.',{acik:-0.3,rez:1.5,des:-0.5},'Bazı şartlar esnetildi.'), ch('Programdan çekil',4,'Egemenlik söylemi.',{rez:-5,kur:6,des:1,par:0.5,bat:-1.5},'Programdan çekilme kararı verildi. Piyasalar sert tepki verdi.') ]},
{id:'l_skandal',g:'later',tag:'Sonuç · Yolsuzluk',t:'Skandal Yeniden Gündemde',x:()=>`Savunduğun bakanla ilgili yeni belgeler ortaya çıktı. Koalisyon ortağı ve parti içi sesler yükseliyor.`,c:[ ch('İstifa ettir',1,'Bu sefer geç kalma.',{des:-0.5,par:-0.5},'Bakan istifa etti. Geç kalındığı yorumları yapıldı.'), ch('Savunmaya devam et',2,'Direnişi sürdür.',{des:-2,kol:-1,par:-0.7},'Savunma sürüyor. Koalisyon ortağı öfkeli.') ]},
{id:'l_ab_tepki',g:'later',tag:'Sonuç · Avrupa',t:'AB Parlamentosu Kararı',x:()=>`Avrupa Parlamentosu, basın özgürlüğü konusunda sert bir karar tasarısı hazırladı. Gümrük birliği ve fon konularında baskı artabilir.`,c:[ ch('Sert yanıt ver',1,'Egemenlik vurgusu.',{bat:-1,des:0.8,par:0.3},'Sert bir yanıt verildi. Avrupa ile ilişkiler soğudu.'), ch('Diyalog kanalı aç',2,'Yumuşat.',{bat:0.7,des:-0.3},'Diyalog kanalı açıldı.'), ch('Yok say',0,'Yorum yapma.',{bat:-0.4},'Karar geldi ve gitti.') ]},
{id:'l_sinir',g:'later',tag:'Sonuç · Sınır',t:'Kapıda İnsani Kriz',x:()=>`Kapatılan sınır kapılarında binlerce kişi bekliyor. Uluslararası kuruluşlar acil insani yardım çağrısı yaptı.`,c:[ ch('Sınırlı koridor aç',2,'Baskıyı azalt.',{bol:0.5,bat:0.5,huz:-0.3,des:-0.5},'Sınırlı bir geçiş açıldı.'), ch('Sınırda kamp kur',2,'Yardımı sınırın öbür yanında ver.',{bat:0.3,acik:0.3,huz:0.2},'Kamp kuruldu. Yardım kuruluşlarıyla ortak çalışıldı.'), ch('Kapıyı kapalı tut',0,'Sert tutum.',{bat:-1,bol:-0.7,des:0.3},'Sınır kapalı kaldı. Uluslararası eleştiri arttı.') ]}
,
/* --- YENİ: EKONOMİ --- */
{id:'e_faizbaski',g:'eko',tag:'Ekonomi · Para politikası',t:'Faiz İndirimi Baskısı',x:()=>`Sanayi lobisi ve parti içinden bir grup "faizler indirilsin, üretim durdu" diyor. ${M.mb.name} enflasyon düşmeden indirimin kur şoku yaratacağı görüşünde.`,c:[ ch(`Faizi 5 puan indir`,3,`Krediler ucuzlar, büyüme canlanır. Kur ve enflasyon riski artar.`,{buy:0.5,des:1,kur:4,enf:1,rez:-2,lv:{faiz:-5}},`Faiz indirildi. Krediler ucuzladı, dolar yukarı yürüdü.`), ch(`Merkez Bankası'na dokunma`,1,`Bağımsızlığı koru.`,{bat:0.4,par:-0.3,des:-0.5},`Karar değişmedi. Sanayiciler hayal kırıklığını dile getirdi.`), ch(`Kademeli indirim takvimi`,2,`Piyasaya sinyal ver.`,{buy:0.2,kur:1,par:0.2,lv:{faiz:-2.5}},`Takvim açıklandı. Piyasa temkinli.`) ]},
{id:'e_konut',g:'eko',tag:'Ekonomi · Konut',t:'Kira ve Konut Fiyatı Patlaması',x:()=>`Büyükşehirlerde kiralar bir yılda ikiye katlandı. Gençler ve dar gelirliler tepkili, müteahhitler ise sınırlama istemiyor.`,c:[ ch(`Kira artışına tavan koy`,2,`Kiracı rahatlar, yatırımcı tepki gösterir.`,{des:1.5,huz:0.5,buy:-0.2,enf:-0.3},`Tavan yasası çıktı. Ev sahipleri dava yoluna gitti.`), ch(`Sosyal konut seferberliği`,3,`Uzun vadeli çözüm, bütçe yükü.`,{acik:0.5,des:1,isz:-0.3,buy:0.3},`Yüz binlerce konut için ihale açıldı.`), ch(`Piyasaya bırak`,0,`Müdahale etme.`,{des:-1.5,huz:-0.5},`Kiralar yükselmeye devam etti.`) ]},
{id:'e_megaproje',g:'eko',tag:'Ekonomi · Altyapı',t:'Mega Proje İhalesi',x:()=>`Bir köprü ve otoyol projesi için dev bir ihale hazır. Getiri-geçiş garantisi döviz cinsinden veriliyor, bütçe uzmanları uyarıyor.`,c:[ ch(`Garantili ihale ver`,2,`İstihdam ve prestij, gelecek yıllara borç.`,{buy:0.4,isz:-0.3,borc:1.5,des:0.5,cari:1},`İhale sonuçlandı. Açılış törenlerinin tarihi bile belli.`), ch(`Garanti olmadan yeniden tasarla`,2,`Yatırımcı çekilir mi, bilinmez.`,{buy:0.1,acik:-0.2,par:-0.2},`Proje küçüldü ama borç yükü de azaldı.`), ch(`Projeyi iptal et`,1,`Bütçeyi koru.`,{buy:-0.2,des:-1,par:0.2},`Proje iptal edildi. Yerel yönetimler öfkeli.`) ]},
{id:'e_emekli',g:'eko',tag:'Ekonomi · Sosyal',t:'Emekli Maaşı Zammı',x:()=>`Emekliler enflasyona ezildi. Dernekler Ankara'da yürüyüş hazırlığında. ${M.maliye.name} tam telafiyi bütçeye sığdıramıyor.`,c:[ ch(`Tam telafi zammı`,3,`Büyük memnuniyet, büyük maliyet.`,{acik:0.9,enf:0.6,des:2.5,huz:0.6},`Zam yapıldı. Emekliler sevindi, Maliye kaygılı.`), ch(`Kısmi zam ve bayram ikramiyesi`,2,`Orta yol.`,{acik:0.4,des:1,huz:0.3},`Kısmi zam açıklandı.`), ch(`Zam yapma`,0,`Bütçeyi koru.`,{des:-2,huz:-0.7,acik:-0.2},`Emekliler sokağa çıktı.`) ]},
{id:'e_gida',g:'eko',tag:'Ekonomi · Gıda',t:'Market Fiyatları ve Stokçuluk',x:()=>`Bazı zincir marketlerin fiyat artışlarını sürdürmek için stok tuttuğu söyleniyor. Halk öfkeli, ticaret odaları "serbest piyasa" diyor.`,c:[ ch(`Sert fiyat denetimi ve cezalar`,2,`Kısa vadede etki, arz sıkıntısı riski.`,{enf:-0.5,des:1,buy:-0.1},`Denetimler yapıldı. Bazı raflar boşaldı.`), ch(`Kamu marketlerini yaygınlaştır`,3,`Devlet piyasaya girer.`,{acik:0.4,enf:-0.4,des:1,huz:0.3},`Kamu marketleri açıldı. Kuyruklar oluştu.`), ch(`Gönüllü fiyat anlaşması`,1,`Zincirlerle uzlaşı.`,{},``,{fn:()=>Math.random()<0.5?{fx:{enf:-0.3,des:0.5},msg:`Anlaşma imzalandı. Fiyatlar bir süre sabit kaldı.`}:{fx:{des:-0.5},msg:`Zincirler sözünü tutmadı.`}}) ]},
{id:'e_altin',g:'eko',tag:'Ekonomi · Tasarruf',t:'Yastık Altı Altın Sorunu',x:()=>`Vatandaşın evde tuttuğu altın ve dövizin ekonomiye kazandırılması gerekiyor. Yeni bir dönüşüm planı masada.`,c:[ ch(`Altın mevduat teşviki`,2,`Faiz avantajı ile bankaya çek.`,{rez:3,acik:0.2,des:0.3},`Kampanya başladı. Bankalara altın akışı görüldü.`), ch(`Vergi barışı ile beyan`,2,`Kaynağı sorulmadan beyan.`,{rez:4,bat:-0.3,des:-0.5,par:0.2},`Beyan penceresi açıldı.`), ch(`Hiçbir şey yapma`,0,`Kendi haline bırak.`,{},`Konu gündemden düştü.`) ]},
{id:'e_kredikarti',g:'eko',tag:'Ekonomi · Hane halkı',t:'Kredi Kartı Borç Bombası',x:()=>`Hanelerin kart borçları rekor. Bankalar temerrüt bekliyor, tüketici dernekleri yapılandırma istiyor.`,c:[ ch(`Yapılandırma ve faiz tavanı`,2,`Halk rahatlar, bankalar sıkışır.`,{des:1.5,huz:0.4,acik:0.2,bat:-0.2},`Yapılandırma geçti. Bankalar itiraz etti.`), ch(`Kredi kartı limitlerini sıkılaştır`,1,`Riski azalt.`,{enf:-0.2,des:-0.7,buy:-0.2},`Limitler düştü. Tüketim yavaşladı.`), ch(`Piyasa çözer`,0,`Müdahale etme.`,{des:-1,isz:0.2},`Temerrütler arttı.`) ]},
{id:'e_ozel',g:'eko',tag:'Ekonomi · Kamu varlıkları',t:'Kamu Varlıklarının Satışı',x:()=>`Hazine, limanlar ve enerji şirketlerinin hisselerinin satışıyla bütçe açığını kapatmayı öneriyor. Sendikalar ve Gelenekçiler karşı.`,c:[ ch(`Büyük satış planı`,3,`Hızlı kaynak, siyasi bedel.`,{acik:-0.9,rez:4,des:-1.5,par:-0.8,fG:-4,bat:0.5},`Satış ihaleye çıktı. Muhalefet "vatan satılıyor" dedi.`), ch(`Halka arz ile sınırlı satış`,2,`Vatandaşa pay.`,{acik:-0.4,rez:1.5,des:0.3},`Halka arz ilgi gördü.`), ch(`Satma`,0,`Stratejik varlıkları koru.`,{par:0.3,acik:0.2},`Satış gündemden kalktı.`) ]},
{id:'e_maden',g:'eko',tag:'Ekonomi · Çevre',t:'Maden ve Enerji Yatırımı',x:()=>`Ege'de büyük bir altın madeni yatırımı ihracat gelirini artıracak. Köylüler ve çevre örgütleri zeytinlikler için karşı çıkıyor.`,c:[ ch(`Ruhsatı ver`,2,`Döviz ve istihdam getirir.`,{cari:-2,buy:0.3,huz:-0.6,des:-0.5,bat:-0.3},`Ruhsat verildi. Eylemler başladı.`), ch(`Sıkı çevre şartlarıyla izin`,2,`Orta yol.`,{cari:-1,buy:0.1,huz:-0.2},`Şartlı izin çıktı.`), ch(`Reddet`,0,`Doğayı koru.`,{des:0.5,huz:0.4,cari:0.3},`Ruhsat reddedildi. Şirket uluslararası tahkime gitti.`) ]},
{id:'e_girisim',g:'eko',tag:'Ekonomi · Teknoloji',t:'Yazılım ve Girişimci Teşviği',x:()=>`Genç girişimciler vergi ve düzenleme baskısından bunalıyor, yetenekli mühendisler yurt dışına gidiyor.`,c:[ ch(`Teknokent vergi bağışıklığı`,3,`Yetenek kaçışını yavaşlatır.`,{cari:-1.5,buy:0.4,isz:-0.2,acik:0.3,bat:0.3},`Teşvik yasası çıktı. Yabancı fonlar ilgi gösterdi.`), ch(`Risk sermayesi fonu kur`,2,`Devlet fonu.`,{buy:0.3,acik:0.2,des:0.3},`Fon kuruldu. İlk yatırımlar duyuruldu.`), ch(`Sadece söz ver`,0,`Program açıkla.`,{des:0.2},`Söz verildi, somut adım yok.`) ]},
{id:'e_calisma',g:'eko',tag:'Ekonomi · İşgücü',t:'Göçmen Çalışma İzni',x:()=>`Milyonlarca mülteci kayıt dışı çalışıyor. Sanayiciler yasal izin istiyor, kamuoyunda ise "işimizi alıyorlar" tepkisi var.`,c:[ ch(`Kısıtlı çalışma izni`,2,`Vergi ve sigorta gelir getirir.`,{acik:-0.4,buy:0.2,des:-1,huz:-0.3,bat:0.4},`İzin sistemi devreye girdi. Sokakta itirazlar arttı.`), ch(`Sıkı denetim ve sınırlama`,2,`Kayıt dışını azalt.`,{des:0.5,buy:-0.2,bat:-0.4},`Denetimler sıkılaştı. Bazı fabrikalar işçi bulamadı.`), ch(`Dokunma`,0,`Mevcut düzen.`,{},`Durum aynı kaldı.`) ]},
{id:'e_elektrik',g:'eko',tag:'Ekonomi · Enerji',t:'Elektrik Kesintileri',x:()=>`Sıcak hava dalgası tüketimi rekora çıkardı. Şebeke yetersiz, sanayi bölgelerinde planlı kesintiler başladı.`,c:[ ch(`Sanayiye öncelik ver`,1,`Üretim sürer, evler karanlık kalır.`,{buy:0.1,des:-1.5,huz:-0.5},`Konutlarda kesintiler sürdü.`), ch(`Evlere öncelik ver`,1,`Halk rahat, sanayi zarar eder.`,{buy:-0.4,isz:0.2,des:0.5},`Fabrikalar vardiya azalttı.`), ch(`Acil ithalat ve santral devreye alma`,3,`Pahalı ama etkili.`,{cari:1.2,acik:0.3,des:0.8,huz:0.3},`Kesintiler sona erdi. Fatura bütçeye yazıldı.`) ]},
{id:'e_bogaz',g:'eko',tag:'Ekonomi · Lojistik',t:'Boğazlarda Gemi Trafiği Krizi',x:()=>`Karadeniz'deki gerginlik yüzünden Boğazlardan geçen gemi sayısı arttı. Sigorta primleri ve geçiş ücretleri tartışılıyor.`,c:[ ch(`Ek geçiş ücreti ve düzenleme`,2,`Gelir artar, sürtüşme çıkar.`,{cari:-1,acik:-0.2,bat:-0.5,dog:-0.3},`Yeni düzenleme yürürlükte. Bazı ülkeler itiraz etti.`), ch(`Uluslararası koordinasyon`,2,`Ortak trafik yönetimi.`,{bat:0.6,bol:0.4,des:-0.3},`Toplantılar yapıldı. Trafik yönetimi iyileşti.`), ch(`Mevcut düzeni sürdür`,0,`Değişiklik yok.`,{},`Gemi trafiği sıkışık kalmaya devam etti.`) ]},
{id:'e_hazine',g:'eko',tag:'Ekonomi · Borçlanma',t:'Hazine İhalesi Tutmadı',x:()=>`Devlet tahvili ihalesine beklenenden az talep geldi. Faizler yükselmeden yeni borç bulmak zorlaşıyor.`,c:[ ch(`Yüksek faizle borçlan`,2,`Kaynak bulunur, maliyet artar.`,{borc:1,acik:0.4,rez:1},`Borçlanma tamamlandı, faiz yüksek.`), ch(`Harcama kesintisi ilan et`,3,`Güven verir, sosyal maliyeti var.`,{acik:-0.7,des:-1,huz:-0.3,bat:0.5},`Kesinti duyuruldu. Piyasa olumlu baktı.`), ch(`Merkez Bankası'ndan avans al`,2,`Enflasyonist yol.`,{enf:1.5,kur:3,bat:-0.5},`Avans alındı. Piyasa alarm verdi.`) ]},
{id:'e_toplusoz',g:'eko',tag:'Ekonomi · Kamu',t:'Kamu Çalışanları Toplu Sözleşme',x:()=>`Memurlar zam talebiyle masaya oturdu. Öğretmenler ve sağlıkçılar uyarı eylemine hazırlanıyor.`,c:[ ch(`Talebin büyük bölümünü kabul et`,3,`Huzur getirir, açık büyür.`,{acik:0.7,enf:0.4,des:1.5,huz:0.6,par:0.3},`Sözleşme imzalandı. Memurlar memnun.`), ch(`Enflasyon hedefi kadar zam`,1,`Bütçeye uyumlu.`,{des:-0.5,huz:-0.2},`Zam kabul edildi ama hoşnutsuzluk sürdü.`), ch(`Sert pazarlık, eylemleri yasakla`,2,`Kararlılık göster.`,{des:-1.5,huz:-1,par:0.3},`Sözleşme tıkandı. İş bırakmalar başladı.`) ]},
{id:'e_varlik',g:'eko',tag:'Ekonomi · Sermaye',t:'Yurt Dışındaki Sermayeyi Geri Çekme',x:()=>`Yurt dışında tutulan büyük bir sermaye var. Beyan karşılığında vergi indirimi önerisi geldi.`,c:[ ch(`Yüzde 5 vergiyle geri getir`,2,`Döviz gelir, eşitlik tartışması çıkar.`,{rez:6,acik:-0.3,des:-1,huz:-0.2},`Kanun çıktı. Milyarlarca dolar geri döndü.`), ch(`Yüzde 15 vergiyle daha sınırlı`,2,`Daha adil, daha az döviz.`,{rez:3,acik:-0.3,des:-0.3},`Sınırlı düzenleme geçti.`), ch(`Yapma`,0,`Vergi kaçakçılığı gündemi kalmasın.`,{des:0.3},`Konu kapandı.`) ]},
/* --- YENİ: İÇ SİYASET --- */
{id:'i_gerilim',g:'ic',tag:'İç siyaset · Toplum',t:'Mülteci Karşıtı Olaylar',x:()=>`Bir şehirde çıkan bir kavga mültecilere yönelik saldırılara dönüştü. Sosyal medyada nefret söylemi yükseliyor. ${M.ic.name} kararlı adım bekliyor.`,c:[ ch(`Olayları sert bastır`,2,`Huzur sağlanır, eleştiri gelir.`,{huz:0.8,des:0.3,bat:-0.3},`Olaylar bastırıldı. Gözaltılar yapıldı.`), ch(`Uzlaşma ve uyum programı`,3,`Kalıcı çözüm arayışı.`,{huz:0.6,bat:0.7,des:-0.5},`Programın ilk adımları atıldı.`), ch(`Göçmenleri geri gönderme sözü`,2,`Sokağı yatıştır.`,{des:1,huz:0.2,bat:-1,bol:-0.5},`Söz verildi. Uluslararası kuruluşlar tepki gösterdi.`) ]},
{id:'i_infaz',g:'ic',tag:'İç siyaset · Ceza infaz',t:'Cezaevleri ve Af Tartışması',x:()=>`Cezaevleri kapasitenin üstünde. Af kanunu için bir grup parti destek veriyor, kamuoyu ise ikiye bölünmüş durumda.`,c:[ ch(`Genel af çıkar`,3,`Kapasite rahatlar, tepki büyür.`,{des:-1.5,huz:-0.5,par:-0.4,kol:0.5},`Af çıktı. Kamuoyunda büyük tartışma yaşandı.`), ch(`Sınırlı infaz düzenlemesi`,2,`Sadece suç türlerine göre.`,{des:-0.3,huz:0.2},`Düzenleme geçti.`), ch(`Yeni cezaevi yap`,3,`Bütçe yükü.`,{acik:0.4,des:0.3,huz:0.2},`İhale açıldı.`) ]},
{id:'i_saglik',g:'ic',tag:'İç siyaset · Sağlık',t:'Sağlık Çalışanları Eylemi',x:()=>`Doktorlar ve hemşireler düşük maaş ve şiddet nedeniyle iş bıraktı. Hastanelerde ameliyatlar erteleniyor.`,c:[ ch(`Maaş ve şiddet önleme paketi`,3,`Talepleri karşıla.`,{acik:0.5,des:1.5,huz:0.6,par:0.2},`Paket açıklandı. Eylem sona erdi.`), ch(`Zorunlu hizmet kararı`,2,`Sert çözüm.`,{des:-1,huz:-0.7,par:0.2},`Eylemciler sürgün tehdidi aldı, sistem sarsıldı.`), ch(`Görüşme ve söz`,1,`Zaman kazan.`,{huz:0.1,des:-0.3},`Sözler verildi, somut adım yok.`) ]},
{id:'i_kadin',g:'ic',tag:'İç siyaset · Toplumsal',t:'Kadın Hakları Yürüyüşü',x:()=>`Kadın örgütleri, şiddete karşı yasal düzenleme talebiyle büyük bir yürüyüş çağrısı yaptı. Koalisyon ortağı ise karşıt bir çizgide.`,c:[ ch(`Güçlü koruma yasası`,3,`Toplumun büyük kesimi destekler.`,{des:1.5,bat:0.7,huz:0.5,kol:-0.8,par:-0.3},`Yasa çıktı. Koalisyonda gerilim oldu.`), ch(`Mevcut yasaların uygulanmasını sıkılaştır`,1,`Yeni yasa çıkarma.`,{des:0.3,huz:0.2},`Kılavuz yayımlandı.`), ch(`Yürüyüşü yasakla`,1,`Sert cevap.`,{huz:-1,des:-1.5,bat:-0.6},`Yürüyüş engellendi. Tepki büyüdü.`) ]},
{id:'i_mufredat',g:'ic',tag:'İç siyaset · Eğitim',t:'Eğitim Müfredatı Tartışması',x:()=>`Yeni müfredat taslağı iç kamuoyunu böldü. Öğretmen sendikaları, veliler ve muhafazakâr çevreler farklı istekler sıralıyor.`,c:[ ch(`Taslağı olduğu gibi uygula`,2,`Kararlılık göster.`,{des:-0.5,huz:-0.4,kol:0.4,par:0.2},`Müfredat yürürlüğe girdi. Tartışma sürdü.`), ch(`Geniş bir danışma süreci`,2,`Uzlaşı ara.`,{des:0.4,huz:0.4,par:-0.2},`Danışma toplantıları başladı.`), ch(`Taslağı geri çek`,1,`Tartışmayı kapat.`,{des:0.3,kol:-0.5,par:-0.2},`Taslak geri çekildi. Koalisyon ortağı hoşnutsuz.`) ]},
{id:'i_spor',g:'ic',tag:'İç güvenlik · Spor',t:'Derbi Sonrası Şiddet',x:()=>`Büyük bir derbinin ardından taraftar grupları arasında kanlı olaylar yaşandı. Yayıncı kuruluşlar ve federasyon önlem bekliyor.`,c:[ ch(`Seyirci yasağı ve sert cezalar`,2,`Kısa vadede rahatlık.`,{huz:0.5,des:0.2},`Yasak geldi. Kulüpler mali kayıp yaşadı.`), ch(`Kimlik ve biletli giriş sistemi`,2,`Uzun vadeli tedbir.`,{huz:0.6,des:0.3,acik:0.1},`Yeni sistem kuruldu.`), ch(`Federasyona bırak`,0,`Müdahale etme.`,{huz:-0.3},`Olaylar sonraki haftalarda da yaşandı.`) ]},
{id:'i_sosyalmedya',g:'ic',tag:'İç siyaset · İnternet',t:'Sosyal Medya Kısıtlaması',x:()=>`Bir skandal haberinin yayılmasının ardından, sosyal medya platformlarına bant daraltma önerisi geldi. Gençler ve iş dünyası itiraz ediyor.`,c:[ ch(`Bant daraltma uygula`,2,`Haber yayılımı durur, ama tepki büyür.`,{des:-1.5,huz:-0.8,bat:-1,par:0.2},`Kısıtlama getirildi. VPN indirmeleri arttı.`), ch(`Platformlarla temsilci şartı`,2,`Yasal düzenleme.`,{bat:-0.2,des:-0.3},`Şartlar konuldu. Bazı platformlar uyum sağladı.`), ch(`Dokunma`,0,`Serbest bırak.`,{bat:0.3,des:0.2},`Konu kendi kendine söndü.`) ]},
{id:'i_esnaf',g:'ic',tag:'İç siyaset · Ekonomi',t:'Esnaf Kepenk Kapattı',x:()=>`Kira, vergi ve enerji giderlerinden bunalan esnaf odaları uyarı olarak bir günlük kepenk kapatma kararı aldı.`,c:[ ch(`Vergi ve SGK erteleme paketi`,2,`Esnafı rahatlat.`,{acik:0.4,des:1.5,huz:0.4},`Paket açıklandı. Kepenkler açıldı.`), ch(`Odalarla görüş, ufak destek`,1,`Sembolik destek.`,{des:0.3,acik:0.1},`Görüşme yapıldı. Esnaf yeterli bulmadı.`), ch(`Aldırma`,0,`Tepkiyi yoksay.`,{des:-1.2,huz:-0.3},`Eylem büyüdü.`) ]},
{id:'i_orman',g:'ic',tag:'İç güvenlik · Afet',t:'Orman Yangınları',x:()=>`Ege ve Akdeniz'de yüzlerce hektar orman yanıyor. Yangın söndürme uçakları yetersiz, köyler tahliye ediliyor.`,c:[ ch(`Kalıcı yangın filosu kur`,3,`Uzun vadeli ama pahalı.`,{acik:0.4,des:1,huz:0.4,ord:0.2},`Filo için ihale açıldı. Yeni yangınlara daha hazırsınız.`), ch(`Uluslararası yardım iste`,1,`Hızlı çözüm.`,{bat:0.4,bol:0.4,des:0.2},`Yardım uçakları geldi.`), ch(`Bölgeye git, liderlik göster`,2,`Kişisel varlık.`,{des:1.2,huz:0.3},`Ziyaret medyada geniş yer buldu.`) ]},
{id:'i_donusum',g:'ic',tag:'İç siyaset · Kentsel dönüşüm',t:'Kentsel Dönüşüm Direnişi',x:()=>`Kentsel dönüşüm kapsamındaki bir mahallede sakinler tahliyeye direniyor. Müteahhit ve belediye arasında rant tartışması var.`,c:[ ch(`Yüksek tazminat ve yeniden yerleşim`,3,`Halkı ikna et.`,{acik:0.3,des:0.8,huz:0.3},`Sakinler ikna edildi. Yıkım başladı.`), ch(`Zorla tahliye`,2,`Hızlı sonuç, sert tepki.`,{des:-1.5,huz:-1,par:0.2},`Tahliye yapıldı. Görüntüler sosyal medyada infiale yol açtı.`), ch(`Projeyi durdur`,1,`Yeniden değerlendir.`,{des:0.5,huz:0.4,buy:-0.1},`Proje askıya alındı.`) ]},
{id:'i_lider',g:'ic',tag:'İç siyaset · Parti',t:'Genç Lider Adayı Çıktı',x:()=>`Partide popüler bir genç bakan, liderlik için "vakit geldi" demeye başladı. Sadakatçiler rahatsız, Reformcular ise heyecanlı.`,c:[ ch(`Genç lideri kabineye al`,2,`Yakınına çek.`,{par:0.4,fR:4,des:0.5,fS:-2},`Genç lider kabinede yerini aldı.`), ch(`Etkisizleştir`,2,`Görev alanını daralt.`,{par:-0.6,fS:3,fR:-3,des:-0.3},`Genç lider geri plana itildi. Reformcular rahatsız.`), ch(`Açıkça destekle`,1,`Halefiyet planı.`,{des:0.8,par:0.3,fR:5,fG:-3},`Destek açıklandı. Kamuoyu heyecanlandı.`) ]},
{id:'i_dokunulmaz',g:'ic',tag:'İç siyaset · Meclis',t:'Milletvekili Dokunulmazlığı',x:()=>`Muhalefet ve iktidardan birkaç milletvekili hakkında fezleke geldi. Meclis'te dokunulmazlık kaldırılsın mı tartışması yaşanıyor.`,c:[ ch(`Dokunulmazlıkları kaldır`,3,`Eşitlik mesajı.`,{des:1,par:-0.5,kol:-0.3,huz:0.2},`Meclis oylaması sonuçlandı. Kamuoyu memnun.`), ch(`Sadece kendi vekillerini koru`,2,`Kısmi koruma.`,{des:-1.5,bat:-0.4,par:0.3},`Seçici davranış eleştirildi.`), ch(`Meclis komisyonuna havale et`,0,`Ertele.`,{},`Komisyon dosyayı bekletti.`) ]},
{id:'i_muhittifak',g:'ic',tag:'İç siyaset · Muhalefet',t:'Muhalefet Birleşiyor',x:()=>`Farklı görüşten muhalefet partileri ortak aday ve ortak seçim stratejisi konusunda anlaştı. Anketlerde hükümetin önüne geçme ihtimali var.`,c:[ ch(`Karşı ittifak duyur`,3,`Ortaklarla güç birliği.`,{kol:1,des:0.5,par:0.3,kamp:0},`İttifak duyuruldu. Koalisyon ortağıyla sıkı işbirliği sağlandı.`), ch(`Muhalefeti bölmeye çalış`,3,`Riskli manevra.`,{},``,{fn:()=>Math.random()<0.45?{fx:{des:1.5,kol:0.3},msg:`Muhalefet içinde çatlak oluştu.`}:{fx:{des:-1,par:-0.3},msg:`Girişim ortaya çıktı, itibar zedelendi.`}}), ch(`Sadece kendi işine bak`,0,`Ekonomiye odaklan.`,{des:-0.5},`Muhalefet güçlendi.`) ]},
{id:'i_stk',g:'ic',tag:'İç siyaset · Sivil toplum',t:'Yabancı Finansman Yasası',x:()=>`Yabancı kaynaktan fon alan sivil toplum kuruluşlarını denetleyen bir yasa önerisi hazırlandı. AB ve Batılı elçilikler kaygılı.`,c:[ ch(`Yasayı çıkar`,2,`Denetim güçlenir, tepki artar.`,{des:0.3,bat:-1.5,huz:-0.4,par:0.3},`Yasa çıktı. Uluslararası eleştiriler yükseldi.`), ch(`Yumuşatılmış versiyon`,2,`Şeffaflık odaklı.`,{bat:-0.3,des:0.1},`Metin yumuşatıldı ve kabul edildi.`), ch(`Rafa kaldır`,0,`Şimdilik gerek yok.`,{bat:0.3,par:-0.2},`Yasa taslağı rafa kalktı.`) ]},
{id:'i_transfer',g:'ic',tag:'İç siyaset · Meclis',t:'Milletvekili Transferi',x:()=>`Muhalefetten üç milletvekili partine geçmek için pazarlığa oturdu. Bakanlık ve liste sırası istiyorlar.`,c:[ ch(`Kabul et`,2,`Meclis çoğunluğu güçlenir.`,{kol:0.5,des:-0.5,par:-0.4,huz:-0.1},`Transfer gerçekleşti. Parti içi tepki geldi.`), ch(`Şartlı kabul`,2,`Bakanlık yok, liste garantisi yok.`,{par:0.1,des:0.1},`Şartlı olarak kabul edildi.`), ch(`Reddet`,0,`İlkeli duruş.`,{des:0.5,par:0.3,kol:-0.2},`Transfer teklifi reddedildi.`) ]},
/* --- YENİ: DIŞ İŞLERİ / ASKERİ --- */
{id:'d_karadeniz',g:'dis',tag:'Dış işleri · Karadeniz',t:'Karadeniz\'de Savaşın Taşması',x:()=>`Karadeniz'de savaşan iki ülkenin gemileri Boğaz yakınlarında olay çıkardı. Bir seyir güvenliği krizi doğdu.`,c:[ ch(`Boğazları kapat`,3,`Sözleşme gereği kararlı adım.`,{bat:0.5,dog:-0.5,bol:0.5,ord:0.3,cari:0.5},`Boğazlar askeri gemilere kapatıldı. Taraflar tepki gösterdi.`), ch(`Arabuluculuk teklifi`,2,`Diplomatik çıkış.`,{bol:0.8,bat:0.4,dog:0.4},`Teklif her iki tarafça ilgiyle karşılandı.`), ch(`Tarafsız kal, bekle`,0,`Kendi çıkarını gözet.`,{},`Ülke tarafsız kaldı.`) ]},
{id:'d_ateskes',g:'dis',tag:'Dış işleri · Bölge',t:'Bölgesel Çatışmada Ateşkes Fırsatı',x:()=>`Komşu bölgede iki silahlı taraf arasında ateşkes için garantör ülke aranıyor. Sorumluluk büyük, itibar getirisi de öyle.`,c:[ ch(`Garantör olmayı kabul et`,3,`Kalıcı barış şansı, risk var.`,{},``,{fn:()=>Math.random()<0.55?{fx:{bol:1.5,bat:0.7,dog:0.7,des:1},msg:`Ateşkes sağlandı. Diplomatik başarı kutlandı.`}:{fx:{bol:-0.5,des:-1,ord:-0.3},msg:`Ateşkes çöktü. Türkiye suçlamalara maruz kaldı.`}}), ch(`Destekleyici rol`,1,`Arka planda kal.`,{bol:0.4,bat:0.2},`Destek sunuldu, sorumluluk paylaşıldı.`), ch(`Katılma`,0,`Sorumluluk alma.`,{bol:-0.3},`Türkiye görüşmelerin dışında kaldı.`) ]},
{id:'d_iran',g:'dis',tag:'Dış işleri · Komşular',t:'Komşuyla Nükleer Gerginlik',x:()=>`Komşu bir ülkenin nükleer programı yüzünden bölgede savaş korkusu var. Batı, yaptırım için desteğini istiyor.`,c:[ ch(`Yaptırımlara destek ver`,2,`Batı memnun, komşu öfkeli.`,{bat:1.2,bol:-1,cari:1,dog:-0.5},`Destek açıklandı. Komşuyla ilişkiler gerildi.`), ch(`Diplomasi ve arabuluculuk`,2,`Dengeli tutum.`,{bol:0.8,bat:0.3,des:0.3},`Görüşmeler yürütüldü.`), ch(`Enerji ticaretini koru, sessiz kal`,1,`Pragmatik yaklaşım.`,{cari:-1,bat:-0.4,dog:0.3},`Enerji ticareti devam etti.`) ]},
{id:'d_ada',g:'dis',tag:'Dış işleri · Ada meselesi',t:'Ada Meselesinde Müzakere Baskısı',x:()=>`BM, adanın geleceği için yeni bir müzakere turu düzenlemek istiyor. Taraflar birbirine şartlar öne sürüyor.`,c:[ ch(`Federal çözüme açık ol`,3,`Uzlaşma jesti, iç siyasette maliyeti var.`,{bat:1,bol:0.6,des:-1.5,par:-0.5,kol:-0.6},`Federal çözüme açıklık sinyali verildi. Milliyetçi çevreler öfkelendi.`), ch(`İki devletli çözümde ısrar`,1,`Mevcut çizgi.`,{des:0.8,bat:-0.8,kol:0.3},`Sert tutum sürdü. Müzakereler tıkandı.`), ch(`Masaya oturma`,0,`Süreci bekle.`,{bat:-0.3},`Türkiye müzakereye katılmadı.`) ]},
{id:'d_afrika',g:'dis',tag:'Dış işleri · Afrika',t:'Afrika\'da Askeri Üs Teklifi',x:()=>`Doğu Afrika'da bir ülke, ticaret ve savunma iş birliği karşılığında askeri üs teklif etti. Bölgesel güç dengeleri hassas.`,c:[ ch(`Üsse ve anlaşmaya evet`,3,`Nüfuz alanı genişler.`,{ord:0.5,cari:-1.5,bol:-0.5,bat:-0.5,dog:0.5},`Anlaşma imzalandı. Bölge rakipleri kaygılı.`), ch(`Sadece ticari ortaklık`,2,`Askeri unsur olmadan.`,{cari:-1.5,dog:0.4,bol:0.2},`Ticari anlaşma imzalandı.`), ch(`Reddet`,0,`Riskten kaçın.`,{},`Teklif geri çevrildi.`) ]},
{id:'d_brics',g:'dis',tag:'Dış işleri · Ekonomik blok',t:'BRICS Üyelik Daveti',x:()=>`Yükselen ekonomiler bloku, ülkeyi üyelik görüşmelerine çağırdı. Batı ittifakının bu durumdan hoşnut olmayacağı belli.`,c:[ ch(`Üyelik başvurusu yap`,3,`Doğu'yla bağı güçlendirir.`,{dog:1.5,bat:-1.5,cari:-1,rez:2,par:-0.3},`Başvuru yapıldı. Batı başkentleri tepkili.`), ch(`Gözlemci statüsü`,2,`Denge politikası.`,{dog:0.7,bat:-0.4,rez:1},`Gözlemci statüsü kabul edildi.`), ch(`Reddet`,0,`Batı ittifakını koru.`,{bat:0.6,dog:-0.6},`Teklif kibarca reddedildi.`) ]},
{id:'d_su',g:'dis',tag:'Dış işleri · Su',t:'Sınır Aşan Nehirlerde Su Krizi',x:()=>`Komşu ülkeler kuraklık yüzünden aşağı havzadaki su paylaşımı için baskı yapıyor. Barajlardan daha fazla su bırakılması isteniyor.`,c:[ ch(`Ek su bırak`,2,`İtibar kazanır, tarım zarar görür.`,{bol:0.8,des:-0.8,buy:-0.1},`Ek su bırakıldı. Çiftçiler şikayetçi.`), ch(`Karşılıklı su-enerji anlaşması`,3,`Takas.`,{bol:0.5,cari:-1,des:0.2},`Su-enerji takas anlaşması imzalandı.`), ch(`Talebi reddet`,0,`Kendi ihtiyacını önle.`,{bol:-1,des:0.3},`Talep reddedildi. Komşu ülkeler öfkeli.`) ]},
{id:'d_buyukelci',g:'dis',tag:'Dış işleri · Diplomasi',t:'Büyükelçi Krizi',x:()=>`Bir Batılı büyükelçinin iç siyaseti eleştiren açıklamaları gündemi karıştırdı. Parti içinde "istenmeyen adam ilan edilsin" sesleri var.`,c:[ ch(`Büyükelçiyi sınır dışı et`,2,`Sert diplomatik adım.`,{des:1.2,bat:-1.5,par:0.3},`Büyükelçi sınır dışı edildi. Karşılıklı gerginlik büyüdü.`), ch(`Resmi nota ver`,1,`Ölçülü tepki.`,{des:0.4,bat:-0.3},`Nota verildi. Büyükelçi açıklama yaptı.`), ch(`Görmezden gel`,0,`Önemsiz say.`,{des:-0.5,par:-0.2},`Kriz kendi kendine söndü.`) ]},
{id:'d_casus',g:'dis',tag:'Dış işleri · İstihbarat',t:'Casusluk Skandalı',x:()=>`Yabancı bir istihbarat servisinin ülkede ağ kurduğu iddia edildi. Gözaltılar yapıldı, diplomatik kanallarda gerginlik var.`,c:[ ch(`Kamuoyuna açıkla`,2,`Kararlılık göster.`,{des:1,bat:-0.8,ord:0.3},`Skandal açıklandı. Kamuoyu destek verdi.`), ch(`Diplomatik kanaldan çöz`,2,`Sessizce halle.`,{bat:0.3,des:-0.3},`Sorun gizlice çözüldü.`), ch(`Karşı operasyon`,3,`Aynı yolla karşılık ver.`,{ord:0.5,bat:-0.5,huz:-0.2},`Karşı operasyon yapıldı. İki taraf da suçladı.`) ]},
{id:'a_havasavunma',g:'dis',tag:'Askeri · Hava savunma',t:'Hava Savunma Sistemi Alımı',x:()=>`Komşu bölgede füze saldırıları arttı. Genelkurmay yeni bir hava savunma sistemi istiyor. Batılı ve Doğulu tedarikçiler yarışıyor.`,c:[ ch(`Batı sistemi al`,3,`İttifakla uyumlu.`,{bat:1,ord:0.5,acik:0.4,dog:-0.4},`Sözleşme imzalandı. Batı başkentleri memnun.`), ch(`Doğu sistemi al`,3,`Daha ucuz ve hızlı, ama yaptırım riski.`,{dog:1,ord:0.5,bat:-1.5,acik:0.3},`Sözleşme imzalandı. Yaptırım tehditleri geldi.`), ch(`Yerli sistemi hızlandır`,2,`Uzun vadeli çözüm.`,{ord:0.2,acik:0.2,buy:0.1},`Yerli proje için ek kaynak ayrıldı.`) ]},
{id:'a_denizalti',g:'dis',tag:'Askeri · Donanma',t:'Denizaltı ve Fırkateyn Programı',x:()=>`Donanma yıpranmış. ${M.sav.name} yeni bir denizaltı ve fırkateyn programı için bütçe istiyor.`,c:[ ch(`Tam programı onayla`,3,`Uzun vadeli güç.`,{ord:0.8,acik:0.5,buy:0.2,bol:-0.2},`Program onaylandı. Tersaneler doldu.`), ch(`Aşamalı program`,2,`Bütçeyi yay.`,{ord:0.4,acik:0.2},`Aşamalı program onaylandı.`), ch(`Ertele`,0,`Kaynak yok.`,{ord:-0.5},`Program ertelendi. Donanmada memnuniyetsizlik var.`) ]},
{id:'a_askerlik',g:'dis',tag:'Askeri · Personel',t:'Askerlik Süresi ve Bedelli',x:()=>`Ordu profesyonelleşme ve daha kısa askerlik süresi tartışıyor. Genç seçmen kısaltma istiyor, generaller tehlike görüyor.`,c:[ ch(`Süreyi kısalt, bedelliyi genişlet`,2,`Gençler memnun.`,{des:1.2,ord:-0.6,acik:-0.2},`Süre kısaltıldı. Gençler sevindi, kışlada rahatsızlık var.`), ch(`Profesyonel orduya geçiş planı`,3,`Uzun vadeli reform.`,{ord:0.3,acik:0.4,des:0.3},`Plan hazırlandı. Uygulaması yıllar alacak.`), ch(`Mevcut düzeni koru`,0,`Değişiklik yok.`,{ord:0.2,des:-0.4},`Sistem aynı kaldı.`) ]},
{id:'a_tatbikat',g:'dis',tag:'Askeri · Tatbikat',t:'Büyük Ortak Tatbikat Daveti',x:()=>`Bir müttefikin öncülüğünde büyük bir ortak tatbikat düzenleniyor. Aynı dönemde bir Doğu ülkesi de ortak tatbikat teklif etti.`,c:[ ch(`Müttefikin tatbikatına katıl`,2,`İttifak bağı güçlenir.`,{bat:0.8,ord:0.5,dog:-0.3},`Tatbikata katılım tamamlandı. Yüksek prestij sağlandı.`), ch(`Doğu ülkesiyle tatbikat yap`,2,`Denge politikası.`,{dog:0.8,ord:0.4,bat:-0.8},`Tatbikat yapıldı. Batı tepki gösterdi.`), ch(`İkisine de katıl`,4,`Çift taraflı denge.`,{bat:0.3,dog:0.3,ord:0.6,acik:0.2},`Her iki tatbikat da yapıldı. Türkiye dengeci imajını korudu.`) ]},
/* --- YENİ: ANİ KRİZLER --- */
{id:'k_suikast',g:'kriz',tag:'ACİL · Suikast',t:'Suikast Girişimi',x:()=>`Bir törende yakın koruma ekibi son anda saldırganı etkisiz hale getirdi. Yaralandın ama hayattasın. Ülke nefesini tuttu.`,c:[ ch(`Ulusa seslen, sakinlik çağrısı yap`,1,`Toplumu birleştir.`,{des:3,huz:0.5,par:0.5},`Yaralı halde yaptığın konuşma büyük yankı buldu.`), ch(`OHAL ve geniş gözaltı`,3,`Sert tepki.`,{des:1,huz:-1,bat:-1,ord:0.3},`Yüzlerce gözaltı yapıldı. Eleştiriler geldi.`), ch(`Şeffaf soruşturma`,2,`Sorumluları bul.`,{des:1.5,bat:0.5,huz:0.3},`Soruşturma başladı.`) ]},
{id:'k_darbe',g:'kriz',tag:'ACİL · Darbe',cond:()=>S.ord<5,t:'Darbe Teşebbüsü',x:()=>`Gece yarısı bir grup subay tankları harekete geçirdi. Havalimanı ve köprüler kapatıldı. Kritik saatler yaşanıyor.`,c:[ ch(`Halkı sokağa çağır`,2,`Meşruiyet direnişi.`,{},``,{fn:()=>Math.random()<0.7?{fx:{des:6,ord:-1,huz:-1,par:1},msg:`Halk sokağa çıktı. Girişim püskürtüldü, tasfiyeler başladı.`}:{fx:{des:-4,huz:-3,ord:-2,par:-1},msg:`Çatışmalar günlerce sürdü. Ülke sarsıldı.`}}), ch(`Sadık birliklere emret`,3,`Hızlı sert cevap.`,{des:2,ord:-1.5,huz:-1,par:0.5},`Sadık birlikler girişimi bastırdı.`), ch(`Müzakere ve teslim çağrısı`,1,`Kan dökmeden çöz.`,{des:-2,ord:-2,huz:-2,par:-1},`Müzakere sonuç vermedi. Kriz uzadı.`) ]},
{id:'k_savas',g:'kriz',tag:'ACİL · Savaş',t:'Komşuda Tam Ölçekli Savaş',x:()=>`Komşu ülkede büyük bir savaş başladı. Sınıra yüz binlerce kişi yöneliyor. Uluslararası toplum bir tavır bekliyor.`,c:[ ch(`Seferberlik ve sınır tahkimi`,4,`Askeri hazırlık.`,{ord:1,des:1,acik:0.8,huz:-0.3,bol:-0.5},`Sınır boyunca tahkimat yapıldı. Ekonomi savaş etkisine girdi.`), ch(`Diplomatik seferberlik`,3,`Barış girişimi.`,{bol:1,bat:0.7,dog:0.7,des:0.3},`Yoğun diplomasi başlatıldı.`), ch(`İnsani koridor ve yardım`,3,`Sivilleri koru.`,{bol:0.8,bat:0.8,acik:0.5,des:-0.3},`İnsani koridor açıldı, yardım ulaştırıldı.`) ]},
{id:'k_pandemi',g:'kriz',tag:'ACİL · Salgın',t:'Yeni Bir Salgın',x:()=>`Hızla yayılan yeni bir virüs görüldü. Hastaneler doluyor, bilim kurulu kısıtlama öneriyor.`,c:[ ch(`Sert kapanma`,3,`Can kaybını önler, ekonomiyi vurur.`,{buy:-1.5,isz:1.2,des:-0.5,huz:0.3,acik:0.7},`Kapanma ilan edildi. Ekonomi yavaşladı.`), ch(`Hedefli kısıtlamalar`,2,`Dengeli yaklaşım.`,{buy:-0.5,isz:0.4,des:0.3,acik:0.3},`Hedefli önlemler uygulandı.`), ch(`Aşı ve tedavi seferberliği`,3,`Bilimsel yaklaşım.`,{acik:0.6,des:0.8,bat:0.4,huz:0.4},`Aşı kampanyası hızla başlatıldı.`) ]},
{id:'k_sebeke',g:'kriz',tag:'ACİL · Siber',t:'Ulusal Şebeke Çöktü',x:()=>`Siber saldırı sonucu iki büyük şehirde elektrik ve iletişim durdu. Hastaneler jeneratörle çalışıyor.`,c:[ ch(`Ordu ve siber birimleri devreye al`,3,`Hızlı müdahale.`,{ord:0.5,des:0.8,huz:0.3,acik:0.3},`Şebeke saatler içinde ayağa kaldırıldı.`), ch(`Yabancı uzman yardımı`,2,`Müttefik desteği.`,{bat:0.5,des:0.2,huz:0.2},`Uzmanlar yardımla sistemi onardı.`), ch(`Kamuoyunu bilgilendir ve sakin kal`,1,`Sadece iletişim.`,{des:-1,huz:-0.7},`Krizin yönetimi eleştirildi.`) ]},
{id:'k_finans',g:'kriz',tag:'ACİL · Küresel piyasa',t:'Küresel Finans Şoku',x:()=>`Büyük bir Batı bankasının çöküşü küresel piyasaları sarstı. Gelişmekte olan ülkelerden sermaye kaçıyor.`,c:[ ch(`Rezervi savun, faizi artır`,3,`Sert savunma.`,{rez:-4,kur:-3,buy:-0.6,des:-1,lv:{faiz:5}},`Faiz artırıldı, rezerv kullanıldı.`), ch(`Kuru serbest bırak`,1,`Rezervi koru.`,{kur:10,enf:2.5,des:-2,cari:-1},`Kur sıçradı ama rezerv korundu.`), ch(`IMF ve Körfez'den acil finansman`,3,`Dışarıdan kaynak.`,{rez:8,borc:2,bat:0.5,dog:0.5,des:-1},`Acil finansman sağlandı.`) ]},
{id:'k_yangin',g:'kriz',tag:'ACİL · Afet',t:'Büyük Sel Felaketi',x:()=>`Karadeniz bölgesinde sel felaketi yaşandı. Köprüler yıkıldı, onlarca kişi kayıp. Afet bölgesi ilan edilmesi isteniyor.`,c:[ ch(`Bölgeye git, kişisel liderlik`,2,`Kriz yönetimi ve sahada olma.`,{des:1.5,huz:0.4},`Ziyaret ve koordinasyon olumlu karşılandı.`), ch(`Afet bölgesi ilan et ve yardım seferberliği`,3,`Güçlü devlet imajı.`,{acik:0.5,des:1.2,huz:0.4},`Yardım ve onarım seferberliği başlatıldı.`), ch(`Yerel yönetime bırak`,0,`Merkezi müdahale yok.`,{des:-2,huz:-0.7},`Yerel yönetim yetersiz kaldı, tepki büyüdü.`) ]},
{id:'k_sizinti',g:'kriz',tag:'ACİL · Sızıntı',t:'Gizli Belgeler Sızdırıldı',x:()=>`Hükümetin özel diplomatik yazışmaları ve bazı gizli iç değerlendirmeler internete sızdırıldı. Müttefiklerle ve kabine içinde güven sarsıldı.`,c:[ ch(`Sızıntıyı kabul et, özür dile`,1,`Şeffaflık.`,{des:-0.5,bat:0.3,par:-0.3},`Özür dileme yaklaşımı krizin büyümesini önledi.`), ch(`Sahte olduğunu iddia et`,2,`İnkâr stratejisi.`,{},``,{fn:()=>Math.random()<0.4?{fx:{des:0.5},msg:`İnkâr işe yaradı. Kriz söndü.`}:{fx:{des:-2.5,bat:-1},msg:`Belgelerin gerçekliği doğrulandı. İtibar sarsıldı.`}}), ch(`Kaynağı bulmak için operasyon`,3,`Sert takip.`,{des:-0.5,huz:-0.4,bat:-0.4},`Soruşturma başladı ama tepki çekti.`) ]},
/* --- YENİ: SEÇİM KAMPANYASI --- */
{id:'c_miting',g:'kamp',tag:'Seçim kampanyası',t:'Büyük Şehir Mitingleri',x:()=>`Seçime az kaldı. Parti teşkilatı büyükşehirlerde miting takvimi hazırladı. Katılım, mesajın gücüne ve ekonomik ruh haline bağlı.`,c:[ ch(`Tüm şehirlerde miting turu`,3,`Yoğun tempo, yüksek risk.`,{},``,{fn:()=>Math.random()<0.35+S.des/150?{fx:{kamp:2.5,des:1,par:0.3},msg:`Meydanlar doldu. Mesaj karşılık buldu.`}:{fx:{kamp:0.5,des:-0.5},msg:`Katılım beklenenin altında kaldı.`}}), ch(`Sadece kilit şehirlerde`,2,`Seçici strateji.`,{kamp:1.2,des:0.4},`Kilit şehirlerde etkili mitingler yapıldı.`), ch(`Miting yerine ev ziyaretleri`,1,`Sessiz kampanya.`,{kamp:0.5,huz:0.2},`Ev ziyaretleri sonuç verdi.`) ]},
{id:'c_ittifak',g:'kamp',tag:'Seçim kampanyası',t:'İttifak Pazarlığı',x:()=>`Seçim öncesi küçük partiler ittifak için masaya oturdu. Her biri bakanlık ve liste sırası istiyor.`,c:[ ch(`Geniş ittifak kur`,3,`Oy tabanını büyüt, taviz ver.`,{kamp:2,kol:0.8,par:-0.6},`İttifak duyuruldu. Oy potansiyeli arttı.`), ch(`Sadece mevcut ortakla devam et`,1,`Sağlam ama dar.`,{kamp:0.5,kol:0.3},`Mevcut ittifak korundu.`), ch(`Tek başına yarış`,0,`Bağımsız duruş.`,{kamp:-0.5,par:0.3,kol:-0.5},`Tek başına yarış kararı alındı.`) ]},
{id:'c_vaat',g:'kamp',tag:'Seçim kampanyası',t:'Seçim Vaatleri Paketi',x:()=>`Kampanya ekibi, seçim beyannamesine büyük sosyal vaatler eklenmesini öneriyor. Maliye Bakanı vaatlerin bütçeye sığmadığını söylüyor.`,c:[ ch(`Cömert vaat paketi`,2,`Oy toplar, bütçeyi zorlar.`,{kamp:2.5,acik:0.6,des:1,lv:{sosyal:1}},`Vaatler açıklandı. Kamuoyunda büyük ilgi gördü.`), ch(`Ölçülü ve maliyetlendirilmiş program`,2,`Güven verir.`,{kamp:1,bat:0.3,des:0.3},`Program açıklandı. Ekonomistler olumlu baktı.`), ch(`Vaat yerine geçmiş performansı anlat`,1,`Deneyim vurgusu.`,{kamp:0.3},`Kampanya performans odaklı ilerledi.`) ]},
{id:'c_munazara',g:'kamp',tag:'Seçim kampanyası',t:'Canlı TV Münazarası',x:()=>`Ana muhalefet lideri seni canlı yayında münazaraya davet etti. Kabul etmezsen "kaçtı" denecek, kabul edersen risk büyük.`,c:[ ch(`Kabul et ve hazırlan`,2,`Sahnede güçlü ol.`,{},``,{fn:()=>Math.random()<0.5+M.dis.sk/50?{fx:{kamp:3,des:1.5},msg:`Münazarada net bir üstünlük sağladın.`}:{fx:{kamp:-1.5,des:-1},msg:`Münazarada zor anlar yaşadın.`}}), ch(`Yerine bir bakan gönder`,1,`Riski dağıt.`,{kamp:0.2,des:-0.3},`Bakanın performansı vasat kaldı.`), ch(`Reddet`,0,`Katılma.`,{kamp:-1,des:-0.5},`Muhalefet "kaçtı" kampanyası yaptı.`) ]},
{id:'c_anket',g:'kamp',tag:'Seçim kampanyası',t:'Anket Savaşı',x:()=>`Anket şirketleri birbirine zıt sonuçlar açıklıyor. Kamuoyunda "hangi anket doğru" tartışması var.`,c:[ ch(`Dost anketleri öne çıkar`,1,`Algı yönetimi.`,{kamp:0.8,des:0.3,bat:-0.2},`Anket sonuçları basında geniş yer buldu.`), ch(`Bağımsız anket şirketine yaptır`,2,`Gerçeği gör.`,{kamp:0.4,des:0.2},`Sonuç objektif bir bakış sağladı.`), ch(`Anketlerle uğraşma`,0,`Sahaya odaklan.`,{kamp:0.2},`Seçmene yönelik çalışma sürdü.`) ]},
{id:'c_medya',g:'kamp',tag:'Seçim kampanyası',t:'Medya Stratejisi',x:()=>`Seçim öncesi televizyonlarda yayın süreleri paylaşılıyor. Yandaş ve muhalif kanallar arasında dengesiz dağılım iddiaları var.`,c:[ ch(`Yoğun reklam ve yayın kampanyası`,3,`Yüksek görünürlük.`,{kamp:2,acik:0.2,bat:-0.2},`Kampanya yoğun şekilde sürdürüldü.`), ch(`Sosyal medya ağırlıklı kampanya`,2,`Genç seçmene odaklan.`,{kamp:1.3,des:0.3},`Sosyal medya kampanyası gençlerden ilgi gördü.`), ch(`Yayın eşitliği taahhüdü`,1,`Adil görün.`,{kamp:0.5,bat:0.5,des:0.2},`Eşit yayın taahhüdü verildi.`) ]},
{id:'c_muhalefet',g:'kamp',tag:'Seçim kampanyası',t:'Muhalefet Saldırısı',x:()=>`Muhalefet, ekonomik zorlukları bir "hesap günü" söylemine dönüştürdü. Kampanya sert bir mesaj çizgisine kayıyor.`,c:[ ch(`Karşı saldırıya geç`,2,`Sert kampanya.`,{kamp:1,des:0.3,huz:-0.4},`Karşı kampanya başladı, gerilim yükseldi.`), ch(`Pozitif kampanya`,2,`Umut vurgusu.`,{kamp:1.5,huz:0.3,des:0.4},`Pozitif kampanya seçmene iyi geldi.`), ch(`Yok say`,0,`Tepki gösterme.`,{kamp:-0.5,des:-0.3},`Muhalefet gündemi belirledi.`) ]},
{id:'c_sandik',g:'kamp',tag:'Seçim kampanyası',t:'Sandık Güvenliği',x:()=>`Seçim güvenliği ve sandık başı örgütlenmesi tartışılıyor. Her iki taraf da hile iddialarına hazırlanıyor.`,c:[ ch(`Ulusal ve uluslararası gözlemci davet et`,2,`Şeffaflık.`,{kamp:0.8,bat:0.8,des:0.3},`Gözlemciler davet edildi. Süreç güven verdi.`), ch(`Sandık başı örgütlenmesini güçlendir`,2,`Teşkilat gücü.`,{kamp:1.5,par:0.3},`Teşkilat sahaya iniyor.`), ch(`Özel önlem alma`,0,`Mevcut düzen yeterli.`,{kamp:-0.3},`Herhangi bir ek tedbir alınmadı.`) ]},
{id:'i_bakanskandal',g:'ic',tag:'İç siyaset · Kabine',t:'Bakan Skandalı',x:()=>`${M.ic.name} hakkındaki yolsuzluk iddiaları basına sızdı. Muhalefet istifa çağrısı yapıyor, koalisyon ortağı sessiz.`,c:[ ch('Bakanı görevden al',2,'Temiz görünürsün, yerine yeni biri atanır.',{},'',{fn:()=>{S.M.ic=newM();return {fx:{des:.5,par:-.3,bat:.3},msg:`Bakan görevden alındı. Yerine ${S.M.ic.name} atandı.`};}}), ch('Bakana sahip çık',1,'Sadakat gösterirsin, tepki çekersin.',{des:-1.5,huz:-.5,par:.3},'Bakana sahip çıktın. Muhalefet sesini yükseltti.'), ch('Soruşturma başlat',1,'Sonuç şansa bağlı.',{},'',{fn:()=>Math.random()<.5?{fx:{des:.5,par:.2},msg:'Soruşturma bakanı akladı. Tartışma dindi.'}:{fx:{des:-1.5,par:-.5},msg:'Soruşturma yeni iddiaları ortaya çıkardı.'}}) ]},
{id:'i_istifa',g:'ic',tag:'İç siyaset · Kabine',t:'Maliye Bakanı İstifa Etti',x:()=>`${M.maliye.name} "farklı düşünüyoruz" diyerek istifa etti. Piyasalar yeni ismi bekliyor.`,c:[ ch('Teknokrat ata',2,'Piyasa güveni artar, parti içinde zayıflarsın.',{},'',{fn:()=>{S.M.maliye={...newM(),sk:8,note:'Teknokrat, disiplinli'};return {fx:{kur:-1,des:-.2,par:-.3},msg:`${S.M.maliye.name} atandı. Piyasa olumlu karşıladı.`};}}), ch('Sadık bir isim ata',1,'Parti memnun olur, piyasa temkinli kalır.',{},'',{fn:()=>{S.M.maliye={...newM(),sk:4,note:'Sadık ama deneyimsiz'};return {fx:{kur:1.5,par:.4},msg:`${S.M.maliye.name} atandı. Piyasa temkinli.`};}}) ]},
{id:'k_deprem',g:'kriz',tag:'ACİL · Afet',t:'Büyük Deprem',x:()=>`Şiddetli bir deprem birkaç ili vurdu, enkaz altında kalanlar var. AFAD hazırlığı İçişleri ve Çevre bütçelerine bağlı. Hazırlık düzeyi %${nf(prep()*100,0)}.`,c:[ ch('Seferberlik ve OHAL',3,'Tüm kaynaklar bölgeye. Hazırlık ne kadar iyiyse o kadar etkili.',{},'',{fn:()=>Math.random()<prep()?{fx:{des:2,huz:.3,acik:1,par:.3},msg:'Arama kurtarma hızlı ilerledi. Kamuoyu devleti takdir etti.'}:{fx:{des:-4,huz:-1.5,acik:1.5,par:-.5},msg:'Müdahale gecikti. Öfke ve eleştiri arttı.'}}), ch('Yardım kampanyası ve yeniden inşa fonu',2,'Yeniden inşa maliyeti bütçeye biner.',{},'',{fn:()=>Math.random()<prep()?{fx:{des:1,acik:1.2,huz:.2},msg:'Fon hızla toplandı, inşaat başladı.'}:{fx:{des:-2,acik:1.5,huz:-.8},msg:'Yardımlar dağıtımda aksadı.'}}), ch('Mevcut kaynaklarla yönet',0,'Ucuz ama riskli.',{des:-3,huz:-1,par:-.3},'Yetersiz müdahale büyük tepki çekti.') ]},
{id:'d_operasyon',g:'dis',tag:'Dış işleri · Güvenlik',t:'Sınır Ötesi Operasyon Önerisi',x:()=>`Genelkurmay sınır ötesinde terör hedeflerine operasyon öneriyor. ${M.sav.name} "koşullar uygun" diyor. Uluslararası tepki bekleniyor.`,c:[ ch('Operasyona onay ver',3,'Ordu ve milliyetçi kesim memnun olur, Batı tepki gösterir.',{},'',{fn:()=>Math.random()<.65?{fx:{ord:.8,des:1.5,huz:.3,bat:-.8,bol:-.4,acik:.3},msg:'Operasyon başarıyla tamamlandı. Kamuoyu destek verdi.'}:{fx:{ord:-.3,des:-1,bat:-1,bol:-.6,acik:.4},msg:'Operasyon beklenenden zor geçti. Kayıplar tartışılıyor.'}}), ch('Diplomasiyi dene',1,'Riski azaltır, sertlik yanlıları tepki gösterir.',{des:-.3,bat:.4,bol:.3,ord:-.2},'Diplomatik temaslar sürdü, operasyon ertelendi.'), ch('Ertele',0,'Şimdilik beklet.',{ord:-.2},'Öneri rafa kalktı.') ]},
{id:'d_yaptirim',g:'dis',tag:'Dış işleri · Yaptırım',t:'Yaptırım Tehdidi',x:()=>`Bazı ülkeler savunma alımlarınız ve bir bankanız üzerinden yaptırım hazırlığında. ${M.dis.name} "önce diplomasi" diyor.`,c:[ ch('Müzakereye otur',2,'Taviz verirsin ama tehdit uzar.',{bat:.6,des:-.3,par:-.2},'Müzakere sürüyor, yaptırım ertelendi.'), ch('Sert karşılık ver',1,'Doğu ile yakınlaşırsın, Batı soğur.',{dog:.8,bat:-1,des:.6,cari:.5},'Sert bir açıklama yapıldı. Doğu ile ticaret arttı.'), ch('Bekle ve gör',0,'Karar verme.',{rez:-1.5,kur:1.5,bat:-.3},'Belirsizlik piyasayı olumsuz etkiledi.') ]},

{id:'e_kripto',g:'eko',tag:'Ekonomi · Finans',t:'Kripto Borsası Çöktü',x:()=>`Büyük bir kripto borsası ödemeleri durdurdu. Yaklaşık iki milyon yerli kullanıcının parası içeride. ${M.maliye.name} "düzenleme boşluğu" uyarısı yapıyor.`,c:[ ch('Borsayı devral, mağdurları koru',3,'Bütçeye yük biner, güven artar.',{acik:.5,des:1,bat:.3},'Borsa kayyuma devredildi. Mağdur ödemeleri planlandı.'), ch('Sıkı lisans düzenlemesi getir',2,'Yasal çerçeve oluşur.',{bat:.4,des:-.3,par:.1},'Kripto varlıklar için lisans zorunluluğu geldi.'), ch('Piyasaya bırak',0,'Devlet karışmaz.',{des:-1.5,huz:-.3},'Mağdurlar sokağa döküldü, tepki büyüdü.') ]},
{id:'e_ticaret',g:'eko',tag:'Ekonomi · Dış ticaret',t:'Gümrük Tarifeleri Artırıldı',x:()=>`Ana ihracat pazarlarından biri ürünlerimize ek gümrük tarifesi getirdi. İhracatçı dernekleri destek bekliyor.`,c:[ ch('İhracat destek paketi',2,'Bütçeye yük, ihracatçı rahatlar.',{acik:.4,cari:-.6,des:.5},'Destek paketi açıklandı. İhracatçılar nefes aldı.'), ch('Yeni pazarlar ara',1,'Zaman alır ama bağımlılığı azaltır.',{dog:.5,cari:-.2,bat:-.2},'Doğu ve Afrika pazarlarına heyetler gitti.'), ch('Karşı tarife koy',2,'Sert cevap, ticaret daralır.',{cari:.5,enf:.4,des:.4,bat:-.6},'Karşı tarife uygulandı. Gerginlik arttı.') ]},
{id:'i_ogrenci',g:'ic',tag:'İç siyaset · Gençlik',t:'Üniversite Öğrencileri Eylemde',x:()=>`Yurt ve burs sorunları nedeniyle onlarca üniversitede oturma eylemi başladı. ${M.ic.name} "kontrol altında" diyor.`,c:[ ch('Burs ve yurt bütçesini artır',2,'Gençler yatışır, bütçeye yük biner.',{des:1,huz:.6,acik:.3},'Burslar artırıldı, eylemler sona erdi.'), ch('Rektörlerle görüş',1,'Kısmi çözüm.',{huz:.2,des:.1},'Rektörlerle toplantı yapıldı, sorunlar kısmen çözüldü.'), ch('Eylemleri yasakla',1,'Kısa vadede sessizlik, uzun vadede öfke.',{huz:-1,des:-1,bat:-.4},'Eylemler yasaklandı, gerilim yükseldi.') ]},
{id:'i_belediye',g:'ic',tag:'İç siyaset · Yerel yönetim',t:'Büyükşehir Belediyesiyle Kriz',x:()=>`Bir büyükşehir belediye başkanıyla ödenek ve yetki tartışması sertleşti. Muhalefet "vesayet" diyor.`,c:[ ch('Ödenekleri serbest bırak',2,'Belediye rahatlar, kamuoyu olumlu bakar.',{},'',{fn:()=>{S.mun=clamp(S.mun+1,0,30);return {fx:{des:.5,par:-.2,acik:.2},msg:'Ödenekler serbest bırakıldı. Yerel yönetimle ilişkiler düzeldi.'};}}), ch('Kayyum atama girişimi',3,'Sert adım, geri tepebilir.',{},'',{fn:()=>Math.random()<.5?{fx:{des:1,par:.4,bat:-.6,huz:-.4},msg:'Kayyum kararı uygulandı. Sokaklar gerildi.'}:{fx:{des:-2,par:-.3,bat:-.8,huz:-.8},msg:'Karar geri tepti. Büyük protestolar oldu.'}}), ch('Görüşmeyi sürdür',0,'Zaman kazan.',{par:-.1},'Görüşmeler sürüyor.') ]},
{id:'d_zirve',g:'dis',tag:'Dış işleri · Diplomasi',t:'Bölgesel Zirve Daveti',x:()=>`Komşu ülkeler bölgesel bir enerji ve güvenlik zirvesine seni davet etti. ${M.dis.name} katılımı öneriyor ama iç siyasette tartışma çıkabilir.`,c:[ ch('Katıl ve konuş',2,'İtibar kazanırsın.',{bol:.8,dog:.4,bat:.2,des:.3},'Zirvede etkili bir konuşma yaptın. Bölgesel itibar yükseldi.'), ch('Bakan gönder',1,'Düşük profil.',{bol:.3},'Bakan katıldı, sonuç bildirgesi imzalandı.'), ch('Katılma',0,'Gerilimden kaçın.',{bol:-.4,dog:-.2},'Zirveye katılım olmadı.') ]},
{id:'d_dogalgaz',g:'dis',tag:'Dış işleri · Enerji',t:'Yeni Doğalgaz Keşfi',x:()=>`Karadeniz'de yeni bir doğalgaz sahası bulundu. Rezervin büyüklüğü tartışılıyor. Yatırımcılar ilgi gösteriyor.`,c:[ ch('Hızlı üretime geç',3,'Yatırım gerekir, cari açık azalır.',{cari:-1.2,acik:.5,des:1.2,bat:.2},'Üretim hızlandırıldı. Enerji ithalatı azalacak.'), ch('Ortaklık ara',2,'Yatırım yükünü paylaş.',{cari:-.6,bat:.3,dog:.3,des:.4},'Uluslararası ortaklık kuruldu.'), ch('Duyuruyu ertele',0,'Sessiz ilerle.',{des:.2},'Keşif temkinli açıklandı.') ]},
{id:'t_yorgun',g:'later',tag:'Dönem · Yorgunluk',t:'Değişim Talebi',x:()=>`Uzun süredir iktidardasın. Anketlerde "artık değişim" sesi yükseliyor, parti içinde bile isimler eleştiri yapıyor.`,c:[ ch('Kabineyi yenile, yeni yüzler getir',2,'Taze bir hava, parti içinde tepki.',{des:1,par:-.3,bat:.2},'Kabinede değişiklik yapıldı. Kamuoyu olumlu karşıladı.'), ch('Reform paketi açıkla',2,'Bütçeye yük, umut verir.',{des:.8,bat:.4,acik:.3},'Reform paketi açıklandı. Beklenti arttı.'), ch('Aldırma',0,'Devam et.',{des:-1.5,par:.2},'Eleştiriler görmezden gelindi. Hoşnutsuzluk büyüdü.') ]},
{id:'t_kuresel',g:'later',tag:'Dönem · Küresel',t:'Küresel Resesyon',x:()=>`Dünya ekonomisi yavaşlıyor. İhracat siparişleri düşüyor, sermaye çıkışı başladı. ${M.maliye.name} acil önlem istiyor.`,c:[ ch('Kemer sıkma programı',2,'Açık azalır, halk sıkışır.',{acik:-.6,des:-1,buy:-.4},'Kemer sıkma açıklandı. Piyasalar sakinleşti, halk tepkili.'), ch('Teşvik paketi',3,'Büyüme korunur, açık artar.',{acik:.8,buy:.6,des:.6},'Teşvik paketi açıklandı. Ekonomi nefes aldı.'), ch('Uluslararası destek ara',1,'Rezerv gelir, taviz verilir.',{rez:2,bat:.3,des:-.6},'Uluslararası kuruluşlarla anlaşmaya varıldı.') ]},
{id:'e_petrol',g:'eko',tag:'Ekonomi · Enerji',t:'Petrol Fiyatları Fırladı',x:()=>`Körfez'deki gerilim yüzünden Brent petrol hızla yükseliyor. Enerji ithalat faturası büyüyor, ${M.maliye.name} acil plan istiyor.`,c:[ ch('Enerji sübvansiyonu ver',3,'Fatura bütçeye biner, halk rahatlar.',{},'',{fn:()=>{S.tr.pe=clamp(S.tr.pe+20,35,150);return {fx:{acik:.8,des:.6,huz:.2},msg:'Sübvansiyon açıklandı. Bütçe baskı altında.'};}}), ch('Yerli enerji yatırımını hızlandır',2,'Uzun vadede bağımlılığı azaltır.',{},'',{fn:()=>{S.tr.pe=clamp(S.tr.pe+20,35,150);S.sec.ene=clamp(S.sec.ene+4,0,100);return {fx:{acik:.4,dog:.2},msg:'Enerji yatırımları hızlandırıldı.'};}}), ch('Piyasaya bırak',0,'Fiyat artışı yansır.',{},'',{fn:()=>{S.tr.pe=clamp(S.tr.pe+25,35,150);return {fx:{enf:1,cari:.8,des:-1},msg:'Fiyatlar yansıdı. Enflasyon ve cari açık arttı.'};}}) ]},
];
const EVB=Object.fromEntries(EV.map(e=>[e.id,e]));

/* ---------- Olay üretimi ve uygulama ---------- */
function pickFrom(g){
  const ok=e=>e.g===g&&(!e.cond||e.cond());
  let c=EV.filter(e=>ok(e)&&!S.used.includes(e.id));
  if(!c.length){S.used=S.used.filter(id=>EVB[id].g!==g);c=EV.filter(ok);}
  return c.length?c[Math.floor(Math.random()*c.length)].id:null;
}
function genEvents(fixed){
  let ids=fixed||['eko','ic','dis'].map(pickFrom).filter(Boolean);
  if(!fixed){
    const p=0.10+(S.huz<4?0.06:0)+(S.ord<4?0.05:0)+((S.dif===undefined?1:S.dif)-1)*.04+(S.term-1)*.02;
    if(Math.random()<p){const k=pickFrom('kriz');if(k)ids.unshift(k);}
    if(S.month%TERM>=TERM-3){const k=pickFrom('kamp');if(k)ids.push(k);}
  }
  if(!fixed&&S.month>=2&&(S.month-2)%12===0){S.hd=Math.max(5,Math.round(S.enf*.6));const W=Math.round(S.enf*.9+rnd(5,12)),E=Math.round(S.enf*.55);S.wage={W,E,G:Math.round((W+E)/2)};}
  const due=S.sched.filter(s=>s.due<=S.month);
  S.sched=S.sched.filter(s=>s.due>S.month);
  due.forEach(s=>ids.unshift(s.id));
  ids.forEach(id=>{if(!S.used.includes(id))S.used.push(id);});
  S.cur={events:ids.map(id=>({id,ch:null,msg:'',fxs:null})),spent:0};
}
function applyFx(fx){
  for(const k in fx){
    const v=fx[k];
    if(k==='lv'){for(const l in v){
      if(l==='faiz'){const r=LVR.faiz;S.lv.faiz=clamp(S.lv.faiz+v[l],r[0],r[1]);S.lv0.faiz=clamp(S.lv0.faiz+v[l],r[0],r[1]);}
      else if(l==='vergi')S.tax.kdv=clamp(S.tax.kdv+v[l]*2,0,100);
      else if(l==='sosyal')S.bud.calisma=clamp(S.bud.calisma*(1+.1*v[l]),MB.calisma*.4,MB.calisma*2);
      else if(l==='sav')S.bud.sav=clamp(S.bud.sav+v[l],MB.sav*.4,MB.sav*2);}}
    else if(k==='kur')S.kur*=1+v/100;
    else if(k==='fR'||k==='fG'||k==='fS'){const f=k[1];S.fac[f]=Math.max(3,S.fac[f]+v);const t=S.fac.R+S.fac.G+S.fac.S;for(const q in S.fac)S.fac[q]=S.fac[q]/t*100;}
    else if(RANGE[k]){S[k]=clamp(S[k]+v,RANGE[k][0],RANGE[k][1]);}
  }
}
function decide(ei,ci){
  const ev=S.cur.events[ei];if(ev.ch!==null)return;
  const d=EVB[ev.id],c=d.c[ci];
  if(c.ss>avail()&&c.ss>Math.min(...d.c.map(x=>x.ss)))return;
  const before=snap();
  let fx=c.fx,msg=c.m,later=c.later;
  if(c.fn){const r=c.fn();fx=r.fx;msg=r.msg;later=r.later||later;}
  applyFx(fx);
  if(later)later.forEach(l=>S.sched.push({due:S.month+l.m,id:l.id}));
  S.cur.spent+=c.ss;
  ev.ch=ci;ev.msg=msg;S.nd++;if(d.g==='kriz')S.nk++;
  const after=snap();const fxs=[];
  STATS.forEach(s=>{const dd=after[s.k]-before[s.k];if(Math.abs(dd)>=0.05)fxs.push([s.l,dd,s.d,s.u]);});
  ev.fxs=fxs;
  S.log.push({m:S.month,t:d.t,c:c.l,msg});
  save();render();
}

