/* ---------- Genişleme 2: sınıf ve refah, zorluk, komuta masası, istatistik, kabine araçları ---------- */
const CL=[['Yoksul (işsiz)',14],['Alt gelir (vasıfsız)',38],['Orta gelir',30],['Üst-orta gelir',13],['Zengin',4],['Çok zengin',1]];
function clS(){const d=clamp((S.enf-48)*.12+(S.isz-9.2)*.6-(ap()-100)*.08-(S.buy-2.8)*.5,-7,12),s=CL.map(c=>c[1]),w=[.7,.5,-.8,-.3,-.1,0];s.forEach((v,i)=>s[i]=Math.max(.3,v+d*w[i]));const t=s.reduce((a,b)=>a+b,0);return {s:s.map(v=>v/t*100),d};}
const refah=()=>{const s=clS().s;return clamp(.9*s[2]+1.6*s[3]+3*s[4]+4*s[5]-.6*s[0],0,100);};
const PRG=[['Çıraklık ve staj','İşsizlik −0,15, büyüme +0,05, bütçe +0,08.',{isz:-.15,buy:.05,acik:.08}],['Üniversite kontenjanı','Destek +0,08, işsizlik +0,05 (mezun işsizliği), bütçe +0,1.',{des:.08,isz:.05,acik:.1}],['Beceri kursları','İşsizlik −0,1, bütçe +0,05.',{isz:-.1,acik:.05}]];
const LV=[['Vasıfsız',.2,-.05],['İlkokul',.25,.02],['Lise',.3,-.01],['Üniversite',.15,.03]];
const ZD=[{buy:.04,des:.04,acik:-.04,enf:-.03,huz:.01},{},{buy:-.04,des:-.04,acik:.04,enf:.03,huz:-.01}],ZN=['Kolay','Normal','Zor'];
function gfxB(){const F={};if(!S.th2)return F;mrg(F,ZD[S.dif===undefined?1:S.dif]);F.des=(F.des||0)+(refah()-55)*.002;
  const ms=Object.values(S.M),av=ms.reduce((a,m)=>a+m.sk,0)/ms.length;F.buy=(F.buy||0)+(av-6)*.012;F.acik=(F.acik||0)-(av-6)*.008;return F;}
const gfxAll=()=>{const F=gfxA();mrg(F,gfxB());return F;};
function genis2Ensure(){if(!S.th2)S.th2={};STATS.forEach(s=>{if(!S.th2[s.k])S.th2[s.k]=[];});if(S.lit===undefined)S.lit=96.5;if(S.ist2===undefined)S.ist2='enf';}
function genis2Up(){genis2Ensure();STATS.forEach(s=>{const a=S.th2[s.k];a.push(Math.round(S[s.k]*100)/100);if(a.length>60)a.shift();});
  S.lit=clamp(S.lit+(cov(SV[1])-78)*.002,80,100);return [];}
function genis2Click(t){const d=t.dataset;
  if(d.prg!==undefined){const x=PRG[+d.prg];if(!x)return true;const m=su('prg');suU('prg');applyFx(sfx2(x[2],m));logA('İşgücü programı',x[0],'Uygulandı.'+sat(m));hap(20,520);save();render();return true;}
  if(d.is){S.ist2=d.is;render();return true;}
  if(d.kauto){let n=0;Object.keys(S.M).forEach(k=>{if(S.own[k])return;const m=S.M[k];if(m.sk<5||(m.gv!==undefined&&m.gv<35)){S.M[k]={name:NAMES1[Math.floor(Math.random()*16)]+' '+NAMES2[Math.floor(Math.random()*16)],sk:Math.round(rnd(5,9)),note:'Otomatik atama',gv:55};n++;}});
    if(n){S.par=clamp(S.par-.1*n,0,10);logA('Kabine değişikliği','Otomatik',n+' zayıf ya da güven kaybeden bakan değiştirildi.');}hap(20,520);save();render();return true;}
  return false;}
const diff=(a,n)=>a.length>n?a[a.length-1]-a[a.length-1-n]:0;
function bigCh(a,c){const v=a.slice(-60);if(v.length<2)return '<div class="dl muted">Grafik için en az iki ay veri gerekir.</div>';const mn=Math.min(...v),mx=Math.max(...v),r=(mx-mn)||1,p=v.map((y,i)=>`${(i/(v.length-1)*290+5).toFixed(1)},${(104-(y-mn)/r*92).toFixed(1)}`).join(' ');
  return `<svg class="ch" viewBox="0 0 300 120" style="width:100%;height:130px"><line x1="5" x2="295" y1="12" y2="12"/><line x1="5" x2="295" y1="104" y2="104"/><text x="6" y="9">${nf(mx,1)}</text><text x="6" y="117">${nf(mn,1)}</text><polyline points="${p}"/></svg>`;}
function istat(){genis2Ensure();const T=S.th2,ss=STATS.filter(s=>T[s.k]),cur=STATS.find(s=>s.k===S.ist2)||STATS[0];
  return `<h2>İstatistik</h2><div class="panel"><b>${cur.l}</b> <span class="muted dl">· son ${Math.min(60,T[cur.k].length)} ay</span>${bigCh(T[cur.k])}<div class="dl">Şimdi ${nf(S[cur.k],cur.d)} ${cur.u} · 12 ay önceye göre ${diff(T[cur.k],12)>=0?'+':'−'}${nf(Math.abs(diff(T[cur.k],12)),cur.d)}</div></div>
  <div class="panel"><b>Tüm göstergeler</b>${ss.map(s=>{const a=T[s.k],df=diff(a,12),gd=(df<0)===!!s.low||!df;return `<button class="ag" data-is="${s.k}" style="grid-template-columns:minmax(0,1fr) auto 80px"><span>${s.l}</span><b class="dl" style="color:var(--${df?(gd?'good':'bad'):'muted'})">${nf(S[s.k],s.d)}${df?(df>0?' ▲':' ▼'):''}</b>${spark(a)}</button>`;}).join('')}<div class="note">Dokunduğun göstergenin grafiği yukarıda açılır. Yeşil, 12 ay önceye göre iyiye gidişi gösterir.</div></div>${trendP()}`;}
function sinif(){const c=clS(),s=c.s,rf=refah(),gini=.413+c.d*.004,ag=[['0-14 Çocuk',kid()],['15-24 Genç',15.5-.01*S.month],['25-54 Yetişkin',100-kid()-(15.5-.01*S.month)-9.5-old()],['55-64 Orta yaş',9.5],['65+ Emekli',old()]],ni=S.nuf||86;
  return `<h2>Sınıf ve refah</h2><div class="panel"><b>Gelir grupları</b>${CL.map((x,i)=>`<div class="fac" style="margin:6px 0 0"><div class="f" style="grid-template-columns:126px minmax(0,1fr) 54px"><span>${x[0]}</span><div class="bar ${i<2?'warn':'good'}"><i style="width:${Math.min(100,s[i]*2)}%"></i></div><span class="dl">%${nf(s[i],1)}</span></div></div>`).join('')}<div class="note">Sınıflar enflasyon, işsizlik, büyüme ve asgari ücretin alım gücüyle kayar. Gini tahmini: ${nf(gini,3)}.</div></div>
  <div class="panel"><b>Refah düzeyi</b> <span class="st ${rf>=55?'good':rf>=40?'warn':'bad'}">${nf(rf,0)}/100</span>${gbar(rf,rf>=55?'good':rf>=40?'warn':'bad')}<div class="dl" style="display:flex;justify-content:space-between"><span>Okuryazarlık</span><span>%${nf(S.lit,1)}</span></div>${gbar(S.lit,'good')}<div class="note">Refah halk desteğini sürekli etkiler (55 üstü destek artırır). Okuryazarlık eğitim hizmetinin kapsamasına göre yavaş değişir.</div></div>
  <div class="panel"><b>Yaş grupları</b>${ag.map(a=>`<div class="fac" style="margin:6px 0 0"><div class="f" style="grid-template-columns:104px minmax(0,1fr) 92px"><span>${a[0]}</span><div class="bar"><i style="width:${Math.min(100,a[1]*2.2)}%"></i></div><span class="dl">${nf(ni*a[1]/100,1)} mn · %${nf(a[1],0)}</span></div></div>`).join('')}</div>
  <div class="panel"><b>İşgücü piyasası</b>${LV.map(l=>{const arz=ni*l[1],tal=arz*(1+(S.buy-2.8)*.02+l[2]-(S.isz-9.2)*.004),r=tal/arz,st=r>1.015?['açık','warn']:r<.985?['işsiz','bad']:['dengede','good'];return `<div class="dl" style="display:flex;justify-content:space-between;border-top:1px solid var(--line);padding:5px 0"><span>${l[0]} · arz ${nf(arz,1)} mn · talep ${nf(tal,1)} mn</span><span class="st ${st[1]}">${st[0]}</span></div>`;}).join('')}
  <div class="lever" style="border:0"><span class="n">İşgücü programı</span><span class="h">${PRG.map(x=>x[0]+': '+x[1]).join(' ')}${sat(su('prg'))}</span><div class="step">${PRG.map((x,i)=>sbtn(`data-prg="${i}"`,x[0].split(' ')[0])).join('')}</div></div></div>`;}
const zorP=()=>{const z=S.dif===undefined?1:S.dif;return `<div class="panel"><b>Zorluk: ${ZN[z]}</b><div class="chips">${ZN.map((n,i)=>`<button class="btn sm ${z===i?'':'sec'}" data-dif="${i}">${n}</button>`).join('')}</div><div class="note">Aylık sürekli etki: ${z===1?'Normal seviyede ek bonus ya da ceza yok.':fxText(ZD[z])+'.'} Zorluk istediğin an değiştirilebilir; kriz olasılığını da etkiler.</div></div>`;};
function cmdP(){const k=S.pz?S.pz.kn:0,nt=typeof notL==='function'?notL(k):'',l=TERM-S.month%TERM,b=(n,v,s,go)=>`<button class="ag" data-go="${go}" style="display:block;border:1px solid var(--line);border-radius:8px;padding:6px 7px;text-align:left"><small style="display:block;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;font-size:9.5px">${n}</small><b style="font-size:17px;font-family:var(--display)">${v}</b><small style="display:block;color:var(--muted);font-size:10px">${s}</small></button>`;
  return `<div class="panel" style="margin-bottom:8px;padding:8px"><b>Komuta masası</b><div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px;margin-top:6px">${b('Bütçe','%'+nf(S.acik,1),'açık/GSYH','butce')}${b('Seçim',l+' ay','destek %'+nf(S.des,0),'donem')}${b('Piyasa',nt||'-','borsa '+nf(S.pz?S.pz.b:0,0),'piyasa')}${b('Ordu',nf(gucu(),0),'savaş gücü','askeri')}</div></div>`;}
function kabP(){const ms=Object.entries(S.M),av=ms.reduce((a,[k,m])=>a+m.sk,0)/ms.length,rk=ms.filter(([k,m])=>m.gv!==undefined&&m.gv<35).length,zy=ms.filter(([k,m])=>m.sk<5).length;
  return `<div class="panel"><b>Kabine özeti</b><div class="dl" style="display:flex;justify-content:space-between"><span>Ortalama yetkinlik</span><span>${nf(av,1)}/10</span></div><div class="dl" style="display:flex;justify-content:space-between"><span>Riskli (güven&lt;35) · zayıf (yetkinlik&lt;5)</span><span>${rk} · ${zy}</span></div><div class="note">Ortalama yetkinlik 6 üstündeyse büyüme artar ve bütçe açığı küçülür; altındaysa tersi (aylık ${nf((av-6)*.012,3)} büyüme).</div><div class="step" style="margin-top:6px">${sbtn('data-kauto="1"','Tümünü otomatik düzelt',!rk&&!zy)}</div></div>`;}
