/* ---------- Lobiler ayrıntısı: talepler, kuruluşlar, ödünler, geçmiş ---------- */
/* Kuruluş adları gerçek; tutumları ve eylemleri kurgusaldır. [ad, eğilim, olumsuz eylem, etkisi, olumlu eylem, etkisi] */
const LS={sen:[['Türk-İş',8,'miting düzenledi',{huz:-.12,des:-.15},'toplu sözleşmede uzlaştı',{des:.2,huz:.05}],['Hak-İş',20,'kamuoyuna eleştiri yöneltti',{des:-.1},'hükümete destek verdi',{des:.3}],['DİSK',-22,'iş bırakma eylemi yaptı',{buy:-.1,huz:-.2,des:-.15},'ortak açıklama yaptı',{des:.1}],['KESK',-18,'kamu iş bırakması yaptı',{huz:-.1,des:-.15},'uzlaşı açıklaması yaptı',{des:.1}]],
 isv:[['TÜSİAD',-6,'eleştirel bir rapor yayımladı',{des:-.15,bat:-.05},'reform önerilerini destekledi',{buy:.1,bat:.05}],['MÜSİAD',16,'temkinli bir açıklama yaptı',{des:-.05},'yatırım çağrısı yaptı',{buy:.12,des:.15}],['TOBB',6,'sorunları açıkça dile getirdi',{des:-.1},'hükümetle ortak toplantı yaptı',{buy:.08}],['Esnaf ve sanatkâr odaları',4,'fiyat ve kredi şikâyetiyle kepenk kapattı',{des:-.15,huz:-.05},'desteklerden memnuniyet bildirdi',{des:.15}]],
 oda:[['TMMOB',-14,'dava açtı ve rapor yayımladı',{des:-.1,bat:-.05},'ortak teknik çalışma yaptı',{des:.08}],['Barolar birliği',-10,'hukuk çağrısıyla açıklama yaptı',{bat:-.1,des:-.08},'yargı reformunu destekledi',{bat:.12}],['Tabip odaları',-8,'sağlık sistemi için uyarı yaptı',{des:-.12},'sağlık politikasını destekledi',{des:.12}],['Ticaret ve sanayi odaları',8,'ekonomi politikasını eleştirdi',{des:-.08},'ihracat çağrısı yaptı',{buy:.08}]],
 stk:[['İnsan hakları dernekleri',-12,'uluslararası rapor yayımladı',{bat:-.12,des:-.05},'ortak çalıştaya katıldı',{bat:.1}],['Çevre platformları',-6,'eylem ve imza kampanyası başlattı',{huz:-.08,des:-.08},'çevre projesine destek verdi',{des:.1}],['Eğitim ve gençlik dernekleri',4,'öğrenci buluşması düzenledi',{huz:-.06},'gençlik programına katıldı',{des:.1,huz:.05}],['Kadın dernekleri',-2,'yürüyüş düzenledi',{huz:-.08,des:-.05},'ortak kampanya yaptı',{des:.1,huz:.05}]],
 vak:[['Dini vakıflar',14,'çağrı bildirisi yayımladı',{des:-.12},'hükümetin yanında durdu',{des:.25,huz:.05}],['Hayır kurumları',8,'yardım dağıtımını yavaşlattı',{huz:-.1},'yardım seferberliği başlattı',{huz:.12,des:.1}],['Eğitim vakıfları',2,'burs programını durdurdu',{des:-.08},'burs programı duyurdu',{des:.1}],['Gençlik vakıfları',6,'ortak etkinliklerden çekildi',{des:-.08},'gençlik etkinliği düzenledi',{des:.1}]]};
/* Lobi eylemleri: [ad, metin, süre (ay), aylık etki, tutum eşiği: bu değerin altındaysa olası] */
const EY={sen:[['Uyarı grevi','uyarı grevi yaptı',1,{buy:-.12,huz:-.15,des:-.2},-35],['Miting ve yürüyüş','büyük bir miting düzenledi',1,{huz:-.25,des:-.3},-40],['Genel grev','genel greve gitti',2,{buy:-.35,huz:-.35,des:-.45,isz:.1},-55]],
 isv:[['Kamuoyuna rapor','hükümeti eleştiren bir rapor yayımladı',1,{des:-.25,bat:-.05},-30],['Yatırım erteleme','yatırım kararlarını erteledi',2,{buy:-.25,isz:.12,des:-.15},-35],['Sermaye transferi','sermaye çıkışı sinyali verdi',2,{buy:-.3,rez:-.8,des:-.2},-55]],
 oda:[['Ortak basın açıklaması','ortak açıklamayla hükümeti eleştirdi',1,{des:-.25,bat:-.08},-30],['Dava ve bilirkişi raporu','yargıya başvurdu ve rapor yayımladı',2,{des:-.2,par:-.05,bat:-.1},-40],['İş bırakma ve yürüyüş','iş bırakıp yürüdü',1,{huz:-.25,des:-.3,bat:-.1},-55]],
 stk:[['İmza kampanyası','imza kampanyası başlattı',2,{des:-.1,huz:-.05},-30],['Uluslararası başvuru','uluslararası kuruluşlara başvurdu',2,{bat:-.2,des:-.1},-40],['Sokak eylemi','sokak eylemleri düzenledi',1,{huz:-.25,des:-.15},-50]],
 vak:[['Destek çekme sinyali','desteğini çekme sinyali verdi',2,{huz:-.15,des:-.15},-30],['Kamuoyu çağrısı','hükümete açık çağrı yaptı',1,{des:-.25},-40],['Yardım boykotu','yardım kampanyalarını durdurdu',2,{huz:-.25,des:-.2},-55]]};
/* Olumlu eylemler (tutum 45 üstünde, anlık etki) */
const ES={sen:['Destek açıklaması','hükümet politikalarına destek verdi',{des:.5,huz:.1}],isv:['Yatırım duyurusu','büyük bir yatırım paketi duyurdu',{buy:.2,isz:-.1,des:.2}],oda:['Ortak çalıştay','hükümetle ortak bir çalıştay düzenledi',{bat:.15,des:.2}],stk:['Ortak kampanya','hükümetle ortak bir toplum kampanyası yaptı',{huz:.15,bat:.1}],vak:['Destek kampanyası','hükümet yanlısı bir yardım kampanyası başlattı',{huz:.15,des:.3}]};
/* Oyuncunun özel eylemleri: [ad, açıklama, etki, tutum, bekleme (ay), özel] */
const LX={sen:[['Asgari ücrete ara zam','Asgari ücret %5 artar.',{acik:.15,enf:.1,des:.3},16,12,'minw'],['Sendikal haklar reformu','Örgütlenme kolaylaşır, etki gücü +8.',{huz:.1,des:.2,acik:.05},12,12,'pw']],
 isv:[['Vergi ve prim yapılandırması','Borçlar yapılandırılır.',{acik:.25,des:-.2,buy:.1},20,12],['Ortak yatırım toplantısı','Sanayiyle yatırım yol haritası.',{buy:.15,acik:.05},10,6]],
 oda:[['Taslağı görüşe aç','Yasa taslakları odalara sunulur.',{par:-.1,bat:.15},12,6],['Bağımsız rapor iste','Sektör raporları istenir.',{des:.1,acik:.03},10,4]],
 stk:[['Ortak sosyal proje','STK ile ortak proje yürütülür.',{huz:.15,acik:.05},12,6],['Kamu spotu iş birliği','Kampanya desteklenir.',{des:.15,huz:.05},10,4]],
 vak:[['Sosyal yardım ortaklığı','Vakıflar yardım dağıtır.',{acik:.08,huz:.15,des:.15},14,8],['Bayram etkinlikleri','Ortak etkinlikler düzenlenir.',{des:.2},10,4]]};
const eyFx=(l,o)=>o.ea!==undefined&&EY[l[0]][o.ea]?EY[l[0]][o.ea][3]:l[3];
function eyPick(id,o){const v=EY[id].map((e,i)=>[...e.slice(0,4),i,e[4]]).filter(e=>o.t<=e[5]),w=v.length>1&&o.t<-55&&Math.random()<.5?v[v.length-1]:v[Math.floor(Math.random()*v.length)];return w||[...EY[id][0].slice(0,4),0];}
/* her ay: kuruluşların bireysel eylemleri ve lobinin olumlu eylemleri */
function lobiUp(){const h=[];LB.forEach(l=>{const id=l[0],o=S.lb[id];LS[id].forEach((s,i)=>{const t=clamp(o.t+s[1]+o.sj[i],-100,100);
    if(t<-40&&Math.random()<.05){applyFx(s[3]);lbLg(o,s[0]+' '+s[2]);h.push(`${s[0]} ${s[2]}.`);}else if(t>40&&Math.random()<.04){applyFx(s[5]);lbLg(o,s[0]+' '+s[4]);h.push(`${s[0]} ${s[4]}.`);}});
  if(o.t>45&&o.ey<=0&&Math.random()<.1){const e=ES[id];applyFx(e[2]);lbLg(o,e[0]);h.push(`${l[1]} ${e[1]}.`);}});return h;}
function lobiX(code){const [id,a]=code.split(':'),o=S.lb[id],l=LB.find(x=>x[0]===id),use=(k,c)=>{if((o.cd[k]||0)>S.month)return false;o.cd[k]=S.month+c;return true;};
  if(a[0]==='x'){const x=LX[id][+a[1]];if(!x||!use(a,x[4]))return true;applyFx(x[2]);o.t=clamp(o.t+x[3],-100,100);if(x[5]==='minw')S.minw=Math.round(S.minw*1.05);if(x[5]==='pw')o.pw=clamp(o.pw+8,10,90);lbLg(o,x[0]);logA('Lobiler',l[1],x[0]+' uygulandı.');}
  else if(a==='b'){if(o.ey<=0||!use('b',8))return true;o.ey=0;o.t=clamp(o.t-15,-100,100);applyFx({huz:-.4,bat:-.15});lbLg(o,'Eylem bastırıldı');logA('Lobiler',l[1],'Eylem bastırıldı: tutum −15, huzur ve itibar zarar gördü.');}
  else{const i=+a[1],s=LS[id][i];if(!s||!use(a,4))return true;o.sj[i]=clamp(o.sj[i]+10,-25,25);o.t=clamp(o.t+2,-100,100);lbLg(o,s[0]+' ile görüşüldü');logA('Lobiler',s[0],'Görüşme yapıldı.');}
  hap(20,520);save();render();return true;}
/* Talepler: [metin, karşılandı mı, şimdiki değer]. Karşılanan her talep tutum hedefini yükseltir, karşılanmayan düşürür. */
const LD={sen:[['Reel asgari ücret korunsun',()=>S.minw/28075/(S.cpi/100)>=.97,()=>'%'+nf(S.minw/28075/(S.cpi/100)*100,0)],['İşsizlik %9\'un altında olsun',()=>S.isz<9,()=>'%'+nf(S.isz,1)],['Kamu çalışanları memnun olsun',()=>S.gr.kamu>=50,()=>nf(S.gr.kamu,0)],['Emekliler memnun olsun',()=>S.gr.emekli>=50,()=>nf(S.gr.emekli,0)]],
 isv:[['Faiz %40\'ın altına insin',()=>S.lv.faiz<40,()=>'%'+nf(S.lv.faiz,1)],['Büyüme %3 ve üstü olsun',()=>S.buy>=3,()=>'%'+nf(S.buy,1)],['Enflasyon %30\'un altına insin',()=>S.enf<30,()=>'%'+nf(S.enf,1)],['Kredi notu BB+ ve üstü olsun',()=>S.pz.kn>=56,()=>notL(S.pz.kn)]],
 oda:[['Yolsuzluk algısı 40\'ın altında olsun',()=>S.bu.yz<40,()=>nf(S.bu.yz,0)],['Batı ile itibar korunsun',()=>S.bat>=5,()=>nf(S.bat,1)+'/10'],['Adalet bütçesi korunsun',()=>rb('adalet')>=0,()=>(rb('adalet')>=0?'+':'−')+'%'+nf(Math.abs(rb('adalet'))*100,0)],['Liyakat düzeyi sıfırın altına inmesin',()=>S.bu.ly>=0,()=>(S.bu.ly>0?'+':'')+S.bu.ly]],
 stk:[['Toplumsal huzur 6 ve üstü olsun',()=>S.huz>=6,()=>nf(S.huz,1)+'/10'],['Gençler memnun olsun',()=>S.gr.genc>=50,()=>nf(S.gr.genc,0)],['Çevre bütçesi korunsun',()=>rb('cevre')>=0,()=>(rb('cevre')>=0?'+':'−')+'%'+nf(Math.abs(rb('cevre'))*100,0)],['Göç politikası insani olsun (Dengeli ve üstü)',()=>S.goc>=2,()=>GK[S.goc][0]]],
 vak:[['Muhafazakâr aileler memnun olsun',()=>S.gr.muhaf>=55,()=>nf(S.gr.muhaf,0)],['Aile bütçesi korunsun',()=>rb('aile')>=0,()=>(rb('aile')>=0?'+':'−')+'%'+nf(Math.abs(rb('aile'))*100,0)],['Milliyetçi kesim memnun olsun',()=>S.gr.milli>=50,()=>nf(S.gr.milli,0)],['Toplumsal huzur 5 ve üstü olsun',()=>S.huz>=5,()=>nf(S.huz,1)+'/10']]};
/* Ödünler: [ad, etki, açıklama]. Tutum +18, 6 ay bekleme. */
const LO={sen:['Toplu sözleşme desteği',{acik:.15,des:.3,enf:.1},'Toplu sözleşmelere bütçeden destek.'],isv:['Yatırım teşviki',{acik:.2,buy:.15},'Vergi indirimi ve düşük faizli yatırım kredisi.'],oda:['Bağımsız denetim yetkisi',{par:-.2,bat:.2},'Kamu ihalelerine bağımsız denetim.'],stk:['Katılım platformu',{huz:.2,acik:.05},'Politikalarda danışma ve katılım mekanizması.'],vak:['Vakıflara kaynak',{acik:.1,huz:.15},'Sosyal yardım vakıflarına bütçe desteği.']};
const lbD=id=>{if(!LD[id]||!S.gr||!S.pz||!S.bu)return 0;const d=LD[id],m=d.filter(x=>x[1]()).length;return (m-d.length/2)*10;};
const lbLg=(o,t)=>{o.lg.unshift([S.month,t]);o.lg.splice(5);};
const lbSt=t=>t>=25?['Yakın','good']:t>-25?['Mesafeli','warn']:['Karşı','bad'];
function lobi(){const id=S.lbs||'sen',l=LB.find(x=>x[0]===id),o=S.lb[id],c=lbSt(o.t),dm=LD[id],met=dm.filter(x=>x[1]()).length,od=LO[id],cl=k=>(o.cd[k]||0)>S.month?(o.cd[k]-S.month)+' ay':null,sp=o.pw/60,ey=o.ey>0?(EY[id][o.ea]||[l[4],0,0,l[3]]):null,sc=f=>fxText(Object.fromEntries(Object.entries(f).map(([k,v])=>[k,v*sp]))),
  act=(n,h,code,k)=>`<div class="lever"><span class="n">${n}</span><span class="h">${h}</span><div class="step">${sbtn(`data-lb="${id}:${code}"`,cl(k)||'Yap',cl(k))}</div></div>`;
  return `<h2>Lobiler ve örgütler</h2><div class="panel">${LB.map(x=>{const p=S.lb[x[0]],q=lbSt(p.t);return `<button class="ag ${q[1]==='good'?'':q[1]}" ${x[0]===id?'style="background:var(--surface2)"':''} data-lbs="${x[0]}"><i></i><span>${x[1]}${p.ey>0?' · eylemde':''}</span><small>${q[0]} · ${nf(p.t,0)}</small></button>`;}).join('')}</div>
  <div class="panel"><b>${l[1]}</b> <span class="st ${c[1]}">${c[0]}</span>${kv('Tutum',nf(o.t,0)+' / 100')}${gbar((o.t+100)/2,c[1])}${kv('Etki gücü',nf(o.pw,0)+' / 100')}${gbar(o.pw,'warn')}
  ${ey?`<div class="dl" style="margin-top:6px"><b style="color:var(--bad)">Eylemde: ${ey[0]} · ${o.ey} ay kaldı</b><br>Aylık etki: ${sc(ey[3])}</div>`:`<div class="dl" style="margin-top:6px">${o.t<-30?'Eylem riski var: her ay %15 ihtimalle bir eylem başlatabilir.':'Şu an sakin.'}</div>`}
  <div class="note"><b>Olası eylemleri:</b> ${EY[id].map(e=>e[0]+' (tutum '+e[4]+' altı, '+e[2]+' ay)').join(' · ')}.<br><b>Yakınken yapabileceği:</b> ${ES[id][0]} (tutum 45 üstü).</div></div>
  <div class="panel"><b>Talepleri (${met}/${dm.length} karşılandı)</b>${dm.map(d=>kv((d[1]()?'✓ ':'✗ ')+d[0],`<span class="st ${d[1]()?'good':'bad'}">${d[2]()}</span>`)).join('')}<div class="note">Karşılanan her talep tutum hedefini +10, karşılanmayan −10 etkiler. Hedefe ulaşmak birkaç ay alır.</div></div>
  <div class="panel"><b>Kuruluşlar</b>${LS[id].map((s,i)=>{const t=clamp(o.t+s[1]+o.sj[i],-100,100),q=lbSt(t);return `<div class="lever"><span class="n">${s[0]} <span class="st ${q[1]}">${q[0]}</span> <span class="dl muted">${nf(t,0)}</span></span><span class="h">Sert: ${s[2]} · Yakın: ${s[4]}</span><div class="step">${sbtn(`data-lb="${id}:s${i}"`,cl('s'+i)||'Görüş',cl('s'+i))}</div></div>`;}).join('')}<div class="note">Kuruluş adları gerçektir; tutumları ve eylemleri kurgusaldır. Her biri ana tutumdan farklı davranır; tutumu −40'ın altına inen kuruluş kendi başına eylem yapabilir. Görüşme o kuruluşun tutumunu +10 artırır (4 ayda bir).</div></div>
  <div class="panel"><b>Eylemler</b>${act('Masaya otur','Tutum +14. 3 ayda bir.','m','m')}${act(od[0],od[2]+' Etki: '+fxText(od[1])+'. Tutum +18. 6 ayda bir.','o','o')}${LX[id].map((x,i)=>act(x[0],x[1]+' Etki: '+fxText(x[2])+'. Tutum +'+x[3]+'. '+x[4]+' ayda bir.','x'+i,'x'+i)).join('')}${act('Yasal düzenleme','Etki gücü −10, tutum −12, huzur −0,3. 12 ayda bir.','y','y')}${o.ey>0?act('Eylemi bastır','Eylem hemen biter. Tutum −15, huzur −0,4, itibar −0,15. 8 ayda bir.','b','b'):''}</div>
  ${o.lg.length?`<div class="panel"><b>Geçmiş</b>${o.lg.map(x=>kv(dateLabel(x[0]),x[1])).join('')}</div>`:''}
  <div class="note">Tutum; ilgili toplumsal gruplardan, işsizlikten, asgari ücretten, faizden, yolsuzluk algısından, itibardan ve taleplerin karşılanmasından oluşur.</div>`;}
