/* ---------- Lobiler ayrıntısı: talepler, kuruluşlar, ödünler, geçmiş ---------- */
/* Kuruluş adları gerçek; tutumları ve eylemleri kurgusaldır. [ad, eğilim, olumsuz eylem, etkisi, olumlu eylem, etkisi] */
const LS={sen:[['Türk-İş',8,'miting düzenledi',{huz:-.12,des:-.15},'toplu sözleşmede uzlaştı',{des:.2,huz:.05}],['Hak-İş',20,'kamuoyuna eleştiri yöneltti',{des:-.1},'hükümete destek verdi',{des:.3}],['DİSK',-22,'iş bırakma eylemi yaptı',{buy:-.1,huz:-.2,des:-.15},'ortak açıklama yaptı',{des:.1}],['KESK',-18,'kamu iş bırakması yaptı',{huz:-.1,des:-.15},'uzlaşı açıklaması yaptı',{des:.1}]],
 isv:[['TÜSİAD',-6,'eleştirel bir rapor yayımladı',{des:-.15,bat:-.05},'reform önerilerini destekledi',{buy:.1,bat:.05}],['MÜSİAD',16,'temkinli bir açıklama yaptı',{des:-.05},'yatırım çağrısı yaptı',{buy:.12,des:.15}],['TOBB',6,'sorunları açıkça dile getirdi',{des:-.1},'hükümetle ortak toplantı yaptı',{buy:.08}],['Esnaf ve sanatkâr odaları',4,'fiyat ve kredi şikâyetiyle kepenk kapattı',{des:-.15,huz:-.05},'desteklerden memnuniyet bildirdi',{des:.15}]],
 oda:[['TMMOB',-14,'dava açtı ve rapor yayımladı',{des:-.1,bat:-.05},'ortak teknik çalışma yaptı',{des:.08}],['Barolar birliği',-10,'hukuk çağrısıyla açıklama yaptı',{bat:-.1,des:-.08},'yargı reformunu destekledi',{bat:.12}],['Tabip odaları',-8,'sağlık sistemi için uyarı yaptı',{des:-.12},'sağlık politikasını destekledi',{des:.12}],['Ticaret ve sanayi odaları',8,'ekonomi politikasını eleştirdi',{des:-.08},'ihracat çağrısı yaptı',{buy:.08}]],
 stk:[['İnsan hakları dernekleri',-12,'uluslararası rapor yayımladı',{bat:-.12,des:-.05},'ortak çalıştaya katıldı',{bat:.1}],['Çevre platformları',-6,'eylem ve imza kampanyası başlattı',{huz:-.08,des:-.08},'çevre projesine destek verdi',{des:.1}],['Eğitim ve gençlik dernekleri',4,'öğrenci buluşması düzenledi',{huz:-.06},'gençlik programına katıldı',{des:.1,huz:.05}],['Kadın dernekleri',-2,'yürüyüş düzenledi',{huz:-.08,des:-.05},'ortak kampanya yaptı',{des:.1,huz:.05}]],
 vak:[['Dini vakıflar',14,'çağrı bildirisi yayımladı',{des:-.12},'hükümetin yanında durdu',{des:.25,huz:.05}],['Hayır kurumları',8,'yardım dağıtımını yavaşlattı',{huz:-.1},'yardım seferberliği başlattı',{huz:.12,des:.1}],['Eğitim vakıfları',2,'burs programını durdurdu',{des:-.08},'burs programı duyurdu',{des:.1}],['Gençlik vakıfları',6,'ortak etkinliklerden çekildi',{des:-.08},'gençlik etkinliği düzenledi',{des:.1}]]};
/* Lobi eylemleri: [ad, metin, süre (ay), aylık etki, tutum eşiği: bu değerin altındaysa olası] */
const EY={sen:[['Uyarı grevi','uyarı grevi yaptı',1,{buy:-.12,huz:-.15,des:-.2},-35],['Miting ve yürüyüş','büyük bir miting düzenledi',1,{huz:-.25,des:-.3},-40],['Genel grev','genel greve gitti',2,{buy:-.35,huz:-.35,des:-.45,isz:.1},-55]],
 isv:[['Kamuoyuna rapor','hükümeti eleştiren bir rapor yayımladı',1,{des:-.25,bat:-.05},-30],['Yatırım erteleme','yatırım kararlarını erteledi',2,{buy:-.25,isz:.12,des:-.15},-35],['Sermaye transferi','sermaye çıkışı sinyali verdi',2,{buy:-.3,rez:-.8,des:-.2},-55]],
 oda:[['Ortak basın açıklaması','ortak açıklamayla hükümeti eleştirdi',1,{des:-.25,bat:-.08},-30],['Dava ve bilirkişi raporu','yargıya başvurdu ve rapor yayımladı',2,{des:-.2,par:-.05,bat:-.1},-40],['İş bırakma ve yürüyüş','iş bırakıp yürüdü',1,{huz:-.25,des:-.3,bat:-.1},-55]],
 stk:[['İmza kampanyası','imza kampanyası başlattı',2,{des:-.1,huz:-.05},-30],['Uluslararası başvuru','uluslararası kuruluşlara başvurdu',2,{bat:-.2,des:-.1},-40],['Sokak eylemi','sokak eylemleri düzenledi',1,{huz:-.25,des:-.15},-50]],
 vak:[['Destek çekme sinyali','desteğini çekme sinyali verdi',2,{huz:-.15,des:-.15},-30],['Kamuoyu çağrısı','hükümete açık çağrı yaptı',1,{des:-.25},-40],['Yardım boykotu','yardım kampanyalarını durdurdu',2,{huz:-.25,des:-.2},-55]]};
/* Olumlu eylemler (tutum 45 üstünde, anlık etki) */
const ES={sen:['Destek açıklaması','hükümet politikalarına destek verdi',{des:.5,huz:.1}],isv:['Yatırım duyurusu','büyük bir yatırım paketi duyurdu',{buy:.2,isz:-.1,des:.2}],oda:['Ortak çalıştay','hükümetle ortak bir çalıştay düzenledi',{bat:.15,des:.2}],stk:['Ortak kampanya','hükümetle ortak bir toplum kampanyası yaptı',{huz:.15,bat:.1}],vak:['Destek kampanyası','hükümet yanlısı bir yardım kampanyası başlattı',{huz:.15,des:.3}]};
const eyFx=(l,o)=>o.ea!==undefined&&EY[l[0]][o.ea]?EY[l[0]][o.ea][3]:l[3];
function eyPick(id,o){const v=EY[id].map((e,i)=>[...e.slice(0,4),i,e[4]]).filter(e=>o.t<=e[5]),w=v.length>1&&o.t<-55&&Math.random()<.5?v[v.length-1]:v[Math.floor(Math.random()*v.length)];return w||[...EY[id][0].slice(0,4),0];}
/* her ay: kuruluşların bireysel eylemleri ve lobinin olumlu eylemleri */
function lobiUp(){const h=[];LB.forEach(l=>{const id=l[0],o=S.lb[id];LS[id].forEach((s,i)=>{const t=clamp(o.t+s[1]+o.sj[i],-100,100);
    if(t<-40&&Math.random()<.05){applyFx(s[3]);lbLg(o,s[0]+' '+s[2]);h.push(`${s[0]} ${s[2]}.`);}else if(t>40&&Math.random()<.04){applyFx(s[5]);lbLg(o,s[0]+' '+s[4]);h.push(`${s[0]} ${s[4]}.`);}});
  if(o.t>45&&o.ey<=0&&Math.random()<.1){const e=ES[id];applyFx(e[2]);lbLg(o,e[0]);h.push(`${l[1]} ${e[1]}.`);}});return h;}
/* Talepler: [metin, karşılandı mı, şimdiki değer]. Karşılanan her talep tutum hedefini yükseltir, karşılanmayan düşürür. */
const LD={sen:[['Reel asgari ücret korunsun',()=>S.minw/28075/(S.cpi/100)>=.97,()=>'%'+nf(S.minw/28075/(S.cpi/100)*100,0)],['İşsizlik %9\'un altında olsun',()=>S.isz<9,()=>'%'+nf(S.isz,1)],['Kamu çalışanları memnun olsun',()=>S.gr.kamu>=50,()=>nf(S.gr.kamu,0)],['Emekliler memnun olsun',()=>S.gr.emekli>=50,()=>nf(S.gr.emekli,0)]],
 isv:[['Faiz %40\'ın altına insin',()=>S.lv.faiz<40,()=>'%'+nf(S.lv.faiz,1)],['Büyüme %3 ve üstü olsun',()=>S.buy>=3,()=>'%'+nf(S.buy,1)],['Enflasyon %30\'un altına insin',()=>S.enf<30,()=>'%'+nf(S.enf,1)],['Kredi notu BB+ ve üstü olsun',()=>S.pz.kn>=56,()=>notL(S.pz.kn)]],
 oda:[['Yolsuzluk algısı 40\'ın altında olsun',()=>S.bu.yz<40,()=>nf(S.bu.yz,0)],['Batı ile itibar korunsun',()=>S.bat>=5,()=>nf(S.bat,1)+'/10'],['Adalet bütçesi korunsun',()=>rb('adalet')>=0,()=>(rb('adalet')>=0?'+':'−')+'%'+nf(Math.abs(rb('adalet'))*100,0)],['Liyakat düzeyi sıfırın altına inmesin',()=>S.bu.ly>=0,()=>(S.bu.ly>0?'+':'')+S.bu.ly]],
 stk:[['Toplumsal huzur 6 ve üstü olsun',()=>S.huz>=6,()=>nf(S.huz,1)+'/10'],['Gençler memnun olsun',()=>S.gr.genc>=50,()=>nf(S.gr.genc,0)],['Çevre bütçesi korunsun',()=>rb('cevre')>=0,()=>(rb('cevre')>=0?'+':'−')+'%'+nf(Math.abs(rb('cevre'))*100,0)],['Göç politikası insani olsun (Seçici ve üstü)',()=>S.goc>=2,()=>GK[S.goc][0]]],
 vak:[['Muhafazakâr aileler memnun olsun',()=>S.gr.muhaf>=55,()=>nf(S.gr.muhaf,0)],['Aile bütçesi korunsun',()=>rb('aile')>=0,()=>(rb('aile')>=0?'+':'−')+'%'+nf(Math.abs(rb('aile'))*100,0)],['Milliyetçi kesim memnun olsun',()=>S.gr.milli>=50,()=>nf(S.gr.milli,0)],['Toplumsal huzur 5 ve üstü olsun',()=>S.huz>=5,()=>nf(S.huz,1)+'/10']]};
const lbD=id=>{if(!LD[id]||!S.gr||!S.pz||!S.bu)return 0;const d=LD[id],m=d.filter(x=>x[1]()).length;return (m-d.length/2)*10;};
const lbLg=(o,t)=>{o.lg.unshift([S.month,t]);o.lg.splice(5);};
const lbSt=t=>t>=25?['Yakın','good']:t>-25?['Mesafeli','warn']:['Karşı','bad'];
/* Görüşme konuları: [ad, açıklama, birimler, etiket (% ya da Sınırlı/Orta/Geniş), birim başına etki, birim başına tutum, özel etki].
   Seçilen birim büyüdükçe etki, maliyet ve tutum kazancı orantılı artar. */
const LT={sen:[['Asgari ücret ara zammı','Yıl ortasında ara zam. Gelir artar; enflasyon ve bütçe baskısı doğar.',[4,8,12],'%',{acik:.03,enf:.025,des:.04},.9,'minw'],['Kamu maaş artışı','Kamu çalışanlarına ek zam.',[5,10,15],'%',{acik:.035,des:.02},.8,'kamu'],['Emekli aylığı artışı','Emekli aylıkları artırılır.',[5,10,15],'%',{acik:.03,des:.03},.7,'emekli'],['İstihdam paketi','Kamu alımı ve işe alım teşviki.',[1,2,3],'s',{isz:-.07,acik:.1,buy:.03},4],['Sendikal haklar','Örgütlenme ve toplu pazarlık hakları genişler; sendikaların gücü artar.',[1,2,3],'s',{huz:.05,des:.08,acik:.02},5,'pw']],
 isv:[['Yatırım teşviki','Vergi indirimi ve bedelsiz arsa.',[1,2,3],'s',{acik:.12,buy:.08,isz:-.03},4],['Vergi ve prim yapılandırması','Geçmiş borçlar yeniden yapılandırılır; dürüst mükellef tepkili.',[1,2,3],'s',{acik:.15,des:-.1,buy:.04},6],['Kredi ve faiz desteği','Düşük faizli yatırım kredisi.',[1,2,3],'s',{acik:.08,enf:.05,buy:.06},4.5],['İhracat desteği','Kur ve nakliye desteği.',[1,2,3],'s',{cari:-.08,acik:.06,buy:.03},4],['Ortak yatırım toplantısı','Sanayiyle yatırım yol haritası.',[1,2,3],'s',{buy:.05},3]],
 oda:[['Taslağı görüşe aç','Yasa taslakları odaların görüşüne sunulur.',[1,2,3],'s',{par:-.05,bat:.06},4],['Bağımsız denetim yetkisi','Kamu ihalelerine bağımsız denetim; yolsuzluk algısı düşer.',[1,2,3],'s',{par:-.1,bat:.1},5,'yz'],['Mesleki düzenleme','Meslek yasalarında odalar söz sahibi olur.',[1,2,3],'s',{acik:.03,des:.06},4],['Sektör raporu iste','Odalardan bağımsız sektör raporları istenir.',[1,2,3],'s',{des:.05},3]],
 stk:[['Ortak sosyal proje','STK ile ortak proje yürütülür.',[1,2,3],'s',{huz:.07,acik:.05},4],['Hibe desteği','Kamu kaynaklı hibe programı.',[1,2,3],'s',{acik:.06,des:.05},4.5],['Danışma kurulu','Politikalarda STK danışma kurulu.',[1,2,3],'s',{huz:.05,bat:.05},4],['Kamu spotu iş birliği','Ortak kamuoyu kampanyası.',[1,2,3],'s',{des:.07,acik:.02},3.5]],
 vak:[['Sosyal yardım ortaklığı','Vakıflar yardım dağıtımını yürütür.',[1,2,3],'s',{acik:.05,huz:.07,des:.06},4.5],['Burs ve yurt desteği','Öğrenci burs ve yurt programları.',[1,2,3],'s',{acik:.05,des:.06},4],['Bayram ve toplum etkinlikleri','Ortak etkinlikler düzenlenir.',[1,2,3],'s',{des:.1},3],['Vakıf kaynak aktarımı','Vakıflara doğrudan bütçe aktarımı.',[1,2,3],'s',{acik:.08,huz:.05},4]]};
/* Görüşme biçimi: [ad, açıklama, tutum, ek etki] */
const LM=[['Kısa görüşme','Yöneticilerle kısa görüşme.',5,{}],['Heyet toplantısı','Bakanlık heyetiyle uzun toplantı.',10,{des:.03}],['Zirve','Liderlerle zirve; parti içinde yankı yapar.',16,{des:.06,par:-.05}]];
/* Yasal düzenleme: [ad, açıklama, etki gücü −, tutum −, huzur −] */
const LY=[['Bildirim zorunluluğu','Eylem öncesi bildirim şartı.',6,8,0],['Eylem sınırlaması','Eylem yeri ve süresine sınırlama.',12,14,.15],['Kapsamlı kısıtlama','Geniş yasal kısıtlamalar; büyük tepki çeker.',20,24,.4]];
/* Kuruluşla iletişim: [ad, açıklama, puan, ek etki] */
const SM=[['Açıklama','Kamuoyuna olumlu açıklama.',4,{}],['Görüşme','Yüz yüze görüşme.',9,{des:.02}],['Proje','Ortak proje yürütülür.',14,{acik:.05,huz:.03}]];
const lbU=(x,j)=>x[3]==='%'?'%'+x[2][j]:['Sınırlı','Orta','Geniş'][j];
function lobiX(code){const [id,a]=code.split(':'),o=S.lb[id],l=LB.find(x=>x[0]===id),k=a[0],[i,j]=a.slice(1).split('.').map(Number),T=v=>clamp(v,-100,100);
  if(k==='m'){const x=LM[i],m=su('lm'+id);applyFx(sfx2(x[3],m));o.t=T(o.t+x[2]*m);suU('lm'+id);lbLg(o,x[0]);logA('Lobiler',l[1],x[0]+': tutum +'+nf(x[2]*m,0)+'.');}
  else if(k==='t'){const x=LT[id][i],u=x[2][j],m=su('lt'+id+i),h=x[6];applyFx(sfx2(x[4],u*m));o.t=T(o.t+x[5]*u*m);
    if(h==='minw'){S.minw=Math.round(S.minw*(1+u*m/100));applyFx({enf:.05*u*m});S.gr.ucret=clamp(S.gr.ucret+u*m*.5,0,100);}else if(h==='kamu'){S.gb.kamu=clamp((S.gb.kamu||0)+u*m*.4,-30,30);S.gr.kamu=clamp(S.gr.kamu+u*m*.3,0,100);}else if(h==='emekli'){S.gb.emekli=clamp((S.gb.emekli||0)+u*m*.5,-30,30);S.gr.emekli=clamp(S.gr.emekli+u*m*.3,0,100);}else if(h==='pw')o.pw=clamp(o.pw+3*u*m,10,90);else if(h==='yz')S.bu.yz=clamp(S.bu.yz-3*u*m,0,100);
    suU('lt'+id+i);lbLg(o,x[0]+' ('+lbU(x,j)+')');logA('Lobiler',l[1],x[0]+' ('+lbU(x,j)+'): tutum +'+nf(x[5]*u*m,0)+'.');}
  else if(k==='y'){const x=LY[i],m=su('ly'+id);suU('ly'+id);o.pw=clamp(o.pw-x[2]*m,10,90);o.t=T(o.t-x[3]*m);applyFx({huz:-x[4]});lbLg(o,x[0]);logA('Lobiler',l[1],x[0]+' getirildi.');}
  else if(k==='b'){if(o.ey<=0)return true;o.ey=0;if(i===0){o.t=T(o.t+4);applyFx({acik:.12});lbLg(o,'Eylem müzakereyle bitirildi');}else{o.t=T(o.t-15);applyFx({huz:-.4,bat:-.15});lbLg(o,'Eylem bastırıldı');}logA('Lobiler',l[1],'Eylem sona erdirildi.');}
  else{const s=LS[id][i],x=SM[j],m=su('ls'+id+i);o.sj[i]=clamp(o.sj[i]+x[2]*m,-25,25);o.t=T(o.t+x[2]*.25*m);applyFx(sfx2(x[3],m));suU('ls'+id+i);lbLg(o,s[0]+': '+x[0]);logA('Lobiler',s[0],x[0]+' yapıldı.');}
  hap(20,520);save();render();return true;}
function lobi(){const id=S.lbs||'sen',l=LB.find(x=>x[0]===id),o=S.lb[id],c=lbSt(o.t),dm=LD[id],met=dm.filter(x=>x[1]()).length,sp=o.pw/60,ey=o.ey>0?(EY[id][o.ea]||[l[4],0,0,l[3]]):null,sc=f=>fxText(Object.fromEntries(Object.entries(f).map(([k,v])=>[k,v*sp]))),
  btn=(code,txt)=>sbtn(`data-lb="${id}:${code}"`,txt),lv=(n,h,b)=>`<div class="lever"><span class="n">${n}</span><span class="h">${h}</span><div class="step">${b}</div></div>`;
  return `<h2>Lobiler ve örgütler</h2><div class="panel">${LB.map(x=>{const p=S.lb[x[0]],q=lbSt(p.t);return `<button class="ag ${q[1]==='good'?'':q[1]}" ${x[0]===id?'style="background:var(--surface2)"':''} data-lbs="${x[0]}"><i></i><span>${x[1]}${p.ey>0?' · eylemde':''}</span><small>${q[0]} · ${nf(p.t,0)}</small></button>`;}).join('')}</div>
  <div class="panel"><b>${l[1]}</b> <span class="st ${c[1]}">${c[0]}</span>${kv('Tutum',nf(o.t,0)+' / 100')}${gbar((o.t+100)/2,c[1])}${kv('Etki gücü',nf(o.pw,0)+' / 100')}${gbar(o.pw,'warn')}
  ${ey?`<div class="dl" style="margin-top:6px"><b style="color:var(--bad)">Eylemde: ${ey[0]} · ${o.ey} ay kaldı</b><br>Aylık etki: ${sc(ey[3])}</div>`:`<div class="dl" style="margin-top:6px">${o.t<-30?'Eylem riski var: her ay %15 ihtimalle bir eylem başlatabilir.':'Şu an sakin.'}</div>`}
  <div class="note"><b>Olası eylemleri:</b> ${EY[id].map(e=>e[0]+' (tutum '+e[4]+' altı, '+e[2]+' ay)').join(' · ')}.<br><b>Yakınken yapabileceği:</b> ${ES[id][0]} (tutum 45 üstü).</div></div>
  <div class="panel"><b>Talepleri (${met}/${dm.length} karşılandı)</b>${dm.map(d=>kv((d[1]()?'✓ ':'✗ ')+d[0],`<span class="st ${d[1]()?'good':'bad'}">${d[2]()}</span>`)).join('')}<div class="note">Karşılanan her talep tutum hedefini +10, karşılanmayan −10 etkiler. Hedefe ulaşmak birkaç ay alır.</div></div>
  <div class="panel"><b>Görüşme konuları</b>${LT[id].map((x,i)=>lv(x[0],x[1]+' Orta seçenekte: '+fxText(sfx2(x[4],x[2][1]))+'; tutum +'+nf(x[5]*x[2][1],0)+'.'+sat(su('lt'+id+i)),x[2].map((u,j)=>btn(`t${i}.${j}`,lbU(x,j))).join(''))).join('')}<div class="note">Seçenek büyüdükçe etki, maliyet ve tutum kazancı artar. Bekleme süresi yoktur; aynı konuyu üst üste yapmak etkiyi azaltır, her ay %25 toparlanır.</div></div>
  <div class="panel"><b>Görüşme biçimi</b>${lv('Lobiyle görüşme',LM.map(x=>x[0]+' (+'+x[2]+'): '+x[1]).join(' ')+sat(su('lm'+id)),LM.map((x,i)=>btn('m'+i,x[0])).join(''))}${lv('Yasal düzenleme',LY.map(x=>x[0]+' (güç −'+x[2]+', tutum −'+x[3]+')').join(' · ')+'.',LY.map((x,i)=>btn('y'+i,x[0].split(' ')[0])).join(''))}${o.ey>0?lv('Eylemi sonlandır','Müzakereyle bitirmek bütçeye yük olur, tutumu +4 artırır. Bastırmak tutumu −15 düşürür, huzur ve itibar zarar görür.',btn('b0','Müzakere')+btn('b1','Bastır')):''}</div>
  <div class="panel"><b>Kuruluşlar</b>${LS[id].map((s,i)=>{const t=clamp(o.t+s[1]+o.sj[i],-100,100),q=lbSt(t);return lv(`${s[0]} <span class="st ${q[1]}">${q[0]}</span> <span class="dl muted">${nf(t,0)}</span>`,'Sert: '+s[2]+' · Yakın: '+s[4]+sat(su('ls'+id+i)),SM.map((x,j)=>btn(`s${i}.${j}`,x[0])).join(''));}).join('')}<div class="note">Kuruluş adları gerçektir; tutumları ve eylemleri kurgusaldır. Tutumu −40'ın altına inen kuruluş kendi başına eylem yapabilir. Açıklama +4, görüşme +9, ortak proje +14 puan verir (proje bütçeye yük olur).</div></div>
  ${o.lg.length?`<div class="panel"><b>Geçmiş</b>${o.lg.map(x=>kv(dateLabel(x[0]),x[1])).join('')}</div>`:''}
  <div class="note">Tutum; ilgili toplumsal gruplardan, işsizlikten, asgari ücretten, faizden, yolsuzluk algısından, itibardan ve taleplerin karşılanmasından oluşur.</div>`;}
