/* ---------- Lobiler ayrıntısı: talepler, kuruluşlar, ödünler, geçmiş ---------- */
/* Kuruluş adları gerçek; tutumları ve eylemleri kurgusaldır. [ad, eğilim (ana tutuma eklenir)] */
const LS={sen:[['Türk-İş',8],['Hak-İş',20],['DİSK',-22],['KESK',-18]],isv:[['TÜSİAD',-6],['MÜSİAD',16],['TOBB',6],['Esnaf ve sanatkâr odaları',4]],oda:[['TMMOB',-14],['Barolar birliği',-10],['Tabip odaları',-8],['Ticaret ve sanayi odaları',8]],stk:[['İnsan hakları dernekleri',-12],['Çevre platformları',-6],['Eğitim ve gençlik dernekleri',4],['Kadın dernekleri',-2]],vak:[['Dini vakıflar',14],['Hayır kurumları',8],['Eğitim vakıfları',2],['Gençlik vakıfları',6]]};
/* Talepler: [metin, karşılandı mı, şimdiki değer]. Karşılanan her talep tutum hedefini yükseltir, karşılanmayan düşürür. */
const LD={sen:[['Reel asgari ücret korunsun',()=>S.minw/28075/(S.cpi/100)>=.97,()=>'%'+nf(S.minw/28075/(S.cpi/100)*100,0)],['İşsizlik %9\'un altında olsun',()=>S.isz<9,()=>'%'+nf(S.isz,1)],['Kamu çalışanları memnun olsun',()=>S.gr.kamu>=50,()=>nf(S.gr.kamu,0)],['Emekliler memnun olsun',()=>S.gr.emekli>=50,()=>nf(S.gr.emekli,0)]],
 isv:[['Faiz %40\'ın altına insin',()=>S.lv.faiz<40,()=>'%'+nf(S.lv.faiz,1)],['Büyüme %3 ve üstü olsun',()=>S.buy>=3,()=>'%'+nf(S.buy,1)],['Enflasyon %30\'un altına insin',()=>S.enf<30,()=>'%'+nf(S.enf,1)],['Kredi notu BB+ ve üstü olsun',()=>S.pz.kn>=56,()=>notL(S.pz.kn)]],
 oda:[['Yolsuzluk algısı 40\'ın altında olsun',()=>S.bu.yz<40,()=>nf(S.bu.yz,0)],['Batı ile itibar korunsun',()=>S.bat>=5,()=>nf(S.bat,1)+'/10'],['Adalet bütçesi korunsun',()=>rb('adalet')>=0,()=>(rb('adalet')>=0?'+':'−')+'%'+nf(Math.abs(rb('adalet'))*100,0)],['Liyakat düzeyi sıfırın altına inmesin',()=>S.bu.ly>=0,()=>(S.bu.ly>0?'+':'')+S.bu.ly]],
 stk:[['Toplumsal huzur 6 ve üstü olsun',()=>S.huz>=6,()=>nf(S.huz,1)+'/10'],['Gençler memnun olsun',()=>S.gr.genc>=50,()=>nf(S.gr.genc,0)],['Çevre bütçesi korunsun',()=>rb('cevre')>=0,()=>(rb('cevre')>=0?'+':'−')+'%'+nf(Math.abs(rb('cevre'))*100,0)],['Göç politikası insani olsun (Dengeli ve üstü)',()=>S.goc>=2,()=>GK[S.goc][0]]],
 vak:[['Muhafazakâr aileler memnun olsun',()=>S.gr.muhaf>=55,()=>nf(S.gr.muhaf,0)],['Aile bütçesi korunsun',()=>rb('aile')>=0,()=>(rb('aile')>=0?'+':'−')+'%'+nf(Math.abs(rb('aile'))*100,0)],['Milliyetçi kesim memnun olsun',()=>S.gr.milli>=50,()=>nf(S.gr.milli,0)],['Toplumsal huzur 5 ve üstü olsun',()=>S.huz>=5,()=>nf(S.huz,1)+'/10']]};
/* Ödünler: [ad, etki, açıklama]. Tutum +18, 6 ay bekleme. */
const LO={sen:['Toplu sözleşme desteği',{acik:.15,des:.3,enf:.1},'Toplu sözleşmelere bütçeden destek.'],isv:['Yatırım teşviki',{acik:.2,buy:.15},'Vergi indirimi ve düşük faizli yatırım kredisi.'],oda:['Bağımsız denetim yetkisi',{par:-.2,bat:.2},'Kamu ihalelerine bağımsız denetim.'],stk:['Katılım platformu',{huz:.2,acik:.05},'Politikalarda danışma ve katılım mekanizması.'],vak:['Vakıflara kaynak',{acik:.1,huz:.15},'Sosyal yardım vakıflarına bütçe desteği.']};
const lbD=id=>{if(!LD[id]||!S.gr||!S.pz||!S.bu)return 0;const d=LD[id],m=d.filter(x=>x[1]()).length;return (m-d.length/2)*10;};
const lbLg=(o,t)=>{o.lg.unshift([S.month,t]);o.lg.splice(5);};
const lbSt=t=>t>=25?['Yakın','good']:t>-25?['Mesafeli','warn']:['Karşı','bad'];
function lobi(){const id=S.lbs||'sen',l=LB.find(x=>x[0]===id),o=S.lb[id],c=lbSt(o.t),dm=LD[id],met=dm.filter(x=>x[1]()).length,od=LO[id],cl=k=>(o.cd[k]||0)>S.month?(o.cd[k]-S.month)+' ay':null,sp=o.pw/60;
  return `<h2>Lobiler ve örgütler</h2><div class="panel">${LB.map(x=>{const p=S.lb[x[0]],q=lbSt(p.t);return `<button class="ag ${q[1]==='good'?'':q[1]}" ${x[0]===id?'style="background:var(--surface2)"':''} data-lbs="${x[0]}"><i></i><span>${x[1]}${p.ey>0?' · eylemde':''}</span><small>${q[0]} · ${nf(p.t,0)}</small></button>`;}).join('')}</div>
  <div class="panel"><b>${l[1]}</b> <span class="st ${c[1]}">${c[0]}</span>${kv('Tutum',nf(o.t,0)+' / 100')}${gbar((o.t+100)/2,c[1])}${kv('Etki gücü',nf(o.pw,0)+' / 100')}${gbar(o.pw,'warn')}
  ${o.ey>0?`<div class="dl" style="margin-top:6px"><b style="color:var(--bad)">Eylemde · ${o.ey} ay kaldı</b><br>Aylık etki: ${fxText(Object.fromEntries(Object.entries(l[3]).map(([k,v])=>[k,v*sp])))}</div>`:`<div class="dl" style="margin-top:6px">${o.t<-35?'Eylem eşiğinin altında: her ay eylem riski var.':'Eylem eşiği: tutum −35 altı.'} ${o.t>=25?'Yakın olduğu için desteği: '+fxText(Object.fromEntries(Object.entries(l[5]).map(([k,v])=>[k,v*o.t/50])))+'.':''}</div>`}</div>
  <div class="panel"><b>Talepleri (${met}/${dm.length} karşılandı)</b>${dm.map(d=>kv((d[1]()?'✓ ':'✗ ')+d[0],`<span class="st ${d[1]()?'good':'bad'}">${d[2]()}</span>`)).join('')}<div class="note">Karşılanan her talep tutum hedefini +10, karşılanmayan −10 etkiler. Hedefe ulaşmak birkaç ay alır.</div></div>
  <div class="panel"><b>Kuruluşlar</b>${LS[id].map(([n,b],i)=>{const t=clamp(o.t+b+o.sj[i],-100,100),q=lbSt(t);return kv(n,`<span class="st ${q[1]}">${q[0]}</span> <span class="muted">${nf(t,0)}</span>`);}).join('')}<div class="note">Kuruluş adları gerçektir; tutumları ve eylemleri kurgusaldır. Her biri ana tutumdan biraz farklı davranır.</div></div>
  <div class="panel"><b>Eylemler</b><div class="lever"><span class="n">Masaya otur</span><span class="h">Tutum +14. 3 ayda bir.</span><div class="step">${sbtn(`data-lb="${id}:m"`,cl('m')||'Yap',cl('m'))}</div></div>
  <div class="lever"><span class="n">${od[0]}</span><span class="h">${od[2]} Etki: ${fxText(od[1])}. Tutum +18. 6 ayda bir.</span><div class="step">${sbtn(`data-lb="${id}:o"`,cl('o')||'Yap',cl('o'))}</div></div>
  <div class="lever"><span class="n">Yasal düzenleme</span><span class="h">Etki gücü −10, tutum −12, huzur −0,3. 12 ayda bir.</span><div class="step">${sbtn(`data-lb="${id}:y"`,cl('y')||'Yap',cl('y'))}</div></div></div>
  ${o.lg.length?`<div class="panel"><b>Geçmiş</b>${o.lg.map(x=>kv(dateLabel(x[0]),x[1])).join('')}</div>`:''}
  <div class="note">Tutum; ilgili toplumsal gruplardan, işsizlikten, asgari ücretten, faizden, yolsuzluk algısından, itibardan ve taleplerin karşılanmasından oluşur.</div>`;}
