/* Oyun müziği: saz, kopuz ve kam davulu (kodla üretilir, dosya yok). Ayarlar > Müzik. Duruma göre parça seçilir: sakin / orta / gergin. */
(function(){
function NB(c,d){var n=Math.floor(c.sampleRate*d),b=c.createBuffer(1,n,c.sampleRate),a=b.getChannelData(0);for(var i=0;i<n;i++)a[i]=Math.random()*2-1;return b}
function IR(c){var d=2.8,n=Math.floor(c.sampleRate*d),b=c.createBuffer(2,n,c.sampleRate);for(var ch=0;ch<2;ch++){var a=b.getChannelData(ch);for(var i=0;i<n;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/n,2.6)}return b}
/* enstrümanlar: her biri (c,out,t,...) */
function tone(c,o,f,t,d,type,g,f2,at){var x=c.createOscillator(),v=c.createGain();x.type=type||'sine';x.frequency.setValueAtTime(f,t);if(f2)x.frequency.exponentialRampToValueAtTime(f2,t+d);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+(at||.01));v.gain.exponentialRampToValueAtTime(.0001,t+d);x.connect(v).connect(o);x.start(t);x.stop(t+d+.05)}
function nz(c,o,t,d,type,fr,g,fr2){var s=c.createBufferSource();s.buffer=NB(c,d+.05);var f=c.createBiquadFilter();f.type=type;f.frequency.setValueAtTime(fr,t);if(fr2)f.frequency.exponentialRampToValueAtTime(fr2,t+d);f.Q.value=type==='bandpass'?3:.7;var v=c.createGain();v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);s.connect(f).connect(v).connect(o);s.start(t)}
function saz(c,o,f,t,g,d){d=d||.7;var x=c.createOscillator(),x2=c.createOscillator(),fl=c.createBiquadFilter(),v=c.createGain(),g2=c.createGain();x.type='sawtooth';x.frequency.value=f;x2.type='triangle';x2.frequency.value=f*2.005;g2.gain.value=.35;fl.type='lowpass';fl.frequency.setValueAtTime(4200,t);fl.frequency.exponentialRampToValueAtTime(700,t+d*.7);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.003);v.gain.exponentialRampToValueAtTime(.0001,t+d);x.connect(fl);x2.connect(g2).connect(fl);fl.connect(v).connect(o);x.start(t);x2.start(t);x.stop(t+d+.05);x2.stop(t+d+.05);nz(c,o,t,.02,'bandpass',3500,g*.4)}
function selpe(c,o,f,t,dur,g,rate){var n=Math.max(1,Math.floor(dur*rate));for(var i=0;i<n;i++)saz(c,o,f,t+i/rate,g*(i%2?.7:1),.16)}
function kopuz(c,o,f,t,g,d){d=d||.9;var x=c.createOscillator(),x2=c.createOscillator(),bp=c.createBiquadFilter(),lp=c.createBiquadFilter(),v=c.createGain(),g2=c.createGain();x.type='triangle';x.frequency.setValueAtTime(f*1.025,t);x.frequency.exponentialRampToValueAtTime(f,t+.04);x2.type='sawtooth';x2.frequency.value=f;g2.gain.value=.35;bp.type='peaking';bp.frequency.value=650;bp.gain.value=9;bp.Q.value=1.2;lp.type='lowpass';lp.frequency.setValueAtTime(1800,t);lp.frequency.exponentialRampToValueAtTime(500,t+d);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.006);v.gain.exponentialRampToValueAtTime(.0001,t+d);x.connect(bp);x2.connect(g2).connect(bp);bp.connect(lp).connect(v).connect(o);x.start(t);x2.start(t);x.stop(t+d+.05);x2.stop(t+d+.05);nz(c,o,t,.05,'bandpass',2800,g*.25)}
function kam(c,o,t,g,k){if(k==='tek'){nz(c,o,t,.09,'bandpass',2200,g*.8);tone(c,o,320,t,.1,'sine',g*.35,210)}else if(k==='jing'){for(var i=0;i<4;i++)nz(c,o,t+i*.035,.12,'bandpass',6500,g*.35)}else{tone(c,o,95,t,.38,'sine',g,52);tone(c,o,190,t,.16,'sine',g*.3,120);nz(c,o,t,.18,'bandpass',420,g*.6);nz(c,o,t+.01,.05,'highpass',3000,g*.15)}}
function roll(c,o,t,n,gap,g){for(var i=0;i<n;i++)kam(c,o,t+i*gap,g*(.5+.5*i/n),i%2?'tek':'dum')}
function strum(c,o,fs,t,g){fs.forEach(function(f,i){saz(c,o,f,t+i*.03,g,1.1)})}
function seq(l,t,s,fn){l.forEach(function(x){fn(x[1],t+x[0]*s,x[2]*s)})}
var K=[220,233.08,261.63,293.66,329.63,349.23,392,440,466.16,523.25];
var SC={kurdi:[0,1,3,5,7,8,10],hicaz:[0,1,4,5,7,8,10],ussak:[0,2,3,5,7,8,10],nihavend:[0,2,3,5,7,8,11],dorian:[0,2,3,5,7,9,10]};
function fq(r,iv,d){var o=Math.floor(d/7),i=((d%7)+7)%7;return r*Math.pow(2,(iv[i]+12*o)/12)}
var H=[[[0,.3],[.5,.2],[.75,.22]],[[0,.3],[.5,.2]],[[0,.3],[.75,.22]],[[0,.3],[.33,.18],[.66,.2]],[[0,.3],[.25,.15],[.5,.2],[.75,.15]],[[0,.32],[.5,.2],[.75,.2],[.875,.16]]];
function kamGal(c,o,b,t,s,k){if(k===0){if(b%4===0)kam(c,o,t,.32);if(b%4===2)kam(c,o,t,.16,'tek')}else if(k===1){if(b%2===0)kam(c,o,t,.34);else kam(c,o,t+s*.5,.14,'tek')}else if(k===2){if(b%4===0){kam(c,o,t,.34)}if(b%4===3)kam(c,o,t+s*.5,.24);if(b%4===1)kam(c,o,t,.12,'tek')}else{if(b%8===4)kam(c,o,t,.2,'jing');if(b%8===0)kam(c,o,t,.3)}}
function gal(o){var iv=SC[o.sc];return {bpm:o.bpm,r:o.r,sc:o.sc,f:function(c,out,b,t,s){H[o.h].forEach(function(h){kopuz(c,out,o.r,t+h[0]*s,h[1],.32)});if(b%4===3&&o.five)kopuz(c,out,fq(o.r,iv,4),t+s*.5,.2,.4);if(b%4===0)kopuz(c,out,fq(o.r*2,iv,o.mel[(b/4)%o.mel.length]),t,.24,1.2);kamGal(c,out,b,t,s,o.k)}}}

var A=110,Dd=73.42,E=82.41,G=98,TR1=[
{n:'Kam ayini',d:'Sadece kam davulu: kalp atışı gibi vuruşlar, zil sesi ve her dört ölçüde yükselen vurma.',tag:['56 bpm','kam davulu','trans'],bpm:56,f:function(c,o,b,t,s){if(b%2===0){kam(c,o,t,.55);kam(c,o,t+s*.28,.25)}if(b%8===4)kam(c,o,t,.3,'jing');if(b%16===12)roll(c,o,t,10,.09,.45)}},
{n:'Bozkır yürüyüşü',d:'Kopuzda dörtnala ritim: uzun, kısa, kısa. Üstte seyrek melodi, altta kam.',tag:['84 bpm','kopuz','dörtnala'],bpm:84,f:function(c,o,b,t,s){kopuz(c,o,110,t,.3,.4);kopuz(c,o,110,t+s*.5,.2,.3);kopuz(c,o,110,t+s*.75,.22,.3);if(b%4===0){kopuz(c,o,[220,261.63,293.66,329.63][(b/4)%4],t,.24,1.2);kam(c,o,t,.32)}if(b%4===2)kam(c,o,t,.16,'tek')}},
{n:'Saz ve şelpe',d:'Bağlama şelpe tekniğiyle kürdi dizisinde yavaş bir cümle. Altta alçak tel ve hafif davul.',tag:['72 bpm','saz','kürdi'],bpm:72,f:function(c,o,b,t,s){if(b%8===0)seq([[0,K[3],1],[1,K[4],1],[2,K[5],1],[3,K[4],1],[4,K[3],1],[5,K[2],1],[6,K[0],2]],t,s,function(f,tt,d){selpe(c,o,f,tt,d,.11,12)});if(b%4===0)saz(c,o,110,t,.2,1.8);if(b%8===0)kam(c,o,t,.28)}},
{n:'Ordu hazırlığı',d:'Ağır ve sabit kam davulu, alçak kopuz vuruşları ve saz akorlarıyla askerî gerilim.',tag:['92 bpm','kam · kopuz','yürüyüş'],bpm:92,f:function(c,o,b,t,s){kam(c,o,t,.5);if(b%2===1)kam(c,o,t+s*.5,.16,'tek');if(b%2===0)kopuz(c,o,110,t,.28,.6);if(b%4===3)kopuz(c,o,82.41,t,.26,.6);if(b%8===0)strum(c,o,[220,329.63,440],t,.13);if(b%16===12)roll(c,o,t,8,.07,.4)}},
{n:'Göç yolu',d:'Yalnız bir kopuz, uzun ve kederli bir cümle. Arada tek davul vuruşu.',tag:['50 bpm','kopuz','yalnız'],bpm:50,f:function(c,o,b,t,s){if(b%16===0)seq([[0,440,3],[3,392,1],[4,349.23,2],[6,329.63,2],[8,293.66,2],[10,329.63,1],[11,293.66,1],[12,261.63,2],[14,220,2]],t,s,function(f,tt,d){kopuz(c,o,f,tt,.26,d+.6)});if(b%4===0)kopuz(c,o,110,t,.18,s*4);if(b%8===0)kam(c,o,t,.26);if(b%8===4)kam(c,o,t,.14,'jing')}},
{n:'Han divanı',d:'Resmî ve ağır: saz akorları, düzenli kam ve tek tek melodi notaları.',tag:['60 bpm','saz akor','kam'],bpm:60,f:function(c,o,b,t,s){if(b%8===0)strum(c,o,[220,329.63,440],t,.14);if(b%8===4)strum(c,o,[196,293.66,392],t,.14);if(b%8===6)saz(c,o,K[4],t,.2,1.6);if(b%4===0)kam(c,o,t,.42);if(b%4===2)kam(c,o,t,.14,'tek')}},
{n:'Gerilim şelpesi',d:'Sürekli titreyen saz teli giderek hızlanır, kam vurguları artar, sonda büyük bir vurma.',tag:['100 bpm','şelpe','kabarma'],bpm:100,f:function(c,o,b,t,s){var u=(b%32)/32;selpe(c,o,220,t,s,.05+.06*u,8+u*10);if(b%2===0)kam(c,o,t,.18+.3*u);if(b%32===0)strum(c,o,[110,220,329.63],t,.16);if(b%32===28)roll(c,o,t,16,.06,.5)}},
{n:'Tuğ altında',d:'Kopuz soru sorar, saz cevap verir; altında tören ritmi.',tag:['84 bpm','kopuz · saz','soru–cevap'],bpm:84,f:function(c,o,b,t,s){var m=b%16;if(m===0)seq([[0,220,1],[1,261.63,1],[2,293.66,1],[3,329.63,3]],t,s,function(f,tt,d){kopuz(c,o,f,tt,.26,d+.5)});if(m===8)seq([[0,329.63,1],[1,293.66,1],[2,261.63,1],[3,220,3]],t,s,function(f,tt,d){selpe(c,o,f,tt,d*.7,.11,10)});if(b%4===0)kam(c,o,t,.4);if(b%4===2)kam(c,o,t,.15,'tek');if(b%8===0)kopuz(c,o,110,t,.2,s*4)}},
{n:'Ateş başı',d:'3+3+2 vuruşlu trans ritmi, zil sesleri ve kopuzun tek notalık dönüşü.',tag:['100 bpm','3+3+2','zil'],bpm:100,f:function(c,o,b,t,s){var m=b%4;if(m===0){kam(c,o,t,.5);kam(c,o,t+s*.75,.14,'tek')}if(m===1)kam(c,o,t+s*.5,.42);if(m===2){kam(c,o,t+s*.25,.14,'tek');kam(c,o,t,.2,'jing')}if(m===3){kam(c,o,t,.45);kam(c,o,t+s*.5,.14,'tek')}if(m===0)kopuz(c,o,110,t,.28,s*4)}},
{n:'Yalnız saz',d:'Çok seyrek: uzun bırakılan tek tel sesleri ve sessizlik. Gerilim boşluktan gelir.',tag:['44 bpm','saz','minimal'],bpm:44,f:function(c,o,b,t,s){if(b%8===0)saz(c,o,[K[7],K[4],K[3],K[0]*2][(b/8)%4],t,.22,3.6);if(b%16===0)saz(c,o,110,t,.2,4);if(b%32===0)kam(c,o,t,.2)}},
{n:'Kurultay',d:'Tören adımı: ağır kam, alçak kopuz zemini ve cümle sonlarında saz akoru.',tag:['66 bpm','kam · kopuz · saz','resmî'],bpm:66,f:function(c,o,b,t,s){if(b%4===0)kam(c,o,t,.5);if(b%4===2)kam(c,o,t,.15,'tek');if(b%4===3)kam(c,o,t+s*.5,.2);if(b%4===0)kopuz(c,o,110,t,.24,s*4);if(b%8===0)strum(c,o,[220,329.63,440],t,.13);if(b%16===8)seq([[0,329.63,2],[2,293.66,2],[4,261.63,4]],t,s,function(f,tt,d){kopuz(c,o,f,tt,.25,d+.4)})}},
{n:'Son savaş',d:'Hızlı kam, alçak kopuz nabzı ve sürekli şelpe; her dört ölçüde vurma.',tag:['120 bpm','savaş','şelpe'],bpm:120,f:function(c,o,b,t,s){kam(c,o,t,.5);kam(c,o,t+s*.5,.16,'tek');kopuz(c,o,110,t,.2,.3);kopuz(c,o,110,t+s*.5,.15,.25);if(b%4===0)selpe(c,o,K[7],t,s*2,.08,14);if(b%16===12)roll(c,o,t,12,.06,.5)}},
{n:'Uyanış',d:'Önce yalnız kam, sonra kopuz, sonra saz; her 48 vuruşta yeniden başlar.',tag:['60 bpm','katman katman','yükseliş'],bpm:60,f:function(c,o,b,t,s){var st=Math.floor((b%48)/16);if(b%2===0)kam(c,o,t,.4);if(st>=1){if(b%4===0)kopuz(c,o,110,t,.22,s*4);if(b%8===4)kopuz(c,o,[220,261.63,293.66][Math.floor(b/8)%3],t,.2,1.5)}if(st>=2){selpe(c,o,K[4],t,s,.07,9);if(b%4===0)strum(c,o,[220,329.63,440],t,.12)}}}
];
var T=[TR1[1],TR1[2],TR1[3],
{n:'Otağ önü',bpm:92,f:gal({r:G,sc:'ussak',bpm:92,h:5,mel:[0,2,0,4],k:1}).f},
{n:'Dağ geçidi',bpm:100,f:gal({r:Dd,sc:'nihavend',bpm:100,h:1,mel:[4,2,3,1],k:2,five:1}).f},
{n:'Kuzey yolu',bpm:64,f:gal({r:E,sc:'kurdi',bpm:64,h:3,mel:[0,2,4,6],k:3}).f},
{n:'Uzun yürüyüş',bpm:86,f:gal({r:A,sc:'hicaz',bpm:86,h:4,mel:[0,1,2,1],k:0,five:1}).f},
{n:'Ana tema',bpm:20/3,buf:1,bar:1,max:8,f:function(c,o,b,t){if(!tema)return;var src=c.createBufferSource(),g=c.createGain(),L=tema.duration,x=.9;src.buffer=tema;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(.55,t+x);g.gain.setValueAtTime(.55,t+L-x);g.gain.linearRampToValueAtTime(.0001,t+L);src.connect(g).connect(o);src.start(t)}}];
var tema=null,ML=[[7,5,6,0],[7,1,3,0],[2,4]],VOL=[0,.4,.7,1];
var ctx=null,master=null,cur=null,ready=false,t0=Date.now();
const lsg=k=>{try{return localStorage.getItem(k)}catch(e){return null}};
function mood(){try{if(typeof S==='undefined'||!S.hist)return 0;var bad=0,warn=0;STATS.forEach(function(s){if(s.k==='kur')return;var c=s.st(S[s.k]);if(c==='bad')bad++;else if(c==='warn')warn++});var el=typeof toEl==='function'?toEl():99;return bad>=2||(el>=0&&el<=3)?2:(bad===1||warn>=3)?1:0}catch(e){return 0}}
function lvl(){var v=lsg('km-mu');return v===null?2:+v}
function ac(){if(!ctx){var C=window.AudioContext||window.webkitAudioContext;if(!C)return null;ctx=new C();var cm=ctx.createDynamicsCompressor();master=ctx.createGain();master.connect(cm);cm.connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume();loadTema();return ctx}
function start(i,md){var c=ctx,tr=T[i],g=c.createGain();g.gain.value=0;g.gain.setTargetAtTime(1,c.currentTime,.5);g.connect(master);var dry=c.createGain(),wet=c.createGain(),cv=c.createConvolver();cv.buffer=IR(c);dry.gain.value=.8;wet.gain.value=.55;dry.connect(g);cv.connect(wet);wet.connect(g);var bus=c.createGain();bus.connect(dry);bus.connect(cv);cur={i:i,tr:tr,g:g,bus:bus,b:0,next:c.currentTime+.2,md:md,s:60/tr.bpm}}
function fade(o){var c=ctx;o.g.gain.cancelScheduledValues(c.currentTime);o.g.gain.setTargetAtTime(0,c.currentTime,.35);setTimeout(function(){try{o.g.disconnect()}catch(e){}},2500)}
function loadTema(){if(tema||!window.KM_TEMA||!ctx)return;try{var s=atob(KM_TEMA.split(',')[1]),u=new Uint8Array(s.length);for(var i=0;i<s.length;i++)u[i]=s.charCodeAt(i);ctx.decodeAudioData(u.buffer,function(b){tema=b},function(){})}catch(e){}}
function pick(md){var l=ML[md],k=l.indexOf(cur?cur.i:-1),p;for(var j=1;j<=l.length;j++){p=l[(k+j)%l.length];if(!(T[p].buf&&!tema))return p}return l[0]}
function loop(){var v=lvl();if(!ready||!v||document.hidden){if(cur&&(!v)){fade(cur);cur=null}return}var c=ac();if(!c||c.state!=='running')return;master.gain.value=VOL[v];var md=mood();if(!cur)start(pick(md),md);else if(cur.b>0&&cur.b%(cur.tr.bar||16)===0&&(md!==cur.md||cur.b>=(cur.tr.max||64))){var o=cur;fade(o);start(pick(md),md);return}
while(cur.next<c.currentTime+.6){try{cur.tr.f(c,cur.bus,cur.b,cur.next,cur.s)}catch(e){}cur.next+=cur.s;cur.b++}}
function unlock(){if(ready||Date.now()-t0<2800)return;ready=true;ac()}
['pointerdown','touchend','keydown'].forEach(function(e){document.addEventListener(e,unlock,{passive:true})});
setInterval(loop,100);
document.addEventListener('visibilitychange',function(){if(!ctx)return;if(document.hidden)ctx.suspend();else if(ready)ctx.resume()});
window.kmMu={now:function(){return cur?cur.tr.n:null},mood:mood,go:function(){ready=true;ac()}};
})();
