/* ---------- Kesime ve ülkeye özel somut seçenekler ---------- */
/* Toplumsal gruplar: [ad, açıklama, hoşnutluk hedefi, anlık etki, diğer gruplara etki] — açık: GSYH puanı */
const GMO={
emekli:[['Bayram ikramiyesini artır','Her bayram ödenen ikramiye 1.000 ₺ artırılır.',6,{acik:.12,des:.1},{}],['En düşük emekli aylığını yükselt','Taban aylık asgari ücretin yarısına çekilir.',10,{acik:.3,des:.15,enf:.05},{kamu:-1}],['Refah payı zammı','Enflasyon farkına ek %5 refah payı verilir.',14,{acik:.5,enf:.12,des:.2},{ucret:-2,sanayi:-2}],['İlaç katkı payını kaldır','Emeklilerden alınan ilaç ve muayene katkı payı kaldırılır.',5,{acik:.08},{}],['EYT benzeri düzenleme','Yaşa takılanlara erken emeklilik hakkı; SGK yükü kalıcı artar.',12,{acik:.6,isz:-.1,des:.3},{genc:-3,sanayi:-3}],['Emekli dernekleriyle görüş','Talepler dinlenir, takvim sözü verilir.',3,{},{}]],
ucret:[['Asgari ücrete ara zam','Yıl ortasında %8 ara zam yapılır.',10,{enf:.25,acik:.05,des:.15,isz:.05},{sanayi:-5,esnaf:-3}],['Asgari ücretten vergiyi kaldır','Gelir ve damga vergisi istisnası genişletilir.',7,{acik:.25,des:.1},{}],['Kıdem tazminatı güvencesi','Fon tartışması rafa kalkar, kıdem hakkı korunur; işveren tepkili.',5,{buy:-.01},{sanayi:-3}],['İş güvenliği denetim seferberliği','Maden ve inşaatta denetim ikiye katlanır.',4,{acik:.03,huz:.05},{sanayi:-1}],['Kiracıya kira yardımı','Asgari ücretli kiracılara aylık destek.',8,{acik:.2,des:.1},{genc:2}],['Sendikalarla üçlü danışma','Hükümet, işçi ve işveren masaya oturur.',3,{},{}]],
esnaf:[['Faiz destekli Halkbank kredisi','Esnafa sübvansiyonlu işletme kredisi.',8,{acik:.12,buy:.05,enf:.03},{}],['Vergi ve SGK borcu yapılandırması','Gecikme faizleri silinir, borç taksitlendirilir.',9,{acik:-.05,des:.05},{ucret:-1,kentli:-1}],['Kira artışına tavan','İşyeri kiralarına yıllık artış sınırı.',6,{buy:-.03},{sanayi:-1}],['AVM ve zincir market düzenlemesi','Mahalle esnafını koruyan açılış ve indirim kuralları.',6,{enf:.03},{sanayi:-2,kentli:-1}],['Kayıt dışıyla mücadele','Denetim artar, haksız rekabet azalır; kısa vadede tepki.',-4,{acik:-.15,des:-.05},{ucret:1}],['Esnaf odalarıyla görüş','TESK ile sorunlar masaya yatırılır.',3,{},{}]],
ciftci:[['Mazot ve gübre desteği','Girdi maliyetine doğrudan ödeme.',9,{acik:.15,enf:-.05},{}],['Taban fiyatı yüksek açıkla','TMO hububat alım fiyatı enflasyonun üstünde.',10,{acik:.12,enf:.08},{kentli:-2}],['Tarım kredi borçlarını ertele','Ziraat Bankası ve kooperatif borçlarına erteleme.',6,{acik:.08},{}],['Sulama ve kooperatif yatırımı','Damla sulama ve depolama tesisleri.',7,{acik:.15,buy:.03},{}],['İthalat gümrüğünü artır','Buğday ve et ithalatında gümrük yükselir.',8,{enf:.12,cari:-.05},{kentli:-3,ucret:-2}],['Ziraat odalarıyla görüş','Hasat ve fiyat beklentileri dinlenir.',3,{},{}]],
sanayi:[['Yatırım teşvik paketi','Bölgesel teşvik, vergi indirimi ve arsa tahsisi.',8,{acik:.2,buy:.08,isz:-.05},{}],['Eximbank ihracat kredisi','Döviz kazandırana ucuz finansman.',7,{acik:.1,cari:-.1,buy:.05},{}],['Enerji maliyetine sübvansiyon','Sanayi elektriğine indirimli tarife.',8,{acik:.2,enf:-.03},{kentli:-1}],['Kıdem fonu reformu','Kıdem tazminatı fona devredilir; sendikalar tepkili.',10,{buy:.05},{ucret:-8}],['Mesleki eğitim ortaklığı','OSB ile meslek liseleri ortak program.',4,{acik:.05,isz:-.05},{genc:2}],['TOBB ve TÜSİAD ile görüş','Sanayicilerin talepleri dinlenir.',3,{},{}]],
kamu:[['Memur maaşına ek zam','Toplu sözleşmenin üstüne %5 ek artış.',10,{acik:.4,enf:.1},{ucret:-2,sanayi:-1}],['Ek gösterge düzenlemesi','Emeklilikte ek gösterge yükseltilir.',8,{acik:.2},{emekli:2}],['Sözleşmeliye kadro','Sözleşmeli personel kadroya geçirilir.',8,{acik:.15},{genc:1}],['Esnek ve uzaktan çalışma','Kamu kurumlarında esnek mesai; hizmet saatleri tartışılır.',4,{des:-.02},{ucret:-1}],['Liyakatli atama sözü','Atama ve terfi sınavla yapılır; parti içi kadro beklentisi olanlar rahatsız.',5,{par:-.05},{}],['Memur sendikalarıyla görüş','Memur-Sen ve diğerleriyle görüşme.',3,{},{}]],
genc:[['KYK borçlarını sil','Öğrenim kredisi borçları silinir.',10,{acik:.25,des:.1},{kentli:1}],['Burs ve yurt kapasitesi','Burs miktarı artar, yeni yurtlar açılır.',7,{acik:.15},{muhaf:1}],['Genç girişimci fonu','İlk iş kuranlara hibe ve vergi muafiyeti.',6,{acik:.1,buy:.03},{}],['İlk iş istihdam teşviki','Genç işe alana SGK primi desteği.',7,{acik:.12,isz:-.08},{sanayi:2}],['Ücretsiz internet ve ulaşım','Öğrenciye ücretsiz kota ve toplu taşıma.',5,{acik:.08},{}],['Gençlik kurultayı','Gençlerle açık oturum düzenlenir.',3,{},{}]],
kentli:[['Yargı reformu paketi','Tutukluluk süreleri kısalır, ifade özgürlüğü genişler.',9,{bat:.15},{muhaf:-2,milli:-2}],['İnternet erişim yasaklarını gevşet','Sosyal medya erişim engelleri azaltılır.',7,{bat:.08},{muhaf:-2}],['Kentsel dönüşüm ve yeşil alan','Deprem dönüşümü ve park yatırımları.',6,{acik:.15},{}],['Toplu taşıma yatırımı','Metro ve raylı sistem projeleri.',6,{acik:.2,buy:.03},{}],['Sanat ve kültür desteği','Bağımsız sanata fon, festival izinleri.',4,{acik:.03},{muhaf:-1}],['Barolar ve STK ile görüş','Hukuk ve özgürlük talepleri dinlenir.',3,{},{}]],
muhaf:[['Aile destek paketi','Evlilik kredisi ve çocuk yardımı artar.',9,{acik:.2,des:.05},{kentli:-2}],['Din eğitimi ve Kuran kursları','Seçmeli din dersleri ve kurs kapasitesi artar.',7,{acik:.03},{kentli:-4}],['Hafta sonu ve alkol düzenlemesi','Satış saatleri kısıtlanır.',6,{},{kentli:-5,esnaf:-1}],['Doğum ve annelik izni uzat','Doğum izni uzar, yarı zamanlı çalışma hakkı.',6,{acik:.08},{sanayi:-1,kentli:1}],['Vakıf ve cemaat yurtlarına destek','Yurt ve burs ağına kamu desteği.',5,{acik:.05},{kentli:-3}],['Kanaat önderleriyle görüş','Dini ve toplumsal liderlerle görüşme.',3,{},{}]],
milli:[['Sınır ve göç sıkılaştırması','Geri gönderme merkezleri ve sınır duvarı.',9,{acik:.1,huz:.05,bat:-.05},{kentli:-3,dogu:-1}],['Şehit ve gazi ailelerine destek','Aylık ve istihdam hakları genişler.',7,{acik:.08},{ordu:3}],['Terörle mücadele operasyonu','Sınır ötesi operasyon hazırlığı.',8,{acik:.15,ord:.1,bat:-.1},{dogu:-4}],['Millî tarih ve kültür programı','Okullarda millî kültür dersi ve anıt projeleri.',5,{acik:.03},{kentli:-1}],['Yerli silah ve TOGG vurgusu','Yerli üretim kampanyası.',5,{acik:.05},{sanayi:1}],['Ülkü ocakları ve dernekleriyle görüş','Milliyetçi tabanla görüşme.',3,{},{}]],
dogu:[['Bölgesel kalkınma yatırımı','Doğu ve Güneydoğu\'da sanayi ve altyapı.',9,{acik:.25,buy:.05,isz:-.05},{}],['Anadilde eğitim adımı','Seçmeli Kürtçe ders ve yayın kolaylığı.',8,{bat:.08},{milli:-6}],['Kayyum yerine seçilmiş başkanlar','Görevden alınan belediye başkanları iade edilir.',10,{bat:.1,huz:.05},{milli:-8,ordu:-2}],['Sınır ticareti ve kapı açılışı','Irak ve İran sınırında yeni kapılar.',6,{cari:-.05,buy:.02},{}],['Köy yolları ve sağlık ocakları','Kırsal hizmet altyapısı.',6,{acik:.12},{}],['Bölge temsilcileriyle görüş','Aşiret, STK ve belediyelerle görüşme.',3,{},{}]],
ordu:[['Askerî maaş ve tazminat artışı','Subay ve astsubay maaşlarına zam.',8,{acik:.15},{kamu:-1}],['Modernizasyon ve tedarik','Yeni mühimmat ve platform alımı.',8,{acik:.25,ord:.15},{}],['Lojman ve sosyal tesis','Ordu lojmanları ve orduevleri yenilenir.',5,{acik:.08},{}],['Gazilere istihdam ve konut','Gazilere kamu istihdamı ve konut kredisi.',6,{acik:.08},{milli:2}],['Askerlik süresini kısalt','Bedelli ücreti düşer, süre kısalır.',-3,{acik:-.05,des:.1},{genc:6,milli:-2}],['Komuta kademesiyle görüş','Genelkurmayla değerlendirme toplantısı.',3,{},{}]]};
/* Ülkeler: [ad, açıklama, ilişki, anlık etki, koşul] — reg: o bölgenin itibarı */
const UHO=[['Dışişleri bakanı ziyareti','Bakan düzeyinde temas; düşük maliyetli.',3,{},()=>1],['Cumhurbaşkanı resmî ziyareti','Zirve ve anlaşma törenleri; bölge itibarı artar.',7,{reg:.1,acik:.01},()=>1],['Ticaret heyeti ve fuar','İş insanları ve ihracatçılarla heyet.',4,{cari:-.03,buy:.01},()=>1],['Yatırım forumu','Karşılıklı yatırım ve sermaye girişi.',4,{rez:.05},()=>1],['Savunma sanayii görüşmesi','Ortak üretim ve satış görüşmeleri.',5,{ord:.05,cari:-.02},(c)=>c[0]!=='gre'&&c[0]!=='isr'],['Enerji anlaşması görüşmesi','Doğalgaz, petrol ve boru hattı görüşmeleri.',5,{enf:-.03,cari:-.03},(c)=>['rus','aze','irn','irq','qat','sau','uae'].includes(c[0])],['Vize kolaylığı ve öğrenci değişimi','Kültürel bağ ve turizm artar.',3,{des:.02},()=>1],['Arabulucu ve insani yardım','Kriz bölgesine yardım ve arabuluculuk.',5,{reg:.08,acik:.03},(c)=>['syr','irq','egy','isr'].includes(c[0])]];
/* Lobilere özel görüşme biçimleri: [ad, açıklama, tutum, etki] */
const LMO={sen:[['Toplu sözleşme masası','Kamu ve özel sektör toplu sözleşmeleri için masa kurulur.',8,{}],['Üçlü danışma kurulu','Hükümet, işçi ve işveren aynı masada.',11,{des:.03}],['Konfederasyon başkanlarıyla zirve','Türk-İş, DİSK ve Hak-İş liderleriyle zirve.',16,{des:.05,par:-.04}]],
 isv:[['Ekonomi koordinasyon toplantısı','Bakanlarla iş dünyası temsilcileri bir araya gelir.',6,{}],['Yatırım danışma konseyi','Büyük şirket CEO\'larıyla konsey.',11,{bat:.03}],['Reform takvimi sözü','Vergi ve düzenleme takvimi taahhüt edilir.',15,{bat:.05,par:-.03}]],
 oda:[['Oda başkanlarıyla görüşme','TOBB, baro ve tabip odası başkanları dinlenir.',6,{}],['Mevzuat taslağını paylaş','Yasa taslakları meslek örgütlerine açılır.',10,{}],['Mesleki özerklik sözü','Odaların yetkileri korunur.',14,{par:-.05}]],
 stk:[['Bilgilendirme toplantısı','STK\'lara politika brifingi.',5,{}],['Sivil toplum istişaresi','Yasa süreçlerine STK görüşü alınır.',10,{bat:.03}],['Ortak izleme kurulu','STK\'larla ortak izleme ve raporlama.',14,{bat:.05,par:-.04}]],
 vak:[['Vakıf ziyaretleri','Büyük vakıf ve derneklere ziyaret.',6,{}],['Ortak sosyal proje','Burs, yurt ve yardım projelerinde ortaklık.',11,{acik:.03}],['Cemaat liderleriyle görüşme','Dini toplulukların liderleriyle görüşme.',15,{bat:-.03,par:.03}]]};
/* ortak liste çizimi */
const opRow=(n,h,b)=>{const k=/data-(gm|uh|pzo|tro|dgo|oac|tat|sco)=/.test(b)&&!/disabled/.test(b)?xkey(n):'',v=k?ui(k,100):100;return `<div ${k?`data-xk="${k}"`:''} style="display:grid;grid-template-columns:minmax(0,1fr) auto;gap:4px 10px;align-items:center;padding:7px 0;border-top:1px solid var(--line)"><div><b style="font-size:14px">${n}</b><div class="note" style="margin:2px 0 0">${h}</div></div>${b}${k?`<div style="grid-column:1/-1"><div class="dl" style="font-size:12px">Şiddet %${v}${v>100?' · daha güçlü etki, daha yüksek maliyet':v<100?' · daha hafif etki ve maliyet':''}</div>${sld(k,25,200,25,v)}</div>`:''}</div>`;};
const gfxT=o=>{const t=Object.entries(o).filter(([k,v])=>v).map(([k,v])=>(GRP.find(g=>g[0]===k)||[0,k])[1]+' '+(v>0?'+':'−')+Math.abs(v)).join(', ');return t?' Diğer kesimler: '+t+'.':'';};
function gmList(id){const L=GMO[id]||[],m=su('g_'+id);return `<div style="grid-column:1/-1;margin-top:4px">${L.map((x,i)=>opRow(x[0],`${x[1]} Hoşnutluk ${x[2]>=0?'+':''}${x[2]}${fxText(x[3])?' · '+fxText(x[3]):''}.${gfxT(x[4])}`,sbtn(`data-gm="${id}:${i}"`,'Uygula'))).join('')}<div class="note">${sat(m)||'Aynı kesimle arka arkaya yapılan hamlelerin etkisi azalır, her ay toparlanır.'}</div></div>`;}
function ulList(c){const L=UHO.map((x,i)=>[x,i]).filter(([x])=>x[4](c)),m=su('u'+c[0]);return `<div style="grid-column:1/-1;margin-top:4px">${L.map(([x,i])=>opRow(x[0],`${x[1]} İlişki ${x[2]>0?'+':''}${x[2]}${fxText(Object.fromEntries(Object.entries(x[3]).filter(([k])=>k!=='reg')))?' · '+fxText(Object.fromEntries(Object.entries(x[3]).filter(([k])=>k!=='reg'))):''}${x[3].reg?' · '+RN[c[2]]+' itibarı +'+nf(x[3].reg,2):''}.`,sbtn(`data-uh="${c[0]}:${i}"`,'Uygula'))).join('')}<div class="note">${sat(m)||'Aynı ülkeyle arka arkaya temasın etkisi azalır.'}</div></div>`;}
function sec2Click(t){const d=t.dataset;if(d.gsel){S.gsel=S.gsel===d.gsel?null:d.gsel;render();return true;}if(d.usel){S.usel=S.usel===d.usel?null:d.usel;render();return true;}return false;}
