/* Yeni oyun ekranı: harita bandı, parti şeridi, lider kartı, zorluk ve senaryo seçimi. Başlatma eski data-pick akışını kullanır. */
(function(){
let sel='AKP';
const D={AKP:['#f08a00','#8a4b00','Muhafazakâr · Popülist'],CHP:['#d6202c','#7a0f16','Laik · Sosyal devletçi'],MHP:['#b5121b','#5e0b10','Milliyetçi · Muhafazakâr'],IYI:['#1e9fd4','#0c5878','Milliyetçi · Liberal'],DEM:['#7b3fa0','#43205c','Çoğulcu · Sosyal devletçi'],YRP:['#c4161c','#6b0d11','Muhafazakâr · Sosyal devletçi']};
/* özellik etiketleri: [anahtar, değer] — oyun başlarken gerçekten uygulanır */
const TG={Milliyetçi:[['des',3],['ord',.5],['bat',-.4],['kol',-.3]],Popülist:[['des',4],['rez',-4],['bat',-.3]],'Sosyal devletçi':[['des',2],['huz',.5],['rez',-2]],Liberal:[['bat',.6],['rez',3],['par',-.3]],Teknokrat:[['rez',5],['bat',.4],['des',-2]],Muhafazakâr:[['huz',.3],['par',.5],['dog',.4],['bat',-.3]],Laik:[['bat',.5],['ord',.3],['dog',-.4]],Çoğulcu:[['huz',.5],['bol',.4],['ord',-.4]]};
const KL={des:'Halk desteği',ord:'Ordu memnuniyeti',bat:'İtibar: Batı',dog:'İtibar: Doğu',bol:'İtibar: Bölge',kol:'İttifak uyumu',par:'Parti içi birlik',huz:'Toplumsal huzur',rez:'Net rezerv'};
const LD={AKP:[['Recep Tayfur Erdoğmuş','Milliyetçi','Popülist'],['Hakan Fidanoğlu','Teknokrat','Muhafazakâr'],['Süleyman Soyalp','Milliyetçi','Muhafazakâr']],
CHP:[['Özgür Özgül','Sosyal devletçi','Liberal'],['Mansur Yavaşoğlu','Milliyetçi','Laik'],['Ekrem İmanoğlu','Liberal','Popülist']],
MHP:[['Devlet Bahçevan','Milliyetçi','Muhafazakâr'],['Yusuf Halaçlı','Milliyetçi','Teknokrat'],['Mehmet Özdağlı','Milliyetçi','Laik']],
IYI:[['Müjdat Dervişoğlu','Milliyetçi','Liberal'],['Meral Akşenel','Milliyetçi','Laik'],['Ümit Özdal','Milliyetçi','Popülist']],
DEM:[['Tuncay Bakırlı','Çoğulcu','Sosyal devletçi'],['Selahattin Demirkan','Çoğulcu','Liberal'],['Pervin Buldanlı','Çoğulcu','Popülist']],
YRP:[['Fatih Erbaşan','Muhafazakâr','Sosyal devletçi'],['Necdet Erbek','Muhafazakâr','Teknokrat'],['Doğan Bekin','Muhafazakâr','Popülist']]};
const PT={AKP:['Muhafazakâr','Popülist'],CHP:['Laik','Sosyal devletçi'],MHP:['Milliyetçi','Muhafazakâr'],IYI:['Milliyetçi','Liberal'],DEM:['Çoğulcu','Sosyal devletçi'],YRP:['Muhafazakâr','Sosyal devletçi']};
let li=0;
const sum=ts=>{const o={};ts.forEach(t=>(TG[t]||[]).forEach(([k,v])=>o[k]=(o[k]||0)+v));return o;};
const fmt=(k,v)=>{const u=k==='des'?'%':k==='rez'?' mlr $':'';const n=Math.abs(v)<1&&k!=='des'?Math.abs(v).toFixed(1).replace('.',','):String(Math.abs(v)).replace('.',',');return `${KL[k]} ${v>0?'+':'−'}${k==='des'?'%':''}${n}${k==='rez'?' mlr $':''}`;};
const trH=ts=>`<div class="tr">${ts.map(t=>`<div class="tg"><b>${t}</b>${(TG[t]).map(([k,v])=>`<span class="${v>0?'pz':'ng'}">${fmt(k,v)}</span>`).join(' ')}</div>`).join('')}</div>`;
const SKN=['#e2b48f','#d9a47c','#c99068'],HR=['#2a2220','#3b2f2a','#8c8c8c','#1c1c1c','#5a4636','#a9a9a9'];
const L={
AKP:'<circle cx="20" cy="16" r="9" fill="#fff"/><path d="M15 22h10l-1 5h-8z" fill="#fff"/><rect x="16" y="28" width="8" height="3" rx="1.5" fill="#fff"/><path d="M20 10v7M17 13l3 3 3-3" stroke="#f08a00" stroke-width="1.6" fill="none"/>',
CHP:'<circle cx="20" cy="20" r="14" fill="none" stroke="#fff" stroke-width="2"/>'+[0,60,120,180,240,300].map(a=>`<path d="M20 7l3.2 7h-6.4z" fill="#fff" transform="rotate(${a} 20 20)"/>`).join('')+'<circle cx="20" cy="20" r="3" fill="#fff"/>',
MHP:[[13,13],[27,13],[20,26]].map(([x,y])=>`<path d="M${x+4} ${y-6}a7 7 0 1 0 0 12a5.5 5.5 0 1 1 0-12z" fill="#fff"/>`).join(''),
IYI:'<path d="M5 28q15-24 30 0" fill="none" stroke="#fff" stroke-width="2.2"/><text x="20" y="27" text-anchor="middle" font-size="12" font-weight="700" fill="#fff" font-family="Barlow Condensed,sans-serif">İYİ</text><circle cx="20" cy="9" r="2.4" fill="#ffd54a"/>',
DEM:'<circle cx="20" cy="20" r="6" fill="#ffd54a"/>'+[0,45,90,135,180,225,270,315].map(a=>`<path d="M20 6l2.2 6h-4.4z" fill="#8fd18a" transform="rotate(${a} 20 20)"/>`).join('')+'<circle cx="20" cy="20" r="2.4" fill="#d6202c"/>',
YRP:'<path d="M24 8a12 12 0 1 0 0 24a9.5 9.5 0 1 1 0-24z" fill="#fff"/><path d="M29 17l1.4 3.4 3.6.3-2.7 2.3.9 3.5-3.2-1.9-3.2 1.9.9-3.5-2.7-2.3 3.6-.3z" fill="#fff"/>'};
const logo=(k,s)=>`<svg class="lgo" width="${s}" height="${s}" viewBox="0 0 40 40"><defs><linearGradient id="g${k}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${D[k][0]}"/><stop offset="1" stop-color="${D[k][1]}"/></linearGradient></defs><rect width="40" height="40" rx="9" fill="url(#g${k})"/>${L[k]}</svg>`;
const face=(k,n)=>{const i=PK.indexOf(k)+n;return `<svg viewBox="0 0 64 64" width="72" height="72"><circle cx="32" cy="32" r="31" fill="#1b2430"/><path d="M8 62c2-14 12-20 24-20s22 6 24 20z" fill="#1f2a3a"/><path d="M28 42l4 8 4-8z" fill="#f2f2f2"/><path d="M31 46h2l1 12h-4z" fill="${D[k][0]}"/><rect x="27" y="34" width="10" height="10" rx="3" fill="${SKN[i%3]}"/><ellipse cx="32" cy="26" rx="11" ry="13" fill="${SKN[i%3]}"/><path d="M20 24c0-10 6-14 12-14s12 4 12 14c-3-5-7-7-12-7s-9 2-12 7z" fill="${HR[i%6]}"/><circle cx="27.5" cy="27" r="1.4" fill="#222"/><circle cx="36.5" cy="27" r="1.4" fill="#222"/>${i%2?'<rect x="23" y="25" width="8" height="5" rx="2" fill="none" stroke="#222" stroke-width="1"/><rect x="33" y="25" width="8" height="5" rx="2" fill="none" stroke="#222" stroke-width="1"/>':'<path d="M27 34c3 2 7 2 10 0" stroke="#5a3a2a" stroke-width="1.6" fill="none"/>'}${n===0&&i%3===0?'<path d="M26 33c3 2 9 2 12 0v2c-3 1-9 1-12 0z" fill="#3b2f2a"/>':''}</svg>`;};
const map=()=>`<svg class="mp" viewBox="0 0 400 170" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="mg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#e0562a"/><stop offset="1" stop-color="#a62818"/></linearGradient></defs><rect width="400" height="170" fill="#0d1218"/><rect x="0" y="0" width="24" height="170" fill="#2c4d7a"/><rect x="0" y="0" width="24" height="60" fill="#3d7a52"/><rect x="326" y="0" width="74" height="60" fill="#8a5a1c"/><rect x="326" y="60" width="74" height="110" fill="#2a6a45"/><rect x="326" y="96" width="74" height="12" fill="#c33"/><rect x="190" y="146" width="136" height="24" fill="#6b5a2e"/><rect x="326" y="146" width="74" height="24" fill="#222"/><path d="M26 24L40 20L58 21L74 36L93 36L117 31L141 20L170 20L184 27L205 38L243 40L272 30L291 29L304 38L302 52L325 66L318 82L317 102L315 116L286 118L267 118L216 123L194 126L187 140L187 124L162 125L133 139L99 123L74 128L59 125L46 120L43 102L37 92L35 74L27 61L37 52L50 41L27 49L25 44L30 26z" fill="url(#mg)" stroke="#f2c76a" stroke-width="2.4" stroke-linejoin="round"/><path d="M110 64a14 14 0 1 0 5 21a11.5 11.5 0 1 1-5-21z" fill="#f0dcb4"/><path d="M142 66l2.6 6.6 7 .5-5.4 4.4 1.8 6.8-6-3.8-6 3.8 1.8-6.8-5.4-4.4 7-.5z" fill="#f0dcb4"/><g font-family="Barlow Condensed,sans-serif" font-weight="700" fill="#fff" font-size="12" stroke="#000" stroke-width=".5" paint-order="stroke"><text x="2" y="76" font-size="9">Yunan.</text><text x="120" y="14">Karadeniz</text><text x="336" y="30">Gürcistan</text><text x="336" y="52" font-size="10">Azerbaycan</text><text x="336" y="130">İran</text><text x="336" y="164">Irak</text><text x="215" y="160">Suriye</text><text x="60" y="150">Akdeniz</text><text x="190" y="82" font-size="19">Türkiye</text></g><rect x="214" y="92" width="16" height="11" fill="#e30a17"/><circle cx="220" cy="97.5" r="3" fill="#fff"/></svg>`;
const css=document.createElement?document.createElement('style'):{};
css.textContent='.ny{max-width:520px;margin:0 auto;padding-bottom:84px}.ny .mp{display:block;width:100%;height:150px;border-radius:12px;border:1px solid var(--line)}'
+'.ny .ps{display:flex;gap:8px;overflow-x:auto;padding:10px 0;scrollbar-width:none}.ny .ps::-webkit-scrollbar{display:none}'
+'.ny .pc{flex:none;display:flex;align-items:center;gap:8px;padding:6px 14px 6px 6px;border:1px solid var(--line);border-radius:999px;background:var(--pn);color:var(--ink);font-family:var(--display);font-weight:700;font-size:15px;letter-spacing:.04em;cursor:pointer}'
+'.ny .pc.on{background:var(--accent);color:var(--bg,#111);border-color:var(--accent)}'
+'.ny .lgo{display:grid;place-items:center;flex:none;border-radius:10px;color:#fff;font-family:var(--display);font-weight:700;letter-spacing:.02em;border:1px solid rgba(255,255,255,.25)}.ny .pc .lgo{border-radius:8px}'
+'.ny .hd{display:flex;align-items:center;gap:12px;margin:4px 0 8px}.ny .hd b{font-family:var(--display);font-size:26px;color:var(--accent);line-height:1.1}.ny .hd small{margin-left:auto;color:var(--muted);font-size:12px;text-align:right}'
+'.ny .st{display:flex;flex-wrap:wrap;gap:6px 16px;padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:var(--pn);font-size:14px;color:var(--muted)}.ny .st b{color:var(--accent);font-family:var(--display);font-size:18px}'
+'.ny .sh{font-family:var(--display);font-weight:700;font-size:13px;letter-spacing:.14em;text-transform:uppercase;color:var(--accent);margin:14px 0 6px}'
+'.ny .ld{display:flex;align-items:center;gap:12px;padding:10px 12px;border:1px solid var(--accent);border-radius:12px;background:var(--pn)}.ny .ld svg{flex:none;border-radius:50%;border:2px solid var(--accent)}.ny .ld b{display:block;font-family:var(--display);font-size:19px}.ny .ld span{color:var(--muted);font-size:13px}'
+'.ny .ls{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;padding:2px 0}.ny .ls::-webkit-scrollbar{display:none}.ny .lc{flex:none;width:150px;display:flex;flex-direction:column;align-items:center;gap:4px;padding:10px 8px;border:1px solid var(--line);border-radius:12px;background:var(--pn);color:var(--ink);cursor:pointer;text-align:center;font:inherit}.ny .lc.on{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}.ny .lc b{font-family:var(--display);font-size:15px;line-height:1.15}.ny .lc small{color:var(--muted);font-size:12px}.ny .lc svg{border-radius:50%;border:2px solid var(--accent)}'
+'.ny .tr{padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:var(--pn);margin-top:8px}.ny .tg{display:flex;flex-wrap:wrap;align-items:center;gap:4px 10px;margin-bottom:6px;font-size:13px}.ny .tg:last-child{margin:0}.ny .tg b{padding:2px 10px;border-radius:6px;background:var(--surface2);color:var(--accent);font-family:var(--display);font-size:15px}.ny .pz{color:#4caf6a}.ny .ng{color:#e0803a}'
+'.ny .rk{display:flex;flex-wrap:wrap;gap:6px}.ny .rk span{padding:4px 10px;border:1px solid var(--line);border-radius:999px;background:var(--pn);font-size:13px}'
+'.ny .chips{margin:0}.ny .note{margin:6px 0 0}'
+'.ny .go{position:fixed;left:0;right:0;bottom:0;padding:10px 16px calc(10px + env(safe-area-inset-bottom,0px));background:linear-gradient(transparent,var(--bg,#111) 35%);z-index:5}.ny .go .btn{display:block;width:100%;max-width:520px;margin:0 auto;min-height:56px;font-size:19px;letter-spacing:.16em}';
try{document.head.appendChild(css);}catch(e){}
const DN=['Kolay: her ay hafif destek ve büyüme bonusu, daha az kriz, IMF acil kredisi 25 mlr $.','Normal: ek bonus ya da ceza yok, IMF acil kredisi 15 mlr $.','Zor: her ay hafif destek ve büyüme cezası, daha çok kriz, IMF acil kredisi yalnızca 8 mlr $.'];
const SN=['Dengeli başlangıç: enflasyon %31, destek %41.','Kriz ortasında: enflasyon %68, rezerv düşük, destek zayıf.','Seçim öncesi: genel seçime 6 ay var, destek %44.','Yüksek enflasyon: enflasyon %85, kur baskılı.','Toparlanma: kriz geride, enflasyon %36, büyüme %3,8.','Güçlü ekonomi: enflasyon %18, büyüme %5, ama destek zayıf (%34).'];
function scr(){const p=PART[sel],dif=S.dif===undefined?1:S.dif,sc=S.sc||0,ls=LD[sel],ld=ls[li];
return `<div class="wrap"><div class="ny"><div class="tp" style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><button class="bk" data-hm="home" aria-label="Geri" style="width:40px;height:40px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--accent);font-size:22px;cursor:pointer">‹</button><b style="font-family:var(--display);font-size:22px;letter-spacing:.1em;text-transform:uppercase;color:var(--accent)">Yeni oyun</b></div>
${map()}<div class="ps">${PK.map(k=>`<button class="pc ${k===sel?'on':''}" data-ps="${k}">${logo(k,32)}${PART[k].n}</button>`).join('')}</div>
<div class="hd">${logo(sel,46)}<b>${p.n}</b><small>Oy oranı %${p.w}<br>${p.x>.3?'Sağ':'Sol'} çizgi</small></div>
<div class="sh">Lider · Genel Başkan</div><div class="ls">${ls.map((l,n)=>`<button class="lc ${n===li?'on':''}" data-pl="${n}">${face(sel,n)}<b>${l[0]}</b><small>${l[1]} · ${l[2]}</small></button>`).join('')}</div>
${trH([ld[1],ld[2]])}
<div class="sh">Parti</div><div class="st" style="padding:8px 12px"><span>${D[sel][2]}</span></div>${trH(PT[sel])}
<div class="sh">Zorluk</div><div class="chips">${['Kolay','Orta','Zor'].map((n,i)=>`<button class="btn sm ${dif===i?'':'sec'}" data-dif="${i}">${n}</button>`).join('')}</div><div class="note">${DN[dif]}</div>
<div class="sh">Senaryo</div><div class="chips">${['Standart','Kriz ortasında','Seçim öncesi','Yüksek enflasyon','Toparlanma','Güçlü ekonomi'].map((n,i)=>`<button class="btn sm ${sc===i?'':'sec'}" data-sc="${i}">${n}</button>`).join('')}</div><div class="note">${SN[sc]}</div>
<div class="go"><button class="btn" data-pick="${sel}">BAŞLA ▸</button></div></div></div>`;}
{const _r=render;render=function(){if(S&&S.pick&&!(window.kmHome&&window.kmHome.on&&window.kmHome.on())){try{const a=document.getElementById('app');if(a){document.documentElement.removeAttribute('data-nav');a.innerHTML=scr();return;}}catch(e){}}return _r();};}
{const _s=startGame;startGame=function(k){const l=(LD[k]||[])[li]||null;_s(k);try{if(l){const f=sum([l[1],l[2],...PT[k]]);S.ldn=l[0];const fx={};for(const q in f)fx[q]=Math.round(f[q]*10)/10;applyFx(fx);save();render();}}catch(e){}};}
document.addEventListener('click',ev=>{const t=ev.target.closest&&ev.target.closest('button');if(!t)return;const d=t.dataset;
if(d.ps!==undefined){ev.stopPropagation();sel=d.ps;li=0;render();return;}
if(d.pl!==undefined){ev.stopPropagation();li=+d.pl;render();return;}},true);
})();
