/* Yeni oyun ekranı: harita bandı, parti şeridi, lider kartı, zorluk ve senaryo seçimi. Başlatma eski data-pick akışını kullanır. */
(function(){
let sel='AKP';
const D={AKP:['#f08a00','AK','Muhafazakâr · Popülist','#8a4b00'],CHP:['#d6202c','CHP','Sosyal demokrat · Laik','#7a0f16'],MHP:['#b5121b','☾','Milliyetçi · Devletçi','#5e0b10'],IYI:['#1e9fd4','İYİ','Milliyetçi · Liberal','#0c5878'],DEM:['#7b3fa0','DEM','Sol · Çoğulcu','#43205c'],YRP:['#c4161c','☪','Muhafazakâr · Sosyal devlet','#6b0d11']};
const SK=['#e2b48f','#d9a47c','#c99068'],HR=['#2a2220','#3b2f2a','#8c8c8c','#1c1c1c','#5a4636','#a9a9a9'];
const mn=id=>{const m=(typeof MIN!=='undefined'?MIN:[]).find(x=>x[0]===id);return m?m[1]:(ROLES[id]?ROLES[id][0]:id);};
const logo=(k,s)=>`<span class="lgo" style="width:${s}px;height:${s}px;background:linear-gradient(145deg,${D[k][0]},${D[k][3]});font-size:${Math.round(s*(D[k][1].length>2?.3:.5))}px">${D[k][1]}</span>`;
const face=k=>{const i=PK.indexOf(k);return `<svg viewBox="0 0 64 64" width="68" height="68"><circle cx="32" cy="32" r="31" fill="#1b2430"/><path d="M8 62c2-14 12-20 24-20s22 6 24 20z" fill="#1f2a3a"/><path d="M28 42l4 8 4-8z" fill="#f2f2f2"/><path d="M31 46h2l1 12h-4z" fill="${D[k][0]}"/><rect x="27" y="34" width="10" height="10" rx="3" fill="${SK[i%3]}"/><ellipse cx="32" cy="26" rx="11" ry="13" fill="${SK[i%3]}"/><path d="M20 24c0-10 6-14 12-14s12 4 12 14c-3-5-7-7-12-7s-9 2-12 7z" fill="${HR[i]}"/><circle cx="27.5" cy="27" r="1.4" fill="#222"/><circle cx="36.5" cy="27" r="1.4" fill="#222"/>${i%2?'<rect x="23" y="25" width="8" height="5" rx="2" fill="none" stroke="#222" stroke-width="1"/><rect x="33" y="25" width="8" height="5" rx="2" fill="none" stroke="#222" stroke-width="1"/>':'<path d="M27 34c3 2 7 2 10 0" stroke="#5a3a2a" stroke-width="1.6" fill="none"/>'}</svg>`;};
const map=()=>`<svg class="mp" viewBox="0 0 400 150" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="mg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#e0562a"/><stop offset="1" stop-color="#a62818"/></linearGradient></defs><rect width="400" height="150" fill="#0d1218"/><rect x="0" y="0" width="70" height="150" fill="#3a2a1c"/><rect x="330" y="60" width="70" height="90" fill="#27402f"/><rect x="250" y="0" width="150" height="40" fill="#2a3a52"/><rect x="60" y="118" width="300" height="32" fill="#4a3320"/><path d="M40 70l30-15 30 5 30-15 40 5 40-8 40 8 40-2 40 10 25 17-5 17-35 6-40 7-40 3-40 8-40 5-30-13-20-12-25-5z" fill="url(#mg)" stroke="#f2c76a" stroke-width="2.5" stroke-linejoin="round"/><path d="M120 78a17 17 0 1 0 6 25a14 14 0 1 1-6-25z" fill="#f0dcb4"/><path d="M168 82l3 8 8 .5-6 5 2 8-7-4-7 4 2-8-6-5 8-.5z" fill="#f0dcb4"/><g font-family="Barlow Condensed,sans-serif" font-weight="700" fill="#fff" font-size="11" stroke="#000" stroke-width=".4" paint-order="stroke"><text x="10" y="30">Yunanistan</text><text x="150" y="38">Karadeniz</text><text x="290" y="28">Gürcistan</text><text x="150" y="135">Akdeniz</text><text x="350" y="120">Irak</text><text x="260" y="132">Suriye</text></g><text x="215" y="82" font-family="Barlow Condensed,sans-serif" font-weight="700" font-size="17" fill="#fff" stroke="#000" stroke-width=".5" paint-order="stroke">Türkiye</text></svg>`;
const css=document.createElement?document.createElement('style'):{};
css.textContent='.ny{max-width:520px;margin:0 auto;padding-bottom:84px}.ny .mp{display:block;width:100%;height:150px;border-radius:12px;border:1px solid var(--line)}'
+'.ny .ps{display:flex;gap:8px;overflow-x:auto;padding:10px 0;scrollbar-width:none}.ny .ps::-webkit-scrollbar{display:none}'
+'.ny .pc{flex:none;display:flex;align-items:center;gap:8px;padding:6px 14px 6px 6px;border:1px solid var(--line);border-radius:999px;background:var(--pn);color:var(--ink);font-family:var(--display);font-weight:700;font-size:15px;letter-spacing:.04em;cursor:pointer}'
+'.ny .pc.on{background:var(--accent);color:var(--bg,#111);border-color:var(--accent)}'
+'.ny .lgo{display:grid;place-items:center;flex:none;border-radius:10px;color:#fff;font-family:var(--display);font-weight:700;letter-spacing:.02em;border:1px solid rgba(255,255,255,.25)}.ny .pc .lgo{border-radius:50%}'
+'.ny .hd{display:flex;align-items:center;gap:12px;margin:4px 0 8px}.ny .hd b{font-family:var(--display);font-size:26px;color:var(--accent);line-height:1.1}.ny .hd small{margin-left:auto;color:var(--muted);font-size:12px;text-align:right}'
+'.ny .st{display:flex;flex-wrap:wrap;gap:6px 16px;padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:var(--pn);font-size:14px;color:var(--muted)}.ny .st b{color:var(--accent);font-family:var(--display);font-size:18px}'
+'.ny .sh{font-family:var(--display);font-weight:700;font-size:13px;letter-spacing:.14em;text-transform:uppercase;color:var(--accent);margin:14px 0 6px}'
+'.ny .ld{display:flex;align-items:center;gap:12px;padding:10px 12px;border:1px solid var(--accent);border-radius:12px;background:var(--pn)}.ny .ld svg{flex:none;border-radius:50%;border:2px solid var(--accent)}.ny .ld b{display:block;font-family:var(--display);font-size:19px}.ny .ld span{color:var(--muted);font-size:13px}'
+'.ny .rk{display:flex;flex-wrap:wrap;gap:6px}.ny .rk span{padding:4px 10px;border:1px solid var(--line);border-radius:999px;background:var(--pn);font-size:13px}'
+'.ny .chips{margin:0}.ny .note{margin:6px 0 0}'
+'.ny .go{position:fixed;left:0;right:0;bottom:0;padding:10px 16px calc(10px + env(safe-area-inset-bottom,0px));background:linear-gradient(transparent,var(--bg,#111) 35%);z-index:5}.ny .go .btn{display:block;width:100%;max-width:520px;margin:0 auto;min-height:56px;font-size:19px;letter-spacing:.16em}';
try{document.head.appendChild(css);}catch(e){}
const DN=['Kolay: her ay hafif destek ve büyüme bonusu, daha az kriz, IMF acil kredisi 25 mlr $.','Normal: ek bonus ya da ceza yok, IMF acil kredisi 15 mlr $.','Zor: her ay hafif destek ve büyüme cezası, daha çok kriz, IMF acil kredisi yalnızca 8 mlr $.'];
const SN=['Dengeli başlangıç: enflasyon %31, destek %41.','Kriz ortasında: enflasyon %68, rezerv düşük, destek zayıf.','Seçim öncesi: genel seçime 6 ay var, destek %44.','Yüksek enflasyon: enflasyon %85, kur baskılı.','Toparlanma: kriz geride, enflasyon %36, büyüme %3,8.','Güçlü ekonomi: enflasyon %18, büyüme %5, ama destek zayıf (%34).'];
function scr(){const p=PART[sel],dif=S.dif===undefined?1:S.dif,sc=S.sc||0;
return `<div class="wrap"><div class="ny"><div class="tp" style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><button class="bk" data-hm="home" aria-label="Geri" style="width:40px;height:40px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--accent);font-size:22px;cursor:pointer">‹</button><b style="font-family:var(--display);font-size:22px;letter-spacing:.1em;text-transform:uppercase;color:var(--accent)">Yeni oyun</b></div>
${map()}<div class="ps">${PK.map(k=>`<button class="pc ${k===sel?'on':''}" data-ps="${k}">${logo(k,34)}${PART[k].n}</button>`).join('')}</div>
<div class="hd">${logo(sel,48)}<b>${p.n}</b><small>Parti seç</small></div>
<div class="st"><span>Oy oranı <b>%${p.w}</b></span><span>Çizgi <b>${p.x>.3?'Sağ':'Sol'}</b></span><span style="flex-basis:100%">${D[sel][2]}</span></div>
<div class="sh">Lider · Genel Başkan</div><div class="ld">${face(sel)}<div><b>${p.lead}</b><span>${D[sel][2]}</span></div></div>
<div class="sh">Öncelikli bakanlıklar</div><div class="rk">${p.want.map(w=>`<span>${mn(w)}</span>`).join('')}</div>
<div class="sh">Zorluk</div><div class="chips">${['Kolay','Orta','Zor'].map((n,i)=>`<button class="btn sm ${dif===i?'':'sec'}" data-dif="${i}">${n}</button>`).join('')}</div><div class="note">${DN[dif]}</div>
<div class="sh">Senaryo</div><div class="chips">${['Standart','Kriz ortasında','Seçim öncesi','Yüksek enflasyon','Toparlanma','Güçlü ekonomi'].map((n,i)=>`<button class="btn sm ${sc===i?'':'sec'}" data-sc="${i}">${n}</button>`).join('')}</div><div class="note">${SN[sc]}</div>
<div class="go"><button class="btn" data-pick="${sel}">BAŞLA ▸</button></div></div></div>`;}
{const _r=render;render=function(){if(S&&S.pick&&!(window.kmHome&&window.kmHome.on&&window.kmHome.on())){try{const a=document.getElementById('app');if(a){document.documentElement.removeAttribute('data-nav');a.innerHTML=scr();return;}}catch(e){}}return _r();};}
document.addEventListener('click',ev=>{const t=ev.target.closest&&ev.target.closest('button');if(!t||t.dataset.ps===undefined)return;ev.stopPropagation();sel=t.dataset.ps;render();},true);
})();
