/* ---------- Siyaset 2: Meclis görseli, belediyeler, bürokrasi reformları, ayrıntılı karne, yeni yasalar, hizip ve lobi seçenekleri ---------- */
const PCL={AKP:'#F2A623',CHP:'#D9363E',MHP:'#8E2B2B',IYI:'#3FA9D9',DEM:'#8A5CC2',YRP:'#2E9E5B'};
/* Meclis yarım dairesi: 600 sandalye, partiler ideolojik sıraya göre soldan sağa */
function meclisSVG(){const R=12,N=600,rs=[...Array(R)].map((_,i)=>.42+.58*i/(R-1)),tr=rs.reduce((a,b)=>a+b,0),cnt=rs.map(r=>Math.round(N*r/tr));cnt[R-1]+=N-cnt.reduce((a,b)=>a+b,0);
  const P=[];rs.forEach((r,i)=>{for(let j=0;j<cnt[i];j++){const a=Math.PI*(1-j/(cnt[i]-1||1));P.push([a,r]);}});P.sort((x,y)=>y[0]-x[0]||x[1]-y[1]);
  const ord=PK.slice().sort((a,b)=>PART[a].x-PART[b].x),seq=[];ord.forEach(k=>{for(let i=0;i<(S.seats[k]||0);i++)seq.push(k);});
  const inG=k=>k===S.me||S.coal.includes(k),g=govSeats();
  const dots=P.map(([a,r],i)=>{const k=seq[i]||null,x=150+Math.cos(a)*r*138,y=150-Math.sin(a)*r*138;return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="2.6" fill="${k?PCL[k]:'#333'}" ${k&&!inG(k)?'opacity=".55"':''}/>`;}).join('');
  const mk=(n,l)=>`<span class="dl" style="margin-right:10px">${l}: <b style="color:var(--${g>=n?'good':'muted'})">${n}</b></span>`;
  return `<div class="panel"><b>Meclis dağılımı</b><svg viewBox="0 0 300 160" style="width:100%;display:block;margin:8px 0 4px">${dots}<text x="150" y="146" text-anchor="middle" style="fill:var(--ink);font-size:20px;font-weight:700">${g}</text><text x="150" y="158" text-anchor="middle" style="fill:var(--muted);font-size:8px">İKTİDAR BLOĞU / 600</text></svg>
  <div style="display:flex;flex-wrap:wrap;gap:4px 12px">${ord.map(k=>`<span class="dl"><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${PCL[k]};margin-right:4px"></i>${PART[k].n} ${S.seats[k]||0}${inG(k)?' ✓':''}</span>`).join('')}</div>
  <div style="margin-top:6px">${mk(301,'Yasa çoğunluğu')}${mk(360,'Halkoylamalı anayasa / erken seçim')}${mk(400,'Doğrudan anayasa')}</div></div>`;}
/* Büyükşehir belediyeleri: [il, 2024 yerel seçim galibi, ideolojik eğilim (−1 sol … +1 sağ), Kürt seçmen ağırlığı] */
const BLD=[['İstanbul','CHP',.05,.1],['Ankara','CHP',.15,0],['İzmir','CHP',-.45,.05],['Bursa','CHP',.2,0],['Antalya','CHP',.05,0],['Adana','CHP',-.05,.15],['Mersin','CHP',-.1,.2],['Balıkesir','CHP',.15,0],['Manisa','CHP',.1,0],['Aydın','CHP',-.15,.05],['Muğla','CHP',-.25,0],['Denizli','CHP',.15,0],['Tekirdağ','CHP',-.1,0],['Eskişehir','CHP',-.1,0],
 ['Konya','AKP',.7,0],['Kayseri','AKP',.65,0],['Gaziantep','AKP',.45,.15],['Kocaeli','AKP',.4,0],['Sakarya','AKP',.6,0],['Samsun','AKP',.55,0],['Ordu','AKP',.55,0],['Trabzon','AKP',.6,0],['Erzurum','AKP',.65,.1],['Malatya','AKP',.55,.1],['Kahramanmaraş','AKP',.7,.05],['Hatay','AKP',.3,.05],
 ['Diyarbakır','DEM',-.5,.85],['Mardin','DEM',-.4,.7],['Van','DEM',-.45,.75],['Şanlıurfa','YRP',.6,.4]];
function s2Ensure(){if(!S.bel){S.bel={};BLD.forEach(b=>S.bel[b[0]]=b[1]);if(S.me!=='AKP'&&S.me!=='CHP')Object.keys(S.bel).forEach(c=>{});}if(!S.bix)S.bix={};if(!S.kay)S.kay={};if(S.bu&&S.bu.kb===undefined){S.bu.kb=0;S.bu.yb=0;}if(!S.krH)S.krH=[];}
const belN=p=>Object.values(S.bel||{}).filter(x=>x===p).length;
/* yerel seçimde il il sonuç: oyuncu partisinin kazandığı il sayısı genel formülden, hangi iller olduğu eğilime ve yatırımlara göre */
function belSecim(){s2Ensure();const me=S.me,n=S.mun,aff=b=>-Math.abs(PART[me].x-b[2])*2+(me==='DEM'?b[3]*3:-b[3]*.8)+(S.bel[b[0]]===me?.6:0)+(S.bix[b[0]]||0)*.15+rnd(-.3,.3);
  const L=BLD.slice().sort((a,b)=>aff(b)-aff(a)),oth=PK.filter(k=>k!==me);L.forEach((b,i)=>{if(i<n){S.bel[b[0]]=me;return;}
    const sc=k=>-Math.abs(PART[k].x-b[2])*2+(k==='DEM'?b[3]*3.2:0)+Math.log(PART[k].w)*.9+(S.bel[b[0]]===k?.5:0)+rnd(-.3,.3);S.bel[b[0]]=oth.reduce((a,k)=>sc(k)>sc(a)?k:a,oth[0]);});
  S.kay={};S.bix={};}
const BLA=[['İller Bankası yatırımı','Altyapı, toplu taşıma ve kentsel dönüşüm için kaynak aktarılır.',{acik:.03,des:.05},3],['Ortak hizmet protokolü','Muhalefet belediyesiyle ortak proje: hizmet ve huzur artar.',{huz:.05,des:.04,par:-.03},1.5],['Borç yapılandırması','SGK ve vergi borçları taksitlendirilir.',{acik:.02},2],['Mülkiye müfettişi denetimi','Belediye denetlenir; usulsüzlük çıkarsa başkan zor durumda kalır.',{des:-.03},-2],['Kayyum ata','Terör soruşturması gerekçesiyle seçilmiş başkan görevden alınır.',{huz:-.3,bat:-.15,des:-.2},-6]];
function belAct(c,i){const b=BLD.find(x=>x[0]===c),x=BLA[i];if(!b||!x)return;const own=S.bel[c]===S.me;if(i===4&&(own||S.kay[c]))return;const m=su('bl'+c+i);suU('bl'+c+i);applyFx(sfx2(x[2],m));
  if(i===4){S.kay[c]=S.bel[c];S.gr.dogu=clamp(S.gr.dogu-8*(b[3]+.3),5,95);S.gr.milli=clamp(S.gr.milli+3,5,95);if(S.lb)S.lb.stk.t=clamp(S.lb.stk.t-10,-100,100);}
  else if(i===3){if(!own&&Math.random()<.4){S.bix[c]=(S.bix[c]||0)+2;logA('Belediye',c,'Denetimde usulsüzlük bulundu; muhalefet belediyesi yıprandı.');}else S.bix[c]=(S.bix[c]||0)+x[3]*m;}
  else{S.bix[c]=(S.bix[c]||0)+x[3]*m*(own?1:.5);if(!own&&i===0)applyFx({des:.03*m});}
  logA('Belediye',c+' · '+PART[S.bel[c]].n,x[0]+'.'+sat(m));hap(20,520);save();render();}
function belP(){s2Ensure();const sel=S.bsel,cnt=PK.map(k=>[k,belN(k)]).filter(x=>x[1]),nx=S.month<29?29:29+Math.ceil((S.month-28)/TERM)*TERM;
  return `<h2>Belediyeler</h2><div class="panel"><div style="display:flex;height:16px;border-radius:4px;overflow:hidden;margin:4px 0 8px">${cnt.map(([k,n])=>`<i style="flex:${n};background:${PCL[k]}"></i>`).join('')}</div>${cnt.map(([k,n])=>`<span class="dl" style="margin-right:10px"><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${PCL[k]};margin-right:4px"></i>${PART[k].n} ${n}</span>`).join('')}
  <div class="dl" style="margin-top:6px">Senin partin: <b>${belN(S.me)}</b>/30 büyükşehir · sonraki yerel seçim ${dateLabel(nx)} (${nx-S.month} ay)</div><div class="note">2024 yerel seçim sonuçlarıyla başlar. Belediyeler parti örgütünü ve Sadakatçi hizbi güçlendirir; yatırım ve hizmet yaptığın iller yerel seçimde sana daha yatkın olur. Muhalefet belediyesine yatırım tarafsızlık algısıyla desteği de artırır.</div></div>
  <div class="panel"><b>Büyükşehirler</b>${BLD.map(b=>{const c=b[0],p=S.bel[c],k=S.kay[c];return `<div class="lever"><span class="n"><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${PCL[p]};margin-right:6px"></i>${c}</span><span class="h">${PART[p].n}${k?' · <b style="color:var(--bad)">kayyum</b>':''}${S.bix[c]?' · yatırım etkisi '+nf(S.bix[c],1):''}</span><div class="step">${sbtn(`data-bsel="${c}"`,sel===c?'Kapat':'Seçenekler')}</div>${sel===c?`<div style="grid-column:1/-1">${BLA.map((x,i)=>i===4&&(p===S.me||k)?'':opRow(x[0],x[1]+(fxText(x[2])?' Etki: '+fxText(x[2])+'.':''),sbtn(`data-bla="${c}:${i}"`,'Uygula'))).join('')}</div>`:''}</div>`;}).join('')}</div>`;}
/* Bürokrasi reformları: [ad, açıklama, kapasite hedefi, yolsuzluk ofseti, liyakat, kamu çalışanı tepkisi, etki] */
const BZO=[['e-Devlet ve dijital dönüşüm','Kamu hizmetleri dijitalleşir, bürokratik süreler kısalır.',4,-1,0,1,{acik:.06}],['Kamu İhale Kanunu reformu','İstisnalar daraltılır, ihaleler açık ve rekabetçi olur.',1,-5,0,0,{par:-.15,buy:.02}],['Sayıştay ve iç denetimi güçlendir','Denetim raporları yayımlanır, yetkiler genişler.',1,-4,0,-1,{par:-.1,bat:.03}],['Performansa dayalı ücret','Başarılı birimlere prim; ölçülebilir hedefler.',3,0,0,2,{acik:.05}],['Kamu personel alımı','Eksik kadrolara KPSS ile atama.',2,0,0,3,{acik:.08,isz:-.03}],['Kadro tasarrufu','Yeni alım dondurulur, emekliliğe ayrılanın yeri doldurulmaz.',-2,0,0,-4,{acik:-.08}],['Yerinden yönetim','Belediyelere ve il idarelerine yetki devri.',2,1,0,0,{par:-.05}],['Kamu yönetimi akademisi','Hizmet içi eğitim ve yönetici okulu.',3,0,1,1,{acik:.03}],['İhbar ve bilgi uçuran koruması','Yolsuzluk ihbarı yapana koruma.',0,-3,0,0,{par:-.05,bat:.02}],['Üst kademeye siyasi atama','Genel müdür ve kurum başkanlıklarına partili isimler.',-2,3,-1,1,{par:.3}]];
function bzAct(i){const x=BZO[i],b=S.bu;if(!x||!b)return;const m=su('bz'+i);suU('bz'+i);b.kb=clamp(b.kb+x[2]*m,-15,15);b.yb=clamp(b.yb+x[3]*m,-20,20);b.ly=clamp(b.ly+x[4],-2,3);b.yz=clamp(b.yz+x[3]*.4*m,0,100);S.gr.kamu=clamp(S.gr.kamu+x[5]*m,5,95);applyFx(sfx2(x[6],m));logA('Bürokrasi',x[0],'Uygulandı.'+sat(m));hap(20,520);save();render();}
function buroX(){const b=S.bu;return `<div class="panel"><b>Kamu yönetimi reformları</b><div class="dl">Reform etkisi: kapasite hedefi ${b.kb>=0?'+':''}${nf(b.kb,1)} · yolsuzluk ofseti ${b.yb>=0?'+':''}${nf(b.yb,1)} · yaklaşık 5,2 milyon kamu görevlisi</div>${BZO.map((x,i)=>opRow(x[0],`${x[1]} Kapasite ${x[2]>=0?'+':''}${x[2]}, yolsuzluk ${x[3]>=0?'+':''}${x[3]}${x[4]?', liyakat '+(x[4]>0?'+':'')+x[4]:''}${x[5]?', kamu çalışanları '+(x[5]>0?'+':'')+x[5]:''}${fxText(x[6])?' · '+fxText(x[6]):''}.`,sbtn(`data-bzo="${i}"`,'Uygula'))).join('')}<div class="note">Reform etkileri kalıcıdır ama yavaş söner; aynı reformu tekrarlamak etkisini azaltır.</div></div>`;}
/* Ayrıntılı karne */
function krDet(){const pr=promRes().concat((S.pri||[]).map(k=>[PRI[k]?PRI[k][0]:k,PRI[k]&&PRI[k][2]()]));
  const I=(n,v,u,s)=>[n,v,u,s];return [['Ekonomi',[I('Enflasyon',S.enf,'%',lin(S.enf,80,15)),I('Büyüme',S.buy,'%',lin(S.buy,-2,5)),I('İşsizlik',S.isz,'%',lin(S.isz,14,5)),I('Bütçe açığı',S.acik,'%',lin(S.acik,8,2))]],
   ['Toplum',[I('Huzur',S.huz,'/10',lin(S.huz,2,8)),I('Grup memnuniyeti',gDev(),'',lin(gDev(),-20,15)),I('Huzursuzluk',uns(),'/100',lin(uns(),70,10))]],
   ['Dış ilişkiler',[I('İtibar ortalaması',(S.bat+S.dog+S.bol)/3,'/10',lin((S.bat+S.dog+S.bol)/3,3,8)),I('Kredi notu',S.pz.kn,'/100',lin(S.pz.kn,25,70))]],
   ['Güvenlik',[I('Ordu memnuniyeti',S.ord,'/10',lin(S.ord,3,8)),I('Savaş gücü',gucu(),'/100',lin(gucu(),40,75))]],
   ['Yönetim',[I('Yolsuzluk algısı',S.bu.yz,'/100',lin(S.bu.yz,80,20)),I('Devlet kapasitesi',S.bu.kap,'/100',lin(S.bu.kap,30,80)),I('Parti içi birlik',S.par,'/10',lin(S.par,3,8))]],
   ['Sözler',pr.map(p=>I(p[0]||'Öncelik',p[1]?1:0,'',p[1]?100:0))]];}
function donemX(){const D=krDet(),all=D.flatMap(c=>c[1].map(x=>[c[0],...x])).filter(x=>x[0]!=='Sözler'),srt=all.slice().sort((a,b)=>b[4]-a[4]),T=(S.th&&S.th.kr)||[],d12=T.length>12?krSc()-T[T.length-13]:0;
  return `<div class="panel"><b>Karnenin ayrıntısı</b><div class="dl">Son 12 ayda değişim: <b style="color:var(--${d12>=0?'good':'bad'})">${d12>=0?'+':''}${nf(d12,1)}</b> puan</div>${spark(T)}
  ${D.map(([c,L])=>`<div style="margin-top:8px"><div class="dl"><b>${c}</b></div>${L.length?L.map(x=>`<div style="display:grid;grid-template-columns:minmax(0,1fr) 60px 34px;gap:6px;align-items:center;padding:2px 0"><span class="dl">${x[0]}</span><span class="dl" style="text-align:right">${c==='Sözler'?(x[1]?'tutuluyor':'tutulmuyor'):nf(x[1],1)+x[2]}</span><span class="st ${grc(x[3])}" style="text-align:center">${gr(x[3])}</span></div>`).join(''):'<div class="dl muted">Söz verilmedi.</div>'}</div>`).join('')}
  <div class="note"><b>En güçlü alanların:</b> ${srt.slice(0,3).map(x=>x[1]).join(', ')}. <b>En zayıf alanların:</b> ${srt.slice(-3).reverse().map(x=>x[1]).join(', ')}.</div></div>`;}
/* Yeni yasalar: [anahtar, ad, maliyet, gereken oy, muhalefet desteği, açıklama, etki] */
LAWS.push(['iklim','İklim Kanunu','2',301,.5,'Emisyon ticaret sistemi ve 2053 net sıfır hedefi; sanayiye karbon maliyeti.',{bat:.4,buy:-.1,cari:-.3}],['siber','Siber Güvenlik Kanunu',2,301,.3,'Siber Güvenlik Başkanlığı; kritik altyapıya zorunlu standartlar, veri sızıntısına ceza.',{huz:.2,ord:.1,bat:-.1}],['ajan','Etki Ajanlığı Düzenlemesi',3,301,.05,'Yabancı devlet çıkarına çalışmayı suç sayar; basın ve STK\'lar tepkili.',{bat:-.8,huz:-.3,des:-.3,par:.3}],['hayvan','Sokak Hayvanları Düzenlemesi',2,301,.35,'Belediyelere toplama ve barınak yükümlülüğü.',{huz:-.1,des:-.2}],['kidem','Kıdem Tazminatı Fonu',3,301,.1,'Kıdem tazminatı fona devredilir; işçiler hak kaybından korkar.',{buy:.2,des:-.8,huz:-.4}],['saglik','Sağlıkta Şiddet Yasası',2,301,.85,'Sağlık çalışanına şiddete ağır ceza, hastanelere güvenlik.',{des:.4,huz:.2}],['maden','Maden Kanunu Değişikliği',2,301,.15,'Maden ruhsatlarında hızlı onay; çevreciler ve köylüler karşı.',{buy:.2,cari:-.3,des:-.4,huz:-.2}],['israf','Gıda İsrafı ve Fiyat Denetimi',2,301,.6,'Haksız fiyat artışına ceza, gıda bankacılığı.',{enf:-.3,des:.3,buy:-.05}],['tuketici','Tüketici Kredisi Düzenlemesi',2,301,.4,'Kredi kartı taksit ve limit sınırları.',{enf:-.2,cari:-.2,des:-.2}],['dogum','Doğum İzni ve Aile Yasası',2,301,.7,'Doğum izni 24 haftaya, babalık izni 15 güne çıkar.',{des:.5,acik:.15}],['ozel','Kişisel Verilerin Korunması Güncellemesi',2,301,.6,'AB uyumlu veri koruma; Batı ile veri akışı kolaylaşır.',{bat:.4}],['turizm','Turizm Teşvik Kanunu',2,301,.5,'Turizm yatırımlarına arazi tahsisi ve vergi indirimi.',{cari:-.3,acik:.1,buy:.1}]);
LAWS.forEach(l=>{if(typeof l[2]==='string')l[2]=+l[2];});
YT.push(['mkd','Kıdem tazminatı düzenlemesi',{buy:.2,des:-.6,huz:-.3},.2],['msg','Sağlık çalışanlarına koruma',{des:.5,huz:.2,acik:.05},.8],['miy','Emisyon ve iklim tedbirleri',{bat:.4,buy:-.1,cari:-.2},.5],['msk','Siber güvenlik ve veri',{huz:.2,ord:.1,bat:.1},.5],['myg','Yargı paketi',{bat:.5,des:.3,par:-.2},.5],['mgd','Fiyat denetimi ve gıda',{enf:-.3,des:.3,buy:-.05},.6],['mkk','Kredi kartı ve borç düzenlemesi',{enf:-.2,cari:-.2,des:-.1},.4],['mtr','Turizm ve kültür teşviki',{cari:-.3,acik:.1,bat:.1},.5]);
/* Lobilere ek konular ve kuruluş iletişim biçimleri */
LT.sen.push(['Haftalık çalışma süresi','Çalışma süresi kademeli 40 saate iner.',[1,2,3],'s',{buy:-.04,isz:-.03,des:.08},4.5],['Taşeron işçiye kadro','Kamu taşeron çalışanları kadroya alınır.',[1,2,3],'s',{acik:.08,des:.06},4.5],['İş güvenliği yasası','İş kazalarına ağır ceza, denetim artar.',[1,2,3],'s',{huz:.05,buy:-.02,des:.05},3.5]);
LT.isv.push(['Enerji fiyat istikrarı','Sanayi elektriğine sabit tarife sözü.',[1,2,3],'s',{acik:.08,enf:-.02},4],['Bürokrasiyi azalt','İzin ve ruhsat süreleri kısalır, tek durak ofis.',[1,2,3],'s',{buy:.04,par:-.03},3.5],['Kıdem fonu reformu','İşveren kıdem yükünden kurtulur; sendikalar karşı.',[1,2,3],'s',{buy:.05,des:-.08,huz:-.05},5.5]);
LT.oda.push(['Hekim ve avukat ücretleri','Asgari ücret tarifeleri güncellenir.',[1,2,3],'s',{acik:.03,des:.04},4],['Yargı reformu istişaresi','Barolarla yargı reformu masası.',[1,2,3],'s',{bat:.06,par:-.04},4.5],['Mühendis odalarına deprem denetimi','Yapı denetiminde odalara yetki.',[1,2,3],'s',{huz:.04,acik:.02},4]);
LT.stk.push(['Çevre etki raporu','Büyük projelerde bağımsız çevre raporu.',[1,2,3],'s',{bat:.05,buy:-.02},4],['Kadına şiddetle mücadele','6284 sayılı yasanın etkin uygulanması.',[1,2,3],'s',{des:.06,huz:.04},4.5],['Bilgi edinme hakkı','Kamu verisi açık erişime açılır.',[1,2,3],'s',{bat:.06,par:-.04},4]);
LT.vak.push(['Din eğitimi işbirliği','Okullarda değerler eğitimi için ortak program.',[1,2,3],'s',{des:.05,bat:-.02},4],['Vakıf mülklerinin iadesi','Azınlık ve vakıf mülkleri iade edilir.',[1,2,3],'s',{bat:.08,des:-.02},3.5],['Yurt ve pansiyon izinleri','Vakıf yurtlarına kolay ruhsat.',[1,2,3],'s',{acik:.02,des:.04},4]);
SM.push(['Danışma kuruluna al','Kurum temsilcisi bakanlık danışma kuruluna girer.',12,{par:-.02}],['Kamu finansmanı sağla','Projelerine kamu kaynağı aktarılır; yolsuzluk algısı riski.',17,{acik:.06}],['Mali denetim başlat','Hesapları denetlenir; ilişki bozulur ama kamuoyu olumlu.',-14,{des:.03}]);
/* Hizip: ortak ve hizbe özel ek hamleler */
const HZX=[['İstişare kampı','Kızılcahamam kampı: bütün hiziplerle ortak değerlendirme.',{R:4,G:4,S:4},{par:.2,acik:.01}],['Teşkilat yenilemesi','İl ve ilçe başkanları değişir; Sadakatçiler güçlenir.',{R:-3,G:-3,S:8},{par:-.1}],['Dengeli aday listesi','Milletvekili listelerinde hiziplere orantılı yer.',{R:5,G:5,S:2},{kamp:-.3}],['Disiplin affı','İhraç edilenlere ve küskünlere kapı açılır.',{R:5,G:5,S:-3},{par:.15}]];
const HZS={R:[['Ekonomi programını onlara yazdır','Mali disiplin ve yapısal reform programı.',{R:10,S:-4},{bat:.08,buy:.02}],['Hukuk reformu sözü','Yargı bağımsızlığı ve ifade özgürlüğü paketi.',{R:8,G:-3},{bat:.08}]],
 G:[['Aile ve değerler reformu','Aile yılı, nafaka ve medya düzenlemeleri.',{G:10,R:-4},{bat:-.05}],['Diyanet ve din eğitimi bütçesi','Kuran kursu ve imam hatip kapasitesi artar.',{G:8,R:-3},{acik:.03}]],
 S:[['Lider etrafında kenetlenme kampanyası','Mitingler ve "tek adam" vurgusu.',{S:10,R:-4},{des:.04,bat:-.03}],['Teşkilata kadro ve kaynak','Belediye ve kamuda teşkilata istihdam.',{S:8,R:-4},{acik:.04}]]};
function hzX(code){const [t,i]=code.split(':'),L=t==='x'?HZX:HZS[t];const x=L&&L[+i];if(!x)return;const m=su('hx'+code);suU('hx'+code);for(const k in x[2])S.fb[k]+=x[2][k]*m;applyFx(sfx2(x[3],m));logA('Parti',x[0],'Uygulandı.'+sat(m));hap(20,520);save();render();}
function hzExtra(){return `<div class="panel"><b>Parti yönetimi hamleleri</b>${HZX.map((x,i)=>opRow(x[0],x[1]+' '+Object.entries(x[2]).map(([k,v])=>HZF.find(h=>h[0]===k)[1]+' '+(v>0?'+':'')+v).join(', ')+(fxText(x[3])?' · '+fxText(x[3]):'')+'.',sbtn(`data-hzx="x:${i}"`,'Uygula'))).join('')}
  ${HZF.map(([k,n])=>`<div class="dl" style="margin-top:8px"><b>${n} için</b></div>`+HZS[k].map((x,i)=>opRow(x[0],x[1]+' '+Object.entries(x[2]).map(([q,v])=>HZF.find(h=>h[0]===q)[1]+' '+(v>0?'+':'')+v).join(', ')+(fxText(x[3])?' · '+fxText(x[3]):'')+'.',sbtn(`data-hzx="${k}:${i}"`,'Uygula'))).join('')).join('')}</div>`;}
const partiP0=partiP;partiP=()=>partiP0()+hzExtra();
function s2Click(t){const d=t.dataset;
  if(d.bsel){S.bsel=S.bsel===d.bsel?null:d.bsel;render();return true;}
  if(d.bla){const p=d.bla.split(':');belAct(p[0],+p[1]);return true;}
  if(d.bzo!==undefined){bzAct(+d.bzo);return true;}
  if(d.hzx){hzX(d.hzx);return true;}
  return false;}
