/* Yargı sistemi: bağımsızlık göstergesi, yüksek yargı atamaları, mahkeme kararı olayları */
function yg(){S.yg=S.yg||{bag:50,cd:{},son:[],l1:0,l2:0};return S.yg;}
const ygb=d=>{const y=yg();y.bag=clamp(y.bag+d,0,100);};
const YS=[['aym','Anayasa Mahkemesi üyeliği'],['hsk','Hâkimler ve Savcılar Kurulu üyeliği'],['yarg','Yargıtay Birinci Başkanlığı'],['dan','Danıştay Başkanlığı']];
const YO=[['Bağımsız ve saygın hukukçu',6,{bat:.35,des:-.4,par:-.3},'Barolar ve akademi memnun; parti kurmayları "bizden değil" diyor.'],['Siyasete yakın isim',-7,{des:.6,par:.4,bat:-.5},'Atama hızlı geçti; barolar ve AB tepki gösterdi.'],['Muhalefetle uzlaşılan isim',3,{kol:.3,des:-.1,huz:.15,bat:.2},'Meclis\'te uzlaşıyla geçti; her iki taraf da yarı memnun.']];
const ygP=()=>{const y=yg(),b=Math.round(y.bag),pr=clamp(Math.round(b*.7+S.bat*3),0,100);
 return `<h2>Yargı</h2><div class="panel"><b>Yargı bağımsızlığı</b><div class="lever"><span class="n">Bağımsızlık · %${b}</span><span class="h">Düşük olursa AB ve yatırımcı güveni her ay aşınır, yüksek olursa itibar artar. Kararlar ve atamalar bunu değiştirir.</span><div class="bar"><i style="width:${b}%"></i></div></div><div class="lever"><span class="n">Hukuk devleti algısı · %${pr}</span><span class="h">Bağımsızlık ve dış itibardan oluşur.</span><div class="bar"><i style="width:${pr}%"></i></div></div></div>
 <div class="panel"><b>Yüksek yargı atamaları</b>${YS.map(([k,n])=>{const cd=y.cd[k]||0,wait=cd>S.month;return `<div class="lever"><span class="n">${n}</span><span class="h">${wait?'Yakın zamanda atama yapıldı; yeni boşluk '+(cd-S.month)+' ay sonra.':'Boş kontenjan var. Bir isim seç.'}</span>${wait?'':`<div class="chips" style="grid-column:1/-1">${YO.map((o,i)=>`<button class="btn sm ${i?'sec':''}" data-ygs="${k}:${i}">${o[0]}</button>`).join('')}</div>`}</div>`;}).join('')}<div class="note">Bağımsız isim bağımsızlığı artırır; siyasete yakın isim kısa vadede destek, uzun vadede itibar kaybı getirir.</div></div>
 <div class="panel"><b>Son yargı gelişmeleri</b>${y.son.length?y.son.slice(-6).reverse().map(s=>`<div class="dl">${s}</div>`).join(''):'<div class="note">Henüz kayda değer bir gelişme yok.</div>'}</div>`;};
document.addEventListener('click',ev=>{const t=ev.target.closest&&ev.target.closest('[data-ygs]');if(!t)return;ev.stopPropagation();ev.preventDefault();
 const [k,i]=t.dataset.ygs.split(':'),o=YO[+i],s=YS.find(x=>x[0]===k);if(!o||!s)return;const y=yg();if((y.cd[k]||0)>S.month)return;
 const nm=BN[Math.floor(Math.random()*BN.length)];y.cd[k]=S.month+8;ygb(o[1]);applyFx(o[2]);
 y.son.push(`${dateLabel(S.month)} · ${s[1]}: ${nm} (${o[0].toLowerCase()})`);logA('Yargı',s[1]+' ataması',`${nm} atandı. ${o[3]}`);
 if(+i===1)S.sched.push({due:S.month+3,id:'l_yargirapor'});save();render();},true);
/* Mahkeme kararı olayları: seçimler bağımsızlığı değiştirir */
const yc=(l,ss,d,b,fx,m)=>ch(l,ss,d,fx,m,{fn:()=>{ygb(b);yg().son.push(`${dateLabel(S.month)} · ${m}`);return {fx,msg:m};}});
EV.push(
{id:'y_aym',g:'ic',tag:'Yargı · Anayasa Mahkemesi',t:'Anayasa Mahkemesi Bir Yasayı İptal Etti',x:()=>`Anayasa Mahkemesi çıkardığın bir düzenlemenin kilit maddesini Anayasa'ya aykırı buldu. ${M.adalet?M.adalet.name:'Adalet Bakanı'} "yeniden düzenleme" istiyor, muhalefet "hukuk kazandı" diyor.`,c:[ yc(`Karara uy ve metni düzelt`,1,`Hukuka saygı.`,4,{bat:.4,des:-.4,par:-.2},`Karara uyuldu, metin yeniden yazıldı.`), yc(`Kararı sert eleştir`,0,`Mahkemeyi hedef al.`,-4,{des:.5,bat:-.5,par:.2},`Karar açıkça eleştirildi. AB ve barolar tepki gösterdi.`), yc(`Yeni düzenlemeyle aş`,2,`Aynı hedefe başka yoldan git.`,-6,{des:.3,bat:-.7,par:.3},`Yeni düzenleme Meclis'ten geçti. Hukukçular "etkisizleştirme" dedi.`) ]},
{id:'y_tahliye',g:'ic',tag:'Yargı · Ceza',t:'Yüksek Profilli Tutuklu İçin Tahliye Kararı',x:()=>`Aylardır tutuklu bulunan tanınmış bir isim için mahkeme tahliye kararı verdi. Savcılık itiraz etti. Sosyal medya ikiye bölündü.`,c:[ yc(`Karara saygı göster`,0,`Müdahale etme.`,3,{bat:.5,des:-.4,huz:.2},`Tahliye gerçekleşti. Dış basın olumlu yazdı.`), yc(`İtirazı destekle`,0,`Savcılığı güçlendir.`,-5,{des:.4,bat:-.6,huz:-.2},`İtiraz kabul edildi, tahliye durduruldu. Tepki büyüdü.`), yc(`Sessiz kal`,0,`Yargıya bırak.`,0,{des:-.1},`Karar tartışmaya açık kaldı.`) ]},
{id:'y_aihm',g:'dis',tag:'Yargı · AİHM',t:'AİHM Türkiye Aleyhine Karar Verdi',x:()=>`Avrupa İnsan Hakları Mahkemesi bir bireysel başvuruda Türkiye'nin hak ihlali yaptığına hükmetti. Konsey Bakanlar Komitesi izliyor.`,c:[ yc(`Kararı uygula, tazminat öde`,1,`AB ile ilişkiyi koru.`,5,{bat:.8,des:-.5,acik:.05},`Karar uygulandı. Avrupa Konseyi'nden olumlu not geldi.`), yc(`Kararı tanımadığını açıkla`,0,`Egemenlik vurgusu.`,-6,{des:.6,bat:-1.2,dog:.1},`Karar tanınmadı. Konsey ihlal prosedürü başlattı.`), yc(`Tazminat öde, tutuklu kalsın`,1,`Orta yol.`,-2,{bat:-.2,des:.1},`Yalnız tazminat ödendi; AB "eksik" dedi.`) ]},
{id:'y_danistay',g:'ic',tag:'Yargı · Danıştay',t:'Danıştay Büyük Projeyi Durdurdu',x:()=>`Danıştay bir büyük kentsel projede çevre ve imar uygunluğu eksikliği saptayarak yürütmeyi durdurma kararı verdi. Müteahhit ve belediye başkanı "yatırım durur" diyor.`,c:[ yc(`Kararı uygula, projeyi gözden geçir`,1,`Yargıya uy.`,3,{buy:-.15,bat:.3,des:-.3,huz:.15},`Proje durduruldu, yeniden planlanıyor.`), yc(`Kanun değişikliğiyle engeli kaldır`,2,`Yasayla aş.`,-5,{buy:.15,des:.3,bat:-.5,huz:-.2},`Kanun çıkarıldı, proje yoluna girdi. Çevre örgütleri tepki gösterdi.`), yc(`Yürütmeyi durdurma kararına rağmen devam`,0,`Karara uyma.`,-8,{buy:.1,des:.2,bat:-.8,huz:-.4},`Çalışmalar sürdü. Barolar "yargı kararı çiğnendi" dedi.`) ]},
{id:'y_ysk',g:'ic',tag:'Yargı · YSK',t:'YSK Bir Seçimi İptal Etti',x:()=>`Yüksek Seçim Kurulu itirazlar üzerine bir büyük şehirdeki seçim sonucunu iptal etti ve yenilenmesine karar verdi. Muhalefet "sandığa darbe" diyor.`,c:[ yc(`Seçimi destekle, kampanya yürüt`,1,`Hukuki zemine gir.`,-4,{des:.4,huz:-.4,bat:-.6},`Seçim yenilendi. Kampanya sertleşti.`), yc(`Kararı tartışma, sonucu kabul et`,0,`Sakin kal.`,1,{des:-.3,huz:.2,bat:.1},`Karar tartışmasız kabul edildi.`), yc(`YSK'nin bağımsız olduğunu savun`,1,`Tarafsız duruş.`,3,{bat:.4,des:-.5,huz:.2},`Tarafsızlık vurgusu dış basında olumlu yankı buldu.`) ]},
{id:'y_hsk',g:'ic',tag:'Yargı · HSK',t:'HSK Toplu Hâkim ve Savcı Kararnamesi',x:()=>`Hâkimler ve Savcılar Kurulu bu yılki toplu atama kararnamesini hazırladı. Binlerce hâkim ve savcının yeri değişiyor. Barolar "kriter şeffaf mı" diye soruyor.`,c:[ yc(`Kararnameyi şeffaflaştır`,1,`Kriterleri açıkla.`,5,{bat:.4,des:-.2,par:-.1},`Kriterler yayımlandı. Hâkimler derneği memnun.`), yc(`Olduğu gibi onaylat`,0,`Mevcut düzen.`,0,{des:.1},`Kararname değişmeden yürürlüğe girdi.`), yc(`İstenilen isimleri yerleştir`,1,`Güvenilir kadrolar.`,-7,{des:.5,par:.3,bat:-.7},`Kararname hükümete yakın isimlerle şekillendi. Basında "yargıda tasfiye" yazıldı.`) ]},
{id:'y_bakandava',g:'ic',tag:'Yargı · Kabine',t:'Eski Bakana Soruşturma İzni',x:()=>`Eski bir bakan hakkındaki fezlekeye ilişkin Meclis'ten soruşturma izni isteniyor. Parti içinde ismin dostları var. Muhalefet "Yüce Divan" diyor.`,c:[ yc(`Soruşturmaya izin ver`,1,`Hukuk öncelik.`,4,{des:-.8,par:-.6,bat:.6},`İzin verildi. Parti içinde gerginlik büyüdü.`), yc(`Bekletmek için komisyona çek`,0,`Zaman kazan.`,-4,{des:.2,par:.3,bat:-.5},`Dosya komisyonda bekletildi. Muhalefet tepkili.`), yc(`Kişiyi istifaya ikna et`,0,`Sessiz çıkış.`,0,{des:-.2,par:.1,bat:.1},`İsim kendi isteğiyle görevden ayrıldı.`) ]},
{id:'l_yargirapor',g:'later',tag:'Sonuç · Yargı',t:'Venedik Komisyonu ve AB Raporu',x:()=>`Yargıya yaptığın siyasi atamalar uluslararası raporlara girdi. Avrupa Komisyonu ve Venedik Komisyonu "yargı bağımsızlığında gerileme" saptıyor.`,c:[ yc(`Reform takvimi sun`,2,`Açık hedefler.`,6,{bat:.7,des:-.5,par:-.2},`Takvim sunuldu. AB "kısmen tatmin edici" dedi.`), yc(`Raporu reddet`,0,`Kayıtsız kal.`,-4,{bat:-.6,des:.4},`Rapor reddedildi. Yatırımcı güveni zayıfladı.`), yc(`Bağımsız bir yargı konseyi kur`,3,`Yapısal reform.`,10,{bat:1,des:-.6,par:-.4,acik:.1},`Yeni konsey yasası Meclis'e sunuldu.`) ]}
);
Object.assign(EVB,Object.fromEntries(EV.map(e=>[e.id,e])));
/* Aylık etki ve yasa bağlantısı */
{const _e=endTurn;endTurn=function(){const m=S.month,r=_e.apply(this,arguments);
 try{if(S.month>m&&!S.over){const y=yg();if(S.laws.yargi&&!y.l1){y.l1=1;ygb(15);}if(S.laws.hukukd&&!y.l2){y.l2=1;ygb(8);}
  if(y.bag<30)applyFx({bat:-.06,buy:-.02,des:-.03});else if(y.bag>70)applyFx({bat:.05,buy:.02});}}catch(e){}return r;};}
/* Menüye ekle */
{const g=GR.find(x=>x[0]==='sia');if(g&&!g[2].includes('yargi'))g[2].splice(g[2].indexOf('buro')+1,0,'yargi');SUBN.yargi='Yargı';V.yargi=ygP;}
