/* ---------- Yeni: gazete, kampanya önceliği, tahmin, bakan güveni, programlar, refah ---------- */
/* Kampanya öncelikleri: [ad, koşul metni, sağlanıyor mu, kategori] */
const sv=i=>typeof cov==='function'&&typeof SV!=='undefined'?cov(SV[i]):0;
const PRI={fiyat:['İstikrarlı fiyatlar','Enflasyonu %30 altında tut.',()=>S.enf<30,'Ekonomi'],is:['Herkese iş','İşsizliği %8 altında tut.',()=>S.isz<8,'Ekonomi'],buyume:['Güçlü büyüme','Büyümeyi %3,5 üstünde tut.',()=>S.buy>=3.5,'Ekonomi'],butce:['Mali disiplin','Bütçe açığını GSYH\'nın %3 altında tut.',()=>S.acik<3,'Ekonomi'],kur:['Güçlü TL','Kur artışını enflasyonun altında tut.',()=>S.kur/K0<(S.cpi||100)/100,'Ekonomi'],rezerv:['Sağlam rezervler','Net rezervi 40 milyar doların üstünde tut.',()=>S.rez>=40,'Ekonomi'],
 sanayi:['İhracat ve sanayi','Sanayi endeksini 60 üstünde tut.',()=>S.sec.san>=60,'Üretim'],tarim:['Güçlü tarım','Tarım endeksini 60 üstünde tut.',()=>S.sec.tar>=60,'Üretim'],enerji:['Enerjide bağımsızlık','Enerji endeksini 60 üstünde tut.',()=>S.sec.ene>=60,'Üretim'],
 ucret:['Alım gücü','Asgari ücretin reel değerini koru (%100 ve üstü).',()=>typeof ap==='function'&&ap()>=100,'Toplum'],egitim:['Nitelikli eğitim','Eğitim hizmet kapsamasını %85 üstüne çıkar.',()=>sv(1)>=85,'Toplum'],saglik:['Erişilebilir sağlık','Sağlık hizmet kapsamasını %85 üstüne çıkar.',()=>sv(0)>=85,'Toplum'],konut:['Herkese konut','Konut kapsamasını %70 üstünde tut.',()=>sv(3)>=70,'Toplum'],goc:['Düzensiz göçle mücadele','Göçmen nüfusunu 3,4 milyonun altına indir.',()=>(S.ref??3.6)<3.4,'Toplum'],
 deprem:['Depreme dayanıklı şehirler','Afet hazırlığını %60 üstünde tut.',()=>prep()>=.6,'Devlet'],guv:['Dengeli bölgesel güvenlik','Ordu memnuniyeti ve huzur 6 üstünde olsun.',()=>S.ord>=6&&S.huz>=6,'Devlet'],temiz:['Temiz yönetim','Yolsuzluk algısını 40 altına indir.',()=>S.bu&&S.bu.yz<40,'Devlet'],bati:['Avrupa ile yakınlaşma','Batı itibarını 6 üstünde tut.',()=>S.bat>=6,'Devlet'],bolge:['Bölgesel liderlik','Bölge itibarını 7 üstünde tut.',()=>S.bol>=7,'Devlet']};
const priN=()=>S.pri.filter(k=>PRI[k]&&PRI[k][2]()).length;
const priV=()=>S.pri.reduce((a,k)=>a+(PRI[k]&&PRI[k][2]()?1.2:-.6),0);
const priScreen=()=>`<div class="wrap"><div class="end"><h1>Kampanya Önceliği</h1><p>Seçmene iki söz veriyorsun (${S.pri.length}/2). Tuttukça desteğin artar, tutamazsan seçimde bedel ödersin.</p>${[...new Set(Object.values(PRI).map(v=>v[3]))].map(c=>`<h2 style="margin-top:14px">${c}</h2>`+Object.entries(PRI).filter(([k,v])=>v[3]===c).map(([k,v])=>`<div class="panel" style="text-align:left"><div class="lever" style="border:0;padding:0"><span class="n">${v[0]}</span><span class="h">${v[1]} ${v[2]()?'(şu an sağlanıyor)':'(şu an sağlanmıyor)'}</span><div class="step"><button class="btn sm ${S.pri.includes(k)?'':'sec'}" data-pri="${k}">${S.pri.includes(k)?'Seçildi ✓':'Seç'}</button></div></div></div>`).join('')).join('')}<button class="btn" data-prid="1" style="margin-top:14px" ${S.pri.length===2?'':'disabled'}>Başla</button></div></div>`;
const priP=()=>S.pri.length?`<div class="panel"><b>Kampanya önceliklerin</b>${S.pri.map(k=>`<div class="dl">${PRI[k][2]()?'✓ Tutuyorsun':'✗ Tutmuyorsun'}: ${PRI[k][0]} · ${PRI[k][1]}</div>`).join('')}<div class="note">Her ay tutulan öncelik desteği artırır. Seçimde tutulan +1,2 puan, tutulmayan −0,6 puan.</div></div>`:'';
/* ay sonu gazetesi */
const gazete=r=>{const d=r.d,T=(l,v,u)=>`<div class="dl" style="text-align:center"><b style="font-size:18px;display:block;color:${v>=0?'var(--good)':'var(--bad)'}">${v>=0?'+':'−'}${nf(Math.abs(v),1)}${u}</b>${l}</div>`,pv=promRes().filter(x=>x[1]);
  return `<div class="report" style="border-top:3px double var(--ink);text-align:center"><div class="dl">KARAR GAZETESİ · ${dateLabel(r.m)} · ${S.term}. dönem</div><h3 style="font-size:22px;line-height:1.25;margin:8px 0;text-transform:none;letter-spacing:0">${r.h[0]||'Sakin bir ay geçti.'}</h3>${d?`<div class="dl" style="margin-top:10px">Bu ayın etkisi</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:6px 0 10px">${T('Onay',d.des,'')}${T('Hazine',d.rez,' $')}${T('İstikrar',d.huz,'')}${T('İtibar',d.it,'')}</div>`:''}${r.h.length>1?`<div class="dl" style="text-align:left">Sayı kayıtları</div><ul style="text-align:left">${r.h.slice(1).map(x=>`<li>${x}</li>`).join('')}</ul>`:''}${pv.length?`<div class="note" style="text-align:left">Vaat mührü: ${pv.map(x=>x[0]).join(' · ')}</div>`:''}${r.carry?`<div class="note" style="text-align:left">Kullanmadığın ${r.carry} Siyasi Sermaye devredildi.</div>`:''}</div>`;};
const gzD=(a,b)=>({des:b.des-a.des,rez:b.rez-a.rez,huz:b.huz-a.huz,it:(b.bat+b.dog+b.bol-a.bat-a.dog-a.bol)/3});
/* tahmin paneli: mevcut ayarlarla gelecek ayın beklenen değeri */
function pred(n){const o=S,acc={};STATS.forEach(x=>acc[x.k]=0);try{for(let i=0;i<n;i++){S={...o,lv:{...o.lv},loans:o.loans.map(l=>({...l})),sec:{...o.sec}};simulate();STATS.forEach(x=>acc[x.k]+=S[x.k]/n);}}finally{S=o;}return acc;}
const tahminP=()=>{const p=pred(8);return `<div class="panel"><b>Gelecek ay tahmini</b>${['enf','buy','isz','acik','kur','rez','des'].map(k=>{const s=STATS.find(x=>x.k===k),d=p[k]-S[k],good=(d<0)===!!s.low;return `<div class="dl" style="display:flex;justify-content:space-between;padding:2px 0"><span>${s.l}</span><span>${nf(S[k],s.d)} → ${nf(p[k],s.d)} <small style="color:var(--${Math.abs(d)<.005?'muted':good?'good':'bad'})">(${Math.abs(d)<.005?'±0':(d>=0?'+':'−')+nf(Math.abs(d),s.d+1)})</small></span></div>`;}).join('')}<div class="note">Kayıtlı politika ayarlarıyla, rastgele şokların ortalaması. Henüz vermediğin kararları içermez.</div></div>`;};
/* bakan güveni, programlar, yaşam maliyeti */
const PG=[['ihr','Küçük işletme ihracat programı',4,{cari:-.15,des:.08,acik:.06}],['gnc','Gençlik istihdam programı',6,{isz:-.12,des:.1,acik:.08}],['kon','Kentsel dönüşüm programı',8,{huz:.1,des:.08,acik:.1}]];
function pgStart(id){if(S.prg.length>=2||S.prg.some(p=>p.id===id)||avail()<1)return;const g=PG.find(x=>x[0]===id);S.cur.spent+=1;S.prg.push({id,left:g[2]});logA('Program',g[1],`${g[2]} ay sürecek, `);hap(20,520);save();render();}
const pgP=()=>`<h2>Programlar</h2><div class="panel">${PG.map(g=>{const p=S.prg.find(x=>x.id===g[0]);return `<div class="lever"><span class="n">${g[1]}</span><span class="h">${g[2]} ay · aylık etki: ${fxText(g[3])} · bitince bonus</span><div class="step">${sbtn(`data-pg="${g[0]}"`,p?p.left+' ay kaldı':'Başlat',p||S.prg.length>=2||avail()<1)}</div></div>`;}).join('')}<div class="note">En fazla 2 program aynı anda sürer. </div></div>`;
function yeniUp(){const h=[];S.cpi=(S.cpi||100)*Math.pow(1+S.enf/100,1/12);S.des=clamp(S.des+.12*priN(),0,100);
  for(const k in S.M){const m=S.M[k];if(m.gv===undefined)m.gv=40+m.sk*5;m.gv=clamp(m.gv+(40+m.sk*5-m.gv)*.08+((MB[k]?S.bud[k]/MB[k]:1)>=1?.5:-1.2)+(S.des-41)*.03+rnd(-2.5,2.5),0,100);if(m.gv<35)S.des-=.08;
    if(m.gv<15&&!S.own[k]){const c=cd();S.M[k]={name:c.name,sk:c.sk,note:'Yeni atanan isim',gv:55};h.push(`${m.name} istifa etti, yerine ${c.name} atandı.`);applyFx({par:-.3,des:-.3});}}
  S.prg=S.prg.filter(p=>{const g=PG.find(x=>x[0]===p.id);applyFx(g[3]);p.left--;if(p.left>0)return true;applyFx({des:.5,par:.1});h.push(g[1]+' tamamlandı.');return false;});return h;}
const refahP=()=>{const pc=S.gdp*1000/(S.nuf||86.1),md=pc*.42*(1-(S.isz-9.2)*.012),ap=S.minw/28075/(S.cpi/100)*100;return `<div class="panel"><b>Refah göstergeleri</b><div class="dl" style="display:flex;justify-content:space-between"><span>Nüfus</span><span>85,7 milyon</span></div><div class="dl" style="display:flex;justify-content:space-between"><span>Kişi başına GSYH</span><span>${nf(pc/1000,1)} bin $</span></div><div class="dl" style="display:flex;justify-content:space-between"><span>Medyan gelir (tahmini)</span><span>${nf(md/1000,1)} bin $</span></div><div class="dl" style="display:flex;justify-content:space-between"><span>Asgari ücret (net)</span><span>${nf(S.minw/S.kur,0)} $</span></div><div class="dl" style="display:flex;justify-content:space-between"><span>Yaşam maliyeti endeksi</span><span>${nf(S.cpi,1)}</span></div><div class="dl" style="display:flex;justify-content:space-between"><span>Asgari ücretin alım gücü</span><span>${nf(ap,1)}</span></div><div class="note">Yaşam maliyeti ve alım gücü oyunun başlangıcında 100 kabul edilir. Enflasyon bunları aşındırır, asgari ücret zammı toparlar.</div></div>`;};
function yeniClick(t){const d=t.dataset;
  if(d.pri){const i=S.pri.indexOf(d.pri);if(i<0){if(S.pri.length<2)S.pri.push(d.pri);}else S.pri.splice(i,1);render();return true;}
  if(d.prid){S.prip=0;save();render();return true;}
  if(d.pg){pgStart(d.pg);return true;}return toplumClick(t)||dunyaClick(t)||piyasaClick(t)||ileriClick(t)||genisClick(t)||genis2Click(t)||partiClick(t)||arayuzClick(t);}
